### ISSUE TITLE
errors after  `brew install emacs-plus`

### ISSUE THREAD

**Issue by niskrev** [d12frosted/homebrew-emacs-plus#106]
==> Pouring imagemagick@6-6.9.10-12.high_sierra.bottle.tar.gz
Error: Failed changing install name in /usr/local/Cellar/imagemagick@6/6.9.10-12/lib/libMagickWand-6.Q16.6.dylib
  from @@HOMEBREW_PREFIX@@/opt/freetype/lib/libfreetype.6.dylib
    to /usr/local/opt/freetype/lib/libfreetype.6.dylib
Error: Unrecognized Mach-O magic: 0xa741543
Warning: Bottle installation failed: building from source.
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick%406--6.9.10-12.tar.xz
==> Downloading from https://akamai.bintray.com/54/54549fe394598f6a7cec8cb5adc45d5d65b8b
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 54549fe394598f6a7cec8cb5adc45d5d65b8b4f043745c6610693618b1372966
Actual: fa3067df9f0b51af2683f5ee23f4109c9d4c8e5131c6c13d1445ae0c40161cad

**Comment by d12frosted** [comment]
This is interesting. I've checked both URLs (main and the mirror) and got expected checksum.

```
$ curl -L https://dl.bintray.com/homebrew/mirror/imagemagick%406--6.9.10-12.tar.xz | openssl sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8719k  100 8719k    0     0  1226k      0  0:00:07  0:00:07 --:--:-- 1850k
54549fe394598f6a7cec8cb5adc45d5d65b8b4f043745c6610693618b1372966

$ curl https://www.imagemagick.org/download/ImageMagick-6.9.10-12.tar.xz | openssl sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8719k  100 8719k    0     0   599k      0  0:00:14  0:00:14 --:--:--  849k
54549fe394598f6a7cec8cb5adc45d5d65b8b4f043745c6610693618b1372966
```

Could you please try removing `imagemagick` and trying again?

```
$ brew uninstall -f imagemagick@6
```

**Comment by d12frosted** [comment]
No problem! I am glad that it worked out eventually. Pitty to hear about the problems with your OS installation.

P. S. Kudos for reporting back 😸 I am closing the issue then.
