### ISSUE TITLE
Strange things in Mojave

### ISSUE THREAD

**Issue by agzam** [d12frosted/homebrew-emacs-plus#108]
I'm not sure if this is emacs-plus related or it's simply Mojave breaks cocoa Emacs (in `--devel` and `--head`). 

For some reason when I tried installing formula with `--devel` or `--with-pdumper --HEAD` - gui emacs won't display anything. It looks like it's working (not freezing), but there's nothing - just completely blank frame. Creating new frame doesn't fix that. 
Installing with just `--HEAD` worked, but that for some reason completely screws my theme customizations, I don't know maybe they've changed how color customization work.

Anyone else seeing similar problems?

**Comment by agzam** [comment]
@d12frosted it is sad that pdumper doesn't work. I just received a new machine at work with Mojave and have no way to revert. Would you be so kind to ping me here whenever you or someone else gets it to work properly? Fundamentally I want xwidgets and pdumper - those things are cool.

**Comment by d12frosted** [comment]
Sure I will ping you. AFAIK, it is still not working.

Mojave release did break a lot of stuff in Emacs land :(

**Comment by agzam** [comment]
Pdumper branch was merged to `master` https://www.reddit.com/r/emacs/comments/aglmzu/portable_dumper_landed_in_master. However, it still not working in Mojave. Just fyi

**Comment by d12frosted** [comment]
That's neat that it was merged :100: 

Does it work now?

**Comment by agzam** [comment]
nope... I don't think it does. Not on my machine at least

**Comment by parhamdoustdar** [comment]
Is this why `--head` seems to install Emacs version 26.1? When I run the following:

`brew install emacs-plus --without-spacemax-icon --head --with-mailutils --with-dbus --with-ctags`

And I open Emacs and run `emacs-version`, I get:

`GNU Emacs 26.1 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-03-04`

**Comment by d12frosted** [comment]
@parhamdoustdar that's because you have typos in your options list:

1. It should be `--HEAD` instead of `--head`. This is why you don't get the latest version.
2. It should be `--without-spacemacs-icon` instead of `--without-spacemax-icon`. That's why you don't get the default Emacs icon.

**Comment by parhamdoustdar** [comment]
Thanks a lot for the answer! Yes, all mistakes on my side.

**Comment by foltrask** [comment]
Just upgraded to Mojave and I have same issue described by OP launching `Emacs.app` that was built with `--HEAD` on High Sierra: 
```
brew info emacs-plus
d12frosted/emacs-plus/emacs-plus: stable 26.1 (bottled), devel 26.1-rc1, HEAD
GNU Emacs text editor
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs-plus/HEAD-d958487 (3,981 files, 128MB) *
  Built from source on 2018-10-09 at 23:26:24 with: --with-ctags --with-x11 --with-pdumper --with-mailutils
From: https://github.com/d12frosted/homebrew-emacs-plus/blob/master/Formula/emacs-plus.rb
==> Dependencies
Build: pkg-config ✔
Recommended: little-cms2 ✔, gnutls ✔, librsvg ✔, imagemagick@6 ✔
Optional: dbus ✘, mailutils ✔, jansson ✔
==> Requirements
Optional: x11 ✔
```
On terminal `emacs -nw` is working fine.

Trying to reinstall I get:
```
brew reinstall emacs-plus --HEAD  --with-spacemacs-icon
...
Error: invalid option: --HEAD
```

**Comment by foltrask** [comment]
Just checking in to say that pdumper seems to be working for me, I didn't set the flag when building.

**Comment by waymondo** [comment]
I can chime in with @foltrask that I built with pdumper on 10.14.4 and it seems to be working for me

**Comment by agzam** [comment]
Does that mean that --with-pdumper can be re-enabled for Mojave? Will it work?

**Comment by d12frosted** [comment]
Don't know. Needs to be tested. I'll try to check this out today.

**Comment by d12frosted** [comment]
@agzam apparently, pdumper was merged to master, so I am opening this on Mojave. You can try it already :) It still building on my machine, but everything should be fine.

BTW, I've also opened x11 option for Mojave :) It's good to live in the year 2019!

**Comment by d12frosted** [comment]
I am a slowpoke. If `pdumper` was merged to master that actually means that I can remove this part:

```ruby
url "https://github.com/emacs-mirror/emacs.git", :branch => "pdumper"
```

**Comment by d12frosted** [comment]
Ok, here is a PR: https://github.com/d12frosted/homebrew-emacs-plus/pull/165

Anyways, closing this issue as for now Mojave is not an issue. Right? :)
