### ISSUE TITLE
--HEAD build error

### ISSUE THREAD

**Issue by JamesMcMahon** [d12frosted/homebrew-emacs-plus#113]
Trying to work around some of issues effecting Mojave (https://github.com/d12frosted/homebrew-emacs-plus/issues/95)

I am getting the following error when running

    brew install emacs-plus --HEAD

> ==> Installing emacs-plus from d12frosted/emacs-plus
==> Cloning https://github.com/emacs-mirror/emacs.git
Cloning into '/Users/jamie/Library/Caches/Homebrew/emacs-plus--git'...
Checking out files: 100% (3900/3900), done.
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Downloading https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c
Already downloaded: /Users/jamie/Library/Caches/Homebrew/downloads/7dccd5b8ea0bb2eb29cfb643365489d84c16ea33b1743261be66fa9691733a1e--patch-multicolor-font.diff
==> Patching
==> Applying patch-multicolor-font.diff
patching file src/macfont.m
Hunk #1 succeeded at 2344 (offset -29 lines).
==> ./autogen.sh
==> ./configure --disable-silent-rules --enable-locallisppath=/Users/jamie/.brew/share/emacs/site-lis
==> make
Last 15 lines from /Users/jamie/Library/Logs/Homebrew/emacs-plus/03.make:
	  sed -n -e '/0xc940/,$ p' < ../../etc/charsets/BIG5.map | awk -f ./big5.awk ) > ../../etc/charsets/BIG5-2.map
cp mapfiles/MULE-ethiopic.map ../../etc/charsets/MULE-ethiopic.map
cp mapfiles/MULE-ipa.map ../../etc/charsets/MULE-ipa.map
cp mapfiles/MULE-is13194.map ../../etc/charsets/MULE-is13194.map
cp mapfiles/MULE-sisheng.map ../../etc/charsets/MULE-sisheng.map
cp mapfiles/MULE-tibetan.map ../../etc/charsets/MULE-tibetan.map
cp mapfiles/MULE-lviscii.map ../../etc/charsets/MULE-lviscii.map
cp mapfiles/MULE-uviscii.map ../../etc/charsets/MULE-uviscii.map
awk -f ./gb180304.awk < ../../etc/charsets/GB180302.map > ../../etc/charsets/GB180304.map
AWK=awk ./mapconv glibc/EUC-JISX0213.gz '/^<.*[ 	]\/x[a-f]/' GLIBC-2-7 \
	  | sed -f jisx2131-filter \
	  | sed -e 's/0x2015/0x2014/' -e 's/0x2299/0x29BF/' > ../../etc/charsets/JISX2131.map
echo timestamp > charsets.stamp
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....

> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/d12frosted/homebrew-emacs-plus/issues

Happy to help debug further. Hopefully this is useful and not just something weird on my local machine.

**Comment by shuxiao9058** [comment]
> The same error.

It build success with the latest emacs master branch revision.

**Comment by d12frosted** [comment]
Thanks for the report. Unfortunately, it happens time to time with `HEAD` option. Right now it works (apparently not only for me), so I am closing this issue.

P. S. Sorry for the late response - being very busy lately.
