### ISSUE TITLE
Running emacs-plus on terminal similar to nox

### ISSUE THREAD

**Issue by nipunarora** [d12frosted/homebrew-emacs-plus#115]
I am using emacs-plus in mac OS mojave? I wonder if there is a way to run this in `iterm` itself instead of as an app? Is there a `emacs-nox` alternative similar to what we have in ubuntu?

**Comment by d12frosted** [comment]
Sure, just run `emacs -nw`. You can alias this to whatever you like. For some time I aliased it to `em`.

**Comment by d12frosted** [comment]
BTW, there is a similar question:

https://github.com/d12frosted/homebrew-emacs-plus/issues/2#issuecomment-213894581
