### ISSUE TITLE
support `jansson` library on HEAD

### ISSUE THREAD

**Issue by slippycheeze** [d12frosted/homebrew-emacs-plus#116]
Brew packages the `jansson` JSON parser library, and HEAD uses it optionally for higher performance parsing.  It would be nice to add that as an option to the formula, or just as a mandatory dep for HEAD.

I have not checked if 26 supports it at all.

**Comment by d12frosted** [comment]
Neat. There is PR that adds this: https://github.com/d12frosted/homebrew-emacs-plus/pull/120/files#diff-cbfee31de48c4c925ef3e240a0362bb2R262

**Comment by d12frosted** [comment]
Merged to master.
