### ISSUE TITLE
Switch to ImageMagick 7 for HEAD

### ISSUE THREAD

**Issue by slippycheeze** [d12frosted/homebrew-emacs-plus#117]
HEAD now supports ImageMagick 7; it'd be nice to enable that in the formula.

**Comment by daviderestivo** [comment]
I have added ImageMagick 7 support to my personal homebrew GNU/Emacs formula. 
@d12frosted if you like you can use the code in [this commit](
https://github.com/daviderestivo/homebrew-emacs-head/commit/c437dce1b7b35cd56c2efff3022e23b850dcafdb).

**Comment by d12frosted** [comment]
Merged to master.

P. S. @daviderestivo Sorry, I missed your message :( But the work got to this repo!

**Comment by daviderestivo** [comment]
Thanks :)
