### ISSUE TITLE
Disable focusing other frame when closing one

### ISSUE THREAD

**Issue by xenodium** [d12frosted/homebrew-emacs-plus#119]
When closing a frame, Emacs automatically focuses another frame.

![before](https://user-images.githubusercontent.com/8107219/54477896-51be3600-4804-11e9-800a-9b25b9611ce7.gif)

This re-focus has an additional side-effect: when closing a frame from one desktop/space, one gets automatically moved to another desktop/space where the refocused frame lives.

Not been able to find a way to disable the re-focusing in elisp. However, a [small patch in frame.c](https://github.com/xenodium/homebrew-emacs-plus/commit/79a8e98b222fa262746f6db620ddd1fdb151ece9) seems to have done the job:

![after](https://user-images.githubusercontent.com/8107219/54477966-1708cd80-4805-11e9-9bfc-c64b71001be6.gif)

Patched in a fork. Any interest in including this option (disable refocus) in emacs-plus upstream recipe? Happy to submit a pull request.

**Comment by d12frosted** [comment]
I see 3 thumb-ups. I say - send PR, I will be glad to merge it. :smile_cat:

**Comment by d12frosted** [comment]
Merged to master.
