### ISSUE TITLE
Bottles for Emacs 26.2

### ISSUE THREAD

**Issue by d12frosted** [d12frosted/homebrew-emacs-plus#128]
Now that there is a new version of Emacs, I need to prepare bottles.

Hopefully, I will do it this week. But I can do it only for Mojave. If someone can help me with the previous macOS version, it would be really nice. If anyone is interested, just let me know, I will share the instructions.

Basically (if nothing changed from the last time I've done this) all you need to do is

1. Produce a bottle
```
$ brew install --build-bottle emacs-plus
$ brew bottle emacs-plus
```

2. Send generated archive to boris@d12frosted.io

CC @jonhermansen @shuxiao9058

**Comment by jonhermansen** [comment]
@d12frosted I'm happy to do this for High Sierra! I can run a build today.

**Comment by shuxiao9058** [comment]
@d12frosted Sorry for that my macOS version is Mojave too, thanks for your work.

**Comment by jonhermansen** [comment]
@d12frosted I finally emailed you the bottle file, sorry for the delay. Let me know if there's anything else I can do!

**Comment by d12frosted** [comment]
Thank you @jonhermansen. I've uploaded the bottle and added it to the formulae. If someone could test, it would be awesome!

**Comment by d12frosted** [comment]
Worth mentioned - the bottle is available for several days already 😸 Thanks to @jonhermansen
