### ISSUE TITLE
UX: frame doesn't fill window space

### ISSUE THREAD

**Issue by winmillwill** [d12frosted/homebrew-emacs-plus#130]
I found this project while looking for a build with no titlebar, and that seems to work fine, and so does everything else, so kudos and thank you!

One random gotcha that may be worth documenting is that if you don't have something like `(setq frame-resize-pixelwise t)` then you're liable to have some wonky gaps between windows when tiling, unless your typeface is somehow exactly aligned with your effective display area.

**Comment by d12frosted** [comment]
Hi @winmillwill ,

Thank you for the feedback. I am glad that it works for you. 

Indeed, makes sense to document this. PR would be welcome :smile_cat:

**Comment by daviderestivo** [comment]
> One random gotcha that may be worth documenting is that if you don't have something like `(setq frame-resize-pixelwise t)` then you're liable to have some wonky gaps between windows when tiling, unless your typeface is somehow exactly aligned with your effective display area.

Thanks a lot for sharing. I was not aware about this option.

**Comment by d12frosted** [comment]
Documented thanks to @winmillwill  :smile_cat:
