### ISSUE TITLE
Wrong type argument: char-table-p, nil

### ISSUE THREAD

**Issue by stephanschubert** [d12frosted/homebrew-emacs-plus#135]
`brew install emacs-plus --HEAD` fails with:

```
Loading /private/tmp/emacs-plus-20190506-94096-1q1cy6n/lisp/emacs-lisp/lisp.el (source)...
Wrong type argument: char-table-p, nil
make[1]: *** [bootstrap-emacs.pdmp] Error 255
make: *** [src] Error 2
```

It worked a few weeks ago..

**EDIT:** `brew install emacs-plus` works.

**Comment by d12frosted** [comment]
Hey @stephanschubert,

Unfortunately, it's `--HEAD`, a development branch. Things happen to break there sometimes. I already see a [message](https://lists.gnu.org/archive/html/emacs-devel/2019-05/msg00108.html) on `emacs-devel` regarding this particular build failure. Hopefully it will be fixed soon.

P. S. From README:

> Note that --HEAD builds are not really supported. They may fail to install, they may crash at run time. Or even worse, they may work as expected. So use this option at your own risk. And feel free to open up issues you face, just remember that I am not close enough to Emacs development process to provide you much help with any arising issues.

**Comment by d12frosted** [comment]
But please don't close this issue until the build is fixed :smile_cat: It's better to increase the visibility and provide a message that it's a known issue :small_airplane: Let's wait until it's fixed.

All others, please don't upgrade if you are using `--HEAD`.

**Comment by d12frosted** [comment]
I believe it was fixed :)
