### ISSUE TITLE
Error: emacs: undefined method `sha1' for #<Resource::PatchResource:0x00007fbd340da108>

### ISSUE THREAD

**Issue by behike56** [d12frosted/homebrew-emacs-plus#142]
I want use mu4e with spacemacs.
```
$ brew update
Already up-to-date.
```
```
$ brew doctor
Your system is ready to brew.
```
```
$ brew install mu
Error: emacs: undefined method `sha1' for#<Resource::PatchResource:0x00007fbd340da108>
```
```
$brew info mu
mu: stable 1.2.0 (bottled), HEAD
Tool for searching e-mail messages stored in the maildir-format
https://www.djcbsoftware.nl/code/mu/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mu.rb
==> Dependencies
Error: emacs: undefined method `sha1' for#<Resource::PatchResource:0x00007faa0a032cb0>
```

I tried to install emacs just in case.
```
$ brew install emacs
Error: emacs: undefined method `sha1' for #<Resource::PatchResource:0x00007f8baff006d0>
```
```
$brew info emacs
Error: emacs: undefined method `sha1' for #<Resource::PatchResource:0x00007fade04e5670>
Found a cask named "emacs" instead.
emacs: 26.2
https://emacsformacosx.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/emacs.rb
==> Name
Emacs
==> Artifacts
Emacs.app (App)
/Applications/Emacs.app/Contents/MacOS/Emacs -> emacs (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/ebrowse (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/emacsclient (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/etags (Binary)
```

By the way, I installed spacemacs like this...
```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus --with-spacemacs-icon
```

so, what should I do?

**Comment by d12frosted** [comment]
hey @behike56 

sounds bad :crying_cat_face: 

could you please try doing `$ brew upgrade`? and then try again?

**Comment by behike56** [comment]
$ brew info mu
mu: stable 1.2.0 (bottled), HEAD
Tool for searching e-mail messages stored in the maildir-format
https://www.djcbsoftware.nl/code/mu/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mu.rb
==> Dependencies
Error: emacs: undefined method `sha1' for #<Resource::PatchResource:0x00007fd69c706640>

no change

**Comment by d12frosted** [comment]
Well, to be honest, this issue is really unlikely to be related to this repository. It seems that something is wrong in your setup :crying_cat_face: 

I've googled this issue and have several suggestions:

1. Try doing `brew upgrade` (though it seems that it didn't help you).
2. Make sure that `brew doctor` is green.
3. I've seen that similar issue can be caused by some taps. For example, try to `brew untap larsimmisch/avr` (this is the biggest shot in the air).

**Comment by behike56** [comment]
Thank you for your time.
Please give some advice at the end.

Are there any problems with this?
```
$ brew tap
caskroom / fonts
d12frosted / emacs-plus
heroku / brew
homebrew / cask
homebrew / core
homebrew / services
sambadevi / powerlevel9k
sanemat / font
```

**Comment by d12frosted** [comment]
Honestly, I am not sure which can lead to the mentioned problem.

Could you please try untapping listed taps one by one to see if it fixes your problem? Also, did you try `brew doctor`?

**Comment by behike56** [comment]
Yes I did .
```
$ brew doctor
Your system is ready to brew.
```
Anyway, I do something for myself.

**Comment by d12frosted** [comment]
Well, I am run out of ideas :( If you removed all taps and it still happens, I advice you to contact `homebrew` maintainers, because they know the best.
