### ISSUE TITLE
Can --with-no-title-bars be available in emacs 27 --HEAD branch?

### ISSUE THREAD

**Issue by JSpenced** [d12frosted/homebrew-emacs-plus#143]
I know this feature is pushed up for emacs 26.1, but has anyone tested it with emacs 27 HEAD branch. I have upgraded to emacs 27 due to problems with magit and dired in emacs 26.1. I would like to remove the title bar as before. BUt it doesn't allow this option when specified with --HEAD.

**Comment by d12frosted** [comment]
Hey @JSpenced ,

I won't be able to try it until weekends, but you can do it yourself by editing the formula (just remove the `if` check [here](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/Formula/emacs-plus.rb#L116)).

**Comment by JSpenced** [comment]
I'm not that familiar with how to manually install a brew tap after making changes. I am assuming I can clone it and make the change. Then, make a commit and install from my local HEAD branch. I'm just not sure the command to install from a local repo. Any links or tips and I'll give it a try tomorrow.

**Comment by pcr910303** [comment]
@JSpenced try `brew edit emacs-plus` 👍

**Comment by JSpenced** [comment]
Wow, too easy thanks @pcr910303 

This is the error I get. I am not sure if it could be from still using El Capitan or just it doesn't work on emacs 27:
![image](https://user-images.githubusercontent.com/43424787/58652771-4a142500-834f-11e9-9476-8efd3ecc5f04.png)

**Comment by JSpenced** [comment]
I think the main problem is the file nsterm.m changed a bit so the line numbers are a bit different now. The line numbers for the negative part should be:
455
1815
6940
7344
7381.

Not sure how to change a patch to test it though.

**Comment by pcr910303** [comment]
@JSpenced If the numbers change only, the `patch` program gracefully handles it - it looks like some of the code changed :-(
Try `brew install emacs-mac --with-no-title-bars --HEAD --debug` and when the error happens, drop to the shell. Use the [`wiggle`](https://linux.die.net/man/1/wiggle) program to apply the patch and continue building.

**Comment by JSpenced** [comment]
Okay, I tried wiggle but I get 1 unresolved conflict still, which I couldn't figure out how to see what this was. Also, I wasn't sure how to continue the build. If I use `exit` to get out of the shell than the build just cancels. 

But from looking at the code, it looks basically the same so I think the major line differences come from other parts of the code so the patch should work.

**Comment by pcr910303** [comment]
@JSpenced Just open the unresolved file and resolve it. The unresolved parts will be denoted with `<<<<<<`, `|||||||`, and `>>>>>>`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pcr910303** [comment]
@JSpenced I remember that you could exit the shell and the build resumed, but if it doesn’t, just run `make`x

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JSpenced** [comment]
@pcr910303 When I exit out of zsh the build just cancels but I will try this.

**Comment by snarisi** [comment]
I was able to get this to work - after resolving the conflict and exiting the shell, you can choose the option to `ignore` in the brew debugger and the build will continue.

**Comment by JSpenced** [comment]
@snarisi Is there an easy way to post the patched file with all the conflicts resolved?

**Comment by snarisi** [comment]
@JSpenced sure, here's the file after i apply the patch: https://gist.github.com/snarisi/f2dc538378a184636f1df52edf7bca84

**Comment by JSpenced** [comment]
@pcr910303 Can I use wiggle and the patched file above to create the patch for emacs 27?

**Comment by pcr910303** [comment]
@JSpenced Why would you not use `git diff`? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JSpenced** [comment]
Was this patch ever included in the normal install? I never got around to reinstalling. Just wondering if this can be closed.

**Comment by pcr910303** [comment]
@JSpenced No, I don’t think so. What about making a PR? (It looks like you already have successfully installed; just push the modifications) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jakejx** [comment]
I believe https://github.com/d12frosted/homebrew-emacs-plus/pull/160 closes this.

**Comment by d12frosted** [comment]
Exactly, so closing this issue.
