### ISSUE TITLE
Re-enabling multicolor font support in Emacs 25.1

### ISSUE THREAD

**Issue by aatxe** [d12frosted/homebrew-emacs-plus#15]
As you may or may not be aware, in Emacs 25.1, the FSF made the decision to remove multicolor font support from the macOS version of Emacs because it is not currently supported by GNU/Linux. I just recently discovered this through [this blogpost](http://www.lunaryorn.com/posts/bye-bye-emojis-emacs-hates-macos.html) and now understand why my wasted hours of trying to get multicolor fonts working were just banging my head into a wall.

I'm not sure if you have any interest in changing this in your formula, but in order to resolve the issue personally, I prepared a patch that I used locally with this formula to get working multicolor font support once again. So, I thought I would bring this up here with [the patch](https://gist.github.com/aatxe/260261daf70865fbf1749095de9172c5), in case you wish to integrate it. I would make a PR but my local copy is using homebrew's embedded patch feature. That being said I can also prepare one if you're interested in adding this.

**Comment by d12frosted** [comment]
Thank you for brining up this topic! I am aware of that change, but I didn't thought about bringing this feature back to `emacs-plus`. And thanks for the patch! Would be nice to have PR from you 😸 But if you don't want to mess with your local settings, you can leave this to me.
