### ISSUE TITLE
SVG not rendering correctly

### ISSUE THREAD

**Issue by VOID404** [d12frosted/homebrew-emacs-plus#151]
I have an svg embedded in org mode. It's not rendering text on an image. When I open svg by itself it's not rendering anything other than background color of shapes.

**Comment by d12frosted** [comment]
I am not sure if I can help you here.

1. Sharing steps to reproduce would be a good starting point.
2. This issue tracker is mostly for issues related to this specific build/formula of Emacs, but not for Emacs itself. It would be great if you could check if it works or not with default installation options (either by tweaking build options for `emacs-plus` or `brew cask install emacs` and running `Emacs.app` provided by `cask`).

P. S. Sorry for that late reply.

**Comment by d12frosted** [comment]
Closing this issue because it's a) an upstream issue that is not related to this repository and b) lack of activity. Let me know if you still want to leave it open.

P. S. I really hope that you've figured this out. If this is the case, I think it worth sharing solution.

**Comment by tshu-w** [comment]
In the recent commit of emacs28, this issue has been resolved!

**Comment by d12frosted** [comment]
@tshu-w 🎉 happy to hear, will give it a try!

**Comment by tshu-w** [comment]
Aha, I found that the problem I mentioned may be different from what this issue says, anyway, now that the svg is clear
