### ISSUE TITLE
Remove "linkapps" from "caveats" section

### ISSUE THREAD

**Issue by ericzpd** [d12frosted/homebrew-emacs-plus#154]
The `brew linkapps` command is no longer working. I think it's good to remove the `brew linkapps` part from the `caveats` section.

**Comment by jmromer** [comment]
```
Emacs.app was installed to:
  /usr/local/opt/emacs-plus

To link the application to default Homebrew App location:
  brew linkapps
or:
  ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications
```

```
% brew linkapps
Error: Unknown command: linkapps
```

**Comment by d12frosted** [comment]
Done, removed it from there. Now there are two options:

- Use `ln` to link the application.
- Use Alfred (or any other similar software) to launch applications. Alfred allows to configure search paths, so I add `/usr/local/Cellar` to it's search path for Alfred to see Emacs.app without linking.
