### ISSUE TITLE
--HEAD not recognized

### ISSUE THREAD

**Issue by greened** [d12frosted/homebrew-emacs-plus#156]
This does not seem to work:
```
brew reinstall emacs-plus --without-spacemacs-icon --with-ctags --with-mailutils --with-modern-icon --with-jansson --HEAD
[...]
Error: invalid option: --HEAD
```
What is the proper way to install the latest emacs-plus?

**Comment by greened** [comment]
A reinstall without `--HEAD` works.  Is that getting me the latest if I originally installed with `--HEAD`?

**Comment by axelson** [comment]
If I recall correctly, an uninstall followed by an install with `--HEAD` should work.

**Comment by d12frosted** [comment]
Yes, it's how you should reinstall any package with brew if you want new options. Hopefully 4f1a9d6 will help others :)
