### ISSUE TITLE
Wrong window role

### ISSUE THREAD

**Issue by oguzserbetci** [d12frosted/homebrew-emacs-plus#157]
First of all thanks for this awesome distribution! One of the problems I faced was with the window role being `AXTextField`. This causes problems with the window tiler I use, as you can see at its issues: ([yabai](https://github.com/koekeishiya/yabai/issues?utf8=%E2%9C%93&q=is%3Aissue++emacs+)). 

I'm not knowledgeable, but it seems like the easiest change would be to change the Emacs window role to `AXWindow`.

**Comment by pcr910303** [comment]
This repo isn’t the official Emacs repository, and AFAIK the change is non-trivial. If you have a patch for that, you can add it to here; else, I think you should mention this in the emacs-dev mailing list.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d12frosted** [comment]
Thanks yo the @jakejx we now have an option `--with-window-role-fix`. Please test it. If there are no complaints on this change, I am gonna make it turned on by default in several weeks.

**Comment by oguzserbetci** [comment]
I just tried it and it works with yabai :)

**Comment by d12frosted** [comment]
@oguzserbetci cool! I will it give this feature a little bit more time and then will mark it as opt-out 😸
