### ISSUE TITLE
Patch failed with xwidgets

### ISSUE THREAD

**Issue by hanfeng0409** [d12frosted/homebrew-emacs-plus#159]
cmd is `brew install emacs-plus --without-spacemacs-icon --with-jansson --with-xwidgets --HEAD` with master branch. The patch `xwidgets_webkit_in_cocoa.patch` failed on file `src/xwidget.c`. 

> patching file configure.ac
Hunk #1 succeeded at 484 (offset 1 line).
Hunk #2 succeeded at 2792 (offset -12 lines).
Hunk #3 succeeded at 5711 (offset 41 lines).
patching file lisp/xwidget.el
patching file nextstep/templates/Info.plist.in
Hunk #1 FAILED at 675.
1 out of 1 hunk FAILED -- saving rejects to file nextstep/templates/Info.plist.in.rej
patching file src/Makefile.in
Hunk #1 succeeded at 434 (offset 8 lines).
patching file src/emacs.c
Hunk #1 succeeded at 1871 (offset 93 lines).
Hunk #2 succeeded at 1947 (offset 93 lines).
patching file src/nsterm.m
Hunk #2 succeeded at 2412 (offset -39 lines).
Hunk #3 succeeded at 2421 (offset -39 lines).
Hunk #4 succeeded at 4190 (offset -26 lines).
Hunk #5 succeeded at 6849 (offset -24 lines).
Hunk #6 succeeded at 6892 (offset -24 lines).
patching file src/nsxwidget.h
patching file src/nsxwidget.m
patching file src/xwidget.c
Hunk #1 FAILED at 18.
Hunk #2 succeeded at 59 (offset -7 lines).
Hunk #3 succeeded at 73 (offset -7 lines).
Hunk #4 succeeded at 91 (offset -7 lines).
Hunk #5 succeeded at 109 (offset -7 lines).
Hunk #6 succeeded at 168 (offset -7 lines).
Hunk #7 succeeded at 206 (offset -7 lines).
Hunk #8 succeeded at 245 (offset -7 lines).
Hunk #9 succeeded at 261 (offset -7 lines).
Hunk #10 succeeded at 297 (offset -7 lines).
Hunk #11 succeeded at 528 (offset -34 lines).
Hunk #12 succeeded at 538 (offset -34 lines).
Hunk #13 succeeded at 552 (offset -34 lines).
Hunk #14 succeeded at 610 (offset -34 lines).
Hunk #15 succeeded at 626 (offset -34 lines).
Hunk #16 succeeded at 701 (offset -34 lines).
Hunk #17 succeeded at 719 (offset -34 lines).
Hunk #18 FAILED at 742.
Hunk #19 succeeded at 811 (offset -33 lines).
Hunk #20 succeeded at 850 (offset -33 lines).
Hunk #21 succeeded at 894 (offset -33 lines).
Hunk #22 succeeded at 905 (offset -33 lines).
Hunk #23 succeeded at 916 (offset -33 lines).
Hunk #24 succeeded at 937 (offset -33 lines).
Hunk #25 succeeded at 946 (offset -33 lines).
Hunk #26 succeeded at 956 (offset -33 lines).
Hunk #27 succeeded at 982 (offset -33 lines).
Hunk #28 succeeded at 1065 (offset -33 lines).
Hunk #29 succeeded at 1183 (offset -33 lines).
Hunk #30 succeeded at 1357 (offset -33 lines).
Hunk #31 succeeded at 1386 (offset -33 lines).
Hunk #32 succeeded at 1419 (offset -33 lines).
Hunk #33 succeeded at 1433 (offset -33 lines).
2 out of 33 hunks FAILED -- saving rejects to file src/xwidget.c.rej
patching file src/xwidget.h
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/emacs-plus--patch-20191106-76368-m43yq5/xwidgets_webkit_in_cocoa.patch` exited with 1.

after I tried the method mentioned in #146 , replace the url and patch, got another error like this:

> patching file src/nsxwidget.h
patching file src/nsxwidget.m
patching file configure.ac
Hunk #2 succeeded at 2792 (offset -16 lines).
patching file lisp/xwidget.el
patching file nextstep/templates/Info.plist.in
Hunk #1 FAILED at 675.
1 out of 1 hunk FAILED -- saving rejects to file nextstep/templates/Info.plist.in.rej
patching file src/Makefile.in
patching file src/emacs.c
Hunk #1 succeeded at 1871 (offset -31 lines).
Hunk #2 succeeded at 1947 (offset -31 lines).
patching file src/nsterm.m
Hunk #5 succeeded at 6849 (offset 2 lines).
Hunk #6 succeeded at 6892 (offset 2 lines).
patching file src/xwidget.c
Hunk #1 FAILED at 18.
Hunk #2 succeeded at 58 (offset -8 lines).
Hunk #3 succeeded at 72 (offset -8 lines).
Hunk #4 succeeded at 90 (offset -8 lines).
Hunk #5 succeeded at 108 (offset -8 lines).
Hunk #6 succeeded at 167 (offset -8 lines).
Hunk #7 succeeded at 205 (offset -8 lines).
Hunk #8 succeeded at 244 (offset -8 lines).
Hunk #9 succeeded at 260 (offset -8 lines).
Hunk #10 succeeded at 296 (offset -8 lines).
Hunk #11 succeeded at 527 (offset -35 lines).
Hunk #12 succeeded at 537 (offset -35 lines).
Hunk #13 succeeded at 551 (offset -35 lines).
Hunk #14 succeeded at 609 (offset -35 lines).
Hunk #15 succeeded at 625 (offset -35 lines).
Hunk #16 succeeded at 700 (offset -35 lines).
Hunk #17 succeeded at 718 (offset -35 lines).
Hunk #18 succeeded at 741 (offset -35 lines).
Hunk #19 succeeded at 810 (offset -35 lines).
Hunk #20 succeeded at 849 (offset -35 lines).
Hunk #21 succeeded at 893 (offset -35 lines).
Hunk #22 succeeded at 904 (offset -35 lines).
Hunk #23 succeeded at 915 (offset -35 lines).
Hunk #24 succeeded at 936 (offset -35 lines).
Hunk #25 succeeded at 945 (offset -35 lines).
Hunk #26 succeeded at 955 (offset -35 lines).
Hunk #27 succeeded at 981 (offset -35 lines).
Hunk #28 succeeded at 1064 (offset -35 lines).
Hunk #29 succeeded at 1182 (offset -35 lines).
Hunk #30 succeeded at 1356 (offset -35 lines).
Hunk #31 succeeded at 1385 (offset -35 lines).
Hunk #32 succeeded at 1418 (offset -35 lines).
Hunk #33 succeeded at 1432 (offset -35 lines).
1 out of 33 hunks FAILED -- saving rejects to file src/xwidget.c.rej
patching file src/xwidget.h
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/emacs-plus--patch-20191106-77949-14mbdsx/new_xwidget_patch.patch` exited with 1.

I am use macOS 10.15.1 (19B88).
Dose there any method to solve this problem?

**Comment by pcr910303** [comment]
@hanfeng0409 Try out the method shown at #143.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hanfeng0409** [comment]
@pcr910303 thx for your reply, I have run `brew install emacs-plus --with-xwidgets --HEAD --debug`. I don't know how to change patch file and I try modify `src/xwidget.c` directly in debug mode, then I have installed it successfully.  Another question, can `xwidget` use proxy?

**Comment by pcr910303** [comment]
@hanfeng0409 If you are asking about `xwidget-webkit`, you should configure your system proxy for that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hanfeng0409** [comment]
@pcr910303 thx
