### ISSUE TITLE
Is it possible to enable xwidgets?

### ISSUE THREAD

**Issue by brabalan** [d12frosted/homebrew-emacs-plus#17]
As your version lets one choose many new configuration options, I was wondering if it could be used to build an xwidgets-enabled emacs.

**Comment by d12frosted** [comment]
I thought about adding support for this. Thanks to Sylvain `emacs-plus` allows user to build with `X` support. So it should be not hard to build with `xwidgets-enabled` support. PRs are welcome 😸

**Comment by Pitometsu** [comment]
@d12frosted could it use native ns cocoa webkit support (like here https://github.com/veshboo/emacs)?

**Comment by d12frosted** [comment]
Yes! Thanks to @irfn we now have the support of xwidgets! 

5581568c7f2c235860d1ad729e5c150ea5574769
