### ISSUE TITLE
Emacs doesn't cover the full screen

### ISSUE THREAD

**Issue by t-hart** [d12frosted/homebrew-emacs-plus#177]
I tried to install the formula with a couple different options, but they all seemed to cause the same effect where the application window wouldn't fill the whole screen or assigned area.

When given its own space, it's vertically (and maybe horizontally) shorter than my install of Emacs 26.3 (the Railwaycat version). When run as a floating window on the desktop, it wouldn't cover the whole desktop, leaving a visible gap on the bottom and to the right:
![Screenshot 2020-01-10 at 08 37 36](https://user-images.githubusercontent.com/17786332/72134521-9cf19880-3384-11ea-825e-1251ddea8dd1.png). I run Amethyst as a window manager, and all other windows cover the screen fully.

I'm not sure what the cause is, or whether this is on you or not, but I thought I'd flag the issue and get some input on what's going on.

Note: when installing without any options, I did get it to cover my laptop screen, but the issue persists on my external monitor. I have not used the laptop screen for any of the of other install configurations, so I don't know whether that'd work or not.

# Installations I've tried:
Regular:
```
$ brew install emacs-plus
```

`--HEAD`:
```
$ brew install emacs-plus --HEAD
```

Bunch of options:
```
brew install emacs-plus --HEAD --with-ctags --with-jansson --with-modern-icon --with-no-titlebar --with-dbus
```

Like above, but without `--with-no-titlebar`:
```
brew install emacs-plus --HEAD --with-ctags --with-jansson --with-modern-icon --with-dbus
```

**Comment by d12frosted** [comment]
Hey @t-hart 

Can you please try setting `(setq frame-resize-pixelwise t)` somewhere soon in your `init.el` file?

**Comment by t-hart** [comment]
Sure! I won’t be back in until Monday, but I’ll give it a go then. Feel free to nudge me if I forget 😁

**Comment by d12frosted** [comment]
@t-hart so it's Monday and here I am, pinging you to check ;)

**Comment by t-hart** [comment]
Thanks for reminding me! So I tried setting `frame-resize-pixelwise` to `t`, and am happy to report that it appears to be working! What exactly does this do and why does it change the behaviour in this manner?

**Comment by d12frosted** [comment]
No problem! I am glad that it helped! It's actually mentioned in the README file, but hidden behind description of `no-titlebar` option.

In general, when it comes to Emacs configuration, describe functions are the good starting point (e.g. `C-h v frame-resize-pixelwise`). Basically, by default Emacs round the frame size to `frame-char-height ` and `frame-char-width` so you don't see half characters. It's debatable whether it's a good default or not :)
