### ISSUE TITLE
Could not install with --with-no-titlebar --HEAD

### ISSUE THREAD

**Issue by d12frosted** [d12frosted/homebrew-emacs-plus#182]
**Describe the bug**
Installation fails because of patch application.

**Command used to install `emacs-plus`**

```
$ brew install emacs-plus --HEAD --with-no-titlebar
```

**Installation log**

See it here: https://github.com/d12frosted/emacs-plus-basis/runs/414453709?check_suite_focus=true

**Comment by d12frosted** [comment]
Fixed https://github.com/d12frosted/emacs-plus-basis/runs/414745879?check_suite_focus=true

**Comment by jsmestad** [comment]
This is now triggering a checksum error for me.

```
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/fix-window-role.patch
Already downloaded: /Users/jsmestad/Library/Caches/Homebrew/downloads/b7046a273c114e23f734df97967f4016486f1d080bad1ba40dbd53a5c86a09e0--fix-window-role.patch
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: ae92602a95564efe1aecec85563b116bf4211371a7c1f7e5d9c356107b4adf6d
  Actual: b1cd82886e238e1746bc726162f37f60d309446e9a7be7b22c8dca9bd5e8ef91
 Archive: /Users/jsmestad/Library/Caches/Homebrew/downloads/b7046a273c114e23f734df97967f4016486f1d080bad1ba40dbd53a5c86a09e0--fix-window-role.patch
To retry an incomplete download, remove the file above.
```

**Comment by d12frosted** [comment]
🤔 it's interesting, because it thinks that it has already downloaded this patch and then runs the checksum validation. Can you please run `brew update` and try again?

I see that on [CI it's building properly](https://github.com/d12frosted/homebrew-emacs-plus/runs/414796150#step:3:251) (haven't tried on my computer yet).

**Comment by jsmestad** [comment]
Yeah, I am up to date there. I'm not sure what is happening either.

**Comment by jsmestad** [comment]
If I manually delete the file, it works. Looks like homebrew tries to cache the patch files even when running `git cleanup`

**Comment by d12frosted** [comment]
🤔 wow, it's really interesting. Not sure why it behaves like this. Will try to reproduce it. Maybe I did something wrong when defining the patch? Maybe there is a notion of revisions for patch? 

anyway, thank you for letting me know about the problem and I am happy that you found a workaround!

**Comment by d12frosted** [comment]
Don't see any useful information i [Formula Cookbook][1] regarding patch versioning. Checked also [class documentation][2]. I actually expected hash to be some kind of versioning mechanism. 🤔 

  [1]: https://docs.brew.sh/Formula-Cookbook
  [2]: https://rubydoc.brew.sh/Formula#patch-class_method
