### ISSUE TITLE
Could not install with [OPTIONS]

### ISSUE THREAD

**Issue by ciju** [d12frosted/homebrew-emacs-plus#184]
**Describe the bug**
Installation fails for no-titlebar on emacs-27-branch

**Command used to install `emacs-plus`**

```
$ brew install emacs-plus --HEAD --with-no-titlebar --with-emacs-27-branch --with-modern-icon --with-jansson
```

**Installation log**

```
==> Installing emacs-plus from d12frosted/emacs-plus
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/ciju/Library/Caches/Homebrew/emacs-plus--git
From https://github.com/emacs-mirror/emacs
 * branch                  master     -> FETCH_HEAD
   1bcac29b2f..de41161534  emacs-27   -> origin/emacs-27
==> Checking out branch emacs-27
Switched to branch 'emacs-27'
Your branch is behind 'origin/emacs-27' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at de41161534 Tab-bar related fixes.
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/no-titlebar-head.patch
Already downloaded: /Users/ciju/Library/Caches/Homebrew/downloads/9319cd2ff30a3f17d70abca98290e9f42e50b30a19a59ca52466eadb7cb45bf8--no-titlebar-head.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/fix-window-role.patch
Already downloaded: /Users/ciju/Library/Caches/Homebrew/downloads/b7046a273c114e23f734df97967f4016486f1d080bad1ba40dbd53a5c86a09e0--fix-window-role.patch
==> Patching
==> Applying no-titlebar-head.patch
patching file src/nsterm.m
Hunk #1 succeeded at 470 (offset -3 lines).
Hunk #2 succeeded at 1828 (offset -76 lines).
Hunk #3 succeeded at 7007 (offset -17 lines).
Hunk #4 succeeded at 7382 with fuzz 2 (offset -21 lines).
Hunk #5 FAILED at 7417.
1 out of 5 hunks FAILED -- saving rejects to file src/nsterm.m.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/emacs-plus--patch-20200131-38205-dke5ia/no-titlebar-head.patch` exited with 1.
```

**Comment by d12frosted** [comment]
Hi @ciju,

Recently I fixed this issue. Can you please `brew update` and try installing again? If you get the hash mismatch, please let me know and [check this thread](https://github.com/d12frosted/homebrew-emacs-plus/issues/182#issuecomment-579863402).

**Comment by ciju** [comment]
hey @d12frosted brew is up to date. The error happens only if both `--with-no-titlebar` and `--with-emacs-27-branch` are passed in options. If I use only one of them, the installation goes through. E.g. Right now, I have `brew install emacs-plus --HEAD --with-emacs-27-branch --with-modern-icon --with-jansson` installed.

**Comment by d12frosted** [comment]
Ah right. I've updated the HEAD patch, but emacs-27 should be the same as it was before. Oh well. Thank you very much for letting me know about this issue.

I am not sure if I will fix it today, but will try to do it on Sunday. Does this work for you?

**Comment by ciju** [comment]
Hey, no hurry :) Thanks in advance for your help.

**Comment by d12frosted** [comment]
@ciju added a test case and fixed the patch for emacs-27 branch. Let me know if it doesn't work for you 😸

**Comment by ciju** [comment]
Hey @d12frosted Thanks. But after installation, emacs is crashing.

```

**Comment by d12frosted** [comment]
🤔 I just tried installing it like this and it doesn't crash (I have runtime errors related to my configurations, but nothing more).

**Comment by d12frosted** [comment]
The last commit fixes it. Just tested it. @ciju can you please check once more?

**Comment by ciju** [comment]
Thanks @d12frosted Installed successfully.

**Comment by d12frosted** [comment]
@ciju nice, happy to hear that it works!
