### ISSUE TITLE
Install throws error "Error: undefined method `rebuild' for #<BottleSpecification:0x007f8f7d9e2c80>"

### ISSUE THREAD

**Issue by jaschwar** [d12frosted/homebrew-emacs-plus#19]
After running 
brew tap d12frosted/emacs-plus
```
==> Tapping d12frosted/emacs-plus
Cloning into '/usr/local/Library/Taps/d12frosted/homebrew-emacs-plus'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Tapped 1 formula (28 files, 120K)

```
And fails on 
brew install emacs-plus
```
Error: undefined method `rebuild' for #<BottleSpecification:0x007fad4d126c48>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus.rb:9:in `block in <class:EmacsPlus>'
```

**Comment by d12frosted** [comment]
Hey,

That's totally strange. Have you tried dong `brew update` before installing?

**Comment by jaschwar** [comment]
Ha spent 15 min getting brew update, but once I resolved that, install worked.

For those curious this were good threads for get brew update to work :
https://github.com/Homebrew/brew/issues/1511
https://github.com/Homebrew/brew/issues/476


Thanks for the help @d12frosted

**Comment by d12frosted** [comment]
Oh well! Glad you figured it out! 😸 

Usually I run `brew doctor` when something fails. Sometimes it helps me to figure out what's wrong with my setup. 

> Thanks for the help @d12frosted

👍 

I am closing this issue. In case you have other questions/problems, just let me know.
