### ISSUE TITLE
Is --with-x11 broken for Catalina?

### ISSUE THREAD

**Issue by nessus42** [d12frosted/homebrew-emacs-plus#190]
It doesn't seem to be working for me. All I get is the app version of Emacs, not the X11 version.

Thanks.

**Comment by d12frosted** [comment]
Can you please share the exact installation options?

**Comment by d12frosted** [comment]
Ok, it seems that it doesn't work even in 26.3. So to reproduce:

```
$ brew install emacs-plus --with-x11
```

**Comment by d12frosted** [comment]
Ok, solution is to install like this:

``` 
$ brew install emacs-plus --with-x11 --without-cocoa
```

I will fix this later 😸

**Comment by d12frosted** [comment]
So now it's enough to use `--with-x11` option.
