### ISSUE TITLE
Can add this icon ?

### ISSUE THREAD

**Issue by taigacute** [d12frosted/homebrew-emacs-plus#191]
Is it possible to add this [icon](https://www.gnu.org/graphics/heckert_gnu.html)?

**Comment by d12frosted** [comment]
Sure. I will add it shortly.

**Comment by taigacute** [comment]
@d12frosted  thanks for your great work.

**Comment by d12frosted** [comment]
Added. You can install it using the following command.

```bash
$ brew install emacs-plus --with-gnu-head-icon
```

Some happy screenshots.

<img width="771" alt="Screenshot 2020-03-27 at 12 57 30" src="https://user-images.githubusercontent.com/6507913/77749792-4ca4e100-702b-11ea-9bbf-72371e578ef6.png">

I love it. Thank you for the idea! ❤️

**Comment by taigacute** [comment]
thanks for your love .
