### ISSUE TITLE
[yabai] Post frames are treated as regular windows when built `with-no-titlebar`

### ISSUE THREAD

**Issue by glepnir** [d12frosted/homebrew-emacs-plus#192]
**Describe the bug**

check this https://github.com/koekeishiya/yabai/issues/460

**Comment by scottgrayson** [comment]
@glepnir in the yabai issue you linked. It seems like you had found a workaround. Is this true? If so, could you comment the steps to workaround here?

**Comment by eeshugerman** [comment]
I'm not sure this is the same problem, but I too am seeing issues with posframe and `--with-no-titlebar`. I use `     ivy-posframe
     which-key-posframe

**Comment by eeshugerman** [comment]
I'm not sure this is the same problem, but I too am seeing issues with posframe and `--with-no-titlebar`. I use `ivy-posframe` and `which-key-posframe`. I do not use yabai. The issue I'm seeing is this: when I switch to a non-emacs window and then switch back to emacs, a posframe will have appeared somewhere in the frame, often (when?) in the wrong place. It's sometimes an ivy posframe and sometimes a which-key posframe (presumably whichever I used last, though I'd have to double check this).

**Comment by Artawower** [comment]
any news?

**Comment by d12frosted** [comment]
No news, sorry. I think the fix would be rewrite `no-titlebar.patch` in a way that it does not use `EmacsFSWindow` (as far as I understand this is a problem). Ideally this patch should not be so intrusive and just allow users to decide if they want title bar or no from elisp.

**Comment by spolakh** [comment]
👋 @d12frosted wondering if this might be on your radar? wondering how do you go about this in your own usage - does your set up not rely on posframes or do you just not use no-titlebar option?

**Comment by d12frosted** [comment]
@spolakh not on my radar, tbh. I am not using this patch as I gave up my hopes on making macos UI/UX good.

**Comment by cmacrae** [comment]
I've opened the above PR which addresses this :)

**Comment by d12frosted** [comment]
@glepnir could you please try again?

**Comment by smallstepman** [comment]
sadly, the issue is still present

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/21069150/171526763-d5ebf99e-0736-4da9-85ab-d019a834b83e.png">

```
❯ yabai -m rule --add app=Emacs manage=on space=2

❯ yabai -m rule --list
[{
	"index":0,
	"label":"",
	"app":"Emacs",
	"title":"",
	"display":1,
	"space":2,
	"follow_space":false,
	"opacity":0.0000,
	"manage":true,
	"sticky":null,
	"mouse_follows_focus":null,
	"layer":"",
	"border":null,
	"native-fullscreen":null,
	"grid":"0:0:0:0:0:0"
}]

❯ brew list --versions | rg emacs
emacs-plus@28 HEAD-86b49d5

❯ yabai -v
yabai-v4.0.1

❯ .emacs.d/bin/doom version
> Executing 'doom version' with Emacs 28.1.50 at 2022-06-02 03:17:53
  GNU Emacs     v28.1.50         nil
  Doom core     v3.0.0-dev       HEAD -> master 1b8f46c7 2022-05-27 03:13:00 +0200
  Doom modules  v22.05.0-dev     HEAD -> master 1b8f46c7 2022-05-27 03:13:00 +0200
```

```
    Package: posframe
     Source: Straight
     Pinned: c91d4d53fa479ceb604071008ce0a901770eff57
      Build: grafted, HEAD -> master c91d4d5 2022-01-24 16:59:25 +0800
```

```
    Package: vertico-posframe
     Source: Straight
     Pinned: unpinned
      Build: grafted, HEAD -> master, origin/master, origin/HEAD 8cd6c2c 2022-04-16 00:06:54 +0000
```

P.S. thanks for all the work so far ❤️, I'd gouge my eyes out if it wasn't for your `--no-titllebar` mod

**Comment by noctuid** [comment]
>  yabai -m rule --add app=Emacs manage=on 

You shouldn't manually add a rule to manage Emacs.  That will make any Emacs window tiled.

**Comment by noctuid** [comment]
A lot of child frame windows do not have easily distinguishable titles by default. It is better to just have no tiling rule for Emacs. It is unnecessary in the first place.

**Comment by gusgustavsohn** [comment]
> @smallstepman
> 
> > edit: perhaps there is a way to tell yabai to ignore managing that particular window... not sure how to do it tho
> 
> There is way to ignore specific window using `title!="^posframe$"`
> 
> `yabai -m rule --add app="^Emacs$" title!="^posframe$" space=code manage=on`

That line solves it for me. Thank you @AmayruN5 !
