### ISSUE TITLE
Could not install with --with-xwidgets with version 27, and without it Emacs.app disappear

### ISSUE THREAD

**Issue by MuhmdRaouf** [d12frosted/homebrew-emacs-plus#196]
**Describe the bug**
Trying to install emacs ver 27 with the following options, but it always gave me this error and I don't know what to do, also Cocoa should be enabled by default.

**Command used to install `emacs-plus`**

```
$ brew install emacs-plus --HEAD --with-emacs-27-branch --with-dbus --with-jansson --with-modern-icon --without-spacemacs-icon --with-xwidgets --with-x11
```

**Installation log**

```
snowflake in ~ took 2m 8s
[I] ➜ brew install emacs-plus --HEAD --with-emacs-27-branch --with-dbus --with-jansson --with-modern-icon --without-spacemacs-icon --with-xwidgets --with-x11
Updating Homebrew...
Successfully rebased and updated refs/heads/master.
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
vroom
==> Updated Formulae
jfrog-cli-go                                                                    libphonenumber                                                                  rancher-cli

Error: --with-xwidgets is supported only on cocoa via xwidget webkit
```

Also when I installed it using the following but Emacs.app didn't exist and i have to use emacs from terminal now with the following command:

```
snowflake in ~ took 13s
[I] ➜ brew install emacs-plus --with-emacs-27-branch --with-jansson --with-modern-icon --with-x11 --without-spacemacs-icon --HEAD
==> Installing emacs-plus from d12frosted/emacs-plus
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

==> Cloning https://github.com/emacs-mirror/emacs.git
Cloning into '/Users/snowflake/Library/Caches/Homebrew/emacs-plus--git'...
Updating files: 100% (4021/4021), done.
==> Checking out branch emacs-27
Already on 'emacs-27'
Your branch is up to date with 'origin/emacs-27'.
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/fix-window-role.patch
######################################################################## 100.0%
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8507 (offset -19 lines).
==> ImageMagick PKG_CONFIG_PATH:
/usr/local/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-ac3da1d/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-ac3da1d --with-xml2 --without-dbus --with-gnutls --wit
==> make
==> make install
==> Caveats
Emacs.app was installed to:
  /usr/local/opt/emacs-plus

To link the application to default Homebrew App location:
  ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications

--natural-title-bar option was removed from this formula, in order to
  duplicate its effect add following line to your init.el file
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark))
or:
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . light))


To have launchd start d12frosted/emacs-plus/emacs-plus now and restart at login:
  brew services start d12frosted/emacs-plus/emacs-plus
Or, if you don't want/need a background service you can just run:
  emacs
==> Summary
🍺  /usr/local/Cellar/emacs-plus/HEAD-ac3da1d: 4,006 files, 105MB, built in 9 minutes 56 seconds
```

**Comment by d12frosted** [comment]
Hi @MuhmdRaouf 

Well, the error says it all.

```
Error: --with-xwidgets is supported only on cocoa via xwidget webkit
```

Which means that you need to install with cocoa (e.g. don't use `--with-x11`). Maybe it's not that clear after all 🤔 

> Also when I installed it using the following but Emacs.app didn't exist and i have to use emacs from terminal now with the following command:

Not sure which command exactly you use. But as caveats sections says, if you want to install `Emacs.app` to `/Applications` folder, you need to link it using `ln -s`. Cask builds are not supported (see #41).

**Comment by MuhmdRaouf** [comment]
@d12frosted Ouch the message tells me what I need but I didn't realize it, sorry but I think it's not really clear, at least for me, But Thanks so much for your replay mate.

secondly the command I used 
`brew install emacs-plus --with-emacs-27-branch --with-jansson --with-modern-icon --with-x11 --without-spacemacs-icon --HEAD`

and I did link it as the logs told me like the following 
`ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications`

yet the link was broken and I went into this path `ln -s /usr/local/opt/emacs-plus`
and didn't found the `Emacs.app` which is very strange to me.

PS. removing the flag `--with-x11` solve it and the Emacs worked like a charm.

**Comment by d12frosted** [comment]
> Ouch the message tells me what I need but I didn't realize it, sorry but I think it's not really clear, at least for me,

Yeah... Thanks to you I also realized how unclear it might be.

Yeah, x11 means that you don't want cocoa application, which means, that you won't get `Emacs.app`. Maybe it also needs to be documented.

**Comment by MuhmdRaouf** [comment]
I can confirm that removing `--with-x11` solves both issues for me, Thanks a lot @d12frosted 😄

**Comment by d12frosted** [comment]
No problem! Let me know if you have any other issues!
