### ISSUE TITLE
Unable to get both cocoa and non-cocoa versions at the same time

### ISSUE THREAD

**Issue by cassianoleal** [d12frosted/homebrew-emacs-plus#2]
I'd like to have the option of either using the `Emacs.app` cocoa app or just open `emacs` regularly in the terminal. It looks like if I set the `--with-cocoa` flag I don't get the shell-based one.

**Comment by d12frosted** [comment]
Shell-based one is not related to `--with-cocoa` flag. To run Emacs in terminal, you have to call `emacs -nw`, which actually means `emacs --no-window-system`.

**Comment by cassianoleal** [comment]
Ah cool! Thanks for the clarification!
