### ISSUE TITLE
emacs27: default-directory is `/` instead of `~/`

### ISSUE THREAD

**Issue by verdammelt** [d12frosted/homebrew-emacs-plus#220]
I notice that the `default-directory` is different when running emacs 27 from that of emacs 26.3 when installed with this brew. Is this a change in emacs or in the way this brew builds/installs it?

Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Installing a version of emacs 27 with this brew and running Emacs.app.

## What happened (include command output)

<pre>
$ brew install emacs-plus --with-emacs-27-branch --HEAD
</pre>

<details>
The command worked fine but then when running Emacs.app the `default-directory` is set to `/` instead of `~` as it was when installing version 26.3 via `brew install emacs-plus`
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.17-29-gb2fc8ad
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b2fc8ad7b3fa874ac76f4ee2fba48f7535487caa
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 20d2a8835a31a7ac2de554d0c1627b90631381ad
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.aXxDBIaJtU/org.macosforge.xquartz:0
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_73, 1.7.0_05
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by d12frosted** [comment]
I also can reproduce this 'issue', though I am not sure where it originates from. I tried searching for any relevant stuff in news for Emacs 27.1, but didn't find anything.

On the other hand, when I start Emacs 27.1+ from terminal, my `default-directory` is correct (e.g. `$HOME`). So it might be a combination of some changes in Emacs and the way macOS starts applications (e.g. when you open `Emacs.app`).

Maybe (just maybe), it's related to this change:

```
** Interpretation of relative 'HOME' directory has changed.
If "$HOME" is set to a relative file name, 'expand-file-name' now
interprets it relative to the directory where Emacs was started, not
relative to the 'default-directory' of the current buffer.  We recommend
always setting "$HOME" to an absolute file name, so that its meaning is
independent of where Emacs was started.
```

But when I print value of `$HOME` at the very beginning of `init.el` it shows me proper value, so 🤷

**Comment by d12frosted** [comment]
Oh, found this: https://lists.gnu.org/archive/html/help-gnu-emacs/2020-04/msg00232.html

**Comment by verdammelt** [comment]
Ah, thanks for the link to that thread. I read that newsgroup - but mostly skimming and I only tried emacs 27 over the last few days. I'll keep an eye on it and hope for a solution.

So I shall close this ticket - sorry for the noise and thanks for the help.
