### ISSUE TITLE
Could not install with --with-emacs-27-branch --HEAD

### ISSUE THREAD

**Issue by aaronjensen** [d12frosted/homebrew-emacs-plus#221]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What happened (include command output)

<pre>
$ brew install emacs-plus --with-emacs-27-branch --HEAD
</pre>

<details>
  <summary>Command output</summary>
  <pre>

Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/aaronjensen/Library/Caches/Homebrew/downloads/1f28e8ad86a6243e1328a76837779dbfc098b731e2f0343f1d27b4bd84a4ab5a--system-appearance-emacs-27.patch

  </pre>
</details>

If I download that file manually, I get: 

<details>

<summary>Patch application failure</summary>

<pre>
==> Applying system-appearance-emacs-27.patch
patching file src/frame.h
Hunk #1 FAILED at 70.
1 out of 1 hunk FAILED -- saving rejects to file src/frame.h.rej
patching file src/nsfns.m
Hunk #1 FAILED at 1269.
1 out of 1 hunk FAILED -- saving rejects to file src/nsfns.m.rej
patching file src/nsterm.m
Hunk #1 FAILED at 2027.
Hunk #2 FAILED at 7496.
Hunk #3 succeeded at 8325 with fuzz 2 (offset 68 lines).
Hunk #4 succeeded at 9945 (offset 285 lines).
2 out of 4 hunks FAILED -- saving rejects to file src/nsterm.m.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/var/tmp/emacs-plus--patch-20200520-89937-zyoa68/system-appearance-emacs-27.patch` exited with 1.
</pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.17-49-gb759270
ORIGIN: https://github.com/Homebrew/brew
HEAD: b75927091eea4b1dcb7951db746314d884b5b008
Last commit: 65 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 894388b4ac839d05adfc7f2d40af1de26f351c20
Core tap last commit: 39 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: e
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_TEMP: /var/tmp
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_232
macOS: 10.15.4-x86_64
CLT: 11.0.33.16
Xcode: 11.4.1
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/Spyder.dylib
  /usr/local/lib/Spyder3.dylib
  /usr/local/lib/Spyder5.dylib
  /usr/local/lib/dccmtr.dylib
  /usr/local/lib/dcxmtr.dylib
  /usr/local/lib/libCIEHandler.dylib
  /usr/local/lib/libCalibrationHandler.dylib
  /usr/local/lib/libCompression.dylib
  /usr/local/lib/libDeviceManager.dylib
  /usr/local/lib/libErrorHandler.dylib
  /usr/local/lib/libICMManager.dylib
  /usr/local/lib/libMCCAppManager.dylib
  /usr/local/lib/libMCCEngineWrapper.dylib
  /usr/local/lib/libMonitorDDCCISDK.dylib
  /usr/local/lib/libProtocolEngine.dylib
  /usr/local/lib/libQM2Lib.dylib
</pre>

**Comment by d12frosted** [comment]
I saw something similar on CI recently, but now it's good. Can you please try again?

**Comment by aaronjensen** [comment]
Yep, working now. Thanks.
