### ISSUE TITLE
Automatic support for ligatures like in emacs-mac

### ISSUE THREAD

**Issue by CarlQLange** [d12frosted/homebrew-emacs-plus#222]
Hey, thanks so much for emacs-plus, I love it very much.

I recently switched to Fira Code and was looking to start using some of the ligatures. There are a [lot of ways](https://github.com/tonsky/FiraCode/wiki/Emacs-instructions) to get this to work in emacs (notably `prettify-symbols-mode`) but I noticed that the mituharu emacs-mac fork has a patch for adding automatic ligatures (mentioned in the linked document), and I was wondering if it might be possible to add for us.

My elisp (and my understanding of the emacs build process) is quite poor so I don't know if I have the ability to add a PR at this time - or whether it's even possible to do this at all.

Looks like the implementation is [here](https://bitbucket.org/mituharu/emacs-mac/src/26c8fd9920db9d34ae8f78bceaec714230824dac/lisp/term/mac-win.el?at=master#lines-751), although I get the feeling it's going to sit on a pyramid of emacs-mac specific code...

Otherwise, I was wondering if it would be possible (or sensible) to add this in some other way, natively to emacs-plus. OSX has no problem automatically adding these ligatures in other applications - it would be nice to have it be so easy within Emacs as well 😅

**Comment by d12frosted** [comment]
@CarlQLange thank you for opening this feature request! Especially for filling it with so many useful information to understand what exactly you want and with links to possible solution ❤️ 

I need to check it, but I fear that it's more than just `emacs-lisp` code that makes it possible. I don't use ligratures, because I have an ad-hoc solution embedded into my brain that transforms `\` into lambda, `>>=` into... wait what?

Jokes aside, I will install `emacs-mac` to see how it looks and then will check what's needed to replicate it in `emacs-plus`.

**Comment by CarlQLange** [comment]
Ok, totally, I don't think I even like ligatures, but I got jealous of a screenshot 😅 (And according to [this comment](https://github.com/hlissner/doom-emacs/issues/2217#issuecomment-568037014), Fira Code might work better with emacs than my preferred font, Input - I haven't got a clue if that's true, but I also couldn't help but try and get more performance)

Yeah, I have a feeling it would be quite a deep patch - I think Mituharu did a lot of work in this area to make other alphabets display nicely in Emacs, and ligatures aren't that far away conceptually.

**Comment by CarlQLange** [comment]
Hmm, after another look, it doesn't seem like the emacs-mac port is doing anything enormously special beyond what this code would also do:

```
(let ((alist '((33 . ".\\(?:\\(?:==\\|!!\\)\\|[!=]\\)")
               (35 . ".\\(?:###\\|##\\|_(\\|[#(?[_{]\\)")
               (36 . ".\\(?:>\\)")
               (37 . ".\\(?:\\(?:%%\\)\\|%\\)")
               (38 . ".\\(?:\\(?:&&\\)\\|&\\)")
               (42 . ".\\(?:\\(?:\\*\\*/\\)\\|\\(?:\\*[*/]\\)\\|[*/>]\\)")
               (43 . ".\\(?:\\(?:\\+\\+\\)\\|[+>]\\)")
               (45 . ".\\(?:\\(?:-[>-]\\|<<\\|>>\\)\\|[<>}~-]\\)")
               (46 . ".\\(?:\\(?:\\.[.<]\\)\\|[.=-]\\)")
               (47 . ".\\(?:\\(?:\\*\\*\\|//\\|==\\)\\|[*/=>]\\)")
               (48 . ".\\(?:x[a-zA-Z]\\)")
               (58 . ".\\(?:::\\|[:=]\\)")
               (59 . ".\\(?:;;\\|;\\)")
               (60 . ".\\(?:\\(?:!--\\)\\|\\(?:~~\\|->\\|\\$>\\|\\*>\\|\\+>\\|--\\|<[<=-]\\|=[<=>]\\||>\\)\\|[*$+~/<=>|-]\\)")
               (61 . ".\\(?:\\(?:/=\\|:=\\|<<\\|=[=>]\\|>>\\)\\|[<=>~]\\)")
               (62 . ".\\(?:\\(?:=>\\|>[=>-]\\)\\|[=>-]\\)")
               (63 . ".\\(?:\\(\\?\\?\\)\\|[:=?]\\)")
               (91 . ".\\(?:]\\)")
               (92 . ".\\(?:\\(?:\\\\\\\\\\)\\|\\\\\\)")
               (94 . ".\\(?:=\\)")
               (119 . ".\\(?:ww\\)")
               (123 . ".\\(?:-\\)")
               (124 . ".\\(?:\\(?:|[=|]\\)\\|[=>|]\\)")
               (126 . ".\\(?:~>\\|~~\\|[>=@~-]\\)")
               )
             ))
  (dolist (char-regexp alist)
    (set-char-table-range composition-function-table (car char-regexp)
                          `([,(cdr char-regexp) 0 font-shape-gstring]))))
```

The above block is specific to Fira Code, and I suppose the main difference is that the emacs-mac code has a smaller subset of symbols that are more likely to work.

So I think it's probably fine to close this as something the user can just write themselves - unless you think it really should be in the formula. I think it would still be a pretty nice feature to have by default, given that most native Mac apps add ligatures without question.

**Comment by mtienni** [comment]
Are there plans to add the option of compiling with harfbuzz and cairo? That would make for a simpler solution by using ```ligature.el``` (https://github.com/mickeynp/ligature.el)
```python
a = 1
def c(a):
    a = 2 * a
    return a
```

**Comment by d12frosted** [comment]
I think that since it's easy to achieve this using some Emacs Lisp, there is no need to patch GNU Emacs. I don't want to diverge too much from the upstream 😸 

@CarlQLange thank you for sharing the snippet! I hope that it would help someone :)
