### ISSUE TITLE
emacs-plus exits immediately

### ISSUE THREAD

**Issue by markghayden** [d12frosted/homebrew-emacs-plus#225]
I'm on MacOS 10.15.5.  Normal emacs from Homebrew works but I want to be able to use emacs with X11 support.  When I run emacs-plus version as installed below, all I get is process exiting immediately with "Killed".  When I remove the "--with-x11" option, it seems to run fine.  Something about the "--with-x11" is not working.  Please let me know if there is additional information I can provide.

best, Mark

brew tap d12frosted/homebrew-emacs-plus
brew install d12frosted/emacs-plus/emacs-plus --with-x11

**Comment by d12frosted** [comment]
Hi @markghayden. Please see #195.

Closing as duplicate

**Comment by d12frosted** [comment]
In short, it's a know bug without good solution. Hopefully Emacs 27 will be released soon, which fixes this issue. 

In order to workaround now - please install using `--HEAD` option or `--HEAD --with-emacs-27-branch` or avoid passing any options at all.

**Comment by markghayden** [comment]
Thanks!  Just --HEAD would not build.  --HEAD and --with-emacs-27-branch built and seems to work.
