### ISSUE TITLE
Could not add tap with "brew tap d12frosted/emacs-plus"

### ISSUE THREAD

**Issue by aqrln** [d12frosted/homebrew-emacs-plus#228]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

`$ brew tap d12frosted/emacs-plus`

## What happened (include command output)

<pre>
$ brew tap d12frosted/emacs-plus
</pre>

<details>
  <summary>Command output</summary>
  <pre>
==> Tapping d12frosted/emacs-plus
Cloning into '/usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus'...
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 1224 (delta 78), reused 169 (delta 65), pack-reused 1039
Receiving objects: 100% (1224/1224), 5.07 MiB | 2.77 MiB/s, done.
Resolving deltas: 100% (533/533), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/PatchUrlResolver.rb
No available formula with the name "PatchUrlResolver"
In formula file: /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/PatchUrlResolver.rb
Expected to find class Patchurlresolver, but only found: PatchUrlResolver (not derived from Formula!).
Error: Cannot tap d12frosted/emacs-plus: invalid syntax in tap!
  </pre>
</details>

<pre>
$ brew tap d12frosted/emacs-plus --debug
</pre>

<details>
  <summary>Command output</summary>
  <pre>
==> Tapping as full clone
==> Tapping d12frosted/emacs-plus
Cloning into '/usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus'...
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 1224 (delta 78), reused 169 (delta 65), pack-reused 1039
Receiving objects: 100% (1224/1224), 5.07 MiB | 3.22 MiB/s, done.
Resolving deltas: 100% (533/533), done.
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/PatchUrlResolver.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/PatchUrlResolver.rb
No available formula with the name "PatchUrlResolver"
In formula file: /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/PatchUrlResolver.rb
Expected to find class Patchurlresolver, but only found: PatchUrlResolver (not derived from Formula!).
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@28.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@27.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus.rb
Error: Cannot tap d12frosted/emacs-plus: invalid syntax in tap!
/usr/local/Homebrew/Library/Homebrew/tap.rb:275:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 2.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 77e09fc166f5fb7197b239d5e2727ddc0791c121
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3d68b330eb58d8dd9d1c85461df0feb9c8d0e7ef
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.gfs7XKp552/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.1, 1.8.0_91
macOS: 10.15.5-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h
  /usr/local/include/python3.7m/greenlet/greenlet.h
</pre>

**Comment by d12frosted** [comment]
Thanks for the report! I've prepared a fix (#229). If it will not work, I will just inline this helper.

**Comment by aqrln** [comment]
Thanks!

**Comment by d12frosted** [comment]
Hey. I am not near computer. Can you please test when I merge?

**Comment by aqrln** [comment]
Sure. I subscribed to notifications on the PR, but you may also ping me in this thread so that I won't miss the email. Thank you!

**Comment by aqrln** [comment]
```
Tapped 3 formulae (94 files, 10.5MB).
```

Worked like a charm, thanks!

**Comment by d12frosted** [comment]
Yay. Happy to hear that this risky change worked. Thanks for letting me know about the issue and for testing the fix.
