### ISSUE TITLE
misunderstanding on —with-xwidgets

### ISSUE THREAD

**Issue by beyondpie** [d12frosted/homebrew-emacs-plus#236]
Hi, 
Thank you so much for the great repo!
I face confusion when trying to install it with —with-xwigets.

While the document says (—HEAD only), and —HEAD says “build from emacs-27 … “.  Does it seem that xwidget can only be used on emacs-27? 

But I can install it with Emacs-28. Am I miss something?
Thanks!

**Comment by d12frosted** [comment]
Good point. Forgot to remove `--HEAD only` from the docs. If you want, send a PR ;)

**Comment by beyondpie** [comment]
#237

**Comment by d12frosted** [comment]
Thank you for the PR.

After I've split the packages, `--HEAD` has slightly different meaning now. Now each package installs only one major version. Emacs 26 (e.g. `emacs-plus` or `emacs-plus@26`) has only the released version, so there is no `--HEAD`. Emacs 27 (e.g. `emacs-plus@27`) can be built from the not-yet-release-candidate or from the latest sources (e.g. `emacs-27` branch), so it has `--HEAD` option. On the contrary, Emacs 28 doesn't has any snapshots, it's always from the latest `master`, so it doesn't have `--HEAD` option.
