### ISSUE TITLE
Could not install with --with-modern-icon-cg433n

### ISSUE THREAD

**Issue by fladd** [d12frosted/homebrew-emacs-plus#239]
Please make sure to follow these steps (and mark the checkboxes):

- [ x] run `brew update` and try to reproduce the issue again
- [x ] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I was trying to install with `brew install emacs-plus --with-modern-icon-cg433n`

## What happened (include command output)

<pre>
$ brew install emacs-plus -with-modern-icon-cg433n
</pre>

<details>
  <summary>Command output</summary>
  <pre>

Updating Homebrew...
Usage: brew install [options] formula

Install formula. Additional options specific to formula may be appended to
the command.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the installed formulae or, every 30 days, for all formulae.

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory.
        --env                        If std is passed, use the standard build
                                     environment instead of superenv. If super
                                     is passed, use superenv even if the formula
                                     specifies the standard build environment.
        --ignore-dependencies        An unsupported Homebrew development flag to
                                     skip installing any dependencies of any
                                     kind. If the dependencies are not already
                                     present, the formula will have issues. If
                                     you're not developing Homebrew, consider
                                     adjusting your PATH rather than using this
                                     flag.
        --only-dependencies          Install the dependencies with specified
                                     options but do not install the formula
                                     itself.
        --cc                         Attempt to compile using the specified
                                     compiler, which should be the name of the
                                     compiler's executable, e.g. gcc-7 for GCC
                                     7. In order to use LLVM's clang, specify
                                     llvm_clang. To use the Apple-provided
                                     clang, specify clang. This option will
                                     only accept compilers that are provided by
                                     Homebrew or bundled with macOS. Please do
                                     not file issues if you encounter errors
                                     while using this option.
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is provided. Dependencies will still
                                     be installed from bottles if they are
                                     available.
        --force-bottle               Install from a bottle if it exists for the
                                     current or newest version of macOS, even if
                                     it would not normally be used for
                                     installation.
        --include-test               Install testing dependencies required to
                                     run brew test formula.
        --devel                      If formula defines it, install the
                                     development version.
        --HEAD                       If formula defines it, install the HEAD
                                     version, aka. master, trunk, unstable.
        --fetch-HEAD                 Fetch the upstream repository to detect if
                                     the HEAD installation of the formula is
                                     outdated. Otherwise, the repository's HEAD
                                     will only be checked for updates when a new
                                     stable or development version has been
                                     released.
        --keep-tmp                   Retain the temporary files created during
                                     installation.
        --build-bottle               Prepare the formula for eventual bottling
                                     during installation, skipping any
                                     post-install steps.
        --bottle-arch                Optimise bottles for the specified
                                     architecture rather than the oldest
                                     architecture supported by the version of
                                     macOS the bottles are built on.
    -f, --force                      Install without checking for previously
                                     installed keg-only or non-migrated
                                     versions.
    -v, --verbose                    Print the verification and postinstall
                                     steps.
        --display-times              Print install times for each formula at the
                                     end of the run.
    -i, --interactive                Download and patch formula, then open a
                                     shell. This allows the user to run
                                     ./configure --help and otherwise
                                     determine how to turn the software package
                                     into a Homebrew package.
    -g, --git                        Create a Git repository, useful for
                                     creating patches to the software.
    -h, --help                       Show this message.

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 28ed0801ed5807e176e62a3ba66e47ec867ec17d
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f34594ce752ca8952293a25e9b3ce6ac4e1b9f76
Core tap last commit: 39 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.AE32iYem84/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_1/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 1.7.0_80
macOS: 10.14.5-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2
  pygtk
  dirmngr
  pygtksourceview
  gpg-agent
  shiboken
  ipython@5
  pygobject

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-science
Untap them with `brew untap`.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libmdc.2.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib
  /usr/local/lib/libwkhtmltox.0.12.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/jack/control.h
  /usr/local/include/jack/intclient.h
  /usr/local/include/jack/jack.h
  /usr/local/include/jack/jslist.h
  /usr/local/include/jack/metadata.h
  /usr/local/include/jack/midiport.h
  /usr/local/include/jack/net.h
  /usr/local/include/jack/ringbuffer.h
  /usr/local/include/jack/session.h
  /usr/local/include/jack/statistics.h
  /usr/local/include/jack/systemdeps.h
  /usr/local/include/jack/thread.h
  /usr/local/include/jack/transport.h
  /usr/local/include/jack/types.h
  /usr/local/include/jack/uuid.h
  /usr/local/include/jack/weakjack.h
  /usr/local/include/jack/weakmacros.h
  /usr/local/include/m-acr.h
  /usr/local/include/m-algori.h
  /usr/local/include/m-anlz.h
  /usr/local/include/m-color.h
  /usr/local/include/m-conc.h
  /usr/local/include/m-config.h
  /usr/local/include/m-debug.h
  /usr/local/include/m-defs.h
  /usr/local/include/m-depend.h
  /usr/local/include/m-dicm.h
  /usr/local/include/m-ecat64.h
  /usr/local/include/m-ecat72.h
  /usr/local/include/m-error.h
  /usr/local/include/m-fancy.h
  /usr/local/include/m-files.h
  /usr/local/include/m-getopt.h
  /usr/local/include/m-gif.h
  /usr/local/include/m-global.h
  /usr/local/include/m-init.h
  /usr/local/include/m-intf.h
  /usr/local/include/m-inw.h
  /usr/local/include/m-matrix.h
  /usr/local/include/m-nifti.h
  /usr/local/include/m-pixels.h
  /usr/local/include/m-png.h
  /usr/local/include/m-progress.h
  /usr/local/include/m-qmedian.h
  /usr/local/include/m-raw.h
  /usr/local/include/m-rslice.h
  /usr/local/include/m-split.h
  /usr/local/include/m-stack.h
  /usr/local/include/m-structs.h
  /usr/local/include/m-transf.h
  /usr/local/include/m-vifi.h
  /usr/local/include/m-xtract.h
  /usr/local/include/medcon.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/python3.5m/pygame/_camera.h
  /usr/local/include/python3.5m/pygame/_pygame.h
  /usr/local/include/python3.5m/pygame/_surface.h
  /usr/local/include/python3.5m/pygame/bitmask.h
  /usr/local/include/python3.5m/pygame/camera.h
  /usr/local/include/python3.5m/pygame/fastevents.h
  /usr/local/include/python3.5m/pygame/font.h
  /usr/local/include/python3.5m/pygame/freetype.h
  /usr/local/include/python3.5m/pygame/mask.h
  /usr/local/include/python3.5m/pygame/mixer.h
  /usr/local/include/python3.5m/pygame/pgarrinter.h
  /usr/local/include/python3.5m/pygame/pgbufferproxy.h
  /usr/local/include/python3.5m/pygame/pgcompat.h
  /usr/local/include/python3.5m/pygame/pgopengl.h
  /usr/local/include/python3.5m/pygame/pygame.h
  /usr/local/include/python3.5m/pygame/scrap.h
  /usr/local/include/python3.5m/pygame/surface.h
  /usr/local/include/python3.6m/pygame/_camera.h
  /usr/local/include/python3.6m/pygame/_pygame.h
  /usr/local/include/python3.6m/pygame/_surface.h
  /usr/local/include/python3.6m/pygame/bitmask.h
  /usr/local/include/python3.6m/pygame/camera.h
  /usr/local/include/python3.6m/pygame/fastevents.h
  /usr/local/include/python3.6m/pygame/font.h
  /usr/local/include/python3.6m/pygame/freetype.h
  /usr/local/include/python3.6m/pygame/mask.h
  /usr/local/include/python3.6m/pygame/mixer.h
  /usr/local/include/python3.6m/pygame/pgarrinter.h
  /usr/local/include/python3.6m/pygame/pgbufferproxy.h
  /usr/local/include/python3.6m/pygame/pgcompat.h
  /usr/local/include/python3.6m/pygame/pgopengl.h
  /usr/local/include/python3.6m/pygame/pygame.h
  /usr/local/include/python3.6m/pygame/scrap.h
  /usr/local/include/python3.6m/pygame/surface.h
  /usr/local/include/python3.7m/pygame/_camera.h
  /usr/local/include/python3.7m/pygame/_pygame.h
  /usr/local/include/python3.7m/pygame/_surface.h
  /usr/local/include/python3.7m/pygame/bitmask.h
  /usr/local/include/python3.7m/pygame/camera.h
  /usr/local/include/python3.7m/pygame/fastevents.h
  /usr/local/include/python3.7m/pygame/font.h
  /usr/local/include/python3.7m/pygame/freetype.h
  /usr/local/include/python3.7m/pygame/mask.h
  /usr/local/include/python3.7m/pygame/mixer.h
  /usr/local/include/python3.7m/pygame/palette.h
  /usr/local/include/python3.7m/pygame/pgarrinter.h
  /usr/local/include/python3.7m/pygame/pgbufferproxy.h
  /usr/local/include/python3.7m/pygame/pgcompat.h
  /usr/local/include/python3.7m/pygame/pgopengl.h
  /usr/local/include/python3.7m/pygame/pygame.h
  /usr/local/include/python3.7m/pygame/scrap.h
  /usr/local/include/python3.7m/pygame/surface.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libmdc.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/jack.pc
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libmdc.a
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  vim
  pandoc
  python@2
  ghostscript
  ipython
  pyside
  numpy
  jupyterlab
</pre>

**Comment by d12frosted** [comment]
Hello, `emacs-plus` (e.g. `emacs-plus@26`) doesn't offer icons right now. This is due #195. But since it was fixed, I am going to restore icons soon.

Right now either don't use icons, or use another Emacs version, e.g. `emacs-plus@27` or `emacs-plus@28`.

**Comment by d12frosted** [comment]
Just merged a commit (fd519ad) restoring icons for Emacs 26.

**Comment by d12frosted** [comment]
Sorry, there was actually a bug, and icons were fully restored for Emacs 26 in https://github.com/d12frosted/homebrew-emacs-plus/commit/12186d9a5f5dc809143d162711755f889a2e20c8
