### ISSUE TITLE
Not building with imagemagick

### ISSUE THREAD

**Issue by tokamach** [d12frosted/homebrew-emacs-plus#24]
as the title says, emacs-plus doesn't seem to have imagemagick compiled in. I thought it might be a path issue but after inspecting the ./configure logs when building it says something along the lines of `checking for imagemagick....     no`, so this is a compilation issue.

I built the home-brew standard formula with `brew install emacs --with-cocoa --with-gnutls --with-librsvg --with-imagemagick@6`, with which imagemagick is compiled in and works. Is this to do with the old version of imagemagick (hence the `@6`)? Can this part of the recipe be used in emacs-plus?

**Comment by d12frosted** [comment]
I have pushed a possible fix (thanks to upstream). Gonna test it and if everything works, I'll update the bottle.

**Comment by tokamach** [comment]
`(image-type-available-p 'imagemagick)` returns `t` for me now, so this seems to have worked.

Thanks so much for the quick response!

**Comment by d12frosted** [comment]
Oh. That's great that it works for you 😸 I can't test it right now due to some issues with brew :/ Will update the tap once it gets fixed.

**Comment by d12frosted** [comment]
Ok, works for me as well. Thanks for the report!
