### ISSUE TITLE
emacsclient in GUI mode with no title bar

### ISSUE THREAD

**Issue by jeremy-asher** [d12frosted/homebrew-emacs-plus#241]
I'm not sure if there is a separate patch for this, but when I start a daemon and launch emacsclient with `emacsclient -c -n` I still get the title bar, though the title bar patch works when not using emacsclient.  This is after an install of v27 using `--with-jansson --with-no-titlebar`.

**Comment by d12frosted** [comment]
Hello @jeremy-asher, still haven't time to reproduce and to understand why it happens. Hopefully I will have some time soon. Sorry for the silence :(

**Comment by jeremy-asher** [comment]
No problem, thank you for taking a look!

**Comment by d12frosted** [comment]
Irrelevant for new Emacs. There is no `--with-no-titlebar` in currently supported version (29+).
