### ISSUE TITLE
Icon Option Incorrect

### ISSUE THREAD

**Issue by MarkCubb** [d12frosted/homebrew-emacs-plus#247]
In the process of installing doom emacs:

`brew install emacs-plus@27 --with-modern-sexy-v1-icon `

yields what looks to be an icon not listed in the icons table:

![Screen Shot 2020-07-07 at 1 32 28 PM](https://user-images.githubusercontent.com/7807216/86819932-52f91f00-c056-11ea-931a-4cb3e0277649.png)

Was the option used incorrectly?

**Comment by d12frosted** [comment]
🤦 this is me who used the option incorrectly! forgot to update the list in other place. Will fix soon.

**Comment by d12frosted** [comment]
12186d9 should fix that, please let me know if it still doesn't work. I did it not in the cleanest way, will work on improving that later on (e.g. installation should be part of `EmacsBase`, but for some reason it doesn't work when called from `install` function).

Nevertheless, thank you very much for reporting that issue. Sorry that I didn't test it properly before merging!

**Comment by MarkCubb** [comment]
No need for apologies. Worked correctly on my second pass. Thanks for the quick turnover.
