### ISSUE TITLE
Black background behind Dock icon with --with-modern-black-variant-icon

### ISSUE THREAD

**Issue by angrybacon** [d12frosted/homebrew-emacs-plus#253]
- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

```
brew uninstall emacs-plus@27
brew install emacs-plus@28 --with-modern-black-variant-icon --with-no-titlebar
```

## What happened

<img width="164" alt="image" src="https://user-images.githubusercontent.com/5608624/90106092-3633c380-dd47-11ea-82f3-38914a3e6e25.png">

Also happens with `--with-modern-papirus-icon`. I had @27 installed with `--with-modern-icon` just before and it wasn't showing the black background in the Dock.

## Output of `brew config`

```
❯ brew config
HOMEBREW_VERSION: 2.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9ef993ab570ac6d4f2c4f88a96f2da8c3e71fa85
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 087008a4c8cfba1e728db58d936c24fead0de954
Core tap last commit: 8 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 12.0.26.2
Xcode: N/A
```

## Output of `brew doctor`
```
❯ brew doctor
Your system is ready to brew.
```

**Comment by d12frosted** [comment]
@angrybacon thank you for the report. 

Will double check the license of these icons and if everything is fine, will modify them.

**Comment by d12frosted** [comment]
I've merged a fix. Please validate.

P. S. In case you run into issues with hash mismatch, please do `brew cleanup emacs-plus@28` and retry. Unfortunately, `revision` is not supported by resources :(

**Comment by Azd325** [comment]
@d12frosted 
I got this now on a fresh installation

```
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-black-variant.icns
Already downloaded: /Users/tim/Library/Caches/Homebrew/downloads/533a176691034506a845c226c49e4ebd5c363d07faea64b03aec28df102a1ac6--modern-black-variant.icns
Error: SHA256 mismatch
Expected: b066ee684e68519950bcca06f631a49fbd1f5a463d49114e5063b3a5f1654d0c
  Actual: a56a19fb5195925c09f38708fd6a6c58c283a1725f7998e3574b0826c6d9ac7e
 Archive: /Users/tim/Library/Caches/Homebrew/downloads/533a176691034506a845c226c49e4ebd5c363d07faea64b03aec28df102a1ac6--modern-black-variant.icns
To retry an incomplete download, remove the file above.
```

**Comment by d12frosted** [comment]
Did you run the cleanup for the formula you are using? E.g. `brew cleanup emacs-plus@27`? Otherwise try removing offending file from the cache.

**Comment by Azd325** [comment]
That worked for me `brew cleanup emacs-plus@27`

I removed before the cache file but this didn't help beforehand.

**Comment by d12frosted** [comment]
Would love to find a better way to address the issue. Unfortunately revisions are not supported by resources in brew. Maybe I should change file names when I change content 🤷 

In any case, apologies for inconvenience 🙏

**Comment by Azd325** [comment]
Maybe it can be address in `Known Issues` inside [README.org](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/README.org#known-issues)

> Maybe I should change file names when I change content 

That would be the best way, but I don't know how often people have problems with that, that it is worth the effort.

> In any case, apologies for inconvenience

No Problem. Thanks for your work.

**Comment by angrybacon** [comment]
@d12frosted Works for me! Thanks :-) Though the cleanup wouldn't work for me, had to remove files by hand.

**Comment by daviderestivo** [comment]
@d12frosted thanks for the fix :) ... I bring the fix as well to emacs-head
