### ISSUE TITLE
emacs-plus@28 --with-xwidgets failing

### ISSUE THREAD

**Issue by agzam** [d12frosted/homebrew-emacs-plus#254]
==> Applying xwidgets_webkit_in_cocoa.patch
    patching file configure.ac
    Hunk #1 FAILED at 485.
    Hunk #2 FAILED at 2787.
    Hunk #3 FAILED at 5753.
    3 out of 3 hunks FAILED -- saving rejects to file configure.ac.rej
    patching file lisp/xwidget.el
    Hunk #1 FAILED at 39.
    Hunk #2 FAILED at 83.
    Hunk #3 succeeded at 133 with fuzz 2 (offset 30 lines).
    Hunk #4 FAILED at 156.
    Hunk #5 FAILED at 205.
    Hunk #6 FAILED at 274.
    Hunk #7 succeeded at 314 (offset 62 lines).
    Hunk #8 FAILED at 330.
    Hunk #9 FAILED at 340.
    Hunk #10 FAILED at 529.
    Hunk #11 FAILED at 539.
    Hunk #12 FAILED at 676.
    Hunk #13 FAILED at 731.
    Hunk #14 FAILED at 752.
    Hunk #15 FAILED at 783.
    13 out of 15 hunks FAILED -- saving rejects to file lisp/xwidget.el.rej
    patching file nextstep/templates/Info.plist.in
    Hunk #1 FAILED at 675.
    1 out of 1 hunk FAILED -- saving rejects to file nextstep/templates/Info.plist.in.rej
    patching file src/Makefile.in
    Hunk #1 FAILED at 434.
    1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.in.rej
    patching file src/emacs.c
    Hunk #1 FAILED at 1852.
    Hunk #2 FAILED at 1928.
    2 out of 2 hunks FAILED -- saving rejects to file src/emacs.c.rej
    patching file src/nsterm.m
    Hunk #1 FAILED at 49.
    Hunk #2 FAILED at 2607.
    Hunk #3 FAILED at 2616.
    Hunk #4 succeeded at 4389 with fuzz 1 (offset 19 lines).
    Hunk #5 FAILED at 7089.
    Hunk #6 FAILED at 7132.
    5 out of 6 hunks FAILED -- saving rejects to file src/nsterm.m.rej
    The next patch would create the file src/nsxwidget.h,
    which already exists!  Applying it anyway.
    patching file src/nsxwidget.h
    Patch attempted to create file src/nsxwidget.h, which already exists.
    Hunk #1 FAILED at 1.
    1 out of 1 hunk FAILED -- saving rejects to file src/nsxwidget.h.rej
    The next patch would create the file src/nsxwidget.m,
    which already exists!  Applying it anyway.
    patching file src/nsxwidget.m
    Patch attempted to create file src/nsxwidget.m, which already exists.
    Hunk #1 FAILED at 1.
    1 out of 1 hunk FAILED -- saving rejects to file src/nsxwidget.m.rej
    patching file src/xwidget.c
    Hunk #1 FAILED at 18.
    Hunk #2 FAILED at 67.
    Hunk #3 FAILED at 81.
    Hunk #4 FAILED at 99.
    Hunk #5 FAILED at 117.
    Hunk #6 succeeded at 401 with fuzz 2 (offset 225 lines).
    Hunk #7 succeeded at 408 with fuzz 2 (offset 194 lines).
    Hunk #8 FAILED at 447.
    Hunk #9 FAILED at 463.
    Hunk #10 succeeded at 664 with fuzz 2 (offset 359 lines).
    Hunk #11 succeeded at 890 with fuzz 2 (offset 354 lines).
    Hunk #12 FAILED at 900.
    Hunk #13 FAILED at 914.
    Hunk #14 FAILED at 972.
    Hunk #15 FAILED at 988.
    Hunk #16 FAILED at 1063.
    Hunk #17 FAILED at 1081.
    Hunk #18 FAILED at 1104.
    Hunk #19 FAILED at 1173.
    Hunk #20 FAILED at 1212.
    Hunk #21 succeeded at 1075 (offset 173 lines).
    Hunk #22 succeeded at 1087 (offset 174 lines).
    Hunk #23 FAILED at 1098.
    Hunk #24 FAILED at 1117.
    Hunk #25 succeeded at 1150 with fuzz 2 (offset 198 lines).
    Hunk #26 FAILED at 1160.
    Hunk #27 FAILED at 1186.
    Hunk #28 FAILED at 1269.
    Hunk #29 FAILED at 1387.
    Hunk #30 FAILED at 1561.
    Hunk #31 FAILED at 1590.
    Hunk #32 FAILED at 1623.
    Hunk #33 FAILED at 1637.
    26 out of 33 hunks FAILED -- saving rejects to file src/xwidget.c.rej
    patching file src/xwidget.h
    Hunk #1 FAILED at 29.
    Hunk #2 FAILED at 60.
    Hunk #3 FAILED at 97.
    3 out of 3 hunks FAILED -- saving rejects to file src/xwidget.h.rej

**Comment by d12frosted** [comment]
Hi @agzam 😸 

It's happening for few days already 😞 Didn't have time to address the issue. Will try to do it soon.

P. S. https://github.com/emacs-mirror/emacs/commit/d089c4fbfc8be432dc3015a99b4044dab0a0de97

**Comment by d12frosted** [comment]
@agzam could you please verify that it works as expected?

**Comment by agzam** [comment]
Oh wow.. that was quick. I'm building now.

**Comment by agzam** [comment]
Looking good! Thank you!

![image](https://user-images.githubusercontent.com/1091022/90218346-6a939800-ddb8-11ea-8fcc-c13682c64c8c.png)

**Comment by d12frosted** [comment]
> Oh wow.. that was quick. I'm building now.

😸 It was quick for you (and I am glad that it was), but to be honest, I could address it 3 days ago when it failed for [the first time][1]. Even my [patch application test has failed][2], but I was too scared lol. Nevertheless, I am glad that it's back and that it works as expected ❤️ Thanks for checking it @agzam !

P. S. I am actually happy to drop this patch. Having it in the upstream makes it more stable. 🎉 Something worth celebrating 🍷 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/actions/runs/204277532
  [2]: https://github.com/d12frosted/emacs-plus-basis/actions/runs/204269499

**Comment by agzam** [comment]
Yeah, I noticed it a few days ago myself. I thought must be something upstream. Not the most important feature, but it's nice to have it. Thanks again for fixing it.
