### ISSUE TITLE
SVG displayed with incorrect color

### ISSUE THREAD

**Issue by Jonghyun-Yun** [d12frosted/homebrew-emacs-plus#258]
Hello!

I heavily use (org-latex-preview) with dvisvgm. SVG image files are created by the preview look good, but Emacs displays them using incorrect color. This happens in org-mode as well as image-mode. I don't see this issue with PNG files. The below illustrates color difference: SVG(top) and PNG(bottom). The background of SVG should be the same as that of PNG.

<img width="657" alt="Screen Shot 2020-08-15 at 3 52 04 AM" src="https://user-images.githubusercontent.com/14356723/90309099-cd655c00-deaa-11ea-95bb-d21d935be0a5.png">

I don't know if this can be fixed using installation options or emac config. Please advise me.

PS: I used options: --with-no-titlebar --with-xwidgets --with-jansson --without-imagemagick
emacs-mac doesn't seem to have this issue.

**Comment by d12frosted** [comment]
Hello @Jonghyun-Yun 

This is configured via lisp 😸 You can find some hints on [reddit][1]. I have configured it like this:

```emacs-lisp
  (setq org-format-latex-options
        (list :foreground 'default
              :background 'default
              :scale 1.5
              :html-foreground "Black"
              :html-background "Transparent"
              :html-scale 1.0
              :matchers '("begin" "$1" "$" "$$" "\\(" "\\[")))
```

  [1]: https://www.reddit.com/r/emacs/comments/hr05pc/orgmode_latex_fragment_previews_are_transparent/

**Comment by Jonghyun-Yun** [comment]
Thanks for the prompt attention!
The below is my config for the variable you mentioned, and it seems to be the same as yours.
```emacs-lisp
  (setq org-format-latex-options
        (quote
         (:foreground default :background default :scale 1.5 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers
          ("begin" "$1" "$" "$$" "\\(" "\\["))
         ))
```
I played with this variable, but failed to get the desired outcome. Emacs respects colors specified in this option when creating SVG files. However, Emacs doesn't fully respect it when displaying SVG files. The display issue also occurs when viewing SVG in image-mode. Hence, it is less likely that I can fix the issue using `org-format-latex-options`.

**Comment by d12frosted** [comment]
> Thanks for the prompt attention!

You caught me just before I went out 😸 

I know that it's not that simply to configure that thing. Not only the background is flaky, but the quality of embedded svg is far from being ideal. I know that in `emacs-mac` they solved these issues.

With all my current configurations it looks like this:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/6507913/90311834-0384f900-df08-11ea-9931-8c6d36a81ef0.png">

But if I put the same text in different context with different background, I get this:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6507913/90312110-7a22f600-df0a-11ea-8647-cf45d88da1ef.png">

And here I thought I don't have this problem. This is actually related to the fact that `:background` is set to `default`. So I changed that to `auto` and got more pleasing result:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6507913/90312162-f289b700-df0a-11ea-8ac9-cc83c94902af.png">

```emacs-lisp
(setq org-format-latex-options
        (list :foreground 'auto
              :background 'auto
              :scale 1.5
              :html-foreground "Black"
              :html-background "Transparent"
              :html-scale 1.0
              :matchers '("begin" "$1" "$" "$$" "\\(" "\\[")))
```

Please note that you need to quote `default` and `auto`. In your configurations you don't have a quote. I also found in my configs history this fix (https://github.com/d12frosted/environment/commit/ef1a4151650aa679943ec49c30b801fed49ea052) 😸 

Hope that helps. In any case, thank you for bringing this issue up. I now have a setup where latex preview looks good even in headers.

**Comment by d12frosted** [comment]
Ah, but now it doesn't work with default face. Haha.

```
Debugger entered--Lisp error: (error "Invalid face")
  internal-get-lisp-face-attribute(nil :foreground nil)
  face-attribute(nil :foreground nil default)
  org-format-latex("ltximg/org-ltximg" 717 735 "/Users/d12frosted/Dropbox/vulpea/notes/journal/" overlays nil forbuffer dvipng)
  org--latex-preview-region(717 735)
```

Looks like a regular bug. Don't have much time right now to dig into it. Will take a look later :)

**Comment by Jonghyun-Yun** [comment]
Thanks for the catch!
I quote `default`, and the outcome looks a bit better than `auto` in dark background.
Embedded SVG in Emacs still has lower contrast than an external viewer, make them hard to read.

**Comment by nicehiro** [comment]
Got the same problem here.

SVG picture in [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport) looks great, but in emacs-plus looks blurry.

**Comment by d12frosted** [comment]
Unfortunately, this is how it works in GNU Emacs. There are several tradeoffs when choosing between GNU Emacs and Emacs mac port. The former runs faster but has worse integration with macOS. If someone finds a good and minimal fix for this issue, would gladly accept the patch 😸 

Closing this issue for now as strictly speaking this issue should be reported to Emacs bug tracker. And I am sure it was reported several times 😸 

P. S. don't hesitate to share hacks and configurations that overcome the issue. It could help someone ;)
