### ISSUE TITLE
Add support for Emacs 27.0

### ISSUE THREAD

**Issue by da-edra** [d12frosted/homebrew-emacs-plus#259]
Hello, I've just updated my brew packages and noticed that my Emacs configuration was breaking, I had a lot of bugs with Emacs (it was freezing and when increasing the font size my text was unreadable, among other issues).
I was able to trace this back to the recent update from Emacs 27.0 to Emacs 27.1. Would be it be possible to support Emacs 27.0?

Thank you very much for maintaining this project. ❤️

**Comment by d12frosted** [comment]
Hey. Sorry to hear that. Since 27.0 is a pre-release without specific mark (e.g. tag), I don't think I can help here. 

Maybe try 26 meanwhile?

**Comment by da-edra** [comment]
I understand, thanks.

**Comment by d12frosted** [comment]
Sorry for that.
