### ISSUE TITLE
emacs-plus was not built with native JSON support?

### ISSUE THREAD

**Issue by AbstProcDo** [d12frosted/homebrew-emacs-plus#261]
I installed emacs-plus as:

`brew install emacs-plus`

It works fine with doom-emacs until run testing with `doom docor`

It report warning that Emacs was not built with native JSON support.

```
> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
! Emacs was not built with native JSON support
  Users will see a substantial performance gain by building Emacs with jansson
  support (i.e. a native JSON library), particularly LSP users. You must
  install a prebuilt Emacs binary with this included, or compile Emacs with
  the --with-json option.
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...
```

Is it a decent warning? emacs-plus not come with native json support?

Should I uninstall emacs-plus and re-install it with emacs-plus --with-json

**Comment by kaz-yos** [comment]
This should probably be an opt-out now that 27.1 defaults to its use.

https://www.masteringemacs.org/article/whats-new-in-emacs-27-1
‘’’
The new configure option '--with-json' adds native support for JSON.
This uses the Jansson library.  The option is on by default; use
'./configure --with-json=no' to build without Jansson support.  The
new JSON functions 'json-serialize', 'json-insert',
'json-parse-string', and 'json-parse-buffer' are typically much faster
than their Lisp counterparts from json.el.
‘’’

**Comment by d12frosted** [comment]
Good point, I will remove that options from Emacs 27 and Emacs 28.

**Comment by iT-Boyer** [comment]
@d12frosted emacs-plus@28 or newer，show this isses：`json-parse-buffer`
```

```

**Comment by d12frosted** [comment]
@iT-Boyer make sure you have `Jansson` installed (it's part of Emacs+ dependencies, so you should have it). In the worst case just uninstall Emacs+ and install it again.

**Comment by iT-Boyer** [comment]
i install these, but have the issue!
```sh 
$brew info emacs-plus@30
==> d12frosted/emacs-plus/emacs-plus@30: stable 30.0.50
/opt/homebrew/Cellar/emacs-plus@30/30.0.50 (4,261 files, 208MB) *
  Built from source on 2023-05-28 at 16:46:17 with: --with-xwidgets --with-imagemagick
From: https://github.com/d12frosted/homebrew-emacs-plus/blob/HEAD/Formula/emacs-plus@30.rb
==> Dependencies
Build: make ✔, autoconf ✔, gnu-sed ✔, gnu-tar ✔, grep ✔, awk ✔, coreutils ✔, pkg-config ✔, texinfo ✔, xz ✔
Required: gnutls ✔, librsvg ✔, little-cms2 ✔, jansson ✔, tree-sitter ✔
Optional: imagemagick ✔, dbus ✔, mailutils ✘

$ brew search Jansson      
==> Formulae
jansson ✔
```
