### ISSUE TITLE
Emacs doesn't recognize SPC and TAB sometimes

### ISSUE THREAD

**Issue by parhamdoustdar** [d12frosted/homebrew-emacs-plus#267]
Hi,

I've noticed that when I'm copying URLs in to Emacs, sometimes SPC and TAB will stop working. S-SPC and S-TAB work, however. I've verified that it's not a major mode or minor mode thing by creating a `fundamental` buffer and trying out SPC there, and also I've used `describe-ey`, anditdoesn't recognize those keys, either.

I haven't seen this issue filed against emacs, even though I'm seeing it for months, both in `emacs@27` and `emacs@28`.

I thought I'd ask here for help and ideas on how I can diagnose that it's not caused by any customizations that are done in `emacs-plus` before I reach out toEmacs issue tracker.

Thanks!

**Comment by d12frosted** [comment]
🤔 I never faced this issue before. I was paying attention to tab and space keys and never had any issues so far. 

So few questions.

1. When exactly does it break? I mean, does it break after you `yank` in Emacs or before? 
2. Does it break only with URLs?
3. Did you try to reproduce it by running in a `-Q` mode, e.g. no user configs?
4. Does it reproduce with https://emacsformacosx.com?

**Comment by parhamdoustdar** [comment]
The problem is that I can't reproduce it, it's always random.

Is there a way to do something so that when it happens, I can figure out how to reproduce it? I've tried being conscious, but I haven't figured out any way of doing something that reproduces it every single time.

**Comment by d12frosted** [comment]
🤔 Really hard to tell. I bet you didn't have this issue in other applications, but I have to ask - did you encounter this issue outside Emacs? :) Do you use any applications for configuring macos wide keybindings like skhd or others (just don't remember names)? Asking because with skhd my dumb configs might lead to a dead state where some of the keys are throttled and not propagated to any application (including Emacs).

But it's really weird.

**Comment by parhamdoustdar** [comment]
Yeah, that's the first thing that occurred to me. No, that's not it – space and tab both work in other applications. Strangely, adding the shift key to those keys actually works, they just don't work by themselves.

One thing that I've noticed is that if I keep Emacs running for long enough, the issue gets fixed. I'm also not quite sure what fixes it. Closing and re-opening *always* fixes it, though.

**Comment by d12frosted** [comment]
🤔 Can you please share what options do you use to install `emacs-plus`?

**Comment by parhamdoustdar** [comment]
Before i share my options, I switched to running the Emacs cask for the past month or so, and this issue is not happening at all any more.

Here is the command I use to install emacs-plus:

`brew install emacs-plus@28 --with-mailutils --with-dbus`

I've realized that I don't need the mailutils and dbus any more, so I'll try reinstalling without these.

**Comment by parhamdoustdar** [comment]
I switched from emacsformacosx to emacs-plus, with no options – only `brew install emacs-plus@28`. My configuration hasn't changed, I'm using exactly the same packages and my init file is the same.

The issue started happening again.

If it helps, I'm using MacOS 10.15.7.

**Comment by d12frosted** [comment]
Really no ideas 😞 What version of emacsformacosx do you use? 28 or 27? Maybe there are differences between plist files 🤷

**Comment by parhamdoustdar** [comment]
I'm using `brew cask install emacs` which installs Emacs 27.1-1, according to `brew info --cask emacs`.

**Comment by d12frosted** [comment]
Might be an issue not related to emacs-plus vs other distributions, but rather an issue between emacs 27 vs emacs 28. Could you try to reproduce the issue with `emacs-plus@27`?

**Comment by parhamdoustdar** [comment]
Yeah, I have been able to reproduce the issue with emacs-plus@27 as well.
Also, since I last commented, I've been using the latest macports version
of Emacs and this issue doesn't occur there either.
Do you think it could be caused by a patch that exists in emacs-plus?

**Comment by atanasj** [comment]
I'm getting this exact issues. I have installed with:

```sh
brew install emacs-plus@28 --with-no-frame-refocus --with-no-titlebar --with-xwidgets --with-elrumo2-icon
```

**Comment by d12frosted** [comment]
Is this issue still relevant?

**Comment by g6ai** [comment]
Can confirm on M1 Pro Monterey, with emacs-plus@28 and narive-comp
