### ISSUE TITLE
pixel-scroll-mode doesn't seem to work properly

### ISSUE THREAD

**Issue by lyndondrake** [d12frosted/homebrew-emacs-plus#269]
Hi,

pixel-scroll-mode is very jumpy and doesn't seem to work properly. I'm using `spacemacs`, and pixel scroll mode seems to work fine in the normal Homebrew emacs. But I'm v keen to have the rest of the emacs-plus improvements. Any suggestions?

Best,
Lyndon

**Comment by d12frosted** [comment]
Hello,

Please share the command you used to install `emacs-plus`. I want to know the version and the options you pass. 😸 

And also please do elaborate on what you mean by normal Homebrew emacs? If you mean `brew install emacs`, then I am not sure I understand as it doesn't provide GUI. Or are you talking about the Cask version?

**Comment by lyndondrake** [comment]
`brew install emacs-plus --with-xwidgets --with-spacemacs-icon`

```
d12frosted/emacs-plus/emacs-plus@27: stable 27.1 (bottled), HEAD
/usr/local/Cellar/emacs-plus@27/27.1 (4,015 files, 131.9MB)
  Built from source on 2020-10-24 at 16:59:40 with: --with-xwidgets --with-spacemacs-icon
From: https://github.com/d12frosted/homebrew-emacs-plus/blob/HEAD/
```

And yes, apols for confusion - the one I'm comparing to is:

```
railwaycat/emacsmacport/emacs-mac: stable emacs-27.1-mac-8.0, HEAD
YAMAMOTO Mitsuharu's Mac port of GNU Emacs
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 (4,054 files, 123.6MB) *
  Built from source on 2020-08-12 at 20:04:53
From: https://github.com/railwaycat/homebrew-emacsmacport/blob/HEAD/Formula/emacs-mac.rb
```

**Comment by d12frosted** [comment]
Ah I see 😸 Well, Emacs Mac port is a beefed GNU Emacs to improve GUI experience on macOS. You can find out more about its features in the [official README][1]. In particular, proper scrolling support is [one of its features][2]. Unfortunatelly GNU Emacs doesn't provide this. I remember there are some conversations around this topic on the mailing list, but I can't seem to find the one I have in mind.

  [1]: https://bitbucket.org/mituharu/emacs-mac/src/master/README-mac
  [2]: https://bitbucket.org/mituharu/emacs-mac/src/dfb5869abf8f6892e928042e9f8221f8435a0dcb/README-mac#lines-152

**Comment by lyndondrake** [comment]
OK, thanks for that and I hadn't even noticed that.

I've been trying out your Emacs cask as it's the Spacemacs-recommended distribution. But the main feature I can see of yours vs Emacs Mac is that with yours I can enable webkit support (which is indeed a big plus!).

Am I missing other things? I am still figuring out my journey back into Emacs after many years away (& now on MacOS).

**Comment by d12frosted** [comment]
No problem :) I see how confusing it might be when you want to install Emacs on macOS. There are multiple options! Apart from regular choice of build manually vs package manager, there are still many options when using `brew`: GNU Emacs formula (only CLI), GNU Emacs cask (GUI), `emacs-plus`, `emacs-head`, `emacs-mac` to name few of them 😸 And sometimes the difference is not obvious.

In short, `emacs-plus` (and `emacs-head`) are just GNU Emacs with few additional features. I created `emacs-plus` to provide 'experimental' stuff to official formula. 

But then there is `emacs-mac`, which is a beefed version of GNU Emacs specially for `macOS`. While it is GUI-friendly (aka good scroll support, fonts, high resolution inline images, etc), it is not ideal 😸 For me the bummer is peformance. There are many conversations online regarding GNU Emacs vs Mac Port, one that I quickly found (cause I have it linked) is https://github.com/syl20bnr/spacemacs/issues/4955

**Comment by d12frosted** [comment]
Closing this issue as it's out of scope of `emacs-plus`.
