### ISSUE TITLE
Getting errors when using emacs-plus@7 but not when using emacs

### ISSUE THREAD

**Issue by tintinthong** [d12frosted/homebrew-emacs-plus#271]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

For the longest time I have been using emacs-plus@27. I was doing some experimentation with `graphviz` for `org-roam`. And suddenly the error below occured 

## What happened (include command output)

```
dyld: Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.7.dylib
  Referenced from: /usr/local/Cellar/emacs-plus@27/27.1/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
```

I figured since imageMagick is a dependency of emacs-plus@27. I suspect there may be an issue in this repo. 

EDIT: I tried using emacs-plus@26 and it worked. But not for emacs-plus@latest and emacs-plus@27.

<pre>
$ brew install emacs-plus
</pre>

However, emacs works if I use `brew install emacs`. 

<details>
  <summary>brew services list </summary>
  <pre>

Name          Status  User        Plist
emacs-plus@27 error   justinthong /Users/justinthong/Library/LaunchAgents/homebrew.mxcl.emacs-plus@27.plist
mysql         stopped             
nginx         stopped             
postgresql    stopped             
unbound       stopped   

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ed5d80ff2f8025823de9b9faacfca27fa006c80
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eb54ca1771096a6966b81fbeb70965dc8ea04311
Core tap last commit: 17 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1603499129
Xcode: N/A</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/anaconda3/bin/icu-config
  /usr/local/anaconda3/bin/krb5-config
  /usr/local/anaconda3/bin/freetype-config
  /usr/local/anaconda3/bin/xslt-config
  /usr/local/anaconda3/bin/libpng16-config
  /usr/local/anaconda3/bin/libpng-config
  /usr/local/anaconda3/bin/xml2-config
  /usr/local/anaconda3/bin/python3-config
  /usr/local/anaconda3/bin/curl-config
  /usr/local/anaconda3/bin/ncursesw6-config
  /usr/local/anaconda3/bin/pcre-config
  /usr/local/anaconda3/bin/python3.8-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

</pre>

**Comment by d12frosted** [comment]
Ah, again something happened to `imagemagick`. Please try reinstalling `emacs-plus`. 

```bash
$ brew uninstall emacs-plus@27
$ brew install emacs-plus@27
```

**Comment by Azd325** [comment]
Reinstall doesn't worked for me.

**Comment by chrislockard** [comment]
Same - reinstall following @d12frosted's instructions isn't working. Launching from Finder results in "Emacs cannot be opened because of a problem." Opening from terminal results in 

`LSOpenURLsWithRole() failed for the application /Applications/Emacs.app with error -10810`

FWIW, imagemagick updated earlier today to `7.0.10-37`

**Comment by robertozoia** [comment]
`  ~ emacs
dyld: Library not loaded: /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.7.dylib
  Referenced from: /usr/local/Cellar/emacs-plus@27/27.1/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
[1]    5801 abort      emacs
`
In /usr/local/imagemagick/lib there's `libMagickWand-7.Q16HDRI.8.dylib` but no `libMagickCore-7.Q16HDRI.7.dylib`

**Comment by d12frosted** [comment]
🤔 could you please try as a workaround to install without `imagemagick`? E.g. `--without-imagemagick`?

**Comment by robertozoia** [comment]
It recompiles and launches ok with `--without-imagemagick`.

**Comment by tintinthong** [comment]
Tried reinstalling emacs-plus@27 -> doesn't work. Tried reinstalling emacs-plus@27 without magic -> works for vanilla emacs, but not for doom. 

hmmmm currently im happy with just using emacs-plus@26 -> works fine.

**Comment by robertozoia** [comment]
> * Tried reinstalling emacs-plus@27 -> doesn't work.
> * Tried reinstalling emacs-plus@27 without magic -> works for vanilla emacs, but not for doom.
> 
> hmmmm currently im happy with just using emacs-plus@26 -> works fine.

emacs-plus@27, without magic, worked for me for Doom.  (Maybe it's just I don't have anything that needs Imagemagick in my emacs config.)

**Comment by JasonMFry** [comment]
`brew uninstall emacs-plus@27 && brew install emacs-plus@27 --without-imagemagick` worked for me. Thanks!

**Comment by robertozoia** [comment]
Also works:

`brew install emacs-plus@27 --HEAD`

**Comment by d12frosted** [comment]
Seems like I need to rebuild the bottle. Will do tomorrow.

P. S. You can also build without bottle, but not from head. Forgot the argument, not near computer.

**Comment by naupaka** [comment]
Just adding my +1 that I am seeing the same error, and that @robertozoia's solution worked for me to resolve the issue.

**Comment by d12frosted** [comment]
Hi everyone,

I've prepared a new bottle (see #272). Once it builds, I will merge it.

P. S. I was talking about `-s` (or `--build-from-source`) option, which forces `brew` not to use bottle if it exists.

**Comment by robertozoia** [comment]
> Hi everyone,
> 
> 
> 
> I've prepared a new bottle (see #272). Once it builds, I will merge it.
> 
> 
> 
> P. S. I was talking about `-s` (or `--build-from-source`) option, which forces `brew` not to use bottle if it exists.

Thanks!
