### ISSUE TITLE
Enabling Flycheck throws error

### ISSUE THREAD

**Issue by jojojames** [d12frosted/homebrew-emacs-plus#28]
This is repeatable across different computers with the same config.

```
(use-package flycheck
  :ensure t
    :diminish flycheck-mode
    :commands (flycheck-mode)
    :init
    (setq flycheck-idle-change-delay 2)
    (setq-default flycheck-emacs-lisp-load-path 'inherit)
    (setq-default flycheck-disabled-checkers '(emacs-lisp-checkdoc)))
```
M-x flycheck-mode

An error dialog will show up.

'Emacs quit unexpectedly.

Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple'

**Comment by d12frosted** [comment]
Hey,

Thank your for your report. Could you please share the options you used during installation (especially if you used `--HEAD`) and stack trace from that dialog.

**Comment by jojojames** [comment]
brew install d12frosted/emacs-plus/emacs-plus --without-spacemacs-icon

http://ix.io/qmA

^Paste was too long.

**Comment by d12frosted** [comment]
Ok, that's strange.

Could you please remove regular `emacs` using `brew uninstall emacs`? I see some conflicts.

Also, could you please share the stack trace from crash dialog?

**Comment by jojojames** [comment]
I tried removing all the emacs related conflicts. Here's the build log again (still throws an error dialog).

```
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing emacs-plus from d12frosted/emacs-plus
==> Downloading https://ftpmirror.gnu.org/emacs/emacs-25.1.tar.xz
Already downloaded: /Users/james/Library/Caches/Homebrew/emacs-plus-25.1.tar.xz
==> Downloading https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c62450be1cbee9f11cecba846dd66c7d06/patch-multicolor-font.diff
Already downloaded: /Users/james/Library/Caches/Homebrew/emacs-plus--patch-5af2587e986db70999d1a791fca58df027ccbabd75f45e4a2af1602c75511a8c.diff
==> Patching
==> Applying patch-multicolor-font.diff
patching file src/macfont.m
==> ./configure --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/25.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/25.1 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
==> make
==> make install
==> Caveats
To have launchd start d12frosted/emacs-plus/emacs-plus now and restart at login:
  brew services start d12frosted/emacs-plus/emacs-plus
Or, if you don't want/need a background service you can just run:
  emacs
==> Summary
🍺  /usr/local/Cellar/emacs-plus/25.1: 4,046 files, 120.0MB, built in 1 minute 41 seconds
james:25.1/ $ 
```

Also, there isn't a stacktrace, it just pops up an OSX dialog saying something crashed but Emacs still works.

**Comment by d12frosted** [comment]
@jojojames sorry, but I have no idea what's wrong. Is your `flycheck` up to date?

**Comment by jwintz** [comment]
@jojojames, Could you run `M-x package-list-packages`, then <kbd>U</kbd> to mark upgrades, then <kbd>X</kbd> to execute, just to check if flycheck gets updated ?

**Comment by jojojames** [comment]
My flycheck is up to date.

I'll just close for now since it seems like I'm the only one seeing this. I just built Emacs off the master branch instead. 

Thanks!
