### ISSUE TITLE
Include core formula patches for Apple Silicon support

### ISSUE THREAD

**Issue by nwjsmith** [d12frosted/homebrew-emacs-plus#282]
The homebrew-core `emacs` formula now includes two small patches to allow building Emacs on Apple Silicon. Would you be willing to include those in the emacs-plus formulas?
* The first is [a patch to allow building on arm64](https://github.com/Homebrew/formula-patches/pull/323/files)
* The second is [a patch to code-sign the executable after building](https://github.com/emacs-mirror/emacs/commit/868f51324ac96bc3af49a826e1db443548c9d6cc), which is now required on Apple Silicon.

Thank you

**Comment by d12frosted** [comment]
Amazing. I will definitely accept these patches :100: Will try to do it ASAP, but optimistically I will not be able to until Sunday. So if someone wishes to bring it sooner, PRs are welcome :smile_cat: Just follow the ~white rabbit~ [docs regarding patches][1].

P. S. @nwjsmith thank you for raising this :) 

cc @daviderestivo you might want to take it into `emacs-head`. Unless you already did :smiling_imp: 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/blob/master/docs/development-guidelines.org#patches

**Comment by daviderestivo** [comment]
@nwjsmith thanks for the info :)

> cc @daviderestivo you might want to take it into `emacs-head`. Unless you already did 😈
Not yet ... I probably do it over the weekend.

**Comment by daviderestivo** [comment]
> @nwjsmith thanks for the info :)
> 
> > cc @daviderestivo you might want to take it into `emacs-head`. Unless you already did 😈
Not yet ... I probably do it over the weekend :)

**Comment by d12frosted** [comment]
Actually, had a chance to do it now. So prepared a PR - #283.

Unfortunately, I don't have a chance to test it on real M1 nor on CI (AFAIK), so once the build passes I will simply merge the patch and will ask you folks to test.

**Comment by d12frosted** [comment]
@nwjsmith Merged. Please verify if it works on M1. 

Btw, apparently `--HEAD` does not need to be patched.

**Comment by nwjsmith** [comment]
@d12frosted thanks for adding these in so quickly, I can confirm that they work on the M1. Have a great weeknd

**Comment by d12frosted** [comment]
@nwjsmith cool, thank you for verifying it 😸 enjoy Emacs on new laptop :)
