### ISSUE TITLE
brew warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.

### ISSUE THREAD

**Issue by glyph** [d12frosted/homebrew-emacs-plus#286]
This isn't an error yet, but I am dutifully reporting it as the console told me to:

```
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the d12frosted/emacs-plus tap (not Homebrew/brew or Homebrew/core)
```

**Comment by d12frosted** [comment]
Thanks for reporting! And thanks to @benmezger and @wufniks this is fixed on master now.

**Comment by JackSeven** [comment]
I had same problem when I install freerdp

Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/freerdp.rb:43

 I havent resolved it yet

**Comment by d12frosted** [comment]
@JackSeven `freerdp` is not related to `emacs-plus`. This warning should be fixed in `homebrew/core` as the warning suggests 😸
