### ISSUE TITLE
Could not install with --with-native-comp

### ISSUE THREAD

**Issue by shuxiao9058** [d12frosted/homebrew-emacs-plus#289]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

reinstall libgccjit

## What happened (include command output)

<pre>
$ brew install emacs-plus@28 --with-modern-pen-icon --with-ctags --with-mailutils --with-native-comp  --FETCH-HEAD

<details>
  <summary>Command output</summary>
  <pre>

Updating Homebrew...
fatal: It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr ".git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

==> Auto-updated Homebrew!
Updated Homebrew from a8faeef64 to e6e76a403.
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 4 formulae.
==> Updated Casks
Updated 6 casks.

Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the d12frosted/emacs-plus tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@28.rb:38

==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-28/fix-window-role.patch
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/fe10dba71a5a9f8fef6f4534268970b2b0ae0f941e515daed7ae88465083c287--fix-window-role.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-28/system-appearance.patch
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/aaa0da80d33eac9e551adf7faf404e565c71e86c02ea4659200474fd6d899f5a--system-appearance.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon1.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/eb27034a93614c5890164569ad3b62ac58e76ef0a01d1f002c60dfcbb56826a1--EmacsIcon1.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon2.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/03c143a12e03202b37c1696cf3dd9d535d0d9685573d963b9a88b53b35b7f04d--EmacsIcon2.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon3.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/cc36835b90ae3f5dceeca486c1a748f238462e426b74c3500d96499052c93690--EmacsIcon3.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon4.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/789430283b2f795681c720a0c362df3cc55079d1bbeb6089aa8f158b7b305618--EmacsIcon4.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon5.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/458acac289e84e1923d0ab03c395997504a099e30a2d3662c2273cc16c5cd942--EmacsIcon5.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon6.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/35327c618b96cea3422d45fde52bfad20baebe56da44a7de1a9914c5f0a1b498--EmacsIcon6.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon7.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/c71daceea95ff60aa80b3b47e23382a39ed74f2a52cabd9b5f4ca6291a22b1c8--EmacsIcon7.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon8.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/b9701777d059c3427883063797b3c3e941d9f641cad5a16765453f07a4ab87ae--EmacsIcon8.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/EmacsIcon9.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/0fd1ae80eefa53745a88715dd48db9dd28fab876d835e5946890b524efe92c6b--EmacsIcon9.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/emacs-card-blue-deep.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/4c84a8ed282f7fe6c9af801f51f14664baba413054ac1c576925443dca653a0b--emacs-card-blue-deep.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/emacs-card-british-racing-green.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/f2b8c760dc98d9d177434e6648c621a198d9aaf0337ed03f7e4a2d9b160294bf--emacs-card-british-racing-green.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/emacs-card-carmine.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/1435824e93396928ca6c6acf566f957c0182b284b90426a37087fbb9ca9f071b--emacs-card-carmine.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/emacs-card-green.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/e58c484668bff6062f7f094f6af7252073247fd3c65ab18f0b35639559348133--emacs-card-green.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/spacemacs.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/5d0c663d4bf52e83f87a92a70e3dd140bedae40bfe5a4f26622e179d3f848921--spacemacs.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/gnu-head.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/4c78c128a04ac996f8d64efae68c4a34c9f84b1187e5ad208f38b94970d6f837--gnu-head.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/retro-sink-bw.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/0249aa043c1318a5ca14c31678f7bed8dd3f09ecde5879aefe5e342eaa87b80b--retro-sink-bw.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/retro-sink.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/9ba6c9a4b2f3e9befac6f948f756a407897f90e6c6c96c43be08ac4f634eab5f--retro-sink.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/793faf4d8801cdcff99373bedbad455953884ba9c17937b7823a66e5b4982398--modern.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-cg433n.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/c0d37433bcdfbdcbd7e18f8b36b38cdaf7c67162f5f9573a4149af63caddaea4--modern-cg433n.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-sjrmanning.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/5cbf20baac2387bef1d6767368d19a7ef8116565a073eba568dbdeccf73dcd31--modern-sjrmanning.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-sexy-v1.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/d85501e5117cc403635bb2737469ad662f2071a1d74010e59fc9caad73a665e9--modern-sexy-v1.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-sexy-v2.icns
fAlready downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/ef2c0ceac372ee40737bee87eab114f55cd0e710b18a09bcdc90b1cc03d27956--modern-sexy-v2.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-papirus.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/7e2958ba4ce880c4d4f9ffa884c3e015e8d18a93790b9e5205d531185cddaf39--modern-papirus.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-pen.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/0a31431f197b7a4fb3cf2c5c5e7f15e52b1716ee58dd84607453f91c2fa32794--modern-pen.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-black-variant.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/533a176691034506a845c226c49e4ebd5c363d07faea64b03aec28df102a1ac6--modern-black-variant.icns
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/modern-nuvola.icns
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/468b091e9e23644d724881b3ff4850a80d54d09d78b2feefc49a9257cf272147--modern-nuvola.icns
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/jiya/Library/Caches/Homebrew/emacs-plus@28--git

From https://github.com/emacs-mirror/emacs
   433ae7b0a5c..b99a4744822  feature/native-comp -> origin/feature/native-comp
==> Checking out branch feature/native-comp
Already on 'feature/native-comp'
Your branch is behind 'origin/feature/native-comp' by 144449 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating files: 100% (43/43), done.
HEAD is now at b99a4744822 Merge remote-tracking branch 'savannah/master' into HEAD
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the d12frosted/emacs-plus tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@28.rb:38

==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8794 (offset 26 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1251 (offset -2 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 2193 (offset -1 lines).
Hunk #2 succeeded at 5748 (offset -3 lines).
Hunk #3 succeeded at 5994 (offset -3 lines).
Hunk #4 succeeded at 6044 (offset -3 lines).
Hunk #5 succeeded at 6270 (offset -3 lines).
Hunk #6 succeeded at 9125 (offset -7 lines).
Hunk #7 succeeded at 10007 (offset -7 lines).
==> ImageMagick PKG_CONFIG_PATH:
/usr/local/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with
Last 15 lines from /Users/jiya/Library/Logs/Homebrew/emacs-plus@28/02.configure:
checking for lcms2... yes
checking for library containing inflateEnd... -lz
checking for dladdr... yes
checking for dlfunc... no
checking for gcc_jit_context_acquire in -lgccjit... yes
checking libgccjit.h usability... yes
checking libgccjit.h presence... yes
checking for libgccjit.h... yes
configure: error: Installed libgccjit has failed passing the smoke test.
You can verify it yourself compiling:
<https://gcc.gnu.org/onlinedocs/jit/intro/tutorial01.html>.
Please report the issue to your distribution if libgccjit was installed through
that.
Here instructions on how to compile and install libgccjit from source:
<https://gcc.gnu.org/wiki/JIT>.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues
</pre>

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
 src brew config
HOMEBREW_VERSION: 2.7.0-53-ge6e76a4
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6e76a403a63d74bfbf9dde4054e8f50f6c9c322
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2886f241ce14c35ff867a5e36d062ea29681454e
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ddT9SSBjFX/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_GITHUB_API: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2, 12.0.1, 11.0.2, 11.0.1, 9.0.4, 1.8.202.08, 1.8.0_202, 1.8.0_192, 1.8.0_181, 1.8.0_172, 1.8.0_162, 1.8.0_152
macOS: 11.1-x86_64
CLT: N/A
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
❯ src brew config
HOMEBREW_VERSION: 2.7.0-53-ge6e76a4
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6e76a403a63d74bfbf9dde4054e8f50f6c9c322
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2886f241ce14c35ff867a5e36d062ea29681454e
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ddT9SSBjFX/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_GITHUB_API: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2, 12.0.1, 11.0.2, 11.0.1, 9.0.4, 1.8.202.08, 1.8.0_202, 1.8.0_192, 1.8.0_181, 1.8.0_172, 1.8.0_162, 1.8.0_152
macOS: 11.1-x86_64
CLT: N/A
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
❯ src  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2
  protobuf@3.1
  sshpass

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  boost-python
  cquery
  ext4fuse
  opencv@2
  sshfs

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/anaconda3/bin/icu-config
  /usr/local/anaconda3/bin/krb5-config
  /usr/local/anaconda3/bin/freetype-config
  /usr/local/anaconda3/bin/xslt-config
  /usr/local/anaconda3/bin/libpng16-config
  /usr/local/anaconda3/bin/python3.7-config
  /usr/local/anaconda3/bin/libpng-config
  /usr/local/anaconda3/bin/xml2-config
  /usr/local/anaconda3/bin/python3.7m-config
  /usr/local/anaconda3/bin/python3-config
  /usr/local/anaconda3/bin/curl-config
  /usr/local/anaconda3/bin/ncursesw6-config
  /usr/local/anaconda3/bin/pcre-config
  /usr/local/anaconda3/envs/py3/bin/icu-config
  /usr/local/anaconda3/envs/py3/bin/krb5-config
  /usr/local/anaconda3/envs/py3/bin/freetype-config
  /usr/local/anaconda3/envs/py3/bin/xslt-config
  /usr/local/anaconda3/envs/py3/bin/libpng16-config
  /usr/local/anaconda3/envs/py3/bin/python3.7-config
  /usr/local/anaconda3/envs/py3/bin/libpng-config
  /usr/local/anaconda3/envs/py3/bin/xml2-config
  /usr/local/anaconda3/envs/py3/bin/python3.7m-config
  /usr/local/anaconda3/envs/py3/bin/python3-config
  /usr/local/anaconda3/envs/py3/bin/curl-config
  /usr/local/anaconda3/envs/py3/bin/ncursesw6-config
  /usr/local/anaconda3/envs/py3/bin/pcre-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcaffe.1.0.0.dylib
  /usr/local/lib/libclang.dylib
  /usr/local/lib/librime.1.5.3.dylib
  /usr/local/lib/librime.1.6.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/c++/v1/__bsd_locale_defaults.h
  /usr/local/include/c++/v1/__bsd_locale_fallbacks.h
  /usr/local/include/c++/v1/__cxxabi_config.h
  /usr/local/include/c++/v1/complex.h
  /usr/local/include/c++/v1/ctype.h
  /usr/local/include/c++/v1/cxxabi.h
  /usr/local/include/c++/v1/errno.h
  /usr/local/include/c++/v1/float.h
  /usr/local/include/c++/v1/inttypes.h
  /usr/local/include/c++/v1/limits.h
  /usr/local/include/c++/v1/locale.h
  /usr/local/include/c++/v1/math.h
  /usr/local/include/c++/v1/setjmp.h
  /usr/local/include/c++/v1/stdbool.h
  /usr/local/include/c++/v1/stddef.h
  /usr/local/include/c++/v1/stdint.h
  /usr/local/include/c++/v1/stdio.h
  /usr/local/include/c++/v1/stdlib.h
  /usr/local/include/c++/v1/string.h
  /usr/local/include/c++/v1/support/android/locale_bionic.h
  /usr/local/include/c++/v1/support/fuchsia/xlocale.h
  /usr/local/include/c++/v1/support/ibm/limits.h
  /usr/local/include/c++/v1/support/ibm/locale_mgmt_aix.h
  /usr/local/include/c++/v1/support/ibm/support.h
  /usr/local/include/c++/v1/support/ibm/xlocale.h
  /usr/local/include/c++/v1/support/musl/xlocale.h
  /usr/local/include/c++/v1/support/newlib/xlocale.h
  /usr/local/include/c++/v1/support/solaris/floatingpoint.h
  /usr/local/include/c++/v1/support/solaris/wchar.h
  /usr/local/include/c++/v1/support/solaris/xlocale.h
  /usr/local/include/c++/v1/support/win32/limits_msvc_win32.h
  /usr/local/include/c++/v1/support/win32/locale_win32.h
  /usr/local/include/c++/v1/support/xlocale/__nop_locale_mgmt.h
  /usr/local/include/c++/v1/support/xlocale/__posix_l_fallback.h
  /usr/local/include/c++/v1/support/xlocale/__strtonum_fallback.h
  /usr/local/include/c++/v1/support/xlocale/xlocale.h
  /usr/local/include/c++/v1/tgmath.h
  /usr/local/include/c++/v1/wchar.h
  /usr/local/include/c++/v1/wctype.h
  /usr/local/include/caffe/proto/caffe.pb.h
  /usr/local/include/caffe/util/signal_handler.h
  /usr/local/include/reproc/reproc.h
  /usr/local/include/rime_api.h
  /usr/local/include/rime_levers_api.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/fuse-ext2.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libcaffeproto.a
  /usr/local/lib/libreproc.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt@4
  pyqt@4
  perl
  lua@5.1
  protobuf@3.1
  protobuf
  numpy@1.16

Warning: Some installed formulae are not readable:
  protobuf@3.1: "cxx11" is not a recognized standard

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/prl_convert
  /usr/local/bin/prl_disk_tool
  /usr/local/bin/prl_perf_ctl
  /usr/local/bin/prlcore2dmp
  /usr/local/bin/prlctl
  /usr/local/bin/prlexec
  /usr/local/bin/prlsrvctl
  /usr/local/etc/bash_completion.d/prlctl
  /usr/local/etc/bash_completion.d/prlsrvctl
  /usr/local/share/man/man8/prl_convert.8
  /usr/local/share/man/man8/prl_disk_tool.8
  /usr/local/share/man/man8/prlctl.8
  /usr/local/share/man/man8/prlexec.8
  /usr/local/share/man/man8/prlsrvctl.8

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install openssl@1.0

Run `brew missing` for more details.
</pre>

**Comment by d12frosted** [comment]
Hey, I don't really know what is the root cause of your issue, but I see several issues in the output of `brew` commands:

```
fatal: It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr ".git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.
```

This seems critical. As well as the following:

```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.
```

I would try to `brew reinstall gcc libgccjit` and then try again.

**Comment by shuxiao9058** [comment]
it works fine after `brew update-reset`, reinstall gcc and libgccjit
