### ISSUE TITLE
Adding white title bar option for ns build

### ISSUE THREAD

**Issue by idoo** [d12frosted/homebrew-emacs-plus#30]
Hello, that patch https://github.com/d12frosted/homebrew-emacs-plus/pull/21 is awesome, but it would be nice to have back compatibility with light schemes (it has white text title when window is active, and it's not really readably)

Do you have any ideas how to fix it?

<img width="901" alt="screen shot 2017-04-20 at 09 16 43" src="https://cloud.githubusercontent.com/assets/738921/25216208/3740be20-25aa-11e7-8078-ed9cab6e13a3.png">

**Comment by jwintz** [comment]
Yeah, @d12frosted reporter this, I'll dig up on that one.

**Comment by d12frosted** [comment]
@jwintz would be nice to have a solution for this 😸

**Comment by jwintz** [comment]
Ok, I have looked a bit, here's what I came up with:

```objective-c
    // win.titlebarAppearsTransparent = true;
    // win.appearance = [NSAppearance appearanceNamed:NSAppearanceNameVibrantDark];
    // win.titleVisibility = NSWindowTitleHidden;
```

* `titlebarAppearsTransparent` is the feature
* `NSAppearanceNameVibrantLight` is the default, gives a dark title label colour
* `NSAppearanceNameVibrantDark` is the default, gives a light title label colour
* `NSWindowTitleHidden` does not display the title label at.

I would go for the latest option to update my patch, since the application name and the current buffer's name is redundant information.

What do you guys think ?

**Comment by idoo** [comment]
I think that `current buffer's name` sometimes can be useful. Can you show examples how it will works?

**Comment by jwintz** [comment]
You mean an example with no title bar label and a light theme ?

PS: Current buffer is easily visible by looking at modelines :-)

**Comment by jwintz** [comment]
Ok, `spacemacs-light` theme, and no title label.

![screen shot 2017-04-20 at 15 16 06](https://cloud.githubusercontent.com/assets/3277054/25232628/5d0de77c-25dc-11e7-915d-77f3955ad4a1.png)

**Comment by d12frosted** [comment]
@jwintz ah, so the colours are 'hardcoded'. Personally, I don't look at the buffer name in the title bar. So I don't care about it. But some people might care about it. 

I wonder if it's possible to expose variable in emacs that will control the appearance name. That would be ideal, so people could control it however they want. Even those who use dark/light theme switch based on a sunrise/dawn.

**Comment by jwintz** [comment]
Still reading Cocoa's documentation to find a better solution.

Clearly I'm not in favour of exposing the title bar's label to emacs config, unless this is honoured by a maximum of theme maintainers, which is most likely not gonna happen.

I have two options:

* inferring the background color of the theme, inverse it and set the label's color up (should there be an API for it)
* implement a subclass of `NSAppearence`, but it will lead to a huge and difficult to maintain patch

Will let you know.

**Comment by CarlQLange** [comment]
Just dropping in to say that some elements of this patch may no longer be necessary with `--HEAD` since this commit: https://github.com/emacs-mirror/emacs/commit/7baa50eca28ff21497b058fa22656bbb4a447d87#diff-f43249227e5879c3fc3d7c08b1c41b1c

**Comment by CarlQLange** [comment]
just dropping in again to confirm that I didn't need this patch when installing from HEAD, I just set `ns-transparent-titlebar`.

Changing `ns-appearance` between `dark` and `nil` seems to change the window title font colour from white to black, so that's cool and potentially useful here.

**Comment by jwintz** [comment]
Awesome.

**Comment by d12frosted** [comment]
@CarlQLange that's totally great to hear! thanks for the headsup!

**Comment by CarlQLange** [comment]
👍 No problem! Something that confused me is that these are frame-specific, so you need to add them to `'default-frame-alist` or something like it.

Here's my working config:

```elisp
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . 'nil)) ; or 'dark, to switch to white title text
```

**Comment by jwintz** [comment]
After a clean reinstall of my home-brew environment, I second @CarlQLane, the `with-natural-title-bar` option is no longer needed. I suggest to remove it from the formula.

**Comment by d12frosted** [comment]
@jwintz thanks for checking this out
Pull request is welcome 😸

**Comment by d12frosted** [comment]
Emacs 26.1 is out. And I've removed all 25.x options, so closing this issue 😸 

Let me know if you have any questions/problems.
