### ISSUE TITLE
Add new icons for macOS Big Sur

### ISSUE THREAD

**Issue by tshu-w** [d12frosted/homebrew-emacs-plus#303]
There are several Emacs icons on [macosicons](https://macosicons.com) that fit the big sur icon design, and it would be nice to add them. (Personally, I like the first one.)

<img width="1396" alt="Screen Shot 2021-01-09 at 7 48 15 PM" src="https://user-images.githubusercontent.com/13161779/104090733-a4a78e00-52b3-11eb-9789-52e7285eee11.png">

**Comment by d12frosted** [comment]
Nice! I checked the site and could not find license. How are they being distributed? 

P. S. I hope by the first one that you love is not the clean my mac icon :)

**Comment by tshu-w** [comment]
The repository of this site is [here](https://github.com/elrumo/macOS_Big_Sur_icons_replacements), but I cannot find emacs icons from there. However, it seems difficult to contact the author since the icon can be uploaded directly on the website.

> P. S. I hope by the first one that you love is not the clean my mac icon :)

Haha, of course not ;)

**Comment by seanfarley** [comment]
This might be complicated since it's an opinion but I like the third one (not counting the clean my mac icon):

<img width="140" alt="Screen Shot 2021-01-12 at 2 47 37 PM" src="https://user-images.githubusercontent.com/20887/104371005-6e952480-54d4-11eb-8528-79627be84651.png">

**Comment by solkaz** [comment]
The license of the website is GPL; whether the icons themselves are under GPL licensing is unclear; therefore, I opened elrumo/macOS_Big_Sur_icons_replacements#1042

**Comment by elrumo** [comment]
Hey! I'm the author of [macOSicons.com](https://macosicons.com/), licensing is still a problem I'm trying to solve, here's an [issue](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/issues/1042#issuecomment-763483680) with a better explanation. In the meantime, send me an email with the icons you want and I can try to get in touch with the creator of the icons to see if they'd be happy to share it with you.

**Comment by seanfarley** [comment]
Perhaps I'm naive but since the Emacs icons all (clearly) derive from an icon with a known license, aren't they also the same license?

**Comment by elrumo** [comment]
@seanfarley no, you are totally right. And that's where the issue comes from, every original icon would have its own different license, so I'm trying to figure out how to make that work.

**Comment by seanfarley** [comment]
Sure, gotcha @elrumo; that's much, much, much more difficult for all icons on your (awesome) website! 😬

**Comment by d12frosted** [comment]
@elrumo thank you for your effort! Looking forward 😸

**Comment by d12frosted** [comment]
@seanfarley I would expect it as well... but then... There are original icons not based on GNU Emacs one. Plenty of them 😸 

TBH I am not sure that all included with emacs-plus have license 🤔 but maybe... it should stay between us 🤫

**Comment by elrumo** [comment]
@d12frosted That's another issue I have too 😅

**Comment by elrumo** [comment]
I couldn't help it, but I made a couple of variations of the icon that you are more than welcome to use. Merry Christmas  😁

![Emacs_Plus _2](https://user-images.githubusercontent.com/36299870/105232957-165bc380-5b61-11eb-8da4-37870387857f.png)
![Emacs_Plus _1](https://user-images.githubusercontent.com/36299870/105232963-178cf080-5b61-11eb-8f7f-611b1371f5e8.png)

**Comment by elrumo** [comment]
And [here's](https://www.figma.com/file/sWvalMNLeDrzzqM8zS4gON/Emacs-Big-Sur-icons?node-id=0%3A1) the source file for the icons, which I made in Figma.

**Comment by seanfarley** [comment]
Oh, nice @elrumo! Those look really good!

**Comment by natecox** [comment]
man, I really like the middle one, but I can't actually find that on the site anymore.
![image](https://user-images.githubusercontent.com/2782695/106196669-92a86500-6166-11eb-90a9-eda14c2caa5e.png)

**Comment by elrumo** [comment]
@natecox there was a small issue with the search on the page, I've just fixed it and should work now

**Comment by tshu-w** [comment]
@d12frosted @elrumo Thank you for your efforts, close because of https://github.com/d12frosted/homebrew-emacs-plus/pull/306 is merged

**Comment by JamesGreenaway** [comment]
> @natecox there was a small issue with the search on the page, I've just fixed it and should work now

still not there

**Comment by jasonm23** [comment]
Consider adding any icons you make to the Emacs-icons-project (use a PR, or raise an issue if you need an assist.)

https://github.com/emacsfodder/emacs-icons-project
