### ISSUE TITLE
Installing with the `--with-modern-doom3-icon` flag is blurry

### ISSUE THREAD

**Issue by FrankGerold** [d12frosted/homebrew-emacs-plus#311]
Hi there, 

The icon file that is installed by default with the `--with-modern-doom3-icon` flag is not a perfect square, which leads to a pixellated blurry image in Mac OS. 

It's a bit tricky in this case because the image itself is not a square - but on my end when I look at the actual image and chop off part of the horn to make it a square and manually set that as the icon, it becomes a proper high-res app icon.

**Comment by d12frosted** [comment]
@FrankGerold thank you for report. Indeed, it looks crappy. #312 should fix that.

**Comment by d12frosted** [comment]
Does my solution look good to  you?

**Comment by FrankGerold** [comment]
Wow, that was fast - Looks great!
