### ISSUE TITLE
Could not install with `brew install emacs-plus@28`

### ISSUE THREAD

**Issue by vertexclique** [d12frosted/homebrew-emacs-plus#316]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install emacs plus v28

## What happened (include command output)
<pre>
$ brew install emacs-plus@28
</pre>

<details>
  <summary>Command output</summary>
  <pre>

EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/dns-mode.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/enriched.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/flyspell.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/ispell.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/less-css-mode.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/makeinfo.el

In antlr-mode:
progmodes/antlr-mode.el:2426:20: Error: `c-init-language-vars' defined after use in (c-init-language-vars) (missing `require' of a library file?)
progmodes/antlr-mode.el:2427:26: Warning: c-init-language-vars called with 0
    arguments, but requires 1
make[2]: *** [progmodes/antlr-mode.elc] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [compile-main] Error 2
make: *** [lisp] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304
[ci] add --with-x11 to emacs-plus@28 build matrix https://github.com/d12frosted/homebrew-emacs-plus/pull/280
Could not install emacs-plus@28 --with-x11 https://github.com/d12frosted/homebrew-emacs-plus/issues/279

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c32b1b6839bb623442dfd5f901b84c421753317f
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
Xcode: N/A
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by Sleepful** [comment]
Same issue here:
<Details>
<Summary>
Output
</Summary>
==> make

Last 15 lines from /Users/corporatejose/Library/Logs/Homebrew/emacs-plus@28/03.make:
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/refbib.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/refer.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/refill.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/reftex-auc.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/reftex-cite.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile textmodes/reftex-dcr.el

In antlr-mode:
progmodes/antlr-mode.el:2426:20: Error: `c-init-language-vars' defined after use in (c-init-language-vars) (missing `require' of a library file?)
progmodes/antlr-mode.el:2427:26: Warning: c-init-language-vars called with 0
    arguments, but requires 1
make[2]: *** [progmodes/antlr-mode.elc] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [compile-main] Error 2
make: *** [lisp] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Could not install with `brew install emacs-plus@28` https://github.com/d12frosted/homebrew-emacs-plus/issues/316
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304
[ci] add --with-x11 to emacs-plus@28 build matrix https://github.com/d12frosted/homebrew-emacs-plus/pull/280
Could not install emacs-plus@28 --with-x11 https://github.com/d12frosted/homebrew-emacs-plus/issues/279

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
</Details>

**Comment by d12frosted** [comment]
Hey, it's a known issue. See in the [emacs-devel thread][1].

cc @daviderestivo 

  [1]: https://lists.gnu.org/archive/html/emacs-devel/2021-02/msg01815.html

**Comment by d12frosted** [comment]
And I see that now it builds. At least on [CI][1]. Can anyone please retry? 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/runs/1957149575?check_suite_focus=true

**Comment by vertexclique** [comment]
Works with `brew install emacs-plus@28 --with-no-titlebar`. I am closing this. Thanks @d12frosted

**Comment by d12frosted** [comment]
@benthamite looks like a different issue to me. Does it work now? If not, could you please open a new issue?

```
make[2]: *** [progmodes/antlr-mode.elc] Error 1

vs

make[2]: *** [org/org-tempo.elc] Segmentation fault: 11
```

**Comment by benthamite** [comment]
Apologies—I didn't read carefully. I just tried again and it still failed to install, unfortunately.

<details>
<summary>output</summary>
<p>

```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus@28 --with-no-titlebar --with-spacemacs-icon
==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-28/no-titlebar.patch
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-28/fix-window-role.patch
Already downloaded: /Users/pablostafforini/Library/Caches/Homebrew/downloads/fe10dba71a5a9f8fef6f4534268970b2b0ae0f941e515daed7ae88465083c287--fix-window-role.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-28/system-appearance.patch
Already downloaded: /Users/pablostafforini/Library/Caches/Homebrew/downloads/aaa0da80d33eac9e551adf7faf404e565c71e86c02ea4659200474fd6d899f5a--system-appearance.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/icons/spacemacs.icns
Already downloaded: /Users/pablostafforini/Library/Caches/Homebrew/downloads/5d0c663d4bf52e83f87a92a70e3dd140bedae40bfe5a4f26622e179d3f848921--spacemacs.icns
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/pablostafforini/Library/Caches/Homebrew/emacs-plus@28--git
From https://github.com/emacs-mirror/emacs
   168d262..0b613c9  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 22 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 0b613c9 * lisp/progmodes/simula.el: Use lexical-binding
==> Patching
==> Applying no-titlebar.patch
patching file src/nsterm.m
Hunk #1 succeeded at 441 (offset -32 lines).
Hunk #2 succeeded at 1968 (offset -15 lines).
Hunk #3 succeeded at 7526 (offset -11 lines).
Hunk #4 succeeded at 7563 with fuzz 1 (offset -12 lines).
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8883 (offset 115 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1277 (offset 24 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 2183 (offset -11 lines).
Hunk #2 succeeded at 5679 (offset -72 lines).
Hunk #3 succeeded at 5925 (offset -72 lines).
Hunk #4 succeeded at 5975 (offset -72 lines).
Hunk #5 succeeded at 6201 (offset -72 lines).
Hunk #6 succeeded at 9214 (offset 82 lines).
Hunk #7 succeeded at 10300 (offset 286 lines).
==> ImageMagick PKG_CONFIG_PATH: 
/usr/local/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/em
==> make
Last 15 lines from /Users/pablostafforini/Library/Logs/Homebrew/emacs-plus@28/03.make:
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/org-table.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/org-tempo.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/org-timer.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/org.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/ox-ascii.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/ox-beamer.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/ox-html.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/ox-icalendar.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/ox-latex.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/ox-man.el
EMACSLOADPATH= '../src/emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  -f batch-byte-compile org/ox-md.el
make[2]: *** [org/org.elc] Segmentation fault: 11
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [compile-main] Error 2
make: *** [lisp] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
[ci] add --with-x11 to emacs-plus@28 build matrix https://github.com/d12frosted/homebrew-emacs-plus/pull/280
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304
Could not install emacs-plus@28 --with-x11 https://github.com/d12frosted/homebrew-emacs-plus/issues/279
```

</p>
</details>

<details>
<summary>brew config</summary>
<p>

```
HOMEBREW_VERSION: 3.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0ad2564c5f1ddf6f16f707f2861556b80546713c
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 57ed7d24bc487a7a86e7447411ae54170ecafe43
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

</p>
</details>


<details>
<summary>brew doctor</summary>
<p>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h
```

</p>
</details>

**Comment by d12frosted** [comment]
thanks for sharing more infor @benthamite. I can't reproduce it nor locally nor on [CI][1]. Also I didn't find anything related on the Emacs mailing lists. Could you please build with `--verbose` option and share output? 

[1]: https://github.com/d12frosted/homebrew-emacs-plus/runs/2258177989?check_suite_focus=true#step:4:320

**Comment by benthamite** [comment]
Of course.
[output.txt](https://github.com/d12frosted/homebrew-emacs-plus/files/6253133/output.txt)

**Comment by d12frosted** [comment]
@benthamite sorry, I don't know what's happening there. I tried searching on emacs devel mailing list, but nothing like this has occured. Has it worked before? If yes, how long ago?

**Comment by benthamite** [comment]
I never managed to successfully install emacs-plus@28, since first trying a few weeks ago. I'm happy to use 27, though; this isn't important. Thanks for your help!

**Comment by d12frosted** [comment]
Sorry to hear that :( Well, at least `emacs-plus@27` works for you. Enjoy :)

**Comment by benthamite** [comment]
Not sure if this is of interest, but I thought I should let you know that I tried again today and was successfully able to install `emacs-plus@28`. I didn't do anything differently this time.
