### ISSUE TITLE
Noticeable delays and stalls when using emacs-plus

### ISSUE THREAD

**Issue by declanqian** [d12frosted/homebrew-emacs-plus#317]
I installed `emacs-plus@28 --with-ctags --with-dbus --with-debug --with-mailutils --with-no-frame-refocus --with-xwidgets --without-imagemagick --with-native-comp`
I've been <b>experiencing many noticeable delays and stalls</b> when using Emacs. For example `C-h m` <b>take seconds</b> to finish.
Also tested with only `--without-imagemagick --with-native-comp`

And today I tried `emacs --cask`, the pre compiled binnary from https://emacsformacosx.com/. Which doesn't have this issue.

```
Model Name:	MacBook Pro
Model Identifier:	MacBookPro14,1
Processor Name:	Dual-Core Intel Core i7
Processor Speed:	2.5 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	4 MB
Hyper-Threading Technology:	Enabled
Memory:	16 GB
System Firmware Version:	429.80.1.0.0
SMC Version (system):	2.43f11
```
```
HOMEBREW_VERSION: 3.0.2-21-g3efab3e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3efab3efa7114afe713b2485032b740e6b55d6e4
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 888ad8f6effc26147863935b4b0b1ff3ace8d273
Core tap last commit: 7 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

**Comment by d12frosted** [comment]
Hey, sad to hear about performance issues. I must argue that comparison is not fair, because:

1. You are comparing Emacs 27 (official release) and Emacs 28 (bleeding edge development version)
2. You are comparing bare GNU Emacs and GNU Emacs with highly experimental features (`--with-xwidgets` and `--with-native-comp`).

And since you are using `--with-native-comp`, I have to ask. Does it become better with time? Because in `emacs-plus` we are using JIT compilation, meaning that the first usage of anything will force compilation, which might take some time.

My advice would be - install `emacs-plus@27` without any experimental features, check if it is as fast as you would expect, and then bisect which feature slows you down.

**Comment by declanqian** [comment]
> And since you are using `--with-native-comp`, I have to ask. Does it become better with time? Because in `emacs-plus` we are using JIT compilation, meaning that the first usage of anything will force compilation, which might take some time.

I usually compiled all user/included lisp all at once at first launch when using native comp. But still I got lagging even when invoking `C-h m`.

> My advice would be - install `emacs-plus@27` without any experimental features, check if it is as fast as you would expect, and then bisect which feature slows you down.

Just installed
`brew install emacs-plus@28 --without-imagemagick`
`brew install emacs-plus@27 --without-imagemagick`
`brew install emacs-nightly --cask`

```
(defmacro measure-time (&rest body)
  "Measure and return the running time of the code block."
  (declare (indent defun))
  (let ((start (make-symbol "start")))
    `(let ((,start (float-time)))
       ,@body
       (- (float-time) ,start))))

(measure-time (describe-mode))
(benchmark 1 (describe-mode))
```

`emacs -Q -nw`
Here is the screen cast(trimed). 
https://streamable.com/12gl8r

Here are the output. Only emacs-plus@28 has noticeable delay.
I believe `emacs nightly` also on the master branch?

```
;; emacs plus 28
;; 0.6400909423828125
;; Type C-x 1 to delete the help window, C-M-v to scroll help.
;; Elapsed time: 0.003934s
;; "Elapsed time: 0.003934s"

;; emacs plus 27
;; 0.006138801574707031
;; Type C-x 1 to delete the help window, C-M-v to scroll help.
;; Elapsed time: 0.000001s
;; "Elapsed time: 0.000001s"

;; cask emacs nightly
;; 0.05111503601074219
;; Type C-x 1 to delete the help window, C-M-v to scroll help.
;; Elapsed time: 0.017618s
;; "Elapsed time: 0.017618s"

```

**Comment by declanqian** [comment]
Manually compiled against `master` branch with
```CC=/usr/bin/gcc ./configure --with-ns --with-modules --with-json```
has the similar output as emacs-plus@28.
