### ISSUE TITLE
Any way to display multi tab-bar in GUI?

### ISSUE THREAD

**Issue by tru2dagame** [d12frosted/homebrew-emacs-plus#319]
Emacs 27 now supports tab-bar mode.

Is there a way to show the tab-bar in GUI mode like this?

- First line: tab-bar-mode
- Second line: tab-line-mode

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/1673006/109427355-04f1bb00-7a2d-11eb-8a1d-afe659aadc5a.png">

It seems emacs-plus can only show the tab-bar in terminal version.
I really like the tab-bar mode because sometimes I would like to keep several windows in one tab-bar selection. That would be very useful.

**Comment by d12frosted** [comment]
Hey @tru2dagame,

Thanks for reaching me out with this question. I never heard about this functionality before 😸 In general, `emacs-plus` is the same GNU Emacs, meaning that if something is available in GNU Emacs, it's available in `emacs-plus`. 

Regarding `tab-bar-mode` - it works, but its GUI for macOS is not implemented yet, so you have to use keyboard for managing tabs. Checkout `Emacs > Frames > Tab Bars` manual for more information.

On of the ideas is to place information about tabs in the mode line. Checkout this thread on [reddit][1] for possible implementation. 

  [1]: https://www.reddit.com/r/emacs/comments/fkqj9v/emacs_27_tabbarmode_for_macos_show_in_minibuffer/

**Comment by tru2dagame** [comment]
@d12frosted Thanks for pointing out the workaround. I would definitely try that.

The screenshot I paste is actually from `homebrew-emacsmacport` Mac GUI. It would be nice to always show the tab-bar below title bar.

If you can, please try to add that support for emacs-plus, thanks.

**Comment by d12frosted** [comment]
> If you can, please try to add that support for emacs-plus, thanks.

I would love to use this moment to point out the difference between `emacs-plus` and Emacs Mac Port. `emacs-plus` is a mere `brew` formula for installing GNU Emacs. And Emacs Mac Port is a fork of GNU Emacs focused on GUI features for macOS.

This means that the best way to add something to `emacs-plus` is to add it to [GNU Emacs][1] 😸 There are very few exceptions to this, namely xwidgets and some simple frame-related patches that are unlikely to be accepted by upstream. 

> It would be nice to always show the tab-bar below title bar.

This is a great feedback for Emacs contributors and maintainers. I am not among them 😸 

> The screenshot I paste is actually from homebrew-emacsmacport Mac GUI.

Could you please share the reasons for using `emacs-plus` over mac port? Just curious 😸 

  [1]: https://savannah.gnu.org/projects/emacs

**Comment by tru2dagame** [comment]
@d12frosted I totally got it. It's a feature that terminal version can show it correctly but GUI not. 

> Could you please share the reasons for using emacs-plus over mac port? Just curious 😸

I love to use emacs. 
Emacs-plus gives more options, handle the server-mode better with ohmyzsh emacs plugin.

By the way, I got to know the tab-bar mode from this [YouTube video](https://www.youtube.com/watch?v=C7ZlNRbWdVI)
It gives me another dimension to manager and switch from lots lots of tabs.

**Comment by d12frosted** [comment]
>  Emacs-plus gives more options, handle the server-mode better with ohmyzsh emacs plugin.

Nice. I thought it's a vice versa in terms of `server-mode` 😸 

> By the way, I got to know the tab-bar mode from this YouTube video

Thanks for sharing.

**Comment by d12frosted** [comment]
Closing this issue as it is out of scope of emacs-plus. It should be implemented in GNU Emacs 😸
