### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by srustamo** [d12frosted/homebrew-emacs-plus#32]
Installing with `brew install emacs-plus --HEAD`.

Installation goes without any errors. 

Trying to start crashes.

Homebrew 1.1.13-108-gceb1629ad7
Homebrew/homebrew-core (git revision 00cfb; last commit 2017-04-24)
OS X 10.9.5

**Comment by d12frosted** [comment]
Hey @srustamo,

It might be an upstream issue (you're building from `HEAD`). Either try later or report it to the upstream. For me it even doesn't build right now. 😢 

Anyway, please share your `brew config`.

**Comment by srustamo** [comment]
Thanks. 

HOMEBREW_VERSION: 1.1.13-108-gceb1629ad7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ceb1629ad7aeec4c9e9c264efb29b59a96f8556c
Last commit: 87 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 00cfb61f3ff41be132a57296cdcbdaa6eae73e0b
Core tap last commit: 70 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 6.0 build 600
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/xx3/.rbenv/shims/ruby => /Users/xx3/.rbenv/versions/2.1.2/bin/ruby
Java: 1.8.0_92, 1.6.0_65-b14-462
macOS: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
X11: 2.7.8 => /opt/X11
MacPorts/Fink: /opt/local/bin/port

**Comment by jwintz** [comment]
As of https://debbugs.gnu.org/cgi/bugreport.cgi?bug=22060, I just reinstalled emacs with "--HEAD", on two different machines, and everything goes fine.

FYI: Using Sierra and Xcode 8.3.1.

**Comment by d12frosted** [comment]
@srustamo wow, Xcode version is `6.2` and macOS is `10.9.5-x86_64`. Should not be reason for failures though. 

@jwintz good to hear. Mine is still failing though. 😿

**Comment by srustamo** [comment]
Latest commit fixes the issue.

**Comment by d12frosted** [comment]
Great to hear, @srustamo ! And thanks for reporting it back here. ❤️ 😸
