### ISSUE TITLE
Could not reinstall with @28 --with-native-comp --with-modern-icon

### ISSUE THREAD

**Issue by aaronjensen** [d12frosted/homebrew-emacs-plus#321]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

brew reinstall emas-plus@28 

```
==> Reinstalling d12frosted/emacs-plus/emacs-plus@28 --with-native-comp --with-modern-icon
```

## What happened (include command output)

<pre>
$ brew reinstall emacs-plus@28
</pre>

I'm trying again with a fresh install (not reinstall), I'll report back if anything is different.

<details>
  <summary>Command output</summary>
  <pre>

==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-28/fix-window-role.patch
Already downloaded: /Users/aaronjensen/Library/Caches/Homebrew/downloads/fe10dba71a5a9f8fef6f4534268970b2b0ae0f941e515daed7ae88465083c287--fix-window-role.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-28/system-appearance.patch
Already downloaded: /Users/aaronjensen/Library/Caches/Homebrew/downloads/aaa0da80d33eac9e551adf7faf404e565c71e86c02ea4659200474fd6d899f5a--system-appearance.patch
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/aaronjensen/Library/Caches/Homebrew/emacs-plus@28--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 40d8f83 smerge-vc-next-conflict: Move to conflict markers more reliably
==> Reinstalling d12frosted/emacs-plus/emacs-plus@28 --with-native-comp --with-modern-icon
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8904 (offset 136 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1277 (offset 24 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 2197 (offset 3 lines).
Hunk #2 succeeded at 5693 (offset -58 lines).
Hunk #3 succeeded at 5939 (offset -58 lines).
Hunk #4 succeeded at 5989 (offset -58 lines).
Hunk #5 succeeded at 6215 (offset -58 lines).
Hunk #6 succeeded at 9235 (offset 103 lines).
Hunk #7 succeeded at 10321 (offset 307 lines).
==> ImageMagick PKG_CONFIG_PATH:
/usr/local/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/e
==> make
==> make install
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - native-lisp

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 50db2638cd8b16d577c1919398176458cdbbb95c
Core tap last commit: 32 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--appdir=/Applications"]
HOMEBREW_EDITOR: e
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_TEMP: /var/tmp
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by aaronjensen** [comment]
It built fine with a regular install. The problem only exhibits on a reinstall, it seems.

**Comment by d12frosted** [comment]
> I'm trying again with a fresh install (not reinstall), I'll report back if anything is different.

Yes, please try 😸 Because `reinstall` in `brew` is not the same as `uninstall` + `install`.

**Comment by d12frosted** [comment]
> It built fine with a regular install. The problem only exhibits on a reinstall, it seems.

Ah, you already have an answer 😸 

The question about `reinstall` occured multiple times. I even added a section to [readme][1] saying that one should not use `reinstall`. Since it's "expected", closing the issue.

P. S. Glad it actually worked after after `uninstall` 😸 

[1]: https://github.com/d12frosted/homebrew-emacs-plus#reinstall

**Comment by d12frosted** [comment]
As a follow up - 01973b0
