### ISSUE TITLE
Add nobu417's Big Sur icon 

### ISSUE THREAD

**Issue by jmhammond** [d12frosted/homebrew-emacs-plus#326]
Could we add as an icon option the Big Sur icon from [nobu417 which is found here](https://github.com/nobu417/emacs-icon-replacement-for-macos-big-sur/blob/master/README.md)?  Thanks!

**Comment by d12frosted** [comment]
@jmhammond thanks for suggestion :) added under `--with-nobu417-big-sur-icon` option

enjoy!
