### ISSUE TITLE
brew upgrade emacs-plus -> Errno::ENOENT: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by johnnypea** [d12frosted/homebrew-emacs-plus#327]
## What happened (include command output)

<pre>
$ brew upgrade emacs-plus
</pre>

<details>
  <summary>Command output</summary>
  <pre>
Updating Homebrew...
==> Upgrading 1 outdated package:
d12frosted/emacs-plus/emacs-plus@27 27.1 -> 27.2
==> Upgrading d12frosted/emacs-plus/emacs-plus@27 27.1 -> 27.2 --with-no-titlebar --with-modern-doom-icon
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-27/fix-window-role.patch
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-27/system-appearance.patch
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-27/ligatures-freeze-fix.patch
######################################################################## 100.0%
==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-27.2.tar.xz
Already downloaded: /Users/johnnypea/Library/Caches/Homebrew/downloads/2cd8fd48748257712575a817f0cb133837fd4fbd6f5d6f7c402401af9f862e32--emacs-27.2.tar.xz
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/johnnypea/Library/Caches/Homebrew/downloads/5fa4e19676cb34d14ca64131898d6b8027ef723176a26333b9d43348e1336731--no-titlebar.patch
  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.0.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed87211daa83982a6136e14d181a1550b46a0f17
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c109d8650a57d9008c1f76772eb2ab93ea97e9ec
Core tap last commit: 70 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.DqoOkgERE4/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
</pre>

**Comment by d12frosted** [comment]
Please do not use `brew upgrade` for the same reasons as [reinstall][1]. Try uninstalling and then installing again :smile_cat: 

[1]: https://github.com/d12frosted/homebrew-emacs-plus#reinstall

**Comment by d12frosted** [comment]
@johnnypea does it work? :)

**Comment by johnnypea** [comment]
Yes, @d12frosted it did work, thank you :).

**Comment by d12frosted** [comment]
@johnnypea cool, I am glad 🎉
