### ISSUE TITLE
Unable to copy/paste from/to OSX clipboard

### ISSUE THREAD

**Issue by licorna** [d12frosted/homebrew-emacs-plus#33]
I'm used to copy/paste using OSX clipboard from/to Emacsforosx, but it seems I can't do it with emacs-plus. Is this an non implemented feature?

**Comment by licorna** [comment]
I know what the error is now: I was running `/usr/local/bin/emacs` from within tmux, and it cripples the pbcopy & pbpaste commands.

**Comment by tasmo** [comment]
Shouldn't it be possible to use emacs-plus from inside a tmux session with a proper copy/paste?
