### ISSUE TITLE
Could not install with emacs-plus@27

### ISSUE THREAD

**Issue by jerasky** [d12frosted/homebrew-emacs-plus#331]
when i execute the command: brew install emacs-plus in macos big sur 11.2.3, and get the error informations:

==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-27/fix-wind
##O=-                                                                         
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
Error: Failed to download resource "emacs-plus@27--patch"
Download failed: https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/emacs-27/fix-window-role.patch

**Comment by d12frosted** [comment]
@jerasky could you please retry? Maybe there was some networking issues? Works on [CI][1] and when I run it locally, it also works.

[1]: https://github.com/d12frosted/homebrew-emacs-plus/runs/2242870641?check_suite_focus=true#step:5:75

**Comment by jerasky** [comment]
@d12frosted I try it several times, and process some other errors, eventually, it works, thanks!
