### ISSUE TITLE
Add Metal support

### ISSUE THREAD

**Issue by agzam** [d12frosted/homebrew-emacs-plus#336]
Add `--with-mac-metal` option discussed here: https://www.reddit.com/r/emacs/comments/mhdjxb/macos_emacs_with_metal_support/

**Comment by d12frosted** [comment]
This is nice! Thanks for sharing @agzam

I fear that this option is not available in GNU Emacs, the link discusses new addition to Emacs Mac Port. Will need to check implementation. Quick search over [install instructions][1] and [configuration script][2] didn't result in any evidence that this is something available in GNU Emacs.

[1]: https://github.com/emacs-mirror/emacs/blob/master/INSTALL
[2]: https://github.com/emacs-mirror/emacs/blob/master/configure.ac

**Comment by d12frosted** [comment]
Seems like it's not portable, e.g. very tied to other stuff Emacs Mac Port has. Here is [commit][1] introducing metals.

[1]: https://bitbucket.org/mituharu/emacs-mac/commits/0048cd3c420648bacdba4556bcc79151a2ab3fbf

**Comment by aaronjensen** [comment]
FYI there's a [very long thread about this on emacs-devel](https://yhetil.org/emacs-devel/CAHyO48xaUrR9oB0XvURz3qbT99kULvmK7UUqGyPJw3kfXs_atg@mail.gmail.com/)

The tl;dr is that metal is slower and Emacs 28 has new optimizations in it that make it just as fast or faster than Emacs 27 mac port with or without metal, at least according to my testing. Combined with the recent [hash patch](https://github.com/emacs-mirror/emacs/commit/e3b8ddd5005903465ec86823559a2e884c7b13f2) Emacs 28 for me no longer has an annoying perceptible latency while typing, even with line numbers. 

Unless someone has a good reason to reconsider metal (I couldn't find one) it may be appropriate to close this issue.

**Comment by d12frosted** [comment]
@aaronjensen thanks for sharing that thread and your experience. Your reasoning and the fact that metals is a huge divergence from GNU Emacs is enough for me to mark it as wont fix, unless it is fixed in upstream.

Thanks everyone.
