### ISSUE TITLE
upgrade to 25.2 

### ISSUE THREAD

**Issue by jasonjckn** [d12frosted/homebrew-emacs-plus#34]

**Comment by d12frosted** [comment]
@jasonjckn thanks for the kick! 😸 

Updated to new version in 167d0ee
Updated bottle for sierra in cd43320

Would be nice to have bottle for El Capitan. Maybe @wadkar would help 😸

**Comment by jasonjckn** [comment]
thanks! 💯

**Comment by d12frosted** [comment]
funny thing, I've build a bottle, but forgot to upload it to s3 😸 not it's there, so use it 😸

**Comment by wadkar** [comment]
Bottle [here](https://cmu.box.com/s/fg9yjbd5yirbxmzrqhdqrdkdwkjjf42z). The sha256 is `0cad5513de68ec93b4f522fd6a065ee163bc880a5e8091794fb8b3da3dc635e5`

The pleasure is all mine. Thanks for the update!

**Comment by d12frosted** [comment]
Many thanks, @wadkar.

I've uploaded it and added to the formulae itself. Should be available to all El Capitan users. 😸

**Comment by wadkar** [comment]
Umm, I got HTTP404 when I tried to reinstall it from the bottle. Says,
```
==> Downloading https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-25.2.el_capitan.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "emacs-plus"
Download failed: https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-25.2.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```
Can you please check again?

**Comment by d12frosted** [comment]
@wadkar please, `brew update` and try again 😸

**Comment by wadkar** [comment]
yep, its working now.
