### ISSUE TITLE
native-compile is going to be merged into master

### ISSUE THREAD

**Issue by d12frosted** [d12frosted/homebrew-emacs-plus#340]
As someone said, good GNUs, everyone! Native compilation feature is going to be merged next week into master. [Source][1].

Once it happens, we will simply switch to `master`. I am going to have limited availability till May, but would love to have a PR from soneone, so I can merge it 😸 

CC @daviderestivo 

[1]: https://lists.gnu.org/archive/html/emacs-devel/2021-04/msg00484.html
[pr]: https://github.com/d12frosted/homebrew-emacs-plus/pull/337

**Comment by daviderestivo** [comment]
I'll try to prepare a PR as soon as native-comp is merged into master :).

**Comment by seanfarley** [comment]
It was just merged today!

**Comment by d12frosted** [comment]
Fixed via #346

Thanks @seanfarley for notifying and @aaronjensen for a quick PR :) 

I am overly happy to see it in master.

**Comment by aaronjensen** [comment]
👍 

Would it make sense to change the flag at this time to match emacs's? `--with-native-compilation`?

**Comment by d12frosted** [comment]
Not sure if it worth it. Maybe via https://rubydoc.brew.sh/Formula#deprecated_option-class_method. But I never used it :)

**Comment by seagle0128** [comment]
README should be updated accordingly.
