### ISSUE TITLE
Why use -I for LDFLAGS

### ISSUE THREAD

**Issue by beyondpie** [d12frosted/homebrew-emacs-plus#356]
I can install naive comp emacs28, but seems it cannot find libgccjit. (macOS Catalina)
I read the source:

- https://github.com/d12frosted/homebrew-emacs-plus/blob/05b6ef9157706ae619fb24ddc6db7387ad2ad3f1/Formula/emacs-plus%4028.rb#L112

Should we use  -L and include the library path? 

- Another issue is   https://github.com/d12frosted/homebrew-emacs-plus/blob/05b6ef9157706ae619fb24ddc6db7387ad2ad3f1/Formula/emacs-plus%4028.rb#L104

I check my computer the default HOMEBREW_PREFIX is null. Is this a must? If true,  how should I set it? 
In my computer, brew install both gcc and libgccjit into the local dir `/usr/local/opt/`.

**Comment by d12frosted** [comment]
38d00ad43b832786dd4b8b652bc255f5cc1f7195 removes these flags manipulations from `emacs-plus@29`. I plan to backport https://github.com/d12frosted/homebrew-emacs-plus/pull/453 to `emacs-plus@28`, which will make it possible to get rid of these flags manipulations in `emacs-plus@28` as well. I understand that relation between #453 and flags is not obvious, so for reference - it's related to env change (from `superenv` to standard).

Initially when I've seen your issue like a year ago, I didn't realise that you actually had a problem with installation 🤦 And thought that it's just a question about formula internals. I am sorry that I didn't help you 🙏 

Hope it works these days

**Comment by beyondpie** [comment]
No worries. Later I install Emacs from source by myself. Recently, I tries emacs-plus, now it works without any issues. Thanks for your great contribution!

**Comment by d12frosted** [comment]
@beyondpie great to hear that it works now 🎉 thanks for using `emacs-plus`
