### ISSUE TITLE
[Installation Question] How do I install emacs-28 --with-native-comp from a specific commit

### ISSUE THREAD

**Issue by CsBigDataHub** [d12frosted/homebrew-emacs-plus#357]
How do I pin the emacs-plus --with-native-comp to a specific commit.

want to use verified `good` commits.

https://github.com/jimeh/build-emacs-for-macos/issues/6

**Comment by d12frosted** [comment]
You can `brew edit emacs-plus@28` and manually [pin to specific revision][1].

[1]: https://github.com/d12frosted/homebrew-emacs-plus/commit/6f267537f9ae6f8e01df64d883095db819c48391

**Comment by CsBigDataHub** [comment]
Thanks @d12frosted . Also is it possible to add this feature with `--with-native-comp` ?

```
-j, --parallel COUNT             Compile using COUNT parallel processes (detected: 8)
```

**Comment by d12frosted** [comment]
Since you are making local edits, you can pass [extra arguments][1]. Though maybe this particular argument should be passed by default 🤔 

[1]: https://github.com/d12frosted/homebrew-emacs-plus/blob/master/Formula/emacs-plus%4028.rb#L99

**Comment by CsBigDataHub** [comment]
> Since you are making local edits, you can pass [extra arguments](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/Formula/emacs-plus%4028.rb#L99). Though maybe this particular argument should be passed by default 🤔

+1 for this feature. I have i9 macbook pro and by default the build is taking ~25 mins. I would like to speed up that process and put the cores to good use.

**Comment by jimeh** [comment]
I believe Homebrew already sets make to use as many jobs as your machine has CPU cores, by setting `MAKEFLAGS`.

For reference, search for `HOMEBREW_MAKE_JOBS` on [this](https://docs.brew.sh/Manpage#environment) page, and check this issue from 2010: https://github.com/Homebrew/legacy-homebrew/issues/3118

According to the above issue, if you run `brew install --verbose <formula-name>` you should see it setting `MAKEFLAGS` to include `-j`. Though I haven't tested it myself :)

**Comment by CsBigDataHub** [comment]
Thanks @jimeh and @d12frosted . I am closing this issue. I think I got all the information I need.

**Comment by d12frosted** [comment]
@jimeh you are right. I totally forgot that it already supported by brew out of box.
