### ISSUE TITLE
[Feature Request] Replace emacs toolbar icons with system ones 

### ISSUE THREAD

**Issue by shaunsingh** [d12frosted/homebrew-emacs-plus#363]
Emacs-mac uses the macOS Big Sur icons in place of the much worse looking gnu ones, Is it possible to implement this in emacs-plus as well? Possibly as a patch? 

The commit is here: https://bitbucket.org/mituharu/emacs-mac/commits/d0c85c2876f6fa83c4aec3f0c2b27b7b6afd5bd5, it should be a fairly simple change.

**Comment by d12frosted** [comment]
Hey @shaunsingh , thank you for your feature request.

I've been thinking about this for some time and I am not sure that it makes sense to implement in `emacs-plus`. 

- First and the most important reason - `emacs-plus` is a formula to build GNU Emacs and it tries to stay as close as possible to GNU Emacs, unlike Emacs for Mac, which is a fork. 
- Second reason, I try to keep as little indirection points as possible. This change can't become default, so I will have to introduce new build option which increases build matrix (and I would rather reduce it). 
- And the third reason - I don't want to maintain some C code that changes visuals that I am not using. 

Now, someone might rightfully ask. What about icons? Yes, I've added a bunch of icons and I am open for other icons. But they don't really add any indirection to the build process. It's just a resource that's free to maintain 😸 But patches are not free, as they add indirection to compilation AND runtime. 

@shaunsingh please let me know what you think :)

**Comment by shaunsingh** [comment]
> Second reason, I try to keep as little indirection points as possible. This change can't become default, so I will have to introduce new build option which increases build matrix (and I would rather reduce it)

I didn't know `emacs-plus` was building emacs, I thought it was a fork similar to emacs-mac. Now that I understand how emacs-plus works, I agree with you on this point. I've grown to love the default icons a little more as well.
