### ISSUE TITLE
Could not install with @28 --with-native-comp on old intel core duo iMac (Fatal error 4: Illegal instruction)

### ISSUE THREAD

**Issue by koenige50** [d12frosted/homebrew-emacs-plus#368]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install emacs 28 with native comp on an old 2008 iMac with an Intel Core Duo processor

## What happened (include command output)

Compilation aborts with `Fatal error 4: Illegal instruction`. From what I gather, this error happens with binaries using Intel's AVX instructions, which are not supported by older CPUs such as the Core Duo.

From what I read, it should be possible to set some compiler flags to check for AVX support and compile without it. But I do not know how to do that.

Recently I have been getting more of these "illegal instruction 4" errors with different Homebrew apps, probably because compiler toolchains move on and people don't bother to check for compatibility with older systems. Mine works fine though, and I would like extend its life as long as possible.

<pre>
$ brew install emacs-plus@28 --with-native-comp --with-modern-icon
</pre>

<details>
  <summary>Command output</summary>
  <pre>

==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/xxx/Library/Caches/Homebrew/emacs-plus@28--git
==> Checking out revision 4d63a033a726a8da33bda8d18a503e88bfb794fb
HEAD is now at 4d63a033a7 Small improvements to handling of IMAP mark search
HEAD is now at 4d63a033a7 Small improvements to handling of IMAP mark search
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8859 (offset 91 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1260 (offset 7 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 2167 (offset -27 lines).
Hunk #2 succeeded at 5663 (offset -88 lines).
Hunk #3 succeeded at 5909 (offset -88 lines).
Hunk #4 succeeded at 5959 (offset -88 lines).
Hunk #5 succeeded at 6185 (offset -88 lines).
Hunk #6 succeeded at 9190 (offset 58 lines).
Hunk #7 succeeded at 10294 (offset 280 lines).
==> ImageMagick PKG_CONFIG_PATH: 
/usr/local/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodi
==> make
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/emacs-plus@28/03.make:
emacs-lisp/comp.el: Warning: Missing value for option `(:documentation . "t if pure nil otherwise.")' of slot `pure' in struct comp-func-d!
emacs-lisp/comp.el: Warning: Missing value for option `(:documentation . "Mvar holding the derived return type.")' of slot `type' in struct comp-func-d!
emacs-lisp/comp.el: Warning: Missing value for option `(:documentation . "List of possible types the mvar can assume.
Each element cannot be a subtype of any other element of this slot.")' of slot `typeset' in struct comp-mvar!
emacs-lisp/comp.el: Warning: Missing value for option `(:documentation . "List of possible values the mvar can assume.
Integer values are handled in the `range' slot.")' of slot `valset' in struct comp-mvar!
emacs-lisp/comp.el: Warning: Missing value for option `(:documentation . "Integer interval.")' of slot `range' in struct comp-mvar!
emacs-lisp/comp.el: Warning: Missing value for option `(:documentation . "Non-nil if the constraint is negated")' of slot `neg' in struct comp-mvar!
EMACSLOADPATH= '../src/bootstrap-emacs' -batch --no-site-file --no-site-lisp --eval '(setq load-prefer-newer t)'  \
	-l comp -f batch-byte+native-compile emacs-lisp/autoload.el
Fatal error 4: Illegal instruction
make[2]: *** [emacs-lisp/autoload.elc] Abort trap: 6
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [bootstrap-emacs.pdmp] Error 2
make: *** [src] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Emacs-plus@28 with native comp crashes on MacOS 12/Monterey https://github.com/d12frosted/homebrew-emacs-plus/issues/361
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09f7bc27a99469cf947431df4754737dfbadb31d
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 20c3887cd24984915e6412e69b013c7491d71ecf
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 12.0.0 build 1200
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by koenige50** [comment]
As a followup, these illegal instruction 4 problems are due to Mac OS 10.14 Mojave assuming as a minimum Intel's Nehalem architecture, and Homebrew as well. For those using Mojave and later on unsupported pre-Nehalem machines (via DosDude's patches), problem can be solved by customizing Homebrew to compile packages for the older "core2" architecture.

Edit file `/usr/local/Homebrew/Library/Homebrew/extend/os/mac/hardware.rb` to replace ":nehalem" with ":core2":

```
module Hardware
  extend T::Sig
  sig { params(version: T.nilable(Version)).returns(Symbol) }
  def self.oldest_cpu(version = MacOS.version)
    if CPU.arch == :arm64
      :arm_vortex_tempest
    # TODO: this cannot be re-enabled until either Rosetta 2 supports AVX
    # instructions in bottles or Homebrew refuses to run under Rosetta 2 (when
    # ARM support is sufficiently complete):
    #   https://github.com/Homebrew/homebrew-core/issues/67713
    #
    # elsif version >= :big_sur
    #   :ivybridge
    elsif version >= :mojave
      # :nehalem
      :core2
    else
      # generic_oldest_cpu
      :core2
    end
  end
end
```

Then install the afflicted package from source, e.g. `brew reinstall --build-from-source package --with-native-comp`. Ideally you should install all dependencies from source as well, though that can take a long time. Since not all standard pre-compiled packages crash, you can try your luck by installing them the normal way, then reinstall from source if they crash.

Note that Homebrew seems to restore `hardware.rb` back to default values on every upgrade. Always check before installing from source. Also note that emacs-plus maintainer recommends not using `brew reinstall` but rather `brew rm` followed by `brew install`.

Emacs 28 with now builds and runs on a 2008 Mac with Intel Penryn architecture.

Source: https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/page-466?post=27026470#post-27026470

**Comment by d12frosted** [comment]
Oh my. Thanks for finding solution and sharing it here! Glad it works now 🎉 @koenige50

**Comment by mmolinac** [comment]
@koenige50 you made my day. My MacBook 2008 is grateful for this.

**Comment by d12frosted** [comment]
Since there is a solution, I am closing the issue and pinning it. Thanks!
