### ISSUE TITLE
Broken master due to patch conflct

### ISSUE THREAD

**Issue by d12frosted** [d12frosted/homebrew-emacs-plus#376]
See CI that is red. Unfortunately I can't address this issue in adequate time frame, so I would appreciate a PR that fixes build 🙏

cc @aaronjensen maybe you want to take a look? 🙃

**Comment by aaronjensen** [comment]
Looks like it is just with no titlebar that’s failing. Folks can build without it and be ok until whoever is familiar with that patch can fix it.

**Comment by aaronjensen** [comment]
The Mac window code was rewritten so the patch will likely need to be rewritten as well.  One question is how does no titlebar differ from an undecorated window?

**Comment by d12frosted** [comment]
Ah, sorry for noise then. For some reason I could not view the build log from mobile view. And I feared that the default build is broken. Then it can definitely wait.

As per your question - nowadays I don't know. Maybe it's time to revisit that patch and remove it if it doesn't give anything. In my sense such things must be configurable by some lisp in init.el and not by compilation flag.

Cheers,
***@***.***

**Comment by cmacrae** [comment]
Just a heads up, I opened the above PR which sorts this for now ☝️  
Nothing fancy, but it doe also fix the child frame issue (#192)

**Comment by anildigital** [comment]
Hope this issue fixes #379 sooner.

**Comment by etehtsea** [comment]
Another version that based on the previous one.

```
From 42d9068b3b5d620ccd6548dbb089368875e03f1f Mon Sep 17 00:00:00 2001
From: Konstantin Shabanov <mail@etehtsea.me>
Date: Mon, 9 Aug 2021 15:59:45 +0700
Subject: [PATCH] Disable titlebar on macOS

---
 src/nsterm.m | 16 ++++------------
 1 file changed, 4 insertions(+), 12 deletions(-)

diff --git a/src/nsterm.m b/src/nsterm.m
index ba5d81fb6c..28022822e6 100644
--- a/src/nsterm.m
+++ b/src/nsterm.m
@@ -433,11 +433,9 @@ - (NSColor *)colorUsingDefaultColorSpace
 
 /* These flags will be OR'd or XOR'd with the NSWindow's styleMask
    property depending on what we're doing.  */
-#define FRAME_DECORATED_FLAGS (NSWindowStyleMaskTitled              \
-                               | NSWindowStyleMaskResizable         \
-                               | NSWindowStyleMaskMiniaturizable    \
-                               | NSWindowStyleMaskClosable)
-#define FRAME_UNDECORATED_FLAGS NSWindowStyleMaskBorderless
+#define FRAME_UNDECORATED_FLAGS (NSWindowStyleMaskResizable         \
+                                | NSWindowStyleMaskMiniaturizable    \
+                                | NSWindowStyleMaskClosable)
 
 /* TODO: Get rid of need for these forward declarations.  */
 static void ns_condemn_scroll_bars (struct frame *f);
@@ -8217,10 +8215,8 @@ - (instancetype) initWithEmacsFrame:(struct frame *)f
 
   if (fullscreen)
     styleMask = NSWindowStyleMaskBorderless;
-  else if (FRAME_UNDECORATED (f))
-    styleMask = FRAME_UNDECORATED_FLAGS;
   else
-    styleMask = FRAME_DECORATED_FLAGS;
+    styleMask = FRAME_UNDECORATED_FLAGS;
 
 
   self = [super initWithContentRect:
@@ -8293,10 +8289,6 @@ - (instancetype) initWithEmacsFrame:(struct frame *)f
       if ([col alphaComponent] != (EmacsCGFloat) 1.0)
         [self setOpaque:NO];
 
-      /* toolbar support */
-      if (! FRAME_UNDECORATED (f))
-        [self createToolbar:f];
-
       /* macOS Sierra automatically enables tabbed windows.  We can't
          allow this to be enabled until it's available on a Free system.
          Currently it only happens by accident and is buggy anyway.  */
-- 
2.32.0
```

**Comment by sagittaros** [comment]
@etehtsea patch works great for me

**Comment by anildigital** [comment]
@sagittaros @d12frosted Any info about how to apply this patch pasted here and install emacs-plus 28? Thanks!

**Comment by sagittaros** [comment]
Someone else might be better suited to answer. I am using the patch in my own nix overlay

**Comment by d12frosted** [comment]
Should be fixed now 😸 Kudos to @tsuu32 and @cmacrae.
