### ISSUE TITLE
Listing directory failed but ‘access-file’ worked

### ISSUE THREAD

**Issue by digitive** [d12frosted/homebrew-emacs-plus#383]
Helps needed. I've added `Full Disk Access` to Emacs.app, as well as tried added this permission to ruby, but I still cannot access directories with Dired. There is no problem to open files.

Previously I had Emacs 27 which worked. But recently I uninstalled Emacs 27 and installed 28, it broke. I also tried revoke `Full Disk Access` and regranted, no luck. How did you guys make it work? I'm using macos Big Sur.

**Comment by d12frosted** [comment]
I actually don't know why it's happening. I recently reinstalled macos and didn't do anything special to make it work.

**Comment by digitive** [comment]
@d12frosted I eventually reinstalled my macok and it works now. Thanks heaps.

**Comment by d12frosted** [comment]
Heavy solution, but happy that it work now! Enjoy @digitive

**Comment by digitive** [comment]
FYI. You may not need to full reinstall macos. I just found once I start loading my own config and packages the issue comes back, and skip my own config then issue is gone. So I can confirm that the vanilla Emacs doesn't have issue. It must be one of my packages. I haven't got a chance to figure out which one causes but if anyone here have similar issue, check your config first.

**Comment by digitive** [comment]
UPDATE:

Turned out this line in my config broke it, due to macos built in `ls` doesn't support `--group-directories-first` flag
```
(setq dired-listing-switches "-al --group-directories-first")
```

Solution:
```
brew install coreutils
```

Then in your init.el, add
```
(setq insert-directory-program "gls" dired-use-ls-dired t)
(setq dired-listing-switches "-al --group-directories-first")
```

**Comment by rmf10003** [comment]
@digitive thank you! this solution worked for me but only onece I added gnubin to my path.  below are the instructions printed out from the `brew install coreutils` command

```Commands also provided by macOS and the commands dir, dircolors, vdir have been installed with the prefix "g".
If you need to use these commands with their normal names, you can add a "gnubin" directory to your PATH with:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"```

**Comment by rmf10003** [comment]
update: unfortunately this only works if I open emacs from the terminal.
things I tried: 
add export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" to ~/.bashrc file
add export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" to /etc/environment file

**Comment by simonmichael** [comment]
I'm hitting this today with emacs-plus@29 on monterrey. I granted full disk access to 
- /Applications/Emacs.app gui app
- /opt/homebrew/bin/emacs symlink
- /opt/homebrew/Cellar/emacs-plus@29/29.0.50/bin/emacs bash script
- /opt/homebrew/Cellar/emacs-plus@29/29.0.50/Emacs.app/Contents/MacOS/Emacs binary
- /bin/ls the insert-directory-program, just in case..
- /usr/bin/ruby and even this, even though I see no ruby involved in emacs startup (it's a bash script calling the binary)

Whether started from terminal or dock, in gui or terminal mode, I still can't access any directory with dired.

**Comment by d12frosted** [comment]
> Whether started from terminal or dock, in gui or terminal mode, I still can't access any directory with dired.

If it's only dired, I guess it might be something else. For example, messed up `PATH` and using built-in macos `ls`. See this [message][(https://github.com/d12frosted/homebrew-emacs-plus/issues/383#issuecomment-899157143).

@simonmichael thank you for kind words :)

**Comment by simonmichael** [comment]
Update: I found my emacs was using the default "ls" for insert-directory-program, and that changing it to homebrew's ls fixes the problem:
```elisp
(when (eq system-type 'darwin)
  (setq insert-directory-program "/opt/homebrew/bin/gls"))
```

**Comment by guylyons** [comment]
Thanks @simonmichael and @digitive . I've run into similar issues with differences in GNU/macOS versions of sed as well. Using gls worked great for me.

**Comment by d12frosted** [comment]
BTW, in `emacs-plus@29` now extracts `PATH` value during build and embeds it into `Emacs.app` (actually it's `Info.plist`). This means that if you run `Emacs.app` from Finder/Docker/Spotlight, `ls` from your interactive `PATH` should be picked up. Hope that helps.

P. S. This feature might also land in Emacs 28.

**Comment by DinoChiesa** [comment]
I know this is old, and the problem is solved if you can `brew install coreutils` and then 
```
(when (eq system-type 'darwin)
  (setq insert-directory-program "/opt/homebrew/bin/gls"))
```

If that is not possible you can alternatively tell dired to use the lisp implementation of ls,   like so: 
```
(require 'ls-lisp)
(setq ls-lisp-use-insert-directory-program nil)
```

It's slower. But it works without an extra install, and without modifying the path, etc.
