### ISSUE TITLE
Could not install @28 --with-native-com with OSX Monterey on an M1 mac

### ISSUE THREAD

**Issue by erikc96** [d12frosted/homebrew-emacs-plus#388]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install emacs@28 --with-native-comp

## What happened (include command output)

It never finishes making! Dozens of minutes later even.

<pre>
$ brew install emacs-plus@28 --with-native-comp
</pre>

<details>
  <summary>Command output</summary>
  <pre>

Updating Homebrew...
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/craigoej/Library/Caches/Homebrew/emacs-plus@28--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at ee2ffd9c9e Fix problem with symlinks in compile buffers
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8563 (offset -205 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1256 (offset 3 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1889 (offset -305 lines).
Hunk #2 succeeded at 5387 (offset -364 lines).
Hunk #3 succeeded at 5633 (offset -364 lines).
Hunk #4 succeeded at 5683 (offset -364 lines).
Hunk #5 succeeded at 5909 (offset -364 lines).
Hunk #6 succeeded at 8894 (offset -238 lines).
Hunk #7 succeeded at 10051 (offset 37 lines).
==> ImageMagick PKG_CONFIG_PATH:
/opt/homebrew/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/opt/homebrew/Cellar/emacs-plus@28/28.0.50 --with-
==> make

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
craigoej@Eriks-MacBook-Pro-6 ~ % brew config
HOMEBREW_VERSION: 3.2.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: d14fc2db125c18832fe83c98fdeb54931dc48f03
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 02aff60b6f70b0680d9d04ab90879852f82853de
Core tap last commit: 27 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0-arm64
CLT: 13.0.0.0.1.1627064638
Xcode: 13.0
Rosetta 2: false
craigoej@Eriks-MacBook-Pro-6 ~ % brew upgrade
Updating Homebrew...
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
craigoej@Eriks-MacBook-Pro-6 ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt

Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /opt/homebrew/share/man/man5/package-locks.5
  /opt/homebrew/share/man/man5/shrinkwrap-json.5

</pre>

**Comment by thuringia** [comment]
@erikc96 I managed to have it install using the latest Xcode beta (beta 5) on Monterey beta 6.
Maybe it was only a momentary dependency issue or a bug in Monterey.
Interestingly enough, I did not see any output from `configure` or `make`, so it looked like the install was stuck.

**Comment by d12frosted** [comment]
> I managed to have it install using the latest Xcode beta (beta 5) on Monterey beta 6.

@thuringia glad to hear! Thanks for sharing your experience. 

>  Interestingly enough, I did not see any output from configure or make, so it looked like the install was stuck.

This is because brew doesn't show output of those commands by default. You need to pass `--verbose` flag to see all the logs.

**Comment by d12frosted** [comment]
Ah, and forgot to say, it really takes quite some time to build with native comp. So wait for it to finish (either with success or failure). Like @thuringia did :)
