### ISSUE TITLE
tramp-mode times out

### ISSUE THREAD

**Issue by R0flcopt3r** [d12frosted/homebrew-emacs-plus#389]
Version: Emacs 28 with native compile, and running doom

Every time I attempt to use tramp to open a buffer on a remote machine it times out. Using my linux box with the exact same configuration, also emacs 28 with native compile and doom, it works with no problem. I can also ssh from any terminal (includes vterm-mode), and that works fine from my Mac.

I can also run sudo-{this,find}-file with no problem.

**Comment by d12frosted** [comment]
@R0flcopt3r Have no clues, sorry. I would advice you to search for help either on IRC, mailing list or in doom/spacemacs issues tracker. I am pretty sure that it's not related to `emacs-plus` (and you can easily check that by using emacs for macos build, e.g. `brew cask install emacs`).

Also, I would try checking by running Emacs in terminal.

**Comment by R0flcopt3r** [comment]
I should have added this to my initial message, https://github.com/A6GibKm/emacs-pgtk-nativecomp-copr/issues/9

That was an issue with emacs 28 from a private copr that was related to tramp, however not the same situation, but I do wonder if they can be related.

I will try with the vanilla version of emacs later.

**Comment by R0flcopt3r** [comment]
I can replicate the issue with emacs for macos as well. I can also replicate it using `emacs -q`, both with this fork and emacs for macOS.

`emacs -q` is complaining about the prompt, which is a known issue I've touched on before. It's therefore safe to assume this fork has nothing to do with it, so I am marking this as closed.
