### ISSUE TITLE
[macOS] Emacs freezes if file contains unicode emojis

### ISSUE THREAD

**Issue by nejcvivod** [d12frosted/homebrew-emacs-plus#39]
When opening a file containing unicode emojis, emacs will consume 100% of CPU and become unresponsive; so far it never seems to come out of this loop and has to be killed. I've tried opening the file with emacs running in `-q` mode, but I encountered the same problem. 

This happens with 2 versions (that I have available), one is `25.2`, the other is `HEAD-b372e56` (`--with-natural-title-bar` enabled, former version is installed without this)

The same file can be opened in neovim, macvim, xcode, ... and it seems to work just fine in those editors.

I've also tried renaming the file to various extensions to see if any modes could be responsible, but the results are no different (tried .swift, .cpp, .txt)

Any ideas as to what's happening?

**Comment by d12frosted** [comment]
Hey,

That's really strange. I just tried with different unicode emojis and everything works fine. I am using 25.2. I wonder of the problem persists in official emacs formula (`brew install emacs`) or in [Emacs for macOS](https://emacsformacosx.com).

**Comment by nejcvivod** [comment]
Tried installing plain emacs like you suggested and it also crashes, closing the issue :) 

Thank you for pointing me in the right direction

**Comment by d12frosted** [comment]
Well, doesn't look like I have helped much, but let me know if you find the root of this problem! 😸

**Comment by nejcvivod** [comment]
Just in case someone comes across this - nice people on the emacs bug mailing list have found the issue, seems to be a missing font problem; after I installed Symbola, emacs no longer freezes

**Comment by d12frosted** [comment]
@nejcvivod thank you for letting us know 😸 ❤️ 

P. S. would be nice to have a link to that thread on mailing list.
