### ISSUE TITLE
Could not install emacs-plus@28 with --with-no-titlebar

### ISSUE THREAD

**Issue by zane** [d12frosted/homebrew-emacs-plus#405]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What happened (include command output)

<pre>
$ brew install emacs-plus@28 --with-no-titlebar
</pre>

<details>
  <summary>Command output</summary>
  <pre>==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/zane/Library/Caches/Homebrew/emacs-plus@28--git
==> Checking out branch emacs-28
Already on 'emacs-28'
Your branch is up to date with 'origin/emacs-28'.
HEAD is now at efb1cd7fa9 ; * etc/charsets/README: Update the format documentation.
==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Patching
==> Applying no-titlebar.patch
patching file src/nsterm.m
Hunk #2 FAILED at 8293.
1 out of 2 hunks FAILED -- saving rejects to file src/nsterm.m.rej

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Need to set LIBRARY_PATH for emacs-plus@28 with --with-native-comp https://github.com/d12frosted/homebrew-emacs-plus/issues/378
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304
Emacs-plus@28 with native comp crashes on MacOS 12/Monterey https://github.com/d12frosted/homebrew-emacs-plus/issues/361</pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09b7ab2c1de3ab32f385aac922b2cd644fdd7c79
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 662f1fff319789e8851d359061aa8ce194d7d57b
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.33.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by d12frosted** [comment]
Hey, I am in travel mode and can't fix it right now.

If someone wants to crack it - see https://github.com/d12frosted/homebrew-emacs-plus/pull/377. There is little thing to fix.

**Comment by d12frosted** [comment]
Build is green now. Sorry it took so long.
