### ISSUE TITLE
Emacs dbus support not working even installed with option `--with-dbus`

### ISSUE THREAD

**Issue by stardiviner** [d12frosted/homebrew-emacs-plus#411]
Please make sure to follow these steps (and mark the checkboxes):

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I execute elisp code:
```elisp
(notifications-notify :title "org-mode message" :body "hello" :timeout 1000 :urgency 'low)
```

But I got Emacs error:
```
Debugger entered--Lisp error: (dbus-error "No connection to bus" :session)
  dbus-message-internal(1 :session "org.freedesktop.Notifications" "/org/freedesktop/Notifications" "org.freedesktop.Notifications" "Notify" dbus-call-method-handler :string "Emacs" :uint32 0 :string "/opt/homebrew/Cellar/emacs-plus@28/28.0.50/share/e..." :string "org-mode message" :string "hello" (:array) ((:dict-entry "urgency" (:variant :byte 0))) :int32 1000)
  apply(dbus-message-internal 1 :session "org.freedesktop.Notifications" "/org/freedesktop/Notifications" "org.freedesktop.Notifications" "Notify" dbus-call-method-handler (:string "Emacs" :uint32 0 :string "/opt/homebrew/Cellar/emacs-plus@28/28.0.50/share/e..." :string "org-mode message" :string "hello" (:array) ((:dict-entry "urgency" (:variant :byte 0))) :int32 1000))
  dbus-call-method(:session "org.freedesktop.Notifications" "/org/freedesktop/Notifications" "org.freedesktop.Notifications" "Notify" :string "Emacs" :uint32 0 :string "/opt/homebrew/Cellar/emacs-plus@28/28.0.50/share/e..." :string "org-mode message" :string "hello" (:array) ((:dict-entry "urgency" (:variant :byte 0))) :int32 1000)
  notifications-notify(:title "org-mode message" :body "hello" :timeout 1000 :urgency low)
  eval((notifications-notify :title "org-mode message" :body "hello" :timeout 1000 :urgency 'low) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

I installed dbus support with `brew install dbus dbus-glib`.
my macOS version: `M1 Big Sur 11.6`

## What happened (include command output)

<pre>
$ brew install emacs-plus --with-dbus --with-xwidgets
</pre>

<details>
  <summary>Command output</summary>
  <pre>

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 6 casks.

==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Downloading https://ghcr.io/v2/homebrew/core/libvmaf/manifests/2.3.0
Already downloaded: /Users/stardiviner/Library/Caches/Homebrew/downloads/148a663e84f3db9278aed01b0fa3a565116e0c4836b1bd4ecc6326d7d6f3c7c7--libvmaf-2.3.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libvmaf/blobs/sha256:1977b1939d44b8871ef1d856203b364b761872be00c6654fdf
Already downloaded: /Users/stardiviner/Library/Caches/Homebrew/downloads/eae7ee646631f6bd16c246a55001e83f912e3aaf92ce53a264015115f167f8f2--libvmaf--2.3.0.arm64_big_sur.bottle.tar.gz
==> Cloning https://github.com/emacs-mirror/emacs.git
Cloning into '/Users/stardiviner/Library/Caches/Homebrew/emacs-plus@28--git'...
==> Checking out branch emacs-28
Already on 'emacs-28'
Your branch is up to date with 'origin/emacs-28'.
==> Installing dependencies for d12frosted/emacs-plus/emacs-plus@28: libvmaf
==> Installing d12frosted/emacs-plus/emacs-plus@28 dependency: libvmaf
==> Pouring libvmaf--2.3.0.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libvmaf/2.3.0: 16 files, 2.4MB
==> Installing d12frosted/emacs-plus/emacs-plus@28 --with-xwidgets --with-dbus
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8602 (offset -166 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1315 (offset 59 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1878 (offset -11 lines).
Hunk #2 succeeded at 5389 (offset -6 lines).
Hunk #3 succeeded at 5635 (offset -6 lines).
Hunk #4 succeeded at 5685 (offset -6 lines).
Hunk #5 succeeded at 5911 (offset -6 lines).
Hunk #6 succeeded at 8935 (offset 33 lines).
Hunk #7 succeeded at 10091 (offset 33 lines).
==> ImageMagick PKG_CONFIG_PATH:
/opt/homebrew/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-plus@28/
==> make
==> make install
==> Caveats
Emacs.app was installed to:
  /opt/homebrew/opt/emacs-plus@28

To link the application to default Homebrew App location:
  ln -s /opt/homebrew/opt/emacs-plus@28/Emacs.app /Applications

To have launchd start d12frosted/emacs-plus/emacs-plus@28 now and restart at login:
  brew services start d12frosted/emacs-plus/emacs-plus@28
Or, if you don't want/need a background service you can just run:
  emacs
==> Summary
🍺  /opt/homebrew/Cellar/emacs-plus@28/28.0.50: 4,073 files, 135.6MB, built in 5 minutes 23 seconds
==> Caveats
==> emacs-plus@28
Emacs.app was installed to:
  /opt/homebrew/opt/emacs-plus@28

To link the application to default Homebrew App location:
  ln -s /opt/homebrew/opt/emacs-plus@28/Emacs.app /Applications

To have launchd start d12frosted/emacs-plus/emacs-plus@28 now and restart at login:
  brew services start d12frosted/emacs-plus/emacs-plus@28
Or, if you don't want/need a background service you can just run:
  emacs

❯ which emacs
/opt/homebrew/bin/emacs

❯ ln -s /opt/homebrew/opt/emacs-plus@28/Emacs.app /Applications

  </pre>
</details>

**Comment by zacaytion** [comment]
Is dbus running via `brew services` or `launchd` directly? 

I failed at getting dbus to work and realized that something is likely wrong with the `plist` or `session.conf` provided by homebrew. Haven't figured out a fix

**Comment by stardiviner** [comment]
I try to start dbus homebrew service but always failed.
Here is my steps.

```shell
brew install dbus --HEAD
brew link dbus
```

Then start dbus service with Homebrew:

```shell
brew services start dbus 2>&1 | cat
```

    Bootstrap failed: 5: Input/output error
    Try re-running the command as root for richer errors.
    Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/stardiviner/Library/LaunchAgents/org.freedesktop.dbus-session.plist` exited with 5.

Then check out the dbus service status:

```shell
brew services list 2>&1 | grep dbus
```

    dbus              error  19968    stardiviner ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist

**Comment by dertuxmalwieder** [comment]
That happens when you `2>&1` everything. .. ;-)

```
; brew services start dbus
Error: Formula `dbus` has not implemented #plist, #service or installed a locatable service file
```

So yes, it's a Homebrew problem.

**Comment by stardiviner** [comment]
@dertuxmalwieder Thanks for suggestion. I installed the netatalk-dbus now. But don't know how to start it. I tried to check out github repo README and .rb recipe source code. Not found. And I tried to execute command `brew services start dbus`. Still same error, seems the dbus services is still the old dbus from "dbus" formula. And I can't remove the installed dbus formula because other packages like Emacs qt etc depends on it.
Do you have any idea?

**Comment by dertuxmalwieder** [comment]
Hmm. I'd need to investigate further (tomorrow?), but it *should* be possible to skip installing the "normal" dbus's service. Wouldn't `brew install dbus --skip-post-install` work?

If so:

1. Uninstall dbus and Emacs completely.
2. Install "normal" dbus without the services.
3. Install emacs-plus.
4. Install netatalk-dbus which *should* install the only dbus service now.

If not:

1. Uninstall dbus and Emacs.
2. Install netatalk-dbus with its service.
3. Install emacs-plus without dependencies (they should be there now anyway): `--ignore-dependencies`.

Both are untested.

**Comment by stardiviner** [comment]
I tried both methods, still not working. I also executed `brew unlink dbus` before `brew reinstall dgsga/netatalk-dbus/dbus` to avoid conflict. Need more investigation. Thanks for your help.

**Comment by dertuxmalwieder** [comment]
Potential fix idea: Add a patch to emacs-plus that uses netatalk-dbus instead of dbus as a dependency. But I don't speak Ruby...

**Comment by d12frosted** [comment]
AFAIK it's not possible to depend on formulas from other taps without requiring people to actually tap it. E.g.

```
Warning: No available formula with the name "dgsga/netatalk-dbus/dbus".
Please tap it and then try again: brew tap dgsga/netatalk-dbus
```

Since dbus is such a rare use-case, I would not want to force **all** Emacs+ users to tap that. Maybe it worth documenting (both in README and in caveats section of the formula).

**Comment by stardiviner** [comment]
emacs will automatically install dbus formula, even I tap netatalk-dbus manually.
```
brew install emacs-plus@30 --with-dbus
==> Fetching dependencies for d12frosted/emacs-plus/emacs-plus@30: dbus
==> Fetching dbus
==> Downloading https://ghcr.io/v2/homebrew/core/dbus/manifests/1.14.6
Already downloaded: /Users/stardiviner/Library/Caches/Homebrew/downloads/c08011f94add7594cf029e5a8bf8c31a374069b901cc0d8709b2b10ac9d80eea--dbus-1.14.6.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/dbus/blobs/sha256:ec0d9980cd5e80731bcf807a35719afb8
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:ec0d9980cd5e807
##############################################                                                 50.4%
```

**Comment by d12frosted** [comment]
I am talking about the `netatalk-dbus` tap. The warning (actually the error, despite the wording in the output) comes when I modify dependency from `dbus` to `dgsga/netatalk-dbus/dbus`.

And what I mean by that? AFAIK there is no way to depend on `dgsga/netatalk-dbus/dbus` without forcing people to tap `netatalk-dbus`, which I want to avoid as it's a rather rare use case (according to public stats[^1] the usage is close to zero).

But there is a workaround:

1. Tap and install `dgsga/netatalk-dbus/dbus`.
2. Install Emacs+ ignoring dependencies.
3. Enjoy? 

[^1]: A bit older stats can be found on my [blog](https://d12frosted.io/posts/2022-04-24-emacs-plus-stats.html).

**Comment by dertuxmalwieder** [comment]
That’s what I suggested above…?

**Comment by d12frosted** [comment]
@dertuxmalwieder yes :) I just wanted to comment on your idea to use a formula from tap as dependency, e.g. this:

> Potential fix idea: Add a patch to emacs-plus that uses netatalk-dbus instead of dbus as a dependency. But I don't speak Ruby...

Let me update my previous comment to say that the workaround is suggested by you. Hopefully, it would be less confusing.

**Comment by d12frosted** [comment]
No wait. I commented on your specific suggestion (quoted in previous message) - e.g. replacing `dbus` with `dgsga/netatalk-dbus/dbus` inside the formula. And explained that it's not going to work without forcing _all_ users of Emacs to tap the `dgsga/netatalk-dbus`, which I don't like.

On the other hand, @stardiviner commented on the workaround (e.g. all this mumbo-jumbo with ignoring dependencies). I have not tested it.

Hope that explains what I was talking about :)

**Comment by dertuxmalwieder** [comment]
Ah! Sorry - a clear misunderstanding from my side!

**Comment by dertuxmalwieder** [comment]
FYI, the dbus formula seems to have received a fix. It works OOTB now.

**Comment by d12frosted** [comment]
@dertuxmalwieder thanks for the heads up. Closing this issue 🙃
