### ISSUE TITLE
No emoji rendering?

### ISSUE THREAD

**Issue by EdwardIII** [d12frosted/homebrew-emacs-plus#413]
Sorry if this isn't the right place to report this! Not sure if this is specific to emacs-plus, my font choice, emacs itself, or what.

Emoji don't show up:

![image](https://user-images.githubusercontent.com/412107/139257158-d4c15f9f-7846-45fe-a3c1-c95aea635c8c.png)

![image](https://user-images.githubusercontent.com/412107/139257270-3c8cfdfc-3f4a-443d-a7f1-dce9c5d255a4.png)

Here's the output of `M-x describe-font`

![image](https://user-images.githubusercontent.com/412107/139257531-bea9b74c-73a7-44b8-881d-4447de317c4f.png)

```
GNU Emacs 29.0.50
macOS Big Sur 11.6.1
```

**Comment by kommen** [comment]
I think it isn't the right place to ask here, as this isn't something emacs-plus specific, but let me try to help you anyway 😉

I recently asked about emoji on macOS on reddit, the post has a bunch helpful comments and links to things you can try: https://www.reddit.com/r/emacs/comments/pmghug/how_to_correctly_display_multicharacter_emojis/

**Comment by EdwardIII** [comment]
Ah thanks for the link! I'll put the part that helped me here in case anyone else stumbles across this.

Adding this to my `init.el` (on Emacs 29) fixed it:

```elisp
(set-fontset-font t '(#x1f000 . #x1faff) (font-spec :family "Apple Color Emoji"))
```
