### ISSUE TITLE
Could not install emacs-plus@29 with --with-no-titlebar [SHA mismatch]

### ISSUE THREAD

**Issue by gf3** [d12frosted/homebrew-emacs-plus#415]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install emacs-plus@29 with the no-titlebar patch

## What happened (include command output)

<pre>
brew install --force emacs-plus@29 --with-native-comp --with-xwidgets --with-nobu417-big-sur-icon --with-no-titlebar
</pre>

<details>
  <summary>Command output</summary>
  <pre>

Updating Homebrew...
Error: emacs-plus@29: SHA256 mismatch
Expected: 3ad578e3551667a23a0465b832889b5ed51276303c98d72eaf0681e5664bb4f7
  Actual: 2fa80efc5cda7e96d88a5d145c9313092a6e53d38825c41967c745f08778c41b
    File: /opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/patches/emacs-29/no-titlebar.patch
To retry an incomplete download, remove the file above.

  </pre>
</details>

## Output of `brew config`

<pre>
HOMEBREW_VERSION: 3.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9daf5e2d28396c7a4379605e89e029d9fccb41e6
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f9e6f04bfd243148541cc872d8f225e27ec50ef6
Core tap last commit: 27 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: hx
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: 13.1
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
Your system is ready to brew.
</pre>

**Comment by d12frosted** [comment]
Right. I forgot to restore CI for Emacs 29 and to change hash in Emacs 29 formula. Waiting for CI to verify #417. Thanks for reporting!

**Comment by d12frosted** [comment]
Should be fixed by now. Please try again 🙃

**Comment by gf3** [comment]
works great! thanks for the quick response @d12frosted
