### ISSUE TITLE
New Big Sur Icons

### ISSUE THREAD

**Issue by memeplex** [d12frosted/homebrew-emacs-plus#419]
Hi I've produced some Big Sur style icons. The first two ones are based on the Papyrus icon, they were rasterized only after scaling the original SVG so they're very nitid, one is slightly larger than the other, compared to the current Big Sur icon these ones are sharper, flatter (no gradient) and have a subtle shadow. The third one is based in the org-mode unicorn but the  palette is reminiscent of the Emacs icon. Hope you like them.

https://drive.google.com/file/d/13Wc2pMnn7fN3803mVeVCARn8eNHOXvfn/view?usp=sharing

https://drive.google.com/file/d/13_ju_Ed4PP1BsjnwbCBSF4iwsehutKwA/view?usp=sharing

https://drive.google.com/file/d/13_ixZOW90FTzJXiIkAjBLq4MLvN5CDxS/view?usp=sharing

**Comment by d12frosted** [comment]
@memeplex thank you very much! I will take a look later this week.

**Comment by memeplex** [comment]
I've replaced the first two ones by just this: https://drive.google.com/file/d/13bzarkL9K8k-9EDnYxLREAyCai6N9GS_/view?usp=sharing

It's pretty similar but I've worked a bit on the original SVG because a curve at the bottom was somewhat bumpy (this is so in the icon that's distributed with Emacs and in many other icons are based on it).

**Comment by memeplex** [comment]
Here is another alternative: https://drive.google.com/file/d/13o8LziaT0PSZBeMKiWqa6yqrVukV34bP/view?usp=sharing

I rotated the logo a bit and further soften some curves. This is the one I like the most. And it's the last one, I hope...

Hope you like some of them.

**Comment by memeplex** [comment]
New version:

- png: https://drive.google.com/file/d/14BDnwlGa17ds0CZI1kNBNghqt4TSqVEl/view?usp=sharing

- svg: https://drive.google.com/file/d/14L_roGCSD9dMnhL4Cq3w2_sfP4vvlk0_/view?usp=sharing

This is considerably more polished than the previous ones.

**Comment by d12frosted** [comment]
I've been thinking on making it possible to install ANY icon regardless of what is bundled, but that would require writing some installation wrapper which is kind of an overkill.

So... #448. Please review it @memeplex and let me know if you want to provide other links.
