### ISSUE TITLE
Why is Emacs built with imagemagick by default in this formula?

### ISSUE THREAD

**Issue by aaronjensen** [d12frosted/homebrew-emacs-plus#423]
What is the historical (and current) reason that we build with imagemagick here? What does it enable on macOS that we don't get out of the box?

**Comment by d12frosted** [comment]
Honestly, at this point I don't remember anymore. I think back than it was a way to view various images inside of Emacs. And now all I can say about imagemagick - it's a [constant](https://github.com/d12frosted/homebrew-emacs-plus/issues/310) _ [source](https://github.com/d12frosted/homebrew-emacs-plus/issues/11) of [build](https://github.com/d12frosted/homebrew-emacs-plus/issues/44) _ [problems](https://github.com/d12frosted/homebrew-emacs-plus/issues/75) _ [again and again](https://github.com/d12frosted/homebrew-emacs-plus/issues/161). It's been quite for a while, but if enough people think that it's not needed, I am all for removing it at once.

**Comment by aaronjensen** [comment]
I've got a build without it right now and I can open images and manipulate them just fine. Maybe it's worth making it opt-in for a while and seeing what happens

**Comment by d12frosted** [comment]
@aaronjensen I agree. Would you like to contribute that? I think 28 and 29 are good targets for this experiment.

**Comment by aaronjensen** [comment]
I'm going to close this out, but if anyone has problems w/ not having imagemagick installed, please let us know.
