### ISSUE TITLE
new bottles needed

### ISSUE THREAD

**Issue by ilovezfs** [d12frosted/homebrew-emacs-plus#43]
The imagemagick@6 upgrade we shipped today has broken your bottles, so the formula will need a revision bump and new bottles.

**Comment by halfcrazy** [comment]
try `brew reinstall emacs-plus `

**Comment by ilovezfs** [comment]
@halfcrazy I'm not personally asking for support. (Also, it would need to be `brew reinstall --build-from-source emacs-plus`)

**Comment by d12frosted** [comment]
@ilovezfs thanks for the notice!

I have updated the bottle for Sierra.

@wadkar, could you please create bottle for El Capitan?

**Comment by ilovezfs** [comment]
@d12frosted no problem!

**Comment by wadkar** [comment]
Uploaded [here](https://cmu.box.com/s/w6wt2xp8iiqzy4gv2z8g9t1bzfv79l9f) with sha256 `3f42bd2b2a2e3ebbe8a984b202c127d514b6d112d85e06f33eaa040a42f3251f  emacs-plus-25.2.el_capitan.bottle.2.tar.gz`

**Comment by d12frosted** [comment]
@wadkar many thanks!

**Comment by Blaisorblade** [comment]
@ilovezfs Bottles were rebuilt without a revision bump. IIUC 
https://github.com/d12frosted/homebrew-emacs-plus/pull/45/files is the desired fix, right? (And probably requires new bottles).

**Comment by ilovezfs** [comment]
@Blaisorblade Yeah, it should have had a revision bump _before_ rebuilding the bottles.

**Comment by d12frosted** [comment]
@Blaisorblade thank you for troubleshooting my mistake. I didn't know about 'revision' thing and thought that build number takes care of such things, though it's clearly documented. My bad.

**Comment by Blaisorblade** [comment]
No problem—I only figured after observing the problem!

**Comment by wadkar** [comment]
lmk when to rebuild

**Comment by d12frosted** [comment]
@wadkar i have already pushed everything, so please do a rebuild 😸

**Comment by wadkar** [comment]
@d12frosted [here](https://cmu.box.com/s/ghxxh0iynavhrt43usccxaaprv569y1t) you go:
```
#> shasum -a 256 emacs-plus-25.2_1.el_capitan.bottle.1.tar.gz
895aeb4fd6bd3b17faa0292001bda590eae664613c9849231ab31e8ae5642600  emacs-plus-25.2_1.el_capitan.bottle.1.tar.gz
```

**Comment by d12frosted** [comment]
Many thanks!
