### ISSUE TITLE
'doom sync' on @28 native compilation hangs for hours, Big Sur

### ISSUE THREAD

**Issue by workcomplete** [d12frosted/homebrew-emacs-plus#436]
Using Doom Emacs on OSX Big Sur, emacs-plus@28 installed with --with-xwidgets --with-imagemagick --with-native-comp --with-no-titlebar

When I run `doom sync` after adding a new package to my packages.el, I see the following about native compilation:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/77472800/152574941-5410cb56-7f85-42d3-b4a7-b7483b6a89ea.png">

This process takes hours. I let it run overnight and it was hanging at `Natively compiling 2 files` this morning for a few hours so I aborted.

I also get this message when running `doom upgrade`. If there are no packages to install `doom sync` runs in the usual 5 - 10s range.

I tried recompiling GCC as described here https://github.com/d12frosted/homebrew-emacs-plus/issues/288#issue-773294410

I also performed the following:

run brew update and try to reproduce the issue again
run brew doctor, fix all issues and try to reproduce your issue again
run brew config and brew doctor and include their output:

Brew config:

HOMEBREW_VERSION: 3.3.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae21a582a90571abb66b7fbceb04cd1e53785bf
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a3a67a0a95c17e5c814abcac157cd9a1269f6cb1
Core tap last commit: 78 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.2-x86_64
CLT: 12.5.0.22.11
Xcode: 13.2.1

Brew doctor:
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ext4fuse
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/krb5-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/libpng-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/apr-1-config
  /opt/local/bin/apu-1-config
  /opt/local/bin/pcre-config
  /opt/local/bin/ncurses6-config

**Comment by quangIO** [comment]
See https://github.com/hlissner/doom-emacs/issues/5592 for [workaround](https://github.com/hlissner/doom-emacs/issues/5592#issuecomment-945919856)

**Comment by d12frosted** [comment]
Good sirs, I am glad that this issue has a workaround. Since it's unrelated to `emacs-plus`, I am closing this issue. But please report back if there is a proper fix.
