### ISSUE TITLE
Could not install with --with-spacemacs-icon

### ISSUE THREAD

**Issue by zendevil** [d12frosted/homebrew-emacs-plus#439]
Please make sure to follow these steps (and mark the checkboxes):

- [ x ] run `brew update` and try to reproduce the issue again
- [ x ] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ x ] run `brew config` and `brew doctor` and include their output

## What you were trying to do
Installing emacs-plus@28
`brew install emacs-plus@28 --with-spacemacs-icon`

## What happened (include command output)

```
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 3 formulae.

==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/prikshetsharma/Library/Caches/Homebrew/emacs-plus@28--git
From https://github.com/emacs-mirror/emacs
   cd51d9c7ab..92e2d19fe7  emacs-28   -> origin/emacs-28
==> Checking out branch emacs-28
Already on 'emacs-28'
Your branch is behind 'origin/emacs-28' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 92e2d19fe7 One more fix of the BPA implementation
==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8583 (offset -185 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1315 (offset 59 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1878 (offset -11 lines).
Hunk #2 succeeded at 5389 (offset -6 lines).
Hunk #3 succeeded at 5635 (offset -6 lines).
Hunk #4 succeeded at 5685 (offset -6 lines).
Hunk #5 succeeded at 5911 (offset -6 lines).
Hunk #6 succeeded at 8916 (offset 14 lines).
Hunk #7 succeeded at 10072 (offset 14 lines).
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/
==> make
Last 15 lines from /Users/prikshetsharma/Library/Logs/Homebrew/emacs-plus@28/03.make:
      _tparam in terminfo.o
  "_tputs", referenced from:
      _cmcostinit in cm.o
      _cmgoto in cm.o
      _calccost in cm.o
      _tty_turn_off_insert in term.o
      _string_cost in term.o
      _per_line_cost in term.o
      _calculate_costs in term.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [temacs] Error 1
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304
Need to set LIBRARY_PATH for emacs-plus@28 with --with-native-comp https://github.com/d12frosted/homebrew-emacs-plus/issues/378

```

## Output of `brew config`

```
HOMEBREW_VERSION: 3.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ffc76654da12fba7d34d078fd9bf681fef65921e
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ce16a6ff979bb27fa9b5169755cb98db0ba632aa
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.rPYE4yrDDO/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
```

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  gcsfuse
  ilmbase
  vtk@8.2

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libLTO.dylib
  /usr/local/lib/libOptRemarks.dylib
  /usr/local/lib/libasan.1.dylib
  /usr/local/lib/libasan.5.dylib
  /usr/local/lib/libatomic.1.dylib
  /usr/local/lib/libblas.3.8.0.dylib
  /usr/local/lib/libc++.1.0.dylib
  /usr/local/lib/libc++abi.1.0.dylib
  /usr/local/lib/libcares.2.3.0.dylib
  /usr/local/lib/libcblas.3.8.0.dylib
  /usr/local/lib/libcilkrts.5.dylib
  /usr/local/lib/libcrypto.1.1.dylib
  /usr/local/lib/libdnnl.2.0.dylib
  /usr/local/lib/libedit.0.dylib
  /usr/local/lib/libffi.6.dylib
  /usr/local/lib/libformw.6.dylib
  /usr/local/lib/libfreetype.6.dylib
  /usr/local/lib/libgcc_ext.10.4.dylib
  /usr/local/lib/libgcc_ext.10.5.dylib
   .......

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libLLVMAArch64AsmParser.a
  /usr/local/lib/libLLVMAArch64AsmPrinter.a
  /usr/local/lib/libLLVMAArch64CodeGen.a
  /usr/local/lib/libLLVMAArch64Desc.a
  /usr/local/lib/libLLVMAArch64Disassembler.a
  /usr/local/lib/libLLVMAArch64Info.a
  /usr/local/lib/libLLVMAArch64Utils.a
  /usr/local/lib/libLLVMAMDGPUAsmParser.a
  /usr/local/lib/libLLVMAMDGPUAsmPrinter.a
  /usr/local/lib/libLLVMAMDGPUCodeGen.a
  /usr/local/lib/libLLVMAMDGPUDesc.a
  /usr/local/lib/libLLVMAMDGPUDisassembler.a
  /usr/local/lib/libLLVMAMDGPUInfo.a
  /usr/local/lib/libLLVMAMDGPUUtils.a
  /usr/local/lib/libLLVMARMAsmParser.a
  /usr/local/lib/libLLVMARMAsmPrinter.a
  /usr/local/lib/libLLVMARMCodeGen.a
  /usr/local/lib/libLLVMARMDesc.a
  /usr/local/lib/libLLVMARMDisassembler.a
  /usr/local/lib/libLLVMARMInfo.a
  /usr/local/lib/libLLVMARMUtils.a
  /usr/local/lib/libLLVMAggressiveInstCombine.a
  /usr/local/lib/libLLVMAnalysis.a
  /usr/local/lib/libLLVMAsmParser.a
  /usr/local/lib/libLLVMAsmPrinter.a
  /usr/local/lib/libLLVMBPFAsmParser.a
  /usr/local/lib/libLLVMBPFAsmPrinter.a
  /usr/local/lib/libLLVMBPFCodeGen.a
  /usr/local/lib/libLLVMBPFDesc.a
  /usr/local/lib/libLLVMBPFDisassembler.a
  /usr/local/lib/libLLVMBPFInfo.a
  /usr/local/lib/libLLVMBinaryFormat.a
  /usr/local/lib/libLLVMBitReader.a
  /usr/local/lib/libLLVMBitWriter.a
  /usr/local/lib/libLLVMCodeGen.a
  /usr/local/lib/libLLVMCore.a
  /usr/local/lib/libLLVMCoroutines.a
  /usr/local/lib/libLLVMCoverage.a
  /usr/local/lib/libLLVMDebugInfoCodeView.a
  /usr/local/lib/libLLVMDebugInfoDWARF.a
  /usr/local/lib/libLLVMDebugInfoMSF.a
  /usr/local/lib/libLLVMDebugInfoPDB.a
  /usr/local/lib/libLLVMDemangle.a
  /usr/local/lib/libLLVMDlltoolDriver.a
  /usr/local/lib/libLLVMExecutionEngine.a
  /usr/local/lib/libLLVMFuzzMutate.a
  /usr/local/lib/libLLVMGlobalISel.a
  /usr/local/lib/libLLVMHexagonAsmParser.a
  /usr/local/lib/libLLVMHexagonCodeGen.a
  /usr/local/lib/libLLVMHexagonDesc.a
  /usr/local/lib/libLLVMHexagonDisassembler.a
  /usr/local/lib/libLLVMHexagonInfo.a
  /usr/local/lib/libLLVMIRReader.a
  /usr/local/lib/libLLVMInstCombine.a
  /usr/local/lib/libLLVMInstrumentation.a
  /usr/local/lib/libLLVMInterpreter.a
  /usr/local/lib/libLLVMLTO.a
  /usr/local/lib/libLLVMLanaiAsmParser.a
  /usr/local/lib/libLLVMLanaiAsmPrinter.a
  /usr/local/lib/libLLVMLanaiCodeGen.a
  /usr/local/lib/libLLVMLanaiDesc.a
  /usr/local/lib/libLLVMLanaiDisassembler.a
  /usr/local/lib/libLLVMLanaiInfo.a
  /usr/local/lib/libLLVMLibDriver.a
  /usr/local/lib/libLLVMLineEditor.a
  /usr/local/lib/libLLVMLinker.a
  /usr/local/lib/libLLVMMC.a
  /usr/local/lib/libLLVMMCA.a
  /usr/local/lib/libLLVMMCDisassembler.a
  /usr/local/lib/libLLVMMCJIT.a
  /usr/local/lib/libLLVMMCParser.a
  /usr/local/lib/libLLVMMIRParser.a
  /usr/local/lib/libLLVMMSP430AsmParser.a
  /usr/local/lib/libLLVMMSP430AsmPrinter.a
  /usr/local/lib/libLLVMMSP430CodeGen.a
  /usr/local/lib/libLLVMMSP430Desc.a
  /usr/local/lib/libLLVMMSP430Disassembler.a
  /usr/local/lib/libLLVMMSP430Info.a
  /usr/local/lib/libLLVMMipsAsmParser.a
  /usr/local/lib/libLLVMMipsAsmPrinter.a
  /usr/local/lib/libLLVMMipsCodeGen.a
  /usr/local/lib/libLLVMMipsDesc.a
  /usr/local/lib/libLLVMMipsDisassembler.a
  /usr/local/lib/libLLVMMipsInfo.a
  /usr/local/lib/libLLVMNVPTXAsmPrinter.a
  /usr/local/lib/libLLVMNVPTXCodeGen.a
  /usr/local/lib/libLLVMNVPTXDesc.a
  /usr/local/lib/libLLVMNVPTXInfo.a
  /usr/local/lib/libLLVMObjCARCOpts.a
  /usr/local/lib/libLLVMObject.a
  /usr/local/lib/libLLVMObjectYAML.a
  /usr/local/lib/libLLVMOptRemarks.a
  /usr/local/lib/libLLVMOption.a
  /usr/local/lib/libLLVMOrcJIT.a
  /usr/local/lib/libLLVMPasses.a
  /usr/local/lib/libLLVMPowerPCAsmParser.a
  /usr/local/lib/libLLVMPowerPCAsmPrinter.a
  /usr/local/lib/libLLVMPowerPCCodeGen.a
  /usr/local/lib/libLLVMPowerPCDesc.a
  /usr/local/lib/libLLVMPowerPCDisassembler.a
  /usr/local/lib/libLLVMPowerPCInfo.a
  /usr/local/lib/libLLVMProfileData.a
  /usr/local/lib/libLLVMRuntimeDyld.a
  /usr/local/lib/libLLVMScalarOpts.a
  /usr/local/lib/libLLVMSelectionDAG.a
  /usr/local/lib/libLLVMSparcAsmParser.a
  /usr/local/lib/libLLVMSparcAsmPrinter.a
  /usr/local/lib/libLLVMSparcCodeGen.a
  /usr/local/lib/libLLVMSparcDesc.a
  /usr/local/lib/libLLVMSparcDisassembler.a
  /usr/local/lib/libLLVMSparcInfo.a
  /usr/local/lib/libLLVMSupport.a
  /usr/local/lib/libLLVMSymbolize.a
  /usr/local/lib/libLLVMSystemZAsmParser.a
  /usr/local/lib/libLLVMSystemZAsmPrinter.a
  /usr/local/lib/libLLVMSystemZCodeGen.a
  /usr/local/lib/libLLVMSystemZDesc.a
  /usr/local/lib/libLLVMSystemZDisassembler.a
  /usr/local/lib/libLLVMSystemZInfo.a
  /usr/local/lib/libLLVMTableGen.a
  /usr/local/lib/libLLVMTarget.a
  /usr/local/lib/libLLVMTextAPI.a
  /usr/local/lib/libLLVMTransformUtils.a
  /usr/local/lib/libLLVMVectorize.a
  /usr/local/lib/libLLVMWebAssemblyAsmParser.a
  /usr/local/lib/libLLVMWebAssemblyAsmPrinter.a
  /usr/local/lib/libLLVMWebAssemblyCodeGen.a
  /usr/local/lib/libLLVMWebAssemblyDesc.a
  /usr/local/lib/libLLVMWebAssemblyDisassembler.a
  /usr/local/lib/libLLVMWebAssemblyInfo.a
  /usr/local/lib/libLLVMWindowsManifest.a
  /usr/local/lib/libLLVMX86AsmParser.a
  /usr/local/lib/libLLVMX86AsmPrinter.a
  /usr/local/lib/libLLVMX86CodeGen.a
  /usr/local/lib/libLLVMX86Desc.a
  /usr/local/lib/libLLVMX86Disassembler.a
  /usr/local/lib/libLLVMX86Info.a
  /usr/local/lib/libLLVMX86Utils.a
  /usr/local/lib/libLLVMXCoreAsmPrinter.a
  /usr/local/lib/libLLVMXCoreCodeGen.a
  /usr/local/lib/libLLVMXCoreDesc.a
  /usr/local/lib/libLLVMXCoreDisassembler.a
  /usr/local/lib/libLLVMXCoreInfo.a
  /usr/local/lib/libLLVMXRay.a
  /usr/local/lib/libLLVMipo.a
  /usr/local/lib/libatomic.a
  /usr/local/lib/libc++.a
  /usr/local/lib/libc++abi.a
  /usr/local/lib/libc++experimental.a
  /usr/local/lib/libcares_static.a
  /usr/local/lib/libcilkrts.a
  /usr/local/lib/libcrypto.a
  /usr/local/lib/libedit.a
  /usr/local/lib/libffi.a
  /usr/local/lib/libformw.a
  /usr/local/lib/libfreetype.a
  /usr/local/lib/libgfortran.a
  /usr/local/lib/libgmp.a
  /usr/local/lib/libgmpxx.a
  /usr/local/lib/libgomp.a
  /usr/local/lib/libhdf5.a
  /usr/local/lib/libhdf5_cpp.a
  /usr/local/lib/libhdf5_fortran.a
  /usr/local/lib/libhdf5_hl.a
  /usr/local/lib/libhdf5_hl_cpp.a
  /usr/local/lib/libhdf5hl_fortran.a
  /usr/local/lib/libhistory.a
  /usr/local/lib/libitm.a
  /usr/local/lib/libjpeg.a
  /usr/local/lib/liblzma.a
  /usr/local/lib/libmenuw.a
  /usr/local/lib/libmkl_blacs_mpich_ilp64.a
  /usr/local/lib/libmkl_blacs_mpich_lp64.a
  /usr/local/lib/libmkl_blas95_ilp64.a
  /usr/local/lib/libmkl_blas95_lp64.a
  /usr/local/lib/libmkl_cdft_core.a
  /usr/local/lib/libmkl_core.a
  /usr/local/lib/libmkl_intel_ilp64.a
  /usr/local/lib/libmkl_intel_lp64.a
  /usr/local/lib/libmkl_intel_thread.a
  /usr/local/lib/libmkl_lapack95_ilp64.a
  /usr/local/lib/libmkl_lapack95_lp64.a
  /usr/local/lib/libmkl_scalapack_ilp64.a
  /usr/local/lib/libmkl_scalapack_lp64.a
  /usr/local/lib/libmkl_sequential.a
  /usr/local/lib/libmkl_tbb_thread.a
  /usr/local/lib/libmpc.a
  /usr/local/lib/libmpfr.a
  /usr/local/lib/libncurses++w.a
  /usr/local/lib/libncursesw.a
  /usr/local/lib/libpanelw.a
  /usr/local/lib/libpng16.a
  /usr/local/lib/libprotobuf-lite.a
  /usr/local/lib/libprotobuf.a
  /usr/local/lib/libprotoc.a
  /usr/local/lib/libpython3.7m.a
  /usr/local/lib/libpython3.7m.nolto.a
  /usr/local/lib/libquadmath.a
  /usr/local/lib/libreadline.a
  /usr/local/lib/libsqlite3.a
  /usr/local/lib/libssl.a
  /usr/local/lib/libssp.a
  /usr/local/lib/libssp_nonshared.a
  /usr/local/lib/libstdc++.a
  /usr/local/lib/libstdc++fs.a
  /usr/local/lib/libsupc++.a
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtiff.a
  /usr/local/lib/libtiffxx.a
  /usr/local/lib/libtinfow.a
  /usr/local/lib/libtkstub8.6.a
  /usr/local/lib/libz.a
  /usr/local/lib/libzstd.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libtiff
  gmp
  xorgproto
  libxau
  pyqt@5
  libxdmcp
  freetype
  mpfr
  hdf5
  c-ares
  xz
  numpy
  solidity
  ansible
  leiningen
  libxrender
  zstd
  libxext
  kubernetes-cli
  six
  node
  jpeg
  libx11
  protobuf
  python@3.9
  libmpc
  twilio

Warning: Some installed formulae are not readable:
  elasticsearch-full: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/elastic/homebrew-tap/Formula/elasticsearch-full.rb:9

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/ruby/gems/3.0.0/bin/bundle
  /usr/local/lib/ruby/gems/3.0.0/bin/bundler
</pre>

**Comment by d12frosted** [comment]
Hey @zendevil 

Look, your `brew doctor` output is quite verbose. You should definitely address it. The build works on CI and apparently for many users (otherwise I would get much more reports), so I guess the culprit here is your system.
