### ISSUE TITLE
[Emacs 28] Flashing red screen when quitting emacs from full screen?

### ISSUE THREAD

**Issue by apc** [d12frosted/homebrew-emacs-plus#440]
I've recently noted this somewhat puzzling behavior: when quitting Emacs from full screen, I get this brief flashing of a red screen that always makes me think my computer is about to explode or something. 

https://user-images.githubusercontent.com/350504/156636010-33b0020f-8606-4944-a535-50ba506d3017.mov

Do others get this behavior? 

Here's what `brew info emacs@28` shows: 

```
d12frosted/emacs-plus/emacs-plus@28: stable 28.0.50
/usr/local/Cellar/emacs-plus@28/28.0.50 (4,072 files, 135.6MB) *
  Built from source on 2021-12-14 at 09:50:14 with: --with-modern-sexy-v2-icon
```

**Comment by d12frosted** [comment]
Never experience this. These days I am without personal laptop, so can't do extensive testing.

**Comment by apc** [comment]
Thanks for writing back. I'd be curious to know if anyone else has experienced this, so if it's alright with you I'd like to leave this open for a bit.

**Comment by d12frosted** [comment]
I am pretty sure that it's not related to `emacs-plus`, which is just a formula for homebrew. I guess it's either an upstream Emacs bug, or something in your setup (maybe you use some custom window manager or whatever). Hence closing this issue. But would be glad if you report back solution or other results of your investigation.
