### ISSUE TITLE
may i install with some specific commit

### ISSUE THREAD

**Issue by vinurs** [d12frosted/homebrew-emacs-plus#441]
sometimes i find the latest commit has some problem, so i want to roll back to a specific commit

**Comment by d12frosted** [comment]
Unfortunately, there is no easy out of box solution for this. And this is `homebrew` limitation. Fortunately, `homebrew` provides functionality to [locally edit][1] any formula, meaning that you can replace `branch` with `revision`.

For example, this is how `emacs-plus@29` defines what to build:

https://github.com/d12frosted/homebrew-emacs-plus/blob/9d4f6639f3f931f7423a29936865970c662fff7f/Formula/emacs-plus%4029.rb#L66

And this is how it looked, when `emacs-plus@28` was pinned to specific revision:

https://github.com/d12frosted/homebrew-emacs-plus/blob/5628d0c08009291591152d24e013d2346249fda3/Formula/emacs-plus%4028.rb#L67

Not sure if the syntax is still the same. But at least this is direction to use.

Hope that helps.

P. S. Closing this issue as it's a won't fix from my point of view, at least for now. But feel free to continue conversation here.

[1]: https://docs.brew.sh/FAQ#can-i-edit-formulae-myself
