### ISSUE TITLE
Could not install with emacs-plus@28 --with-native-comp --with-xwidgets  

### ISSUE THREAD

**Issue by kommen** [d12frosted/homebrew-emacs-plus#442]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Installing emacs-plus28 on an MacBook Air M1. This used to work on this computer already. I wanted to update to the latest emacs 28 branch. As suggested, I did not use --reinstall, but `uninstall` and then `install`.

## What happened (include command output)

<pre>
 $ brew install emacs-plus@28 --with-native-comp --with-xwidgets 
</pre>

<details>
  <summary>Command output</summary>
  <pre>

$ brew install emacs-plus@28 --with-native-comp --with-xwidgets 
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating ~/Library/Caches/Homebrew/emacs-plus@28--git
==> Checking out branch emacs-28
Already on 'emacs-28'
Your branch is up to date with 'origin/emacs-28'.
HEAD is now at dbe6a3ecf7 Fix regression in 'custom-prompt-customize-unsaved-options'
==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8583 (offset -185 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1315 (offset 59 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1878 (offset -11 lines).
Hunk #2 succeeded at 5389 (offset -6 lines).
Hunk #3 succeeded at 5635 (offset -6 lines).
Hunk #4 succeeded at 5685 (offset -6 lines).
Hunk #5 succeeded at 5911 (offset -6 lines).
Hunk #6 succeeded at 8916 (offset 14 lines).
Hunk #7 succeeded at 10072 (offset 14 lines).
==> ./autogen.sh
==> ./configure --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/opt/h
==> make
Last 15 lines from ~/Logs/Homebrew/emacs-plus@28/03.make:
codesign -s - -f temacs.tmp
temacs.tmp: replacing existing signature
mv temacs.tmp temacs
.././build-aux/install-sh -c -d ../etc
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../lisp update-subdirs
for file in . ./calc ./calendar ./emacs-lisp ./emulation ./erc ./eshell ./gnus ./image ./international ./language ./mail ./mh-e ./net ./nxml ./obsolete ./org ./play ./progmodes ./term ./textmodes ./url ./vc; do \
	   ./../build-aux/update-subdirs $file; \
	done;
cp -f temacs bootstrap-emacs
rm -f bootstrap-emacs.pdmp
./temacs --batch  -l loadup --temacs=pbootstrap \
		--bin-dest /opt/homebrew/Cellar/emacs-plus@28/28.0.50/bin/ --eln-dest /opt/homebrew/Cellar/emacs-plus@28/28.0.50/lib/emacs/28.0.91/
make[1]: *** [bootstrap-emacs.pdmp] Killed: 9
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.4.1-52-gf0f1eb6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0f1eb6d4ac9af377976c131e92739bcd2f72f60
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7acfa44cff3b26ceae3fbdfe1f48097a6bd593a7
Core tap last commit: 17 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ln58LqYiFt/org.xquartz:0
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-arm64
CLT: 13.2.0.0.1.1637719136
Xcode: 13.2.1
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config
</pre>

**Comment by kommen** [comment]
As my error sounded similar to https://github.com/d12frosted/homebrew-emacs-plus/issues/292#issuecomment-782762144 following the suggestions there actually fixed the issue I was seeing:

1) `brew bundle dump` to produce a Brewfile containing everything I had installed via brew
2) [uninstall homebrew ](https://github.com/homebrew/install#uninstall-homebrew)
3) install homebrew
4) `brew bundle` to reinstall all formulas from the generated Brewfile from 1)
5)  `brew install emacs-plus@28 --with-native-comp --with-xwidgets` now worked

**Comment by d12frosted** [comment]
Doesn't sound like fun. Though happy you figured that out.
