### ISSUE TITLE
M-! ulmit -n shows 1024

### ISSUE THREAD

**Issue by anildigital** [d12frosted/homebrew-emacs-plus#443]
I noticed Emacs doesn't pick max files limit of macOS

```
$ launchctl limit maxfiles
maxfiles    64000          22524288
```

When I use lsp in Emacs, I frequently get ` Creating pipe: Too many open file`

I guess reason could be M-! ulmit -n shows 1024 instead of macOS maxfiles limit

I have set following, but GUI Emacs doesn't pick those

`kern.maxfiles: 22524288`
`kern.maxfilesperproc: 64000`

Any help to fix this is appreciated.

Thanks!

**Comment by d12frosted** [comment]
> I have set following, but GUI Emacs doesn't pick those

I suspect that running from terminal works as expected. Can you please confirm?

**Comment by anildigital** [comment]
@d12frosted 

When I open emacs on macOS with
`open /Applications/Emacs.app` then with M-! ulimit -n, I still see value as 1024

It's same (ulimit -n value 1024) when I open emacs with `/usr/local/Cellar/emacs-plus@29/29.0.50/bin/emacs`

**Comment by d12frosted** [comment]
Then I have no ideas :shrug: My advice would be to approach [Emacs mailing list](https://savannah.gnu.org/mail/?group=emacs). I am sure you will get more help there. This repository is just a formula for homebrew and not a custom distribution of Emacs.
