### ISSUE TITLE
Emacs 28.1 (new stable release)

### ISSUE THREAD

**Issue by jidicula** [d12frosted/homebrew-emacs-plus#445]
It looks like Emacs 28.1 is now the stable Emacs release as of Apr 4, 2022: https://www.gnu.org/software/emacs/#Releases

> [Emacs 28.1](https://www.gnu.org/software/emacs/news/NEWS.28.1) has a wide variety of new features, including:
> 
> - Native compilation of Lisp files
> - Text shaping with HarfBuzz and drawing with Cairo
> - Support for loading Secure Computing filters
> - Much improved display of Emoji and Emoji sequences
> - New system for documenting groups of functions
> - A minor mode for context menus
> - Mode-specific commands
> - Emacs shows matching parentheses by default
> - Many improvements and extensions to project.el

Could the 28 formula be updated?

**Comment by d12frosted** [comment]
Amazing! Already updated the formula in https://github.com/d12frosted/homebrew-emacs-plus/pull/447.
