### ISSUE TITLE
28.1 has been released

### ISSUE THREAD

**Issue by seagle0128** [d12frosted/homebrew-emacs-plus#446]
Hi, 28.1 has been released officially. See https://lists.gnu.org/archive/html/emacs-devel/2022-04/msg00093.html. The receipt should be updated accordingly.

https://github.com/d12frosted/homebrew-emacs-plus/blob/9d4f6639f3f931f7423a29936865970c662fff7f/Formula/emacs-plus%4028.rb#L5

**Comment by d12frosted** [comment]
Thanks! Amazing news.

Fixed by https://github.com/d12frosted/homebrew-emacs-plus/pull/447

**Comment by seagle0128** [comment]
Thank you!
