### ISSUE TITLE
Restore 24 bit color support in Cocoa app

### ISSUE THREAD

**Issue by cacology** [d12frosted/homebrew-emacs-plus#452]
My build of emacs-plus@28 does not create an Emacs.app that supports 24 bit color. I tried to debug this further, but it's a bit beyond me. I can't quite figure out how the Cocoa app decided how many colors to support. Here's my data for emacs-plus@28:

* Emacs.app returns the short list to `M-x` `list-colors-display`, likewise running cocoa emacs from the command line.
* `XTERM=xterm-24bit emacs -nw` returns the long list to `list-colors-display` as long as you follow the setup here: [https://stackoverflow.com/questions/14672875/true-color-24-bit-in-terminal-emacs](https://stackoverflow.com/questions/14672875/true-color-24-bit-in-terminal-emacs)

It seems like emacs-plus is building with 24 bit color support, but there's something off with the Cocoa package. David Caldwell seems to have solved the problem for his package: [https://github.com/caldwell/build-emacs](https://github.com/caldwell/build-emacs) His returns the long list for `list-colors-display` from his Emacs.app.

Respectfully submitted,

**Comment by d12frosted** [comment]
Hey @cacology,

Could you please help me and define the meaning of long list? In `Emacs.app` I have 597 lines in `list-colors-display` buffer. In `XTERM=xterm-24bit emacs -nw` I see only 256 lines when run in `Terminal.app`.

**Comment by d12frosted** [comment]
Went through Emacs News and seems like setting `COLORTERM` environment variable to `truecolor` should be enough to enable it in `emacs -nw`. For me it leads to 556 lines 🤔 

What is the value of `(display-color-cells)`? For me it's exactly `2^24`.

**Comment by d12frosted** [comment]
Sorry for multiple comments in a short time period. Here are some other findings:

1. Seems like `list-colors-display` actually lists defined colours and not colours the display can handle. It uses result `(defined-colors)` as list of colours to display. It's doc string tells that it "computes a list of
colors that the current display can handle", but I could not find it in the code.
2. `(display-color-cells)` returns `2^24` in `Emacs.app` and in `emacs -nw` in Alacrity that supports true color and only 256 in `emacs -nw` in `Terminal.app` that doesn't support it.

So to me it seems like the thing is working, it's just that the list of defined colours is shorter. Will check how it works in emacsformacos.

**Comment by d12frosted** [comment]
Just tried in `Emacs.app` downloaded from https://emacsformacosx.com and have the same result as in in `Emacs.app` built from `emacs-plus`. Basically, `list-colors-display` returns 597 lines, and `(display-color-cells)` returns `2^24`.

I've run out of ideas :(

**Comment by d12frosted** [comment]
Nice. Glad you figured it out. And thanks for sharing your investigation results as well.
