### ISSUE TITLE
Emacs 28 does not seem to reclaim memory and becomes slower and slower?

### ISSUE THREAD

**Issue by Dima-369** [d12frosted/homebrew-emacs-plus#454]
I don't know if this is the correct place to post this, but I noticed how my Emacs built with those settings on macOS 10.14.6, takes up more and more memory and never seems to release it:

```bash
brew install emacs-plus@28 --with-modern-papirus-icon --with-no-titlebar --with-native-comp
```

On loading my config, it starts with around 220 MB, but it then just keeps on increasing slowly over the hours. At around 1.6 GB I have to kill it as Emacs gets so slow that it is painful to use (not sure if it is directly related to the increased memory usage though). My system only has 8 GB and my current fix is to just restart Emacs every second day at max to keep it usable.

Maybe someone else has experienced something similar and knows of a fix?

**Comment by d12frosted** [comment]
Hey @Dima-369,

I am not using `native-comp`, so going to guess. Could it be that you haven't compiled everything and it keeps compiling stuff?

You can also try posting this problem on [emacs mailing list](https://savannah.gnu.org/mail/?group=emacs) (for example, [devel](https://lists.gnu.org/mailman/listinfo/emacs-devel)).

**Comment by Dima-369** [comment]
I tested without `--with-native-comp` and noticed how my Emacs instance still shows the exact same issue that it never frees the memory and becomes slower.

Right now, I am testing the latest build from https://emacsformacosx.com/ and so far it seems that it does not have this memory/performance issue. At first I suspected my Emacs config would be the issue, but that does not seem to be the issue.

Any clues?

**Comment by d12frosted** [comment]
No real clues 😔 Though I am on Emacs 29 for a long time.

Just to clarify, by latest build do you mean Emacs 28 build or the latest nightly build (whatever version it is).

One of the ideas, maybe try to test it with Emacs 29?

Another one, try built-in profiler to see what's eating memory. 

And it would be nice to have some speculations on when it begins. Like, maybe it doesn't happen if you sit in org mode only. Or maybe it happens when you use LSP.

Sorry, not helpful.

**Comment by Dima-369** [comment]
Thanks for the ideas. I'll try Emacs 29 next.

> Just to clarify, by latest build do you mean Emacs 28 build or the latest nightly build (whatever version it is).

Ah, I meant the Emacs 28 build.

> Another one, try built-in profiler to see what's eating memory.

 At least the CPU profiler is completely unaffected by the slow down, it still shows 'regular' CPU usage, but I can try the memory profiler later.

> And it would be nice to have some speculations on when it begins. Like, maybe it doesn't happen if you sit in org mode only. Or maybe it happens when you use LSP.

From what I can tell, it happens regardless what I do in Emacs. And I don't use LSP.

**Comment by Dima-369** [comment]
I tried `emacs-plus@29` and here everything works without the high CPU usage or the memory issue.

```bash
brew update && brew install emacs-plus@29 --with-modern-papirus-icon --with-native-comp
```

Closing as using Emacs 29 is fine for me.

**Comment by d12frosted** [comment]
Amazing. Glad to hear that Emacs 29 works.
