### ISSUE TITLE
Black border around fullscreen emacs. Unexpected behavior?

### ISSUE THREAD

**Issue by jaaasonSun** [d12frosted/homebrew-emacs-plus#456]
Environment:
2021 16-inch MacBook Pro
macOS 12.3.1

There is a thin black border around emacs-plus in native fullscreen. This can be observed on both emacs-plus@29 and emacs-plus@28 with blank init.el.

Full screenshot (view this image in GitHub day theme):
![image](https://user-images.githubusercontent.com/6558643/165657331-002bfb8d-0881-45fa-888b-a305317fd5ab.png)

Comparison with emacs-mac(left):
![image](https://user-images.githubusercontent.com/6558643/165656236-fcf552bf-5442-4030-8292-fab8db667c81.png)

emac-plus in installed with
```
$ brew install emacs-plus@28
$ brew install emacs-plus@29 --with-no-frame-refocus --with-xwidgets --with-imagemagick --with-native-comp
```
Normally this would be hardly noticeable, but I'm using a screen with notch so the menu bar looks unusually tall. The border is present on external display as well. I have not tested on notchless Macs or with other emacs ns ports.

**Comment by d12frosted** [comment]
Hey @jaaasonSun 

Please remind me how to turn native full screen on, so I am 100% running the same steps as you.

**Comment by jaaasonSun** [comment]
It's on by default, just press green traffic light an you are in native full screen
<img width="86" alt="截屏2022-04-29 09 22 54" src="https://user-images.githubusercontent.com/6558643/165871851-4ccaffe3-313e-4789-bc2e-ce7e158c6bc4.png">

I did more tests, and noticed setting `internal-border-width` changes the width of the black border, which is when I realized the black border is resolution dependent. Apparently emacs resize window by character width and height by default, so full screen window size don't necessarily agree with actual display size, hence the black border.

The black border can be removed with
```
(setq frame-resize-pixelwise t)
```

**Comment by d12frosted** [comment]
@jaaasonSun interesting, thanks for sharing the fix.
