### ISSUE TITLE
Command + Tilde does nothing (if deadkeys kb)

### ISSUE THREAD

**Issue by henrymazza** [d12frosted/homebrew-emacs-plus#46]
When using multiple frames (MacOS windows) **⌘ + tilde** won't do what it is supposed to, which is changing to the next OS window (emacs frame in this case). It could be programmatically done, but I wasn't able to map this keystroke to the proper function, apparently it gets swallowed by before it can hit any lisp code. There's no message stating that the said command wasn't defined!

PS: It works correctly in emacs mac port (emacs-mac homebrew package), but I can't use Applescript to change windows sizes there, so I'm still on both boats!

**Comment by d12frosted** [comment]
Hey @henrymazza,

Are you talking about `Move focus to next window` command that is bound to ⌘` (notice, it's not tilde, but backtick). Using it works for me.

1. Start GUI Emacs.
2. Hit `C-x 5 2` to open new frame.
3. Hit ⌘` to switch to previous frame.
4. Hit ⌘` to switch back to new frame.

Could you please tell me how exactly you installed `emacs-plus`? E. g. which options you have passed when building it. Also tell me how do you launch GUI Emacs?

**Comment by henrymazza** [comment]
I’m sorry, you are right. Although ⌘ + ~ (⌘ + shift + backtick) also doesn’t work, which reminds me why I get confused these things names: I don’t speak English! For this reason my keyboard is configured as “U.S. International - PC”, that is, with dead keys. When I change it to “U.S.” only it works.

So, I’ll change it to: when configured with “dead keys” it doesn’t work, even though on every other mac app it does work anyhow. 

-- 
Fabio Mazarotto

On 28 July 2017 at 14:18:24, Boris (notifications@github.com) wrote:

Hey @henrymazza,

Are you talking about Move focus to next window command that is bound to ⌘` (notice, it's not tilde, but backtick). Using it works for me.

Start GUI Emacs.
Hit C-x 5 2 to open new frame.
Hit ⌘` to switch to previous frame.
Hit ⌘` to switch back to new frame.
Could you please tell me how exactly you installed emacs-plus? E. g. which options you have passed when building it. Also tell me how do you launch GUI Emacs?

**Comment by d12frosted** [comment]
@henrymazza That's interesting. I am using ABC - Extended and never used U.S. International, which has that 'deadkey', so I never experienced anything like this. Also, my ⌘ is `meta` key in my setup, and to switch frames I use `ace-window` package (it can be used across frames). And I have bound ⌘` to `ace-window`, so it's like macOS key binding that allows to switch between windows and frames in Emacs - neat! 

Anyways, it seems that Emacs doesn't handle this combination (like other Cocoa applications). Or it consumes this key bindings, but doesn't know what to do with it and doesn't push it further to default Cocoa handler. Unfortunately, I can't really help you in this situation as I am not familiar with Emacs code base. But I could suggest you writing on reddit or Emacs mail list, maybe there you'll be more lucky.

**Comment by henrymazza** [comment]
Great! If I find something related I write back! Thank you for your help!
