### ISSUE TITLE
Error installing Emacs 28.1 tar: unknown letter

### ISSUE THREAD

**Issue by jidicula** [d12frosted/homebrew-emacs-plus#465]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I was trying to install Emacs 28.1 with: `brew install emacs-plus@28 --with-elrumo2-icon --with-mailutils --with-xwidgets --with-native-comp --with-imagemagick --with-no-frame-refocus`

## What happened (include command output)

<pre>
$ brew install emacs-plus@28 --with-elrumo2-icon --with-mailutils --with-xwidgets --with-native-comp --with-imagemagick --with-no-frame-refocus
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  ==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-28.1.tar.xz
Already downloaded: /Users/johanan/Library/Caches/Homebrew/downloads/81fae34a5dbd8042af6a70512829e9d4a11e31e7067bf4da5c5bded31f757129--emacs-28.1.tar.xz
==> Installing emacs-plus@28 from d12frosted/emacs-plus
tar: unknown letter e
tar: unknown letter a
usage: tar {crtx}[PRTfgkmpuvz] [archive] file1 file2...

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.4.11-39-g8a5f664
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a5f6645b8bde6d38b78936f23ce2acf94ff3a6a
Last commit: 5 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 089b5e66806ec196e1f760decd0d994da223bdee
Core tap last commit: 15 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MQ5Ez9zd4o/org.xquartz:0
HOMEBREW_EDITOR: /usr/bin/env emacs
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  szip

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  postgresql@9.5

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/johanan/.pyenv/shims/python3.10-config
  /Users/johanan/.pyenv/shims/python3.9-config
  /Users/johanan/.pyenv/shims/python-config
  /Users/johanan/.pyenv/shims/python3-config
  /Users/johanan/.pyenv/shims/python3.8-config
</pre>

# Other interesting notes

* I don't get a failure when trying to install Emacs 27 with the emacs-plus formula.

* If I prepend `gnu-tar` to my PATH following the directions at https://formulae.brew.sh/formula/gnu-tar#default to supersede the system `tar`, the installation does NOT fail. I've used this fix in the meantime as a workaround.

**Comment by d12frosted** [comment]
Yes, this is related to switch to standard environment. Your workaround is good :smile_cat: I will update formula to explicitly use `gnu-tar`. Thanks for report!

**Comment by d12frosted** [comment]
We are doing all the discussion in #466, so closing this one as a duplicate.
