### ISSUE TITLE
Emacs @28 installs emacs version 29

### ISSUE THREAD

**Issue by IsaacDempsey** [d12frosted/homebrew-emacs-plus#471]
## What you were trying to do

Install emacs plus version 28

## What happened

It installed fine, but after it installed I noticed it was the wrong version - version 29 instead of 28.

<pre>
$ /usr/local/Cellar/emacs-plus@28/28.0.50/bin/emacs --version
GNU Emacs 29.0.50
Copyright (C) 2022 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
</pre>

**Comment by d12frosted** [comment]
Wow. That's super strange. Don't understand how that could be possible. Can you please provide the command you used to install `emacs-plus` and the output of installation?

**Comment by IsaacDempsey** [comment]
I think this is fixed. I ran `brew update` which I hadn't done in a while, and downloaded a bunch of new dependencies and then installed 28.1. Afterwards it removed 28.0.50 with brew cleanup. 

I'm now getting the correct result from the version command:

```
~ /usr/local/Cellar/emacs-plus@28/28.1/bin/emacs --version
GNU Emacs 28.1
Copyright (C) 2022 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

> Can you please provide the command you used to install emacs-plus and the output of installation?

Unfortunately I've already cleared my terminal screen.

Not sure how this happened, the only thing I can think of is that las time I updated homebrew, @28 was the developement version, and it was just set to point to the latest master (which is now v29)?

Anyway, closing this.

**Comment by d12frosted** [comment]
Glad that it works now. Not sure what happened as well. `emacs-plus` is [an alias to](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/Aliases/emacs-plus) `emacs-plus@28` and it was switched from `emacs-plus@27` a month and a half ago. Not sure how Emacs 29 got into this story, but glad that it works now :) Enjoy!
