### ISSUE TITLE
macOS 10.12.6 upgrade seems to break emacs-plus

### ISSUE THREAD

**Issue by JohnGraber** [d12frosted/homebrew-emacs-plus#48]
After upgrading macOS, my Spacemacs install refused to start.

I've tried upgrading emacs-plus, removing and reinstalling, all with the same result — I can't start emacs.

I uninstalled emacs-plus and installed plain ol' emacs via homebrew.  That will start normally.

Here is the output I get from attempting to start with emacs-plus:

```Process:               Emacs [21359]
Path:                  /usr/local/Cellar/emacs-plus/25.2_1/Emacs.app/Contents/MacOS/Emacs
Identifier:            Emacs
Version:               Version 25.2 (9.0)
Code Type:             X86-64 (Native)
Parent Process:        zsh [19940]
Responsible:           Emacs [21359]
User ID:               386003728

Date/Time:             2017-08-08 12:49:12.077 -0500
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        5313FAE0-883D-F119-D098-FDDECE047F74

Sleep/Wake UUID:       3462E68E-BAA6-42FD-B0ED-52FC5F359CBE

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /usr/local/Cellar/emacs-plus/25.2_1/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found

Binary Images:
       0x100000000 -        0x1001c8ff3 +org.gnu.Emacs (Version 25.2 - 9.0) <4306198F-272F-306D-9ACC-8C67C86CDBAD> /usr/local/Cellar/emacs-plus/25.2_1/Emacs.app/Contents/MacOS/Emacs
       0x113ee3000 -        0x113f20dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff90674000 -     0x7fff9144dff3  com.apple.AppKit (6.9 - 1504.83.101) <AE51ACB3-D501-3F91-B369-3D3711F24D0A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff94b19000 -     0x7fff94bafff7  com.apple.framework.IOKit (2.0.2 - 1324.60.3) <7CE4C98B-107C-3AAA-B49A-F2ACFCBBF526> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
```

Please let me know if there is anything further I can add to this report.

**Comment by taiansu** [comment]
It's because the libjpeg has upgraded to 9b, so there is no `libjpeg.8.dylib` in the place anymore. The ultimate solution is let emacs-plus links to `/usr/local/lib/libjpeg.dylib`, which will solve the library upgrade issue in the future, presumably.

**Comment by ilovezfs** [comment]
>The ultimate solution is let emacs-plus links to /usr/local/lib/libjpeg.dylib, which will solve the library upgrade issue in the future, presumably.

FWIW, this is not a good idea, and not even really possible on macOS. The version number of a library changes for good reasons, and not on every minor upgrade, so when it does, the dependents should always be rebuilt.

**Comment by taiansu** [comment]
@ilovezfs Thanks for the correction, you're right.

**Comment by d12frosted** [comment]
This should be fixed with latest update. Thanks for reporting!
