### ISSUE TITLE
does native json already supported out-of-the box ?

### ISSUE THREAD

**Issue by JakeRess** [d12frosted/homebrew-emacs-plus#482]
Use Emacs 27+ with native json support.
Benchmarks show that Emacs 27 is ~15 times faster than Emacs when using Elisp json parser implementation.

**Comment by sayeefm0** [comment]
Emacs versions since 27.1 have native json support builtin.

**Comment by d12frosted** [comment]
Yes, it's support is built-in just as @sayeefm0 said.
