### ISSUE TITLE
Could not install with --with-native-comp --with-ctags --without-cocoa

### ISSUE THREAD

**Issue by sayeefm0** [d12frosted/homebrew-emacs-plus#484]
Please make sure to follow these steps (and mark the checkboxes):

- [-] run `brew update` and try to reproduce the issue again
- [-] run `brew doctor`, fix all issues and try to reproduce your issue again
- [-] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install `emacs-plus@29 --with-native-comp --with-ctags --without-cocoa`.

I do not have this issue on my local, but when running a setup-script on a gh actions macOS runner that installs Emacs from a brew file as an intermediate step. 
- [Workflow](https://github.com/sayeefm0/dotfiles/actions/workflows/setup-script.yml) - intermittently failing emacs install
- [Workflow definition file](https://github.com/sayeefm0/dotfiles/blob/trunk/.github/workflows/setup-script.yml)
- [Brewfile including Emacs](https://github.com/sayeefm0/dotfiles/blob/trunk/brew/Emacs)

I am not using the homebrew setup workflow, but installing it the normal way as part of the script. As far as I can tell `brew` itself is working normally.

## What happened (include command output)

<pre>
$ brew install emacs-plus@29 --with-native-comp --with-ctags --without-cocoa
</pre>

<details>
  <summary>Command output</summary>
  <pre>

==> Installing d12frosted/emacs-plus/emacs-plus@29 --without-cocoa --with-ctags --with-native-comp
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 9385 (offset 617 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1377 (offset 121 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1933 (offset 44 lines).
Hunk #2 succeeded at 5777 (offset 382 lines).
Hunk #3 succeeded at 6065 (offset 424 lines).
Hunk #4 succeeded at 6115 (offset 424 lines).
Hunk #5 succeeded at 6341 (offset 424 lines).
Hunk #6 succeeded at 9718 (offset 816 lines).
Hunk #7 succeeded at 11052 (offset 994 lines).
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodi
==> gmake
Last 15 lines from /Users/runner/Library/Logs/Homebrew/emacs-plus@29/03.gmake:
'../src/emacs' -batch --no-site-file --no-site-lisp --eval "(setq load-prefer-newer t byte-compile-warnings 'all)"  \
-l comp -f batch-byte+native-compile cedet/semantic/symref/list.el
'../src/emacs' -batch --no-site-file --no-site-lisp --eval "(setq load-prefer-newer t byte-compile-warnings 'all)"  \
-l comp -f batch-byte+native-compile cedet/semantic/wisent/comp.el
'../src/emacs' -batch --no-site-file --no-site-lisp --eval "(setq load-prefer-newer t byte-compile-warnings 'all)"  \
-l comp -f batch-byte+native-compile cedet/semantic/wisent/grammar.el

In toplevel form:
cedet/semantic/symref/list.el:35:2: Error: Given parent class semantic-displayer-abstract is not a class
gmake[2]: *** [Makefile:331: cedet/semantic/symref/list.elc] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/private/tmp/emacs-plusA29-20220803-6543-i1n3tu/lisp'
gmake[1]: *** [Makefile:366: compile-main] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20220803-6543-i1n3tu/lisp'
gmake: *** [Makefile:456: lisp] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Could not install emacs-plus@28 because tar can't find xz  https://github.com/d12frosted/homebrew-emacs-plus/issues/481
Could not install with ``brew install emacs-plus@29 --with-native-comp --with-elrumo2-icon`` https://github.com/d12frosted/homebrew-emacs-plus/issues/473
Installing d12frosted/emacs-plus/emacs-plus@29 has failed!

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
N/A
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
N/A
</pre>

**Comment by d12frosted** [comment]
Hey @sayeefm0,

That's intersting. I am not available till the next week, so can't really look into details. I would suggest to check out how this repo CI is configured. You can safely replace `./build 29 [options]` with `brew install emacs-plus@29 [options]`.

**Comment by sayeefm0** [comment]
I take back what I said - It is *intermittently* failing. Not sure what's going on there, but I'll look into it

**Comment by jvtrigueros** [comment]
I'm also seeing this intermittent failure, where the first time I install it it fails, but then I run it immediately again and it works? I'm having some other issues with Doom Emacs with this build so, I'm gonna check out this `./build 29` stuff to find the commit that works.

**Comment by sayeefm0** [comment]
@jvtrigueros To confirm, are you having the exact same build failure? If not, could you post your build logs?

**Comment by d12frosted** [comment]
Possibly related to https://github.com/d12frosted/homebrew-emacs-plus/issues/473.

**Comment by jvtrigueros** [comment]
@sayeefm0 at first it seemed like it was the same thing, but it ended being an issue with [libgccjit](https://github.com/d12frosted/homebrew-emacs-plus/issues/485#issuecomment-1206748102)

**Comment by sayeefm0** [comment]
I am closing this because I scrapped that workflow as it was taking too long, and I cannot reproduce this specific build error locally. 

Re: #473 I encountered this locally, and successfully used the suggested solution of rolling back gcc & libgccjit, so thank you to the people who found that fix.
