### ISSUE TITLE
Is there a way to install Emacs of specific commit?

### ISSUE THREAD

**Issue by agzam** [d12frosted/homebrew-emacs-plus#486]
I use emacs-plus@29 and sometimes something breaks in emacs/master. `brew install emacs-plus@29` pulls the latest. Is there a way to force brew to pull specific version (commit) of Emacs?

**Comment by vinurs** [comment]
@agzam https://github.com/d12frosted/homebrew-emacs-plus/issues/441#issuecomment-1067712666
