### ISSUE TITLE
Emacs doesn't appear in Applications after installation

### ISSUE THREAD

**Issue by Mariownyou** [d12frosted/homebrew-emacs-plus#488]
I installed emacs@28 and I can't find it in my applications though it works if I run from terminal

**Comment by kborling** [comment]
Try running the following command in your terminal:
`ln -s /opt/homebrew/opt/emacs-plus@28/Emacs.app /Applications`

This will create a symbolic link in your /Applications folder that points to the Emacs.app file.

**Comment by d12frosted** [comment]
@Mariownyou this is limitation of `brew` formulaes that don't use cask. See #41 for a proper solution. In general, use @kborling solution as adviced by Emacs+ formula itself (e.g. what is printed when you install Emacs+):

```
==> Caveats
Emacs.app was installed to:
  /opt/homebrew/Cellar/emacs-plus@28/28.1

To link the application to default Homebrew App location:
  ln -s /opt/homebrew/Cellar/emacs-plus@28/28.1/Emacs.app /Applications

To start d12frosted/emacs-plus/emacs-plus@28 now and restart at login:
  brew services start d12frosted/emacs-plus/emacs-plus@28
Or, if you don't want/need a background service you can just run:
  emacs
```

**Comment by strickinato** [comment]
Wanted to call this out here as well:
(https://github.com/d12frosted/homebrew-emacs-plus/issues/41#issuecomment-364973633)

An alternative to symlinking is to drag the application bundle in to your /Applications folder and then spotlight will index it properly 😄

**Comment by d12frosted** [comment]
Another alternative is to use macos aliases - https://github.com/d12frosted/homebrew-emacs-plus/pull/517#issuecomment-1280867786
