### ISSUE TITLE
new bottles needed: JPEG 9

### ISSUE THREAD

**Issue by ilovezfs** [d12frosted/homebrew-emacs-plus#49]
The jpeg upgrade we shipped yesterday has broken your bottles, so the formula will need a revision bump and new bottles.

**Comment by d12frosted** [comment]
@wadkar I summon you 😸 

I've bumped revision number and **then** built new bottles. Should be ok 😸 

@ilovezfs thank you so much for pinging me! ❤️

**Comment by wadkar** [comment]
[Here](https://cmu.box.com/s/co9hxxkmjz0k6s5sq3jvamerics2gpa2) you go:
```
shasum -a 256 emacs-plus-25.2_2.el_capitan.bottle.1.tar.gz
4bb55f2337b6751a4f2f5be6e3387733e46e48611c6a897ef1507a48b6328b79  emacs-plus-25.2_2.el_capitan.bottle.1.tar.gz
```
Note that the link expires at the end of Aug'17.
And thank you all for the continuous updates and fixes! The only job I do is build bottles and I haven't come across any issues (yet) :-)

**Comment by d12frosted** [comment]
@wadkar thank you very much! 💯
