### ISSUE TITLE
Could not install emacs@28 with any flag

### ISSUE THREAD

**Issue by quarkquartet** [d12frosted/homebrew-emacs-plus#494]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Just try to install `emacs-plus`, doing 

```
brew install emacs-plus
```
with any flags (as long as the version is 28).

## What happened (include command output)

<pre>
$ brew install emacs-plus
</pre>

<details>
  <summary>Command output</summary>
  <pre>

==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-28.1.tar.xz
Already downloaded: /Users/isaac/Library/Caches/Homebrew/downloads/81fae34a5dbd8042af6a70512829e9d4a11e31e7067bf4da5c5bded31f757129--emacs-28.1.tar.xz
==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8583 (offset -185 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1315 (offset 59 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1878 (offset -11 lines).
Hunk #2 succeeded at 5389 (offset -6 lines).
Hunk #3 succeeded at 5635 (offset -6 lines).
Hunk #4 succeeded at 5685 (offset -6 lines).
Hunk #5 succeeded at 5911 (offset -6 lines).
Hunk #6 succeeded at 8916 (offset 14 lines).
Hunk #7 succeeded at 10072 (offset 14 lines).
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-pl
==> gmake
Last 15 lines from /Users/isaac/Library/Logs/Homebrew/emacs-plus@28/03.gmake:
  "_bswap_32", referenced from:
      _sha256_read_ctx in libgnu.a(sha256.o)
      _sha224_read_ctx in libgnu.a(sha256.o)
      _sha256_finish_ctx in libgnu.a(sha256.o)
      _sha256_conclude_ctx in libgnu.a(sha256.o)
      _sha224_finish_ctx in libgnu.a(sha256.o)
      _sha256_buffer in libgnu.a(sha256.o)
      _sha224_buffer in libgnu.a(sha256.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [Makefile:393: make-fingerprint] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory '/private/tmp/emacs-plusA28-20220818-27364-67bnw5/emacs-28.1/lib-src'
gmake: *** [Makefile:436: lib-src] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Could not install emacs-plus@28 because tar can't find xz  https://github.com/d12frosted/homebrew-emacs-plus/issues/481

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b027b16eb71a6b0802875c46243ae1cf223eb774
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/isaac/Work/root/bin/root-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config
  /Users/isaac/Work/lhapdf-install/bin/lhapdf-config
  /Users/isaac/Work/pythia8-install/bin/pythia8-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libGLEW.dylib
  /usr/local/lib/libvdt.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/Bswapcpy.h
  /usr/local/include/Buttons.h
  /usr/local/include/Bytes.h
  /usr/local/include/Byteswap.h
  /usr/local/include/Compression.h
  /usr/local/include/DllImport.h
  /usr/local/include/ESTLType.h
  /usr/local/include/GL/eglew.h
  /usr/local/include/GL/glew.h
  /usr/local/include/GL/glxew.h
  /usr/local/include/GL/wglew.h
  /usr/local/include/GLConstants.h
  /usr/local/include/Getline.h
  /usr/local/include/Gtypes.h
  /usr/local/include/GuiTypes.h
  /usr/local/include/Htypes.h
  /usr/local/include/KeySymbols.h
  /usr/local/include/MPCode.h
  /usr/local/include/MPSendRecv.h
  /usr/local/include/Match.h
  /usr/local/include/MessageTypes.h
  /usr/local/include/PoolUtils.h
  /usr/local/include/PosixThreadInc.h
  /usr/local/include/RConfig.h
  /usr/local/include/RGitCommit.h
  /usr/local/include/RQ_OBJECT.h
  /usr/local/include/RStipples.h
  /usr/local/include/RStringView.h
  /usr/local/include/RVersion.h
  /usr/local/include/RZip.h
  /usr/local/include/Riostream.h
  /usr/local/include/RootMetaSelection.h
  /usr/local/include/Rpair.h
  /usr/local/include/Rstrstream.h
  /usr/local/include/Rtypes.h
  /usr/local/include/RtypesCore.h
  /usr/local/include/RtypesImp.h
  /usr/local/include/Strlen.h
  /usr/local/include/TApplication.h
  /usr/local/include/TApplicationImp.h
  /usr/local/include/TArray.h
  /usr/local/include/TArrayC.h
  /usr/local/include/TArrayD.h
  /usr/local/include/TArrayF.h
  /usr/local/include/TArrayI.h
  /usr/local/include/TArrayL.h
  /usr/local/include/TArrayL64.h
  /usr/local/include/TArrayS.h
  /usr/local/include/TAtomicCount.h
  /usr/local/include/TAtomicCountGcc.h
  /usr/local/include/TAtomicCountPthread.h
  /usr/local/include/TAtt3D.h
  /usr/local/include/TAttAxis.h
  /usr/local/include/TAttBBox.h
  /usr/local/include/TAttBBox2D.h
  /usr/local/include/TAttFill.h
  /usr/local/include/TAttLine.h
  /usr/local/include/TAttMarker.h
  /usr/local/include/TAttPad.h
  /usr/local/include/TAttText.h
  /usr/local/include/TBase64.h
  /usr/local/include/TBaseClass.h
  /usr/local/include/TBenchmark.h
  /usr/local/include/TBits.h
  /usr/local/include/TBrowser.h
  /usr/local/include/TBrowserImp.h
  /usr/local/include/TBtree.h
  /usr/local/include/TBuffer.h
  /usr/local/include/TBuffer3D.h
  /usr/local/include/TBuffer3DTypes.h
  /usr/local/include/TCanvasImp.h
  /usr/local/include/TClass.h
  /usr/local/include/TClassEdit.h
  /usr/local/include/TClassGenerator.h
  /usr/local/include/TClassMenuItem.h
  /usr/local/include/TClassRef.h
  /usr/local/include/TClassStreamer.h
  /usr/local/include/TClassTable.h
  /usr/local/include/TClonesArray.h
  /usr/local/include/TCollection.h
  /usr/local/include/TCollectionProxyInfo.h
  /usr/local/include/TColor.h
  /usr/local/include/TColorGradient.h
  /usr/local/include/TCondition.h
  /usr/local/include/TConditionImp.h
  /usr/local/include/TContextMenu.h
  /usr/local/include/TContextMenuImp.h
  /usr/local/include/TControlBarImp.h
  /usr/local/include/TDataMember.h
  /usr/local/include/TDataType.h
  /usr/local/include/TDatime.h
  /usr/local/include/TDictAttributeMap.h
  /usr/local/include/TDictionary.h
  /usr/local/include/TDirectory.h
  /usr/local/include/TEnum.h
  /usr/local/include/TEnumConstant.h
  /usr/local/include/TEnv.h
  /usr/local/include/TError.h
  /usr/local/include/TExMap.h
  /usr/local/include/TException.h
  /usr/local/include/TExec.h
  /usr/local/include/TFileCollection.h
  /usr/local/include/TFileInfo.h
  /usr/local/include/TFileMergeInfo.h
  /usr/local/include/TFolder.h
  /usr/local/include/TFunction.h
  /usr/local/include/TFunctionTemplate.h
  /usr/local/include/TGenericClassInfo.h
  /usr/local/include/TGlobal.h
  /usr/local/include/TGuiFactory.h
  /usr/local/include/THashList.h
  /usr/local/include/THashTable.h
  /usr/local/include/TInetAddress.h
  /usr/local/include/TInspectorImp.h
  /usr/local/include/TInterpreter.h
  /usr/local/include/TInterpreterValue.h
  /usr/local/include/TIsAProxy.h
  /usr/local/include/TIterator.h
  /usr/local/include/TList.h
  /usr/local/include/TListOfDataMembers.h
  /usr/local/include/TListOfEnums.h
  /usr/local/include/TListOfEnumsWithLock.h
  /usr/local/include/TListOfFunctionTemplates.h
  /usr/local/include/TListOfFunctions.h
  /usr/local/include/TMD5.h
  /usr/local/include/TMPClient.h
  /usr/local/include/TMPWorker.h
  /usr/local/include/TMPWorkerExecutor.h
  /usr/local/include/TMacro.h
  /usr/local/include/TMap.h
  /usr/local/include/TMathBase.h
  /usr/local/include/TMemberInspector.h
  /usr/local/include/TMemberStreamer.h
  /usr/local/include/TMessageHandler.h
  /usr/local/include/TMethod.h
  /usr/local/include/TMethodArg.h
  /usr/local/include/TMethodCall.h
  /usr/local/include/TMutex.h
  /usr/local/include/TMutexImp.h
  /usr/local/include/TNamed.h
  /usr/local/include/TNotifyLink.h
  /usr/local/include/TObjArray.h
  /usr/local/include/TObjString.h
  /usr/local/include/TObject.h
  /usr/local/include/TObjectSpy.h
  /usr/local/include/TObjectTable.h
  /usr/local/include/TOrdCollection.h
  /usr/local/include/TPRegexp.h
  /usr/local/include/TParameter.h
  /usr/local/include/TPluginManager.h
  /usr/local/include/TPoint.h
  /usr/local/include/TPosixCondition.h
  /usr/local/include/TPosixMutex.h
  /usr/local/include/TPosixThread.h
  /usr/local/include/TPosixThreadFactory.h
  /usr/local/include/TProcPool.h
  /usr/local/include/TProcessID.h
  /usr/local/include/TProcessUUID.h
  /usr/local/include/TProtoClass.h
  /usr/local/include/TQClass.h
  /usr/local/include/TQCommand.h
  /usr/local/include/TQConnection.h
  /usr/local/include/TQObject.h
  /usr/local/include/TROOT.h
  /usr/local/include/TRWLock.h
  /usr/local/include/TRealData.h
  /usr/local/include/TRedirectOutputGuard.h
  /usr/local/include/TRef.h
  /usr/local/include/TRefArray.h
  /usr/local/include/TRefCnt.h
  /usr/local/include/TRefTable.h
  /usr/local/include/TRegexp.h
  /usr/local/include/TRemoteObject.h
  /usr/local/include/TRint.h
  /usr/local/include/TRootIOCtor.h
  /usr/local/include/TSchemaHelper.h
  /usr/local/include/TSchemaRule.h
  /usr/local/include/TSchemaRuleSet.h
  /usr/local/include/TSemaphore.h
  /usr/local/include/TSeqCollection.h
  /usr/local/include/TSortedList.h
  /usr/local/include/TStatusBitsChecker.h
  /usr/local/include/TStopwatch.h
  /usr/local/include/TStorage.h
  /usr/local/include/TStreamer.h
  /usr/local/include/TStreamerElement.h
  /usr/local/include/TString.h
  /usr/local/include/TStringLong.h
  /usr/local/include/TStyle.h
  /usr/local/include/TSysEvtHandler.h
  /usr/local/include/TSystem.h
  /usr/local/include/TSystemDirectory.h
  /usr/local/include/TSystemFile.h
  /usr/local/include/TTabCom.h
  /usr/local/include/TTask.h
  /usr/local/include/TThread.h
  /usr/local/include/TThreadFactory.h
  /usr/local/include/TThreadImp.h
  /usr/local/include/TThreadPool.h
  /usr/local/include/TThreadSlots.h
  /usr/local/include/TTime.h
  /usr/local/include/TTimeStamp.h
  /usr/local/include/TTimer.h
  /usr/local/include/TToggle.h
  /usr/local/include/TToggleGroup.h
  /usr/local/include/TUUID.h
  /usr/local/include/TUri.h
  /usr/local/include/TUrl.h
  /usr/local/include/TVersionCheck.h
  /usr/local/include/TVirtualArray.h
  /usr/local/include/TVirtualAuth.h
  /usr/local/include/TVirtualCollectionProxy.h
  /usr/local/include/TVirtualFFT.h
  /usr/local/include/TVirtualGL.h
  /usr/local/include/TVirtualIsAProxy.h
  /usr/local/include/TVirtualMonitoring.h
  /usr/local/include/TVirtualMutex.h
  /usr/local/include/TVirtualObject.h
  /usr/local/include/TVirtualPS.h
  /usr/local/include/TVirtualPad.h
  /usr/local/include/TVirtualPadEditor.h
  /usr/local/include/TVirtualPadPainter.h
  /usr/local/include/TVirtualPerfStats.h
  /usr/local/include/TVirtualQConnection.h
  /usr/local/include/TVirtualRWMutex.h
  /usr/local/include/TVirtualRefProxy.h
  /usr/local/include/TVirtualStreamerInfo.h
  /usr/local/include/TVirtualTableInterface.h
  /usr/local/include/TVirtualViewer3D.h
  /usr/local/include/TVirtualX.h
  /usr/local/include/TWin32AtomicCount.h
  /usr/local/include/TWin32Condition.h
  /usr/local/include/TWin32Mutex.h
  /usr/local/include/TWin32Thread.h
  /usr/local/include/TWin32ThreadFactory.h
  /usr/local/include/ThreadLocalStorage.h
  /usr/local/include/Varargs.h
  /usr/local/include/ZipLZ4.h
  /usr/local/include/ZipLZMA.h
  /usr/local/include/ZipZSTD.h
  /usr/local/include/root_std_complex.h
  /usr/local/include/snprintf.h
  /usr/local/include/strlcpy.h
  /usr/local/include/strtok.h
  /usr/local/include/vdt/asin.h
  /usr/local/include/vdt/atan.h
  /usr/local/include/vdt/atan2.h
  /usr/local/include/vdt/cos.h
  /usr/local/include/vdt/exp.h
  /usr/local/include/vdt/identity.h
  /usr/local/include/vdt/inv.h
  /usr/local/include/vdt/log.h
  /usr/local/include/vdt/sin.h
  /usr/local/include/vdt/sincos.h
  /usr/local/include/vdt/sqrt.h
  /usr/local/include/vdt/tan.h
  /usr/local/include/vdt/tanh.h
  /usr/local/include/vdt/vdtMath.h
  /usr/local/include/vdt/vdtcore_common.h
</pre>

**Comment by d12frosted** [comment]
I am not sure if that is the root cause, but you have many `Unexpected header files:` that might contribute to compilation issue.

**Comment by quarkquartet** [comment]
> I am not sure if that is the root cause, but you have many `Unexpected header files:` that might contribute to compilation issue.

Thank you. Removing those files solved the problem. I saw those are "warnings" instead of "errors " and ignored them initially, but they indeed caused problems.
