### ISSUE TITLE
Could not install with `emacs-plus@29 --with-native-comp --with-modern-purple-flat-icon`

### ISSUE THREAD

**Issue by duien** [d12frosted/homebrew-emacs-plus#496]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Trying to do a fresh installation of 29, one of the patches fails to apply.

It appears that the lines changed by `fix-MAC_LIBS-inference-after-gcc-12-release.patch` were changed in emacs-mirror/emacs@16dfe04be2

I tried installing without that patch, but got libgccjit errors. After a couple iterations of skipping the patch and and attempting to edit the patch and/or source, I eventually got it to work but unfortunately I'm not sure which specific combination it was. 

## What happened (include command output)

<pre>
$ brew install emacs-plus --with-native-comp --with-modern-purple-flat-icon
</pre>

<details>
  <summary>Command output</summary>
  <pre>

==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/ehyland/Library/Caches/Homebrew/emacs-plus@29--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 9a7b3673e0 Move `while` syntax check from optimiser to macroexpand
==> Installing emacs-plus@29 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 9385 (offset 617 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1377 (offset 121 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1933 (offset 44 lines).
Hunk #2 succeeded at 5777 (offset 382 lines).
Hunk #3 succeeded at 6065 (offset 424 lines).
Hunk #4 succeeded at 6115 (offset 424 lines).
Hunk #5 succeeded at 6341 (offset 424 lines).
Hunk #6 succeeded at 9718 (offset 816 lines).
Hunk #7 succeeded at 11052 (offset 994 lines).
==> Applying fix-MAC_LIBS-inference-after-gcc-12-release.patch
patching file configure.ac
Hunk #1 FAILED at 4240.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Could not install emacs-plus@28 because tar can't find xz  https://github.com/d12frosted/homebrew-emacs-plus/issues/481

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0da1c3de9a10a14a1e855c286109034117522a08
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: em -w
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.2 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A

</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libftdi0
  libhid

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  emacs-mac
  gawk

</pre>

**Comment by daviderestivo** [comment]
@d12frosted I guess this patch is no more required since the fix is in emacs master branch https://github.com/emacs-mirror/emacs/commit/16dfe04be2c57fc82ccdd56cad97b39d559a5afe

**Comment by d12frosted** [comment]
@daviderestivo yup, I will remove my patch ;)

**Comment by daviderestivo** [comment]
> @daviderestivo yup, I will remove my patch ;)

Did the same :)
