### ISSUE TITLE
no-titlebar option for emacs-plus@29

### ISSUE THREAD

**Issue by BR00l** [d12frosted/homebrew-emacs-plus#498]
Is it possible to happen? :)

**Comment by d12frosted** [comment]
Hey @BR00l 

Does [this explanation/suggestion][1] work for you?

[1]: https://github.com/d12frosted/homebrew-emacs-plus#no-titlebar

**Comment by licht1stein** [comment]
@d12frosted thank you! This should be in the README, I'll make a PR.

**Comment by d12frosted** [comment]
This was a link to readme 😅 @licht1stein or am I missing something?

**Comment by licht1stein** [comment]
Oh, sorry. It's burried under Emacs 26, didn't notice.

**Comment by licht1stein** [comment]
Дякую)

**Comment by d12frosted** [comment]
@licht1stein ❤️ 

Ah, I see now. I guess it can be improved in two ways:

1. Add a separate heading specifically for Emacs 29 under 'No Titlebar' header.
2. Additionally link it from the section that explains Emacs 29 available options.

WDYT?

**Comment by licht1stein** [comment]
Yes, that's what I had in mind. Let me make a PR then :)

**Comment by licht1stein** [comment]
I also aligned the org-tables, sorry about that: 

https://github.com/d12frosted/homebrew-emacs-plus/pull/499

**Comment by d12frosted** [comment]
Closing as it's supported out of box in Emacs. If you still think that something is needed from Emacs+, let me know.
