### ISSUE TITLE
add option to add binaries to $PATH

### ISSUE THREAD

**Issue by everson** [d12frosted/homebrew-emacs-plus#5]
I am running into https://github.com/magit/magit/issues/2318

Also, when typing `emacsclient -V` , I see that it still points to /usr/bin/, which is at 22.1

Would be great to have an option to setup links for binaries under /usr/local/Cellar/emacs-plus/25.1/bin

**Comment by d12frosted** [comment]
Ok, `brew` installs everything to `/usr/local/Cellar` with binary links to `/usr/local/bin`. When it fails to link something - it yells. Running `brew doctor` might help you to check for unlinked stuff. But before doing this - please, check your value of `$PATH`. It must contain `/usr/local/bin`. I believe that `brew` by default setups `$PATH` for bash users (during `brew` installation), but in case you are using something else (for example, `fish`) you have to setup your `PATH` manually.

**Comment by everson** [comment]
@d12frosted thanks. I had `/usr/local/bin`, only a link to emacs was there. That might have been the reason for the linking to have failed. I didn't notice any message about failure in linking, but `brew doctor` revealed: `You have unlinked kegs in your Cellar: emacs-plus`. Sorry, I should have run doctor before assuming this formula wouldn't setup these links.

Deleting `/usr/local/bin/emacs` and running `brew link emacs-plus` fixed my issue. Sorry again for the invalid report and thanks for replying so quickly.

**Comment by d12frosted** [comment]
@everson,

Glad you figured it out 😸 Checking `$PATH` and calling `brew doctor` are usually two steps I do when something goes wrong. Also I forgot to mention that `/usr/local/bin` must come **before** `/usr/bin`.

> Sorry, I should have run doctor before assuming this formula wouldn't setup these links.
> Sorry again for the invalid report and thanks for replying so quickly.

Don't need to be sorry 😸 Have fun with Spacemacs (or stock Emacs) 😸

**Comment by everson** [comment]
Trying to switch to Spacemacs from intellij / atom / vim.
