### ISSUE TITLE
Emacs opens in the wrong display

### ISSUE THREAD

**Issue by itaysharir** [d12frosted/homebrew-emacs-plus#501]
I use my macbook connected to a display and when i launch emacs-plus it opens in my macbook's display instead of the external monitor. Is there any way to solve that? I'm an emacs noob
Thanks in advance!

**Comment by d12frosted** [comment]
Hey @itaysharir 

I don't use (and actually don't have) any external moniutors, so don't understand how it should work. My advice would be to test with https://emacsformacosx.com and if you see the same behaviour, you should ask on mailing list or forums.

**Comment by itaysharir** [comment]
Oh sorry, turns out it was because the external display wasn't set as the main monitor in system preferences. didn't know i had to do that. Thanks anyways
