### ISSUE TITLE
different sockets on different machines.. why

### ISSUE THREAD

**Issue by gillyspy** [d12frosted/homebrew-emacs-plus#502]
Please make sure to follow these steps (and mark the checkboxes):

- [x ] run `brew update` and try to reproduce the issue again
- [ x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ x] run `brew config` and `brew doctor` and include their output

## What happened (include command output)
I have two macs. Both latest monterey. 
Install emacs the same way on both. using ohmyzsh on both w/ emacs plugin -- same release

<pre>
$ brew install emacs-plus 
</pre>

On mac A i have a socket in /tmp/emacs and on B somewhere in /var
On mac A i have to supply emacsclient with socket argument but on B i do not

What is setting the socket to /tmp/emacs on machine A ? 

This isn't a huge deal as I just set EMACS_SOCKET_NAME on mac A, but would like to know anyway

**Comment by gillyspy** [comment]
worth mentioning that i've had macA for a several years and it has had other emacs installations on it in the past but i can't find any artifacts and my zsh and emacs related config files are source controlled so i know they are the same.

**Comment by d12frosted** [comment]
@gillyspy any chance that one of them is Intel and another is M1?

**Comment by gillyspy** [comment]
no, both i7s

**Comment by gillyspy** [comment]
i've learned the older one did have a version where it's current socket would have been the default at the time but i've never installed anything older than 28 on the second, newer machine
