### ISSUE TITLE
New behaviour of Ctrl-p/d in Shell-mode

### ISSUE THREAD

**Issue by Kyrremann** [d12frosted/homebrew-emacs-plus#503]
I just recently switched to Emacs+ and noticed that `C-p` and `C-n` doesn't work anymore. I have to use the arrow keys instead.
Is this a configuration from Emacs+, or am I missing something? Having hard time searching for a fix to this problem.

**Comment by d12frosted** [comment]
Emacs+ is just a formula for GNU Emacs with some minor improvements. But nothing breaking the default behaviour of Emacs.

That being said, I have no clues. If it works everywhere else, it should be working in shell mode. Try running Emacs without any custom configurations (emacs -Q) and try again. If it doesn't work, let me know what command you used to install Emacs+ and share steps to reproduce the issue.

**Comment by Kyrremann** [comment]
This is embarrassing, running with `emacs -Q` it works as intended. So it's a _me_ problem.
Thanks for the help.

**Comment by d12frosted** [comment]
That happens 🙃 that's why I asked if you can reproduce without any configs 😅
