### ISSUE TITLE
Better support for xwidget-webkit

### ISSUE THREAD

**Issue by andyjda** [d12frosted/homebrew-emacs-plus#519]
Currently, the option "--with-xwidgets" builds an Emacs that provides a functional browser widget, but with a few bugs. This is especially true with Emacs 29, as it seems that [the latest version of xwidget.c](https://github.com/emacs-mirror/emacs/blob/master/src/xwidget.c) is quite different from earlier ones, including many functions that weren't present before. This is a problem since, as far as I can tell, the "--with-xwidgets" option uses [veshboo's patch](https://github.com/veshboo/emacs/blob/master/src/xwidget.c), which has since gotten out of date. So when my xwidget.el tries to call functions like `xwidget-webkit-estimated-load-progress`, it runs into `void-function` (aka undefined) errors.
Most of these bugs can be fixed with some minor Emacs-Lisp patches: see [my attempt here](https://github.com/andyjda/emacs-configuration/blob/dev/.emacs.d/custom/packages/my-webkit/my-webkit.el).
However, some of the bugs persist: in particular it's hard to balance the capturing of keys. The resulting browser is great as a navigation tool but is quite limited and buggy whenever I try to interact with an editable text-area on any page.

I'm wondering if there's a better way to go about this. Unfortunately I am not well-versed in Emacs C-code or in Homebrew formulae. I'd like to know if anyone has any idea how to patch up xwidget.c and fix the issues. 
If not, I could keep tinkering with the Emacs Lisp code. We could provide my "fixes" as a separate package for people who want to get rid of the bugs.

**Comment by andyjda** [comment]
I'm not sure if this should count as a "feature request" as technically the xwidget-webkit is a feature that's already there, but not fully functional. It probably shouldn't take priorities over failures to install though

**Comment by DivineDominion** [comment]
Ooof, xwidget.c  is a 4k+ LoC file. With your research, can you narrow down what needs to be adapted a bit? I'm fine with the AppKit/Cocoa side, but I don't know much about what stopped working for you, and why.

**Comment by andyjda** [comment]
Hey @DivineDominion thanks for your response!
I've been tinkering with the code a bit more, and I have some updates:
1) the issue is not specific to the Emacs Plus build. In fact, Emacs Plus doesn't doesn't alter the xwidget code at all, so all of the issues are caused by upstream
2) all of the problems have the same general cause: changes and updates in the xwidget functionality are only applied for the GTK framework, so many functions in the C code are simply not compiled when building on Mac (leading to the 'undefined' errors, or to functions that don't do anything)

Some of the functions that need to be written for Cocoa are:
 - xwidget-webkit-estimated-load-progress
 - xwidget-perform-lispy-event
 - xwidget-webkit-back-forward-list
 - xwidget-webkit-search

I've created[ this fork of the emacs mirror](https://github.com/andyjda/emacs/tree/xwidget-patches) to start working on fixing this. I'm not very familiar with Cocoa, but I've already added a definition for xwidget-webkit-estimated-load-progress that seems to be working.
If you can/want to help out, that'd be great! You can take a look at the changes I've already made, build on your own machine and see if you can replicate the issues. Any suggestions or contributions are welcome

**Comment by andyjda** [comment]
@d12frosted it turns out that this issue is not specific to Emacs Plus. Since the problem is in the upstream code, I will close the issue.
I do think it'd be helpful for Emacs Plus 'users' if you add a brief description of the problem to the ReadMe: in the [xwidget-webkit section](https://github.com/d12frosted/homebrew-emacs-plus#xwidgets-webkit), I would add a note along these lines:

**Note for Emacs-29**
Some updates and changes to xwidget-webkit have only been applied to GTK builds, leaving the MacOS version of this feature out-of-date, and causing a few minor bugs. For a short-term solution, you can check [these Emacs-Lisp patches](https://github.com/andyjda/emacs-configuration/tree/dev/.emacs.d/custom/packages/my-webkit).
If you'd like to contribute to a more long-term solution, please check out [this emacs-mirror fork](https://github.com/andyjda/emacs/blob/xwidget-patches/src/xwidget.c).


Please let me know if you're going to direct people to my Emacs-Lisp patches: I will make sure to create a stable branch with just the necessary fixes

**Comment by andyjda** [comment]
> Emacs 28 and Emacs 29 are using GNU Emacs xwidgets without any modifications

Thanks for clarifying that. It does look like the bulk of veshboo's patch was integrated: "basic" support for the feature is there; it just hasn't been updated to be consistent with the GTK/X11 versions. Which is why, as far as I can tell, the feature is mostly fine in Emacs 28.

Although, I've mentioned this in the [emacs devel](https://lists.gnu.org/archive/html/emacs-devel/2022-10/msg01526.html) mailing list, and apparently another major problem with the macOS version is that the Objective-C code was written without proper memory management, so there's a risk of memory leaks when using xwidget-webkit.

> I would gladly accept README update with points to your fork.

I do have a stable branch in my fork now, which solves the most glaring/annoying problems: users should be able to search text in the widget, the title/modeline isn't constantly updated, and the estimated-load-progress function is defined in the C code.
[xwidget-patch-stable](https://github.com/andyjda/emacs/tree/xwidget-patch-stable)

Note that this doesn't solve the risk of memory leaks yet. So if you'd rather not include it for now I understand. I will keep you updated on my progress here, and merge fixes into that branch as they are completed
