### ISSUE TITLE
Heavy download on upgrade

### ISSUE THREAD

**Issue by ashishwadekar** [d12frosted/homebrew-emacs-plus#52]
Hi,
I was trying to upgrade emacs plus with this command : 
`brew upgrade emacs-plus`

Dependencies were installed and then git was stuck in updating of cache:
```
🍺  /usr/local/Cellar/imagemagick@6/6.9.9-14: 1,469 files, 22.5MB
==> Installing d12frosted/emacs-plus/emacs-plus --HEAD
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/ashish/Library/Caches/Homebrew/emacs-plus--git
```

git has downloaded almost **666** mb of data and there were no signs stopping.
![screen shot 2017-09-21 at 6 26 19 pm](https://user-images.githubusercontent.com/13130213/30696937-f6bd6004-9efa-11e7-927c-fa378f9a1f42.png)

I don't know what went wrong.

Help.

Thanks,
Ashish

**Comment by d12frosted** [comment]
Hey @ashishwadekar,

Sorry for the late reply. I think the size is expected, though it's big. I have just cloned original repo (`git clone git@github.com:emacs-mirror/emacs.git emacs-sources`) and the size is 1.2 GB.

**Comment by ashishwadekar** [comment]
Hi, @d12frosted

Not an issue at all. Thanks for the information. Will try the upgrade procedure once again 😊

On a side note, I feel 1.2 GB of repo for an upgrade is too big for most of the users. Something can change. I don't know how though 😏

Cheers,
Ashish

**Comment by d12frosted** [comment]
Well, it's in the cache. And next time you update, it will not download that much. But yeah, homebrew cache grows :D

**Comment by ashishwadekar** [comment]
Ohh I see 😇

**Comment by d12frosted** [comment]
Seems that there is little I can do about size of repository, closing issue for now.
