### ISSUE TITLE
Font selection issue with @29

### ISSUE THREAD

**Issue by rougier** [d12frosted/homebrew-emacs-plus#521]
I've tested @28 and @29 and I'm unable to make emacs to select some weights for font (Roboto Mono / light weight more precisely, result is regular instead of light). Could anyone give a try to confirm the behavior?

**Comment by subego** [comment]
M-x describe-font
emacs-plus is missing semilight font weight.
emacs-plus@29
<img width="502" alt="image" src="https://user-images.githubusercontent.com/3454566/195523182-b537ada3-1635-402d-9e48-d9d9163c11f2.png">

emacs-mac
<img width="503" alt="image" src="https://user-images.githubusercontent.com/3454566/195523473-8bee1226-d3d8-4852-aaaf-8f2b8c693e39.png">

**Comment by rougier** [comment]
Using `Emacs -Q` and doing a simple face selection, I got the following screenshot. the `e` and `é` characters are displayed with different weights for no obvious reason.

<img width="835" alt="Screenshot 2022-11-13 at 15 37 01" src="https://user-images.githubusercontent.com/327203/201527404-84f68637-d308-4da2-bf41-a4b31dd0fce8.png">

**Comment by d12frosted** [comment]
@rougier I am pretty sure it's an upstream Emacs issue. Unfortunately.

**Comment by d12frosted** [comment]
@rougier after #532 I decided to test with `:font` instead of `:family` and it seems like it does the trick.

![image](https://user-images.githubusercontent.com/6507913/204972580-7ca34556-7d1f-45bd-b76e-e14b41f75fdb.png)

Can you try it as well?

**Comment by rougier** [comment]
In my case it does not select the right font (it falls back to Helvetica)
```
(font-spec :family "Source Code Pro" :weight 'light)
#<font-spec nil nil Source\ Code\ Pro nil nil light nil nil nil nil nil nil nil>

(font-spec :font "Source Code Pro" :weight 'light)
#<font-spec nil nil nil nil nil light nil nil nil nil nil nil ((:font . "Source Code Pro"))>
```

**Comment by d12frosted** [comment]
Two screenshots - with normal and light weights. I called `describe-char` on `é`.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/6507913/205039440-64d93d48-7409-4c0a-9280-94a2d181df41.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/6507913/205039504-355a3407-f4d1-4471-be32-da9f0fa6326a.png">

I might be missing something silly, but seems to be working.

**Comment by rougier** [comment]
It is installed yes. And using `(set-face-font 'default (font-spec :family "Source Code Pro" :weight 'light))` it works properly (with e and é). The Roboto Mono still displays the problem.

**Comment by d12frosted** [comment]
🤦 I did family and not font. Tried with Roboto Mono.

1. Using `:family` with `normal` weight.
2. Using `:family` with `light` weight. The `é` symbol is still using `normal` weight.
3. Using `:font` with `normal` weight.
4. Using `:font` with `light` weight. All dropped to Helvetica :(

But all works with Source Code Pro 🤔 

<img width="882" alt="image" src="https://user-images.githubusercontent.com/6507913/205040665-20b92c1a-240d-424d-8f35-c07b0112b81a.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/6507913/205040832-cdf4dfea-49e4-49c9-9a61-da100f65673e.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/6507913/205040901-13e9ec57-04b8-42eb-acc8-1119e8be831a.png">

<img width="761" alt="image" src="https://user-images.githubusercontent.com/6507913/205040951-95435750-f708-47f8-8123-96cea2aabea7.png">

**Comment by rougier** [comment]
So it is a Roboto Mono specific problem.

**Comment by rougier** [comment]
For the record, I've found a related patch, but I did not test it: https://github.com/yaglo/emacs-mac-patches/blob/main/fix_weights_and_widths.diff

**Comment by d12frosted** [comment]
Oh that's interesting. I will try to assign some time to test it. Thanks for sharing.

**Comment by rougier** [comment]
I contacted the author (@yaglo) and he'll submit a PR. See
