### ISSUE TITLE
Installing multiple versions of emacs

### ISSUE THREAD

**Issue by haji-ali** [d12frosted/homebrew-emacs-plus#524]
Is there a way to install emacs-29 along with emacs-28 using emacs-plus recipes?

I tried doing that but brew is suggesting that I unlink emacs-plus@28. I am hoping to be able to run both versions simulataneously.

**Comment by d12frosted** [comment]
You can install it. Not sure if everything would work correctly (e.g. man), but Emacs will work. Basically, each formula provide versioned executable (e.g. `emacs-29.0.50`) and `emacs` shortcut. The last one clashes between formula, just install the 'default' one first.

**Comment by haji-ali** [comment]
Just to update. This mostly works linking the two Cocoa app in `/Applications` didn't work as only one Emacs version showed up in Launcher. I would guess it's because they have similar metadata and the launcher is seeing them as duplicates.
