### ISSUE TITLE
Add NSCameraUsageDescription to Info.plist

### ISSUE THREAD

**Issue by vedkothavade** [d12frosted/homebrew-emacs-plus#526]
To use programs which access the camera such as [OpenCV](https://opencv.org/), the key [NSCameraUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscamerausagedescription) needs to be in the Info.plist. Adding the key enables Emacs to request camera permissions when a program tries to access the camera, instead of crashing the program.

Is there a way to add this functionality?

**Comment by d12frosted** [comment]
@vedkothavade Sure! Which version are you using? I don't have OpenCV to test it, so would ask you to test it.

**Comment by d12frosted** [comment]
You can test it on Emacs 29 by using `emacs-29/add-camera-usage-description` branch. See #530.

**Comment by vedkothavade** [comment]
I’m using Emacs 29. I’ll test the branch today and let you know if it works. Thanks!

**Comment by vedkothavade** [comment]
@d12frosted I'm unsure how to install a brew recipe using a different branch, or otherwise install from a local branch. How would I go about testing this?

**Comment by d12frosted** [comment]
@vedkothavade you can do it like this:

```bash
$ cd $(brew tap-info --json d12frosted/emacs-plus@29 | jq -r '.[0].path') && git switch BRANCH_NAME
$ brew uninstall emacs-plus@29
$ brew install emacs-plus@29 [OPTIONS]
```

You need `jq` installed (e.g. `brew install jq`).

**Comment by d12frosted** [comment]
Since these instructions are asked time to time, I decided to add them to the readme file :) https://github.com/d12frosted/homebrew-emacs-plus#installing-from-feature-branch

**Comment by vedkothavade** [comment]
@d12frosted seems to be working on my end, but if you want to make sure that it isn't because I manually gave this permission to Emacs prior, I can write a minimal test case for you to run

**Comment by vedkothavade** [comment]
Here is a script, if you get a chance to test. I did try to remove the permission I previously granted before running with the branch so it _should_ be working, but it can't hurt to verify.

Create virtual environment w/ opencv:
```bash
cd /tmp
python3 -m venv
source venv/bin/activate # this assumes bash/zsh, there is a activate.fish if you use that
pip install opencv-python
```
Minimal script to open the webcam. If you run `python test.py` in an emacs terminal it should ask for camera permission, and then open a window with webcam output. Press 'q' to quit the program.
test.py:
```python
import cv2
cam = cv2.VideoCapture(0)  
while(True):
    _, frame = cam.read()
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()
```
Clean up:
```bash
rm -rf venv/
rm test.py
```

**Comment by d12frosted** [comment]
@vedkothavade thank you for script to test it. This is what I saw after running it:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/6507913/204208723-53aae004-67fd-4dfc-9e60-2b75187f2925.png">

The script failed with the following error:

```
OpenCV: not authorized to capture video (status 0), requesting...
OpenCV: camera failed to properly initialize!
Traceback (most recent call last):
  File "/Users/d12frosted/python-open-cv-test/run.py", line 5, in <module>
    cv2.imshow('frame', frame)
cv2.error: OpenCV(4.6.0) /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/highgui/src/window.cpp:967: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
```

Running it for the second time resulted in a new window with me inside. Neat.

Seems like working 🎉

**Comment by d12frosted** [comment]
I will backport this to Emacs 28 as well.

**Comment by vedkothavade** [comment]
That's a strange bug, but great to see that its working correctly!
