### ISSUE TITLE
Emoji don't render

### ISSUE THREAD

**Issue by jonathanj** [d12frosted/homebrew-emacs-plus#53]
I was under the impression that the multicolor font patch should enable emoji rendering, but my emoji mostly just render as blank.

```
$ brew info emacs-plus
d12frosted/emacs-plus/emacs-plus: stable 25.3, HEAD
GNU Emacs text editor
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs-plus/HEAD-dcb8658 (3,972 files, 122.6MB) *
  Built from source on 2017-10-14 at 10:51:36 with: --with-natural-title-bar
From: https://github.com/d12frosted/homebrew-emacs-plus/blob/master/Formula/emacs-plus.rb
```

During the build process there is a message about the multicolor patch being interrupted but claims to have successfully applied it by using a fuzzy match, I'm not sure if this is relevant at all.

I'm using the Operator Mono typeface but I tried Source Code Pro and it was the same. I've also tried `emacs -Q`. I've also noticed that the first time loading a file with an emoji or pasting an emoji into emacs, the editor hangs for several seconds before becoming responsive again, albeit without any emoji rendering just a blank space.

Any suggestions would be greatly appreciated.

Here are the results of `M-x describe-char` on a fire emoji.
![image](https://user-images.githubusercontent.com/112166/31608131-743229ca-b26f-11e7-865f-625af1fd067f.png)

**Comment by threeve** [comment]
@jonathanj it may work if you explicitly tell emacs to use the "Apple Color Emoji" font for emoji symbols, such as with this line in your init.el:

```
  (set-fontset-font t 'symbol 
                    (font-spec :family "Apple Color Emoji") 
                    nil 'prepend)
```

**Comment by jonathanj** [comment]
Worked perfectly, thank you @threeve.

**Comment by tshu-w** [comment]
For those who find the emoji sequence tricky, the emacs-mac implementation is [here](https://bitbucket.org/mituharu/emacs-mac/src/master/lisp/term/mac-win.el?at=master#lines-345:805).  Although this only partially works when I remove the number after `font-shape-gstring`. If anyone can help me make this work on emacs-plus, I would be much appreciate. @d12frosted  Or would you consider adding this to emacs-plus?

**Comment by hraban** [comment]
Update: on my machine (source build of 28) this is not `symbol` but `emoji`:

```emacs-lisp
  (set-fontset-font t 'emoji
                    (font-spec :family "Apple Color Emoji") 
                    nil 'prepend)
```

thanks @threeve  👌

**Comment by LuciusChen** [comment]
when `(set-fontset-font t 'symbol (font-spec :family "Apple Color Emoji") nil 'prepend)`  ⛈️ will not fallback，`(set-fontset-font t 'emoji (font-spec :family "Apple Color Emoji") nil 'prepend)` will make ⛈️ fallback.
<img width="578" alt="image" src="https://github.com/d12frosted/homebrew-emacs-plus/assets/4947981/1fc4230e-7359-4206-a4cb-04edbc2dd67e">

**Comment by LuciusChen** [comment]
Because emojis are scattered, it is still necessary to use 'unicode instead of 'emoji or 'symbol. If using Chinese, set CJK after this.
