### ISSUE TITLE
Weird font behaviour in 29, possibly upstream

### ISSUE THREAD

**Issue by aavanian** [d12frosted/homebrew-emacs-plus#532]
- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I updated my previous build (also @29, from early this year)

## What happened (include command output)

Emacs stopped respecting my `variable-pitch` font configuration. I reduced it to the following (executed in a `emacs -Q` session):

```
(variable-pitch-mode)  ;; to vizualize the effect
(custom-set-faces
  '(variable-pitch ((t (:height 200 :family "Times New Roman"))))
  '(default ((t (:weight medium :height 150 :width normal :family "IBM Plex Mono")))))  ;; set fonts
(describe-char 1)  ;; trigger the extraneous change
```

After executing `custom-set-faces`, the buffer looks as expected (`Times New Roman`). After executing `describe-char`, the font used to display the buffer is changed (in my case to `Avenir`).

* The `variable-pitch` face is unaffected (still shows Times New Roman)
* `describe-char` is only one function that triggers the change, it seems most function calls would trigger it
* It happens with system and non-system fonts for the `variable-pitch` face but I could only reproduce it with non-system fonts for the `default` face (`IBM Plex Mono` and `Iosevka SS15` both trigger it, `Menlo` doesn't)
* The font used seems to be chosen early alphabetically (while trying to isolate, I downloaded `Arima Koshi` and emacs started to use this one rather than `Avenir`, it's immediately preceding `Avenir` by alphabetical order)
* emacs-plus@28 doesn't reproduce the issue, so it seems to be a regression in or introduced by upstream. Feel free to close.

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.6.12-20-g9c88c39
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9c88c39baead6bbc40b12ab1eae9b63bcb5a8042
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3dfe90dfad30c81007345ffaa9a03c30723f86b3
Core tap last commit: 79 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vi -e
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/xxxx/Library/miniconda/bin/icu-config
  /Users/xxxx/Library/miniconda/bin/python3-config
  /Users/xxxx/Library/miniconda/bin/ncursesw6-config
  /Users/xxxx/Library/miniconda/bin/ncurses6-config
  /Users/xxxx/Library/miniconda/bin/python3.8-config
</pre>

**Comment by d12frosted** [comment]
Hey @aavanian ,

Nice investigation 💯 Tried with two commits: https://github.com/emacs-mirror/emacs/commit/e25a108b09d12502527620ec379a0950cb577311 and https://github.com/emacs-mirror/emacs/commit/5b325a03c50d5d828d2a7934bb74f30a45fa108d.

Will try to find the offending commit later.

**Comment by d12frosted** [comment]
Ok, seems https://github.com/emacs-mirror/emacs/commit/df2f6fb7fc4b79834ae40db8be2ccdc1e4a273f1 is the offending commit. It's parent, https://github.com/emacs-mirror/emacs/commit/cc945ec0ed11c93a322db6258d47ea2746aead18 works as 'expected' (e.g. `describe-char` doesn't switch everything to incorrect face). Though I am not sure why/how autoloading breaks stuff.

I think it's better to report it to emacs-devel.

**Comment by d12frosted** [comment]
@aavanian I did a very simple test by using bundled [`build` script][1].

1. Edit `url` inside `emacs-plus@29.rb` (e.g. to something like `url "https://github.com/emacs-mirror/emacs.git", :revision => "df2f6fb7fc4b79834ae40db8be2ccdc1e4a273f1"`).
2. (Optionally) comment out all `local_patch` calls to avoid application failures.
3. Run `./build 29`.
4. Start Emacs from `emacs-plus-local` installation directory (on M1 it's `/opt/homebrew/Cellar/emacs-plus-local/29.0.50/Emacs.app/Contents/MacOS/Emacs -Q`). Why? Because `build` script creates a local copy of Emacs+ to avoid interfering with regular installation. This is what I use to test compilation while maintaining my Emacs installation :)

> Anyway, as for reporting it to emacs-dev, should I or you?

Since you already have such a great report and since you are interested in having a fix, I vote for you to do it :) Once someone has a patch to test, I can help you apply it for testing purposes. What do you say? :)

[1]: https://github.com/d12frosted/homebrew-emacs-plus/blob/master/docs/development-guidelines.org#building-locally

**Comment by d12frosted** [comment]
@aavanian oh nice, so there is a ticket and a workaround which turns to be preferred way to set the font. Nice. Thanks for sharing.
