### ISSUE TITLE
emacs-plus@29 installs Emacs 30.

### ISSUE THREAD

**Issue by wnka** [d12frosted/homebrew-emacs-plus#533]
## What you were trying to do

Install emacs-plus@29

## What happened (include command output)

<pre>
brew install emacs-plus@29 --with-native-comp --with-elrumo2-icon --with-xwidgets --with-imagemagick
</pre>

emacs-version outputs:
<pre>
GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.1.0, NS appkit-2299.00 Version 13.0.1 (Build 22A400)) of 2022-11-29
</pre>

Probably due to the recent branching of Emacs 29 and mainline being 30 now.

**Comment by d12frosted** [comment]
Some see it as an issue. I see it as an absolute win. Time to add nee version 💪

Will do this week.

**Comment by d12frosted** [comment]
Thanks to @aaronjensen, we have #537 🎉 Give it a try!
