### ISSUE TITLE
Emacs 29 fails with `could not load dump file emacs.pdmp: not built for this Emacs executable`

### ISSUE THREAD

**Issue by ckruse** [d12frosted/homebrew-emacs-plus#543]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I tried to install emacs-plus@29.

## What happened (include command output)

It fails because of this error message:

```
emacs: could not load dump file "/private/tmp/emacs-plusA29-20230104-69108-rzi5hv/src/emacs.pdmp": not built for this Emacs executable
```

I attached the logfile: [03.gmake.log](https://github.com/d12frosted/homebrew-emacs-plus/files/10342346/03.gmake.log)

<pre>
$ brew install emacs-plus@29

==> Fetching d12frosted/emacs-plus/emacs-plus@29
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/ckruse/Library/Caches/Homebrew/emacs-plus@29--git
==> Checking out branch emacs-29
Already on 'emacs-29'
Your branch is up to date with 'origin/emacs-29'.
HEAD is now at 651927ac39 ; Fix function reference in comment in c-ts-mode.el (bug#60514)
==> Installing emacs-plus@29 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file 'src/nsterm.m'
==> Applying system-appearance.patch
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.m'
==> Applying round-undecorated-frame.patch
patching file 'src/frame.c'
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.h'
patching file 'src/nsterm.m'
==> ./autogen.sh
==> ./configure --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-plus@29/29.0.60/share/info/emacs --prefix=/opt/homebrew/Cellar/emacs-plus@29/29.0.60 --with-xml2 --with-gnutls --without-compress-install --without-dbus --wit
==> gmake
Last 15 lines from /Users/ckruse/Library/Logs/Homebrew/emacs-plus@29/03.gmake:
gmake[2]: Leaving directory '/private/tmp/emacs-plusA29-20230104-69108-rzi5hv/lisp'
gmake[1]: *** [Makefile:533: lisp] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230104-69108-rzi5hv'
gmake[1]: Entering directory '/private/tmp/emacs-plusA29-20230104-69108-rzi5hv'
***
*** "make all" failed with exit status 2.
***
*** You could try to:
*** - run "make bootstrap", which might fix the problem
*** - run "make V=1", which displays the full commands invoked by make,
***   to further investigate the problem
***
gmake[1]: *** [Makefile:414: advice-on-failure] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230104-69108-rzi5hv'
gmake: *** [Makefile:370: all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config

HOMEBREW_VERSION: 3.6.17-45-gdc19eba
ORIGIN: https://github.com/Homebrew/brew
HEAD: dc19eba5d9360522bd40b58bafe3cfe412745fa1
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: daacbdc6a21a328e09a49fc146303d8e537a0d48
Core tap last commit: 48 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

</pre>

## Output of `brew doctor`

<pre>
$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
</pre>

**Comment by ckruse** [comment]
I forgot to mention that installing Emacs 28 and Emacs 27 works as expected

**Comment by d1egoaz** [comment]
Same issue for me

**Comment by sonofjon** [comment]
Me too. Note also, that Emacs 30 works as expected.

**Comment by ckruse** [comment]
I was poking around a bit today, and after removing the cache directory `~/Library/Caches/Homebrew/emacs-plus@29--git/` installation works again.

**Comment by d12frosted** [comment]
@ckruse oh, that would explain why it builds on CI. There is no cache. Thanks for figuring it out 🙏

**Comment by ckruse** [comment]
Thank you for your work on this homebrew formula!
