### ISSUE TITLE
Title bar text color broken

### ISSUE THREAD

**Issue by sphw** [d12frosted/homebrew-emacs-plus#55]
I am having an issue with the transparent title bar. 

I am using Spacemacs, and the config for the title bar can be seen at the top of this screenshot. I have seen screenshots where it doesn't look like this. Is there a way to fix it? 

![screen shot 2017-11-25 at 9 45 51 am](https://user-images.githubusercontent.com/83453/33233089-a915a66a-d1c5-11e7-9d8c-15ec5e32351b.png)

**Comment by d12frosted** [comment]
Hey,

Did you find a solution?

**Comment by kaz-yos** [comment]
I'm having the same problem with the latest --HEAD. I also noticed the font becomes more visible when the frame is in the background (behind Safari, etc). Is there an option to determine the font color in the frame title?

**Comment by malloryerik** [comment]
I've noticed a similar issue with the natural color title bar option. 
When using light themes the title bar font is rendered in white, so very hard to see. Oddly covering it with another window/frame from emacs or another application (I'm on MacOS High Sierra)  it turns grey, then back to white on focus. Ah, like kaz-yos noticed.

Does anyone know where to set this kind of thing?

**Comment by jhacksworth** [comment]
I'd rather have a blank title bar than one with ugly text, so I'm currently using this hack to remove the title bar text:

```emacs-lisp
(setq frame-title-format '('nil))
```

**Comment by rsrock** [comment]
Try 

```
(add-to-list 'default-frame-alist '(ns-appearance . dark))
```

**Comment by jhacksworth** [comment]
Thanks @rsrock! That worked 🎉

I had tried a similar configuration, but had quoted `dark`, i.e., `'dark`, which doesn't work.

Just to be clear, **this works** for me:

```emacs-lisp
(add-to-list 'default-frame-alist '(ns-appearance . dark))
```

This **doesn't work** *(note the single quote in front of dark)*:
```emacs-lisp
(add-to-list 'default-frame-alist '(ns-appearance . 'dark))
```
@kaz-yos I see that you have the single quote in front of `dark` in your configuration above. Have you tried without the quote?

**Comment by kaz-yos** [comment]
@rsrock @jhacksworth Thanks. Dropping the single quote did solve the issue!

**Comment by jhacksworth** [comment]
@kaz-yos Great to hear! 😄

**Comment by hsg777** [comment]
Thanks @rsrock! It has fixed the issue for spacemacs on macos high sierra.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/19594688/40274745-3d33a786-5bad-11e8-8a02-50bf2bfc163d.png">

**Comment by d12frosted** [comment]
Emacs 26.1 is out. Closing this issue 😸 

Let me know if you have any questions/problems.

**Comment by d12frosted** [comment]
@junjiemars It's interesting. First of all, when I try using `unbound` value Emacs behaves the same as with default values. And also, I don't see `unbound` value handing in the `nsterm.m` file of Emacs.

---

Regarding `ns-appearance`:

```
  if (EQ (new_value, Qdark))
    {
      window.appearance = [NSAppearance
                            appearanceNamed: NSAppearanceNameVibrantDark];
      FRAME_NS_APPEARANCE (f) = ns_appearance_vibrant_dark;
    }
  else
    {
      window.appearance = [NSAppearance
                            appearanceNamed: NSAppearanceNameAqua];
      FRAME_NS_APPEARANCE (f) = ns_appearance_aqua;
    }
```

As you can see, if it's not `dark`, then the default value is used. And this is also described in the info pages.

```
‘ns-appearance’
     Only available on macOS, if set to ‘dark’ draw this frame’s
     window-system window using the “vibrant dark” theme, otherwise use
     the system default.  The “vibrant dark” theme can be used to set
     the toolbar and scrollbars to a dark appearance when using an Emacs
     theme with a dark background.
```

---

Similar story with `ns-transparent-titlebar`:

```
if ([window respondsToSelector: @selector(titlebarAppearsTransparent)]
      && !EQ (new_value, old_value))
    {
      window.titlebarAppearsTransparent = !NILP (new_value);
      FRAME_NS_TRANSPARENT_TITLEBAR (f) = !NILP (new_value);
    }
```

It differentiates only `nil` and any `non-nil` values. And this is exactly what info says.

```
‘ns-transparent-titlebar’
     Only available on macOS, if non-‘nil’, set the titlebar and toolbar
     to be transparent.  This effectively sets the background color of
     both to match the Emacs background color.
```

---

So I have a question - where did you get the idea to set this value to `unbound`? 

P. S. I've checked the sources both on `master` and `emacs-26` branches.

**Comment by junjiemars** [comment]
@d12frosted ```desktop-save``` => ```frameset-save```  => reopen Emacs => frame title bar sucked.

After ```frameset-save```, ```(ns-transparent-titlebar . unbound) (ns-appearance . unbound)``` will be saved into desktop file.

**Comment by d12frosted** [comment]
I see. Thanks.

So yeah, maybe it worth mentioning in the documentation that one might want to set the value of `frameset-filter-alist`.

**Comment by saurabmish** [comment]
With Homebrew Emacs 27.1, the below addition fixes the titlebar text/font:
```
(add-to-list 'default-frame-alist '(ns-appearance . dark))
```

**Comment by mshkrebtan** [comment]
From to the Emacs manual:

>  When the desktop restores the frame and window configuration, it uses
the recorded values of frame parameters, disregarding any settings for
those parameters you have in your init file.  This
means that frame parameters such as fonts and faces for the restored
frames will come from the desktop file, where they were saved when you
exited your previous Emacs session; any settings for those parameters in
your init file will be ignored.  To disable this, customize the value of
‘frameset-filter-alist’ to filter out the frame parameters you don’t
want to be restored.

From the description of the `frameset-filter-alist` variable:

> On saving, PARAMETERS is the parameter alist of each frame processed,
and FILTERED is the parameter alist that gets saved to the frameset.
>
> On restoring, PARAMETERS is the parameter alist extracted from the
frameset, and FILTERED is the resulting frame parameter alist used
to restore the frame.
>
> Elements of ‘frameset-filter-alist’ are conses (PARAM . ACTION),
where PARAM is a parameter name (a symbol identifying a frame
parameter), and ACTION can be:
> 
>  nil       The parameter is copied to FILTERED.
>  :never    The parameter is never copied to FILTERED.
>  :save     The parameter is copied only when saving the frame.
>  :restore  The parameter is copied only when restoring the frame.
>  FILTER    A filter function.

So we just need to ensure that frame parameters `ns-transparent-titlebar` and `ns-appearance` are never copied to `FILTERED`:
```
(add-to-list 'frameset-filter-alist '(ns-transparent-titlebar . :never))
(add-to-list 'frameset-filter-alist '(ns-appearance . :never))
```
