### ISSUE TITLE
Starting Emacs-plus results in the error "Symbol's value as variable is void: native-comp-deferred-compilation-deny-list"

### ISSUE THREAD

**Issue by LuciusChen** [d12frosted/homebrew-emacs-plus#550]
After installing Emacs-plus and trying to start it, I am getting the following error: "Symbol's value as variable is void: native-comp-deferred-compilation-deny-list". To fix the error, I added the following line to my init.el file:

```
(defvar native-comp-deferred-compilation-deny-list nil)
```

After adding this line, I was able to start Emacs-plus without any errors.

**Comment by d12frosted** [comment]
This is not related to Emacs+ per se, but rather to GNU Emacs and native compilation feature. One should report them to [Emacs bug tracker](https://debbugs.gnu.org/Emacs.html). 

And while I am closing the issue, I am still curious if it's somehow related to you configs or not. Can you verify the error by running `emacs -Q`?
