### ISSUE TITLE
Add --ddarwin-unlimited-select option

### ISSUE THREAD

**Issue by octocandeira** [d12frosted/homebrew-emacs-plus#553]
Hey, thanks for your work, which makes ours much more pleasant!

A solution to the "too many files" lsp issue has been proposed: compiling with options

```CFLAGS="-DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT"```

Source: https://en.liujiacai.net/2022/09/03/emacs-maxopenfiles/

Maybe an option could be added?

**Comment by candeira** [comment]
Oops I missed it! https://github.com/d12frosted/homebrew-emacs-plus/pull/507/files

Cheers!

**Comment by d12frosted** [comment]
Indeed, it's already there. Also take a look at #510.
