### ISSUE TITLE
Another Big Sur style icon

### ISSUE THREAD

**Issue by SavchenkoValeriy** [d12frosted/homebrew-emacs-plus#558]
Hi there, I have a custom icon that matches Big Sur icon style. I based it on the default icon that I tweaked a bit, so the Epsilon looks smoother and softer. I know that the recipe already has plenty of these, but I think this one still can match the tastes of some people.

https://github.com/SavchenkoValeriy/emacs-icons

PS I just have to say that this recipe is incredible, I've been using it for years and never looked back! Thank you ❤️

**Comment by d12frosted** [comment]
Thanks to @xenodium the icon is part of Emacs+. Thanks for sharing!
