### ISSUE TITLE
support --devel block

### ISSUE THREAD

**Issue by agzam** [d12frosted/homebrew-emacs-plus#56]
Would be nice to have. Or it's too much hassle to keep it up to date?

**Comment by d12frosted** [comment]
Hey @agzam 

I remember it was there some time ago, but for some reason I just dropped it. 

Though I understand the need of having this switch. I'll consider adding it. Though not sure where :)

**Comment by d12frosted** [comment]
@agzam sorry for taking it so long

I've added `--devel` option. Could you please try it?

**Comment by agzam** [comment]
@d12frosted Nah, it doesn't work for me ;(

    [I] 10:53:17 ~/.emacs.d [develop ?]$ brew install emacs-plus --devel
    ==> Installing emacs-plus from d12frosted/emacs-plus
    ==> Downloading https://alpha.gnu.org/gnu/emacs/pretest/emacs-26.0.90.tar.xz
    Already downloaded: /Users/ag.ibragimov/Library/Caches/Homebrew/emacs-plus-26.0.90.tar.xz
    ==> Downloading https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c62450be1cbee9f11cecba846dd66c7d06/patch-multicolor-font.diff
    Already downloaded: /Users/ag.ibragimov/Library/Caches/Homebrew/emacs-plus--patch-5af2587e986db70999d1a791fca58df027ccbabd75f45e4a2af1602c75511a8c.diff
    ==> Downloading https://gist.githubusercontent.com/aaronjensen/f45894ddf431ecbff78b1bcf533d3e6b/raw/6a5cd7f57341aba673234348d8b0d2e776f86719/Emacs-25-OS-X-use-vfork.patch
    Already downloaded: /Users/ag.ibragimov/Library/Caches/Homebrew/emacs-plus--patch-f2fdbc5adab80f1af01ce120cf33e3b0590d7ae29538999287986beb55ec9ada.patch
    ==> Patching
    ==> Applying patch-multicolor-font.diff
    patching file src/macfont.m
    Hunk #1 succeeded at 2358 (offset -15 lines).
    ==> Applying Emacs-25-OS-X-use-vfork.patch
    patching file src/callproc.c
    Hunk #1 FAILED at 52.
    Hunk #2 FAILED at 636.
    2 out of 2 hunks FAILED -- saving rejects to file src/callproc.c.rej
    patching file src/conf_post.h
    Hunk #1 FAILED at 94.
    1 out of 1 hunk FAILED -- saving rejects to file src/conf_post.h.rej
    patching file src/process.c
    Hunk #1 FAILED at 1823.
    1 out of 1 hunk FAILED -- saving rejects to file src/process.c.rej
    Error: Failure while executing: patch -g 0 -f -p1 -i /tmp/emacs-plus--patch-20171219-22400-1imn6ih/Emacs-25-OS-X-use-vfork.patch

**Comment by d12frosted** [comment]
My bad. Should be fixed by now.

**Comment by d12frosted** [comment]
Sorry, it's a bad evening for me. Broke it totally. Let me fix it.

**Comment by d12frosted** [comment]
Ah. Brew doesn't work nicely with force push. In case of any problems during `brew update` - untap and tap `d12frosted/emacs-plus`.

**Comment by agzam** [comment]
@d12frosted nice, it worked but not `--with-pixel-scrolling`. To be honest I don't know, I don't think I've seen difference of having it with that.
