### ISSUE TITLE
Unable to find Python in path

### ISSUE THREAD

**Issue by theodopolopodous** [d12frosted/homebrew-emacs-plus#560]
I am getting an error...... 

`(file-missing "Searching for program" "No such file or directory" "python")`

So I look in my Info.plist, and I see "/opt/homebrew/bin"

I have python3 already on there, so I link that to "python" in the same directory

` "ln -s /opt/homebrew/bin/python3 /opt/homebrew/bin/python"
`

This works fine in my terminal session.   However Emacs still complains it cannot see "python"

Any ideas why that might be?

**Comment by theodopolopodous** [comment]
Ah I fixed my issue by doing this:

(add-to-list 'exec-path "/opt/homebrew/bin")

So now not sure what the path in the plist is used for. But happy for the moment!

**Comment by d12frosted** [comment]
Hey,

Without actual repro steps I can't really help you. How are you starting Emacs? What are you trying to achieve (e.g. what leads to the error)? Have you tried to reproduce without custom configurations (e.g. `emacs -Q`)?
