### ISSUE TITLE
Error: unknown keyword: tap

### ISSUE THREAD

**Issue by jberdine** [d12frosted/homebrew-emacs-plus#566]
---

> comment from @d12frosted 

⚠️  The issue is fixed thanks to @danielfleischer . But you have to **update brew** in order to get everything working:

```bash
$ brew update
$ brew install emacs-plus [options]
```

---

Please make sure to follow these steps (and mark the checkboxes):

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install emacs-plus@29

## What happened (include command output)

<pre>
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus@29
</pre>

<details>
  <summary>Command output</summary>
  <pre>
Error: unknown keyword: tap
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@29.rb:97:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:643:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:315:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
  </pre>
</details>
This looks like a ruby syntax error, but I'm not a ruby programmer to be sure. This is not happening with other formulas, so reporting here.

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 4.0.15-97-ge191b82
ORIGIN: https://github.com/Homebrew/brew
HEAD: e191b827cce991f52be36b0a8fc3daed3ef66143
Last commit: 2 hours ago
Core tap JSON: 28 Apr 09:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacsclient
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
</pre>

**Comment by danielfleischer** [comment]
Same error with emacs-plus@30 with the following configuration:

<details><summary>config</summary>
<p>

```
HOMEBREW_VERSION: 4.0.15-97-ge191b82
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e191b827cce991f52be36b0a8fc3daed3ef66143
Last commit: 3 hours ago
Core tap JSON: 28 Apr 10:05 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: ["--appdir=/Applications"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.3XtHnXXvlB/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 11.7.6-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

</p>
</details> 

Feels like an upstream issue.

**Comment by d12frosted** [comment]
@jberdine please try again :) @danielfleischer has fixed the issue on Emacs+ side 💯 Don't forget to update.

```
$ brew update
$ brew install emacs-plus@30 [options]
```

**Comment by jberdine** [comment]
Excellent, it works now, that was fast, thanks!

**Comment by bklebe** [comment]
I ran brew update and it's still broken. I untapped and retapped and I still can't get it to work. Is there some other cache I need to clear?

**Comment by d12frosted** [comment]
> I ran brew update and it's still broken. I untapped and retapped and I still can't get it to work. Is there some other cache I need to clear?

Make sure to actually update brew. What version are you on?

**Comment by bklebe** [comment]
@d12frosted I dug through the FAQ and ran this:
```
cd "$(brew --repository)"
git reset --hard FETCH_HEAD
```

Seems to have fixed it. Wasn't updating when I ran `brew update` for some reason.

**Comment by UnderGreen** [comment]
@bklebe That also worked for me. Thanks!

**Comment by d12frosted** [comment]
Small update in this issue. Seems like I found a way to make it working with both version of Homebrew. See #569. Now all you have to do is to update to latest version of Emacs+:

```bash
$ brew update
$ brew install emacs-plus [options]
```

Sorry for troubles 🙏 the root cause was using private APIs. They changed and Emacs+ broke.
