### ISSUE TITLE
emacs-plus@29 term and vterm display utf8 string error

### ISSUE THREAD

**Issue by getong** [d12frosted/homebrew-emacs-plus#568]
the term package cannot display utf8 string
![term3](https://user-images.githubusercontent.com/3949379/235294874-de702031-e6fd-4385-ab19-312ed6133269.jpg)

the vterm package cannot display utf8 string
I also use tmux , the bottom is vterm, and the top is tmux, they should be the same, but in fact, they are not.
![vterm](https://user-images.githubusercontent.com/3949379/235294896-e9a3192a-def7-4b7a-80f6-5117ff1fd17e.jpg)

I install emacs-plus via this command:
```
brew install emacs-plus@29
```

**Comment by getong** [comment]
I finally debug the reason
```
(getenv "LANG")
```
is nil

**Comment by d12frosted** [comment]
You can either set it manually or use [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell). A little bit of explanation can be found [here](https://d12frosted.io/posts/2022-05-12-emacs-plus-path-injection.html).
