### ISSUE TITLE
Install emacs-plus@30 error on nsterm.m

### ISSUE THREAD

**Issue by stardiviner** [d12frosted/homebrew-emacs-plus#579]
Please make sure to follow these steps (and mark the checkboxes):

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] run `brew config` and `brew doctor` and include their output

## What you were trying to do

`brew install emacs-plus@30`

## What happened (include command output)

<pre>
$ brew install emacs-plus@30
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  ==> Fetching d12frosted/emacs-plus/emacs-plus@30
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/stardiviner/Library/Caches/Homebrew/emacs-plus@30--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 3adc1e7f379 Fix crash when creating a child frame in NS (bug#63107)
==> Installing emacs-plus@30 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 9454 (offset 686 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1386 (offset 130 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1932 (offset 43 lines).
Hunk #2 succeeded at 5790 (offset 395 lines).
Hunk #3 succeeded at 6078 (offset 437 lines).
Hunk #4 succeeded at 6128 (offset 437 lines).
Hunk #5 succeeded at 6357 (offset 440 lines).
Hunk #6 succeeded at 9787 (offset 885 lines).
Hunk #7 succeeded at 11121 (offset 1063 lines).
==> Applying round-undecorated-frame.patch
patching file src/frame.c
Hunk #2 succeeded at 3970 (offset 60 lines).
Hunk #3 succeeded at 6190 (offset 136 lines).
patching file src/frame.h
Hunk #1 succeeded at 397 (offset 1 line).
Hunk #2 succeeded at 1097 (offset 15 lines).
Hunk #3 succeeded at 1124 (offset 15 lines).
patching file src/nsfns.m
Hunk #1 succeeded at 1058 (offset 9 lines).
Hunk #2 succeeded at 1386 with fuzz 2 (offset 9 lines).
patching file src/nsterm.h
patching file src/nsterm.m
Hunk #2 succeeded at 9224 (offset 147 lines).
Hunk #3 FAILED at 9165.
1 out of 3 hunks FAILED -- saving rejects to file src/nsterm.m.rej

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Fix emacs-plus@29 install with --with-native-comp and latest libgccjit https://github.com/d12frosted/homebrew-emacs-plus/pull/576
Could not install emacs-plus@29 https://github.com/d12frosted/homebrew-emacs-plus/issues/544
Could not install emacs-plus@28 with MacBookPro M1 https://github.com/d12frosted/homebrew-emacs-plus/issues/555
Could not install emacs-plus@29 with --with-xwidgets --with-imagemagick --with-native-comp https://github.com/d12frosted/homebrew-emacs-plus/issues/556

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 4.0.16-47-g1120812
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11208123782ffcb567de5fb0cea991b10459c3ca
Last commit: 30 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bb8c6bc6b5c33bb16040039088eaf589e7340df4
Core tap last commit: 38 minutes ago
Core tap branch: master
Core tap JSON: 12 Mar 09:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacsclient -t
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  szip

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  docker-swarm
  ilmbase
  lua@5.1
  node@14
  q

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: Found Ruby file outside dwarvesf/tap tap formula directory.
(/opt/homebrew/Library/Taps/dwarvesf/homebrew-tap/Formula):
  /opt/homebrew/Library/Taps/dwarvesf/homebrew-tap/glod-cli.rb
  /opt/homebrew/Library/Taps/dwarvesf/homebrew-tap/miner.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pygments
  jupyterlab
  six
</pre>

**Comment by d12frosted** [comment]
Already fixed thanks to @domq

**Comment by stardiviner** [comment]
@domq Thanks for quick fixing. 😄

**Comment by eeshugerman** [comment]
I'm seeing this issue on `@29` as well :/

**Comment by d12frosted** [comment]
Have you run brew update?

Cheers,
***@***.***

**Comment by eeshugerman** [comment]
Ahh no I had not. That fixed the issue. Thanks!
