### ISSUE TITLE
@28 Crashes when quit

### ISSUE THREAD

**Issue by frankjonen** [d12frosted/homebrew-emacs-plus#582]
I just installed 28 (coming from 27). I'm running it on Intel64, Monterey with Doom Emacs.

When I quit Emacs, it crashes before the workspace is saved.
Emacs Plus or Doom issue?

**Comment by d12frosted** [comment]
I don't know. Normally, when you are not sure if it's your config or Emacs - run without configs. E.g. `emacs -nw`.

**Comment by frankjonen** [comment]
Oh yes. I should have amended it once I did that. Made it hard to check since the vanilla Emacs just quits when you quit it. There's no saving of workspaces. And I now think that might be related.

Then I saw [Emacs-plus@28 with native comp crashes on MacOS 12/Monterey](https://github.com/d12frosted/homebrew-emacs-plus/issues/361) and it had almost the exact same crashlog as me. So I decided to try and see if installing @29 would work (given that Doom doesn't officially support it and all). But so far it works fine.

**Comment by d12frosted** [comment]
Thanks for checking. And happy that 29 works for you.

**Comment by powersurge360** [comment]
Just coming to report the same thing. I tried moving to emacs-plus@29 but I noticed some doom bindings weren't working. I unfortunately don't have much more to contribute but I did want to come in to say that emacs-plus@29 is not a complete solve for the issue for native-comp. It also seemed to fail without doom set up.

**Comment by d12frosted** [comment]
Emacs 28 is not longer supported by Emacs+. We are already focused on 30 and ongoing.
