### ISSUE TITLE
SYSSEGV when closing a frame in Emacs-plus 28.

### ISSUE THREAD

**Issue by aardvark179** [d12frosted/homebrew-emacs-plus#586]
Sometimes when closing a full screen frame I get a segfault (details attached). This appears to happen most commonly when the frame contains a window displaying a buffer that is also visible in another frame, but I haven't reproduced it reliably enough to know if that's just coincidence.
[emacs-segv.txt](https://github.com/d12frosted/homebrew-emacs-plus/files/11478344/emacs-segv.txt)

**Comment by ksqsf** [comment]
I suggest you trying Emacs 29. It has fixed numerous crashes during the development cycle.

**Comment by d12frosted** [comment]
Emacs 28 is not longer supported by Emacs+. We are already focused on 30 and ongoing.
