### ISSUE TITLE
Debug support?

### ISSUE THREAD

**Issue by Pitometsu** [d12frosted/homebrew-emacs-plus#59]
@d12frosted,

Can't find any functions from https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/debug.el

**Comment by d12frosted** [comment]
Hey,

It would be really helpful to know how exactly you installed emacs-plus (have you passed any additional options or not).

But it seems that that module is available starting from Emacs 26, which is not installed by default. Please checkout your emacs version.

**Comment by Pitometsu** [comment]
Yeah. you right, looks like them available from 26 version, and I have stable one (25.3). Sorry for disturb.

**Comment by d12frosted** [comment]
No problem.

Try using `--HEAD` or `--devel` option to install emacs-plus.
