### ISSUE TITLE
Install with --with-native-comp option causes scrolling stutters and produces an error on exit

### ISSUE THREAD

**Issue by kris-anderson** [d12frosted/homebrew-emacs-plus#591]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install emacs-plus with the `--with-native-comp` option on both an M1 and Intel MacBook running macOS 13.4.1.

## What happened (include command output)

<pre>
$ brew install emacs-plus --with-native-comp
</pre>

Everything appears to install okay. At first doom emacs was giving me errors when I tried to run any doom command like `doom sync`. I fixed that by reinstalling gcc and libgccjit though.

```shell
brew reinstall gcc libgccjit
```

Now emacs-plus installs without error, and `doom sync`, `doom upgrade`, and `doom doctor` all work without errors.

So far so good! But here's where I run into two problems.

## Problem 1

When scrolling through a file in emacs, there are stutters every 0.5-1.0 seconds. This is when holding the j/k keys to move the cursor up and down the file.

## Problem 2 

When exiting emacs `C-x C-c`, shortly after exiting, macOS throws up an error report.

## Solution

The only thing that fixes both of the above problems, at least that I've been able to determine, is not using the `--with-native-comp` when building emacs-plus.

```shell
$ brew install emacs-plus
```

When I build without native-comp, scrolling works without issue, and I get no errors when exiting the app.

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 4.0.26
ORIGIN: https://github.com/Homebrew/brew
HEAD: eff45ef570f265e226f14ce91da72d7a6e7d516a
Last commit: 5 days ago
Core tap JSON: 02 Jul 08:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: OneHalfLight
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by d12frosted** [comment]
Hey,

Re problem 1. As mush as I'd love to help, not sure I can do anything about it. Emacs+ is just a formula to build GNU Emacs. And native compilation is quite experimental (at least, the last time I checked). On the other hand, there is always a thing you can check to narrow down the problem - run Emacs without any custom lisp (e.g. `emacs -Q`) and open the file where experience the issue and try to reproduce. 

Re problem 2. Can you please share the error? Also, can you try without any custom lisp (e.g. `emacs -Q`)?

**Comment by Patryk27** [comment]
It's possible the stutter was caused by the asynchronous native-comp happening on the background - you can confirm it by checking the `*Async-native-compile-log*` buffer (if it's working, stuff is getting compiled and eating the CPU time).

You can either wait a few minutes (it should complete within 15 minutes or so) or precompile everything before Emacs is launched (https://github.com/doomemacs/doomemacs/issues/6811).

**Comment by kris-anderson** [comment]
> It's possible the stutter was caused by the asynchronous native-comp happening on the background - you can confirm it by checking the `*Async-native-compile-log*` buffer (if it's working, stuff is getting compiled and eating the CPU time).
> 
> You can either wait a few minutes (it should complete within 15 minutes or so) or precompile everything before Emacs is launched ([doomemacs/doomemacs#6811](https://github.com/doomemacs/doomemacs/issues/6811)).

That was it. Thank you @Patryk27 !

That solved my first issue, and the second issue I had seems to be addressed in version 29+ of Emacs. So I'll go ahead and close out this ticket since both of those items are no longer problems I'm experiencing.
