### ISSUE TITLE
Could not install with [OPTIONS]

### ISSUE THREAD

**Issue by lewisl** [d12frosted/homebrew-emacs-plus#592]
Please make sure to follow these steps (and mark the checkboxes):

- [ ] run `brew update` and try to reproduce the issue again
- [ ] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ ] run `brew config` and `brew doctor` and include their output

## What you were trying to do

brew install emacs-plus@28 --with-native-comp --with imagemagick

## What happened (include command output)

<pre>
➜  ~ brew install emacs-plus@28 --with-native-comp --with imagemagick
Usage: brew install [options] formula|cask [...]

Install a formula or cask. Additional options specific to a formula may be
appended to the command.

Unless HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK is set, brew upgrade or brew
reinstall will be run for outdated dependents and dependents with broken
linkage, respectively.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the installed formulae or, every 30 days, for all formulae.

Unless HOMEBREW_NO_INSTALL_UPGRADE is set, brew install formula will
upgrade formula if it is already installed but outdated.

  -d, --debug                      If brewing fails, open an interactive
                                   debugging session with access to IRB or a
                                   shell inside the temporary build directory.
  -f, --force                      Install formulae without checking for
                                   previously installed keg-only or non-migrated
                                   versions. When installing casks, overwrite
                                   existing files (binaries and symlinks are
                                   excluded, unless originally from the same
                                   cask).
  -v, --verbose                    Print the verification and postinstall steps.
  -n, --dry-run                    Show what would be installed, but do not
                                   actually install anything.
      --formula, --formulae        Treat all named arguments as formulae.
      --ignore-dependencies        An unsupported Homebrew development flag to
                                   skip installing any dependencies of any kind.
                                   If the dependencies are not already present,
                                   the formula will have issues. If you're not
                                   developing Homebrew, consider adjusting your
                                   PATH rather than using this flag.
      --only-dependencies          Install the dependencies with specified
                                   options but do not install the formula
                                   itself.
      --cc                         Attempt to compile using the specified
                                   compiler, which should be the name of the
                                   compiler's executable, e.g. gcc-7 for GCC
                                   7. In order to use LLVM's clang, specify
                                   llvm_clang. To use the Apple-provided
                                   clang, specify clang. This option will only
                                   accept compilers that are provided by
                                   Homebrew or bundled with macOS. Please do not
                                   file issues if you encounter errors while
                                   using this option.
  -s, --build-from-source          Compile formula from source even if a
                                   bottle is provided. Dependencies will still
                                   be installed from bottles if they are
                                   available.
      --force-bottle               Install from a bottle if it exists for the
                                   current or newest version of macOS, even if
                                   it would not normally be used for
                                   installation.
      --include-test               Install testing dependencies required to run
                                   brew test formula.
      --HEAD                       If formula defines it, install the HEAD
                                   version, aka. main, trunk, unstable, master.
      --fetch-HEAD                 Fetch the upstream repository to detect if
                                   the HEAD installation of the formula is
                                   outdated. Otherwise, the repository's HEAD
                                   will only be checked for updates when a new
                                   stable or development version has been
                                   released.
      --keep-tmp                   Retain the temporary files created during
                                   installation.
      --debug-symbols              Generate debug symbols on build. Source will
                                   be retained in a cache directory.
      --build-bottle               Prepare the formula for eventual bottling
                                   during installation, skipping any
                                   post-install steps.
      --skip-post-install          Install but skip any post-install steps.
      --bottle-arch                Optimise bottles for the specified
                                   architecture rather than the oldest
                                   architecture supported by the version of
                                   macOS the bottles are built on.
      --display-times              Print install times for each package at the
                                   end of the run.
  -i, --interactive                Download and patch formula, then open a
                                   shell. This allows the user to run
                                   ./configure --help and otherwise determine
                                   how to turn the software package into a
                                   Homebrew package.
  -g, --git                        Create a Git repository, useful for creating
                                   patches to the software.
      --overwrite                  Delete files that already exist in the prefix
                                   while linking.
      --cask, --casks              Treat all named arguments as casks.
      --[no-]binaries              Disable/enable linking of helper executables
                                   (default: enabled).
      --require-sha                Require all casks to have a checksum.
      --[no-]quarantine            Disable/enable quarantining of downloads
                                   (default: enabled).
      --adopt                      Adopt existing artifacts in the destination
                                   that are identical to those being installed.
                                   Cannot be combined with --force.
      --skip-cask-deps             Skip installing cask dependencies.
      --zap                        For use with brew reinstall --cask. Remove
                                   all files associated with a cask. May remove
                                   files which are shared between applications.
      --appdir                     Target location for Applications (default:
                                   /Applications).
      --keyboard-layoutdir         Target location for Keyboard Layouts
                                   (default: /Library/Keyboard Layouts).
      --colorpickerdir             Target location for Color Pickers (default:
                                   ~/Library/ColorPickers).
      --prefpanedir                Target location for Preference Panes
                                   (default: ~/Library/PreferencePanes).
      --qlplugindir                Target location for QuickLook Plugins
                                   (default: ~/Library/QuickLook).
      --mdimporterdir              Target location for Spotlight Plugins
                                   (default: ~/Library/Spotlight).
      --dictionarydir              Target location for Dictionaries (default:
                                   ~/Library/Dictionaries).
      --fontdir                    Target location for Fonts (default:
                                   ~/Library/Fonts).
      --servicedir                 Target location for Services (default:
                                   ~/Library/Services).
      --input-methoddir            Target location for Input Methods (default:
                                   ~/Library/Input Methods).
      --internet-plugindir         Target location for Internet Plugins
                                   (default: ~/Library/Internet Plug-Ins).
      --audio-unit-plugindir       Target location for Audio Unit Plugins
                                   (default:
                                   ~/Library/Audio/Plug-Ins/Components).
      --vst-plugindir              Target location for VST Plugins (default:
                                   ~/Library/Audio/Plug-Ins/VST).
      --vst3-plugindir             Target location for VST3 Plugins (default:
                                   ~/Library/Audio/Plug-Ins/VST3).
      --screen-saverdir            Target location for Screen Savers (default:
                                   ~/Library/Screen Savers).
      --language                   Comma-separated list of language codes to
                                   prefer for cask installation. The first
                                   matching language is used, otherwise it
                                   reverts to the cask's default language. The
                                   default value is the language of your system.
  -q, --quiet                      Make some output more quiet.
  -h, --help                       Show this message.
Error: invalid option: --with-native-comp
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config`

<pre>
brew config
HOMEBREW_VERSION: 4.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3db1acf3e38e270af4e1c3f214622bbfb18f830e
Last commit: 2 days ago
Core tap JSON: 28 Jul 15:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.HLuYJy4Omv/org.xquartz:0
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libjags.4.dylib
  /usr/local/lib/libjrmath.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/JAGS/Console.h
  /usr/local/include/JAGS/JRmath.h
  /usr/local/include/JAGS/compiler/Compiler.h
  /usr/local/include/JAGS/compiler/Counter.h
  /usr/local/include/JAGS/compiler/CounterTab.h
  /usr/local/include/JAGS/compiler/LogicalFactory.h
  /usr/local/include/JAGS/compiler/MixtureFactory.h
  /usr/local/include/JAGS/compiler/NodeFactory.h
  /usr/local/include/JAGS/compiler/ObsFuncTab.h
  /usr/local/include/JAGS/compiler/ParseTree.h
  /usr/local/include/JAGS/distribution/ArrayDist.h
  /usr/local/include/JAGS/distribution/DistError.h
  /usr/local/include/JAGS/distribution/DistPtr.h
  /usr/local/include/JAGS/distribution/DistTab.h
  /usr/local/include/JAGS/distribution/Distribution.h
  /usr/local/include/JAGS/distribution/RScalarDist.h
  /usr/local/include/JAGS/distribution/ScalarDist.h
  /usr/local/include/JAGS/distribution/VectorDist.h
  /usr/local/include/JAGS/function/ArrayFunction.h
  /usr/local/include/JAGS/function/ArrayLogDensity.h
  /usr/local/include/JAGS/function/DFunction.h
  /usr/local/include/JAGS/function/DPQFunction.h
  /usr/local/include/JAGS/function/FuncError.h
  /usr/local/include/JAGS/function/FuncTab.h
  /usr/local/include/JAGS/function/Function.h
  /usr/local/include/JAGS/function/FunctionPtr.h
  /usr/local/include/JAGS/function/LinkFunction.h
  /usr/local/include/JAGS/function/PFunction.h
  /usr/local/include/JAGS/function/QFunction.h
  /usr/local/include/JAGS/function/ScalarFunction.h
  /usr/local/include/JAGS/function/ScalarLogDensity.h
  /usr/local/include/JAGS/function/ScalarVectorFunction.h
  /usr/local/include/JAGS/function/VectorFunction.h
  /usr/local/include/JAGS/function/VectorLogDensity.h
  /usr/local/include/JAGS/graph/AggNode.h
  /usr/local/include/JAGS/graph/ArrayLogicalNode.h
  /usr/local/include/JAGS/graph/ArrayStochasticNode.h
  /usr/local/include/JAGS/graph/ConstantNode.h
  /usr/local/include/JAGS/graph/DeterministicNode.h
  /usr/local/include/JAGS/graph/Graph.h
  /usr/local/include/JAGS/graph/GraphMarks.h
  /usr/local/include/JAGS/graph/LinkNode.h
  /usr/local/include/JAGS/graph/LogicalNode.h
  /usr/local/include/JAGS/graph/MixTab.h
  /usr/local/include/JAGS/graph/MixtureNode.h
  /usr/local/include/JAGS/graph/Node.h
  /usr/local/include/JAGS/graph/NodeError.h
  /usr/local/include/JAGS/graph/ParentError.h
  /usr/local/include/JAGS/graph/ScalarLogicalNode.h
  /usr/local/include/JAGS/graph/ScalarStochasticNode.h
  /usr/local/include/JAGS/graph/StochasticNode.h
  /usr/local/include/JAGS/graph/VSLogicalNode.h
  /usr/local/include/JAGS/graph/VectorLogicalNode.h
  /usr/local/include/JAGS/graph/VectorStochasticNode.h
  /usr/local/include/JAGS/model/BUGSModel.h
  /usr/local/include/JAGS/model/Model.h
  /usr/local/include/JAGS/model/Monitor.h
  /usr/local/include/JAGS/model/MonitorControl.h
  /usr/local/include/JAGS/model/MonitorFactory.h
  /usr/local/include/JAGS/model/MonitorInfo.h
  /usr/local/include/JAGS/model/NodeArray.h
  /usr/local/include/JAGS/model/NodeArraySubset.h
  /usr/local/include/JAGS/model/SymTab.h
  /usr/local/include/JAGS/module/Module.h
  /usr/local/include/JAGS/module/ModuleError.h
  /usr/local/include/JAGS/rng/RNG.h
  /usr/local/include/JAGS/rng/RNGFactory.h
  /usr/local/include/JAGS/rng/RmathRNG.h
  /usr/local/include/JAGS/rng/TruncatedNormal.h
  /usr/local/include/JAGS/sampler/GraphView.h
  /usr/local/include/JAGS/sampler/ImmutableSampleMethod.h
  /usr/local/include/JAGS/sampler/ImmutableSampler.h
  /usr/local/include/JAGS/sampler/Linear.h
  /usr/local/include/JAGS/sampler/Metropolis.h
  /usr/local/include/JAGS/sampler/MutableSampleMethod.h
  /usr/local/include/JAGS/sampler/MutableSampler.h
  /usr/local/include/JAGS/sampler/RWMetropolis.h
  /usr/local/include/JAGS/sampler/SampleMethodNoAdapt.h
  /usr/local/include/JAGS/sampler/Sampler.h
  /usr/local/include/JAGS/sampler/SamplerFactory.h
  /usr/local/include/JAGS/sampler/SingletonFactory.h
  /usr/local/include/JAGS/sampler/SingletonGraphView.h
  /usr/local/include/JAGS/sampler/Slicer.h
  /usr/local/include/JAGS/sampler/StepAdapter.h
  /usr/local/include/JAGS/sampler/TemperedMetropolis.h
  /usr/local/include/JAGS/sarray/Range.h
  /usr/local/include/JAGS/sarray/RangeIterator.h
  /usr/local/include/JAGS/sarray/SArray.h
  /usr/local/include/JAGS/sarray/SimpleRange.h
  /usr/local/include/JAGS/util/dim.h
  /usr/local/include/JAGS/util/integer.h
  /usr/local/include/JAGS/util/logical.h
  /usr/local/include/JAGS/util/nainf.h
  /usr/local/include/JAGS/version.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libjags.la
  /usr/local/lib/libjrmath.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/jags.pc

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
</pre>

**Comment by lewisl** [comment]
I do brew search emacs-plus and there is no such formula.  Seems like your instructions are wrong.

**Comment by d12frosted** [comment]
> I just confirmed at the homebrew site that none of your formulae even exist. What gives?

@lewisl `emacs-plus` is not part of homebrew core, it's a tap you need to install. Hence you can't find it there. Follow the instructions including the `tap` step.

> Seems like your instructions are wrong.

🤷 according to opt-out homebrew stats, emacs+ was installed more than 1k times over the last 30 days. 

> brew install emacs-plus@28 --with-native-comp --with imagemagick

BTW, You forgot a dash in `--with-imagemagick` option.

**Comment by lewisl** [comment]
Got it. How did I miss the tap thing?

Will give it another shot.

- Lewis

On Jul 28, 2023, at 12:08 PM, Boris Buliga ***@***.***> wrote:

﻿

I just confirmed at the homebrew site that none of your formulae even exist. What gives?

@lewisl<https://github.com/lewisl> emacs-plus is not part of homebrew core, it's a tap you need to install. Hence you can't find it there. Follow the instructions including the tap step.

Seems like your instructions are wrong.

🤷 according to opt-out homebrew stats, emacs+ was installed more than 1k times over the last 30 days.

brew install ***@***.*** --with-native-comp --with imagemagick

BTW, You forgot a dash in --with-imagemagick option.

**Comment by lewisl** [comment]
Tapped.  Successful install with options chosen.
