### ISSUE TITLE
404 error downloading bottle file

### ISSUE THREAD

**Issue by tjstankus** [d12frosted/homebrew-emacs-plus#6]
```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus
==> Installing emacs-plus from d12frosted/emacs-plus
==> Downloading https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-25.1.el_capitan.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "emacs-plus"
Download failed: https://homebrew.bintray.com/bottles-emacs-plus/emacs-plus-25.1.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

The build continued on and Emacs starts fine. Perhaps because of this error I just got the base GNU Emacs install without the "plus" features?

**Comment by d12frosted** [comment]
It's OK to ignore 404 error. There are no `plus` features except for icon 😸 please refer to [readme](https://github.com/d12frosted/homebrew-emacs-plus#emacs-plus) file.

**Comment by edrex** [comment]
AFAIK there's no fallback relationship with the homebrew/core emacs. 

This tap doesn't have a bottle - the listed bottles are left over from the core formula - so you'll always get a source build. 

Is that all correct?

It looks like the homebrew team is recommending installing an https://emacsformacosx.com/ build via `brew cask install emacs` going forward.

**Comment by wadkar** [comment]
/subscribe

Also see my comment [here](https://github.com/syl20bnr/spacemacs/issues/7928#issuecomment-282335014).

**Comment by d12frosted** [comment]
Fixed for Sierra. Ideally it should be automated, but at least now you can use bottled version if you use the same operating system as me 😸 In case someone wants to provide bottles for previous versions of macOS, I will be glad to help you with bottle building. Just write me a note. 

```
brew install Formula/emacs-plus.rb
Updating Homebrew...
[==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
byobu                                                lean-cli                                             lldpd

==> Downloading https://github.com/d12frosted/brew-bottles-emacs-plus/raw/master/emacs-plus-25.1.sierra.bottle.5.tar.gz
==> Downloading from https://media.githubusercontent.com/media/d12frosted/brew-bottles-emacs-plus/master/emacs-plus-25.1.sierra.bottle.5.tar.gz
######################################################################## 100.0%
==> Pouring emacs-plus-25.1.sierra.bottle.5.tar.gz
==> Caveats
To have launchd start emacs-plus now and restart at login:
  brew services start emacs-plus
Or, if you don't want/need a background service you can just run:
  emacs
==> Summary
🍺  /usr/local/Cellar/emacs-plus/25.1: 4,046 files, 120.4MB
  ~> duration: 40242 ms                                     
```
