### ISSUE TITLE
<f20> keypress registers as C-p

### ISSUE THREAD

**Issue by chrchr** [d12frosted/homebrew-emacs-plus#60]
Hi! I map a key on my keyboard to `<f20>` using Karabiner-Elements, for use in Emacs. In emacs-plus, pressing `<f20>` moves the point up one line. Sure enough, `C-h k <f20>` reveals says that the keypress was `C-p`, bound to `(previous-line)`. In emacs-mac, `<f20>` works correctly.

Thank you!

**Comment by d12frosted** [comment]
Sorry, I don't know what's wrong here. And I don't think I'll ever dig into this issue. Though if you (or anyone else) submits PR, I'll consider merging it.

**Comment by d12frosted** [comment]
Ideally, this issue should be fixed in Emacs. But in case someone fetches the patch for this, I am happy to apply it from the formula automatically(?).

**Comment by d12frosted** [comment]
Closing this issue as it's out of scope of this repo and for lack of activity. Let me know if you have any objections 😸
