### ISSUE TITLE
Could not install with [OPTIONS]

### ISSUE THREAD

**Issue by shervinsafavi** [d12frosted/homebrew-emacs-plus#601]
Please make sure to follow these steps (and mark the checkboxes):

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I successfully installed Emacs 29 (without any error), but when run Emacs in the terminal just open the terminal option (as if I use emacs -nw). So, there is no GUI version! Do we have any clue what happened to the GUI?

## What happened (include command output)

<pre>
$ brew install emacs
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  Fetching emacs
==> Downloading https://ghcr.io/v2/homebrew/core/emacs/manifests/29.1_1
Already downloaded: /home/ssafavi/.cache/Homebrew/downloads/ec21cdac3ceab711b3f304d28441ef187396fa7d07819b76a3fa763901b172bf--emacs-29.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/emacs/blobs/sha256:86ae488bbc7b
Already downloaded: /home/ssafavi/.cache/Homebrew/downloads/c002dd1a0649138ced4c84be125dc3ce79f0f4057b3d6b171b9ff18c68d31348--emacs--29.1_1.x86_64_linux.bottle.tar.gz
==> Pouring emacs--29.1_1.x86_64_linux.bottle.tar.gz
==> Caveats
To start emacs now and restart at login:
  brew services start emacs
Or, if you don't want/need a background service you can just run:
  /home/linuxbrew/.linuxbrew/opt/emacs/bin/emacs --fg-daemon
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/emacs/29.1_1: 4,226 files, 119.9MB
==> Running `brew cleanup emacs`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`)
  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 4.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8b46501e4caa1cad75b30627c123127ab09a6a7
Last commit: 2 days ago
Core tap JSON: 15 Aug 19:03 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 16-core 64-bit unknown_0x6_0xba
Clang: N/A
Git: 2.41.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.0.0-1020-oem x86_64 GNU/Linux
OS: Ubuntu 22.04.1 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by d1egoaz** [comment]
I guess you just installed the emacs formula not the `emacs-plus`, which can be installed via:

https://github.com/d12frosted/homebrew-emacs-plus#install

**Comment by shervinsafavi** [comment]
Thanks for your hint. You were right, but trying that led to another error which was discussed in [another issue](https://github.com/d12frosted/homebrew-emacs-plus/issues/565) . I tried the solution explained there, i.e., installing without cocoa (e.g. --without-cocoa), but that also didn't work.  So ended up with different solutions.
