### ISSUE TITLE
another new icon

### ISSUE THREAD

**Issue by compufox** [d12frosted/homebrew-emacs-plus#604]
i've been using a custom icon for emacs on my personal machine and thought it might be fun to see it included directly in the formula

here's the link to the icon, please let me know if you need anything else!

https://github.com/compufox/skamacs-icon

**Comment by compufox** [comment]
no worries!

**Comment by d12frosted** [comment]
The new icon should be released once #617 is merged.

In addition, I've [documented the process of adding a new icon](https://github.com/d12frosted/homebrew-emacs-plus/commit/cddeddef4a9a6e990efb6af459166c02ac3041d7) as I forgot it myself 😂

**Comment by d12frosted** [comment]
P.S. @daviderestivo you might be interested in docs and the icon itself 😅

**Comment by daviderestivo** [comment]
> P.S. @daviderestivo you might be interested in docs and the icon itself 😅

Thanks :)
