### ISSUE TITLE
DBus Error?

### ISSUE THREAD

**Issue by summeremacs** [d12frosted/homebrew-emacs-plus#606]
Hi again! I just posted in another issue but this one is totally different so I'll report it here.

As I said, I recently installed d12frosted. I installed it with dbus because I wanted to get notifications to work. I installed dbus with brew and started the service.
However, I get the following error from Emacs quite often:

Notification error: (dbus-error "No connection to bus" :session)

(Totally random thing: You know you're an Emacs user when you often hit Command-Y in MacOS by mistake to paste.... 😐)

Anyway, after investigating, I noticed that brew services has dbus listed as stopped. I can stop it properly, start it (and it says it has started) and then it still lists it as stopped. I thought this might be an emacs issue but it's probably a mac brew issue.

However:

I'm wondering if I should recompile without dbus? I spoke to Alphapapa this morning in matrix and he said that dbus is probably not what I want on the Mac and I should try another way for notifications. So I'm wondering if I should just do without Dbus? Or is there a simple fix you happen to know of, even if this probably isn't related to your emacs build?

Sorry if I sound random and stuff. I'm still learning a lot of this and I just wanted to ask since I like things to be tidy. 🙃

**Comment by summeremacs** [comment]
Oh! I thought the project was ALSO referred to as d12frosted! (see how new I am sometimes?? I'm so sorry!)

Ok, thank you for your help! I'm going to recompile/reinstall it later today when I have time without dbus. I really appreciate all of the help and sujpport. And I really love this project. BTW, other than that, I haven't really had issues with 30 at all so I'm super happy about it, FYI. 😀

Oh and since I just started playing D&D recently thanks to an online friend, I love the name d12frosted. It's really awesome.

**Comment by d12frosted** [comment]
Ah, just realised that homebrew stopped providing analytics on args usage. So I don't know anymore how often any of the available arguments are used 😓 In any case, I still believe that removing dbus makes sense.

> Oh! I thought the project was ALSO referred to as d12frosted! (see how new I am sometimes?? I'm so sorry!)

No worries :) 

> And I really love this project. BTW, other than that, I haven't really had issues with 30 at all so I'm super happy about it, FYI. 

Well, the credit is to GNU Emacs team. I am just supporting a formula to build GNU Emacs on macos and nothing more.

> Oh and since I just started playing D&D recently thanks to an online friend, I love the name d12frosted. It's really awesome.

Glad you like it 😸 Somehow it stick with me, so I even asked an illustrator to create a 'logo' for me. You can see it on d12frosted.io

P.S. Closing the ticket as there is nothing to do from my side.

**Comment by d12frosted** [comment]
I just realised that I don't fully understand this one:

>  I spoke to Alphapapa this morning in matrix

Are you talking about matrix.org? It feels like Alphapapa is everywhere and has an infinite amount of time haha
