### ISSUE TITLE
Odd error messages about stashed changes on brew update & upgrade commands

### ISSUE THREAD

**Issue by peterdimou** [d12frosted/homebrew-emacs-plus#61]
I run `brew update` and `brew upgrade` regularly. I noticed yesterday that these commands started giving me strange errors related to this repo. Here is the message I'm getting:

```
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
could not detach HEAD
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus run:
  'cd /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus && git stash pop'
```

Not sure if it's related to the commits made recently, or if this is a homebrew error that should be reported to their repo. If that's the case just let me know and I'll post the issue over there. Thanks!

**Comment by d12frosted** [comment]
Thanks for the report! 

It's due to the fact that I've added a screenshot to LFS. I'll try to fix it ASAP.

**Comment by d12frosted** [comment]
Could you please try again?

**Comment by peterdimou** [comment]
```bash
$ brew update
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus run:
  'cd /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus && git stash pop'
Updated 1 tap (d12frosted/emacs-plus).
No changes to formulae.
$ brew update
Already up-to-date.
$ brew upgrade
```

Everything looks good to me! Thank you for fixing the issue and the quick turnaround time!

**Comment by d12frosted** [comment]
Great! Glad that it works now. Sorry for the breakage. Forgot that LFS is not bundled with macOS.
