### ISSUE TITLE
[low prio] [feature inquiry] Performance CFLAGS (-O2, -march=native, etc.) 

### ISSUE THREAD

**Issue by stradicat** [d12frosted/homebrew-emacs-plus#614]
Hi!

I've noticed that `emacs-plus` is built by default with `-Os`, which tries to minimize code size while optimizing towards `-O2` level.

However, since the hardware where Homebrew runs has large-ish cache sizes (oldest officially BigSur-compatible machines have 256kb of L2 & 3Mb of L3 caches, like the 2013 11-inch MacBook Air), is there a specific reason not to go with `-O2`? (At least when building `--with-native-compilation`)
I was also wondering if adding `-march=native` would make sense, since the formula is compiled on the destination machine anyway.

For comparison, the following options are enabled on Linux builds of Emacs: (Ubuntu case, _kelleyk_ PPA)

`CFLAGS="-pipe -O2 -flto=auto -ffat-lto-objects -fstack-protector-strong"`
`CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2"`
`LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro"`

**Comment by d12frosted** [comment]
Hey @stradicat 

Thanks for raising this question. To be honest, Emacs+ doesn't do anything special with `O` flags. You can check [the source code of the formula](https://github.com/d12frosted/homebrew-emacs-plus/blob/4a9d9d7fbda87ab40fffa62610b449b5fd038bc7/Formula/emacs-plus%4030.rb#L111). So we are using whatever Emacs build tools are using.

> is there a specific reason not to go with `-O2`?

There is no specific reason 😄 So it would be a nice contribution.

> I was also wondering if adding `-march=native` would make sense, since the formula is compiled on the destination machine anyway.

Not aware of this flag. What does it do? If my intuitive understanding is correct, it's OK to add this for cocoa flag ([some people use Emacs+ on Lunux](https://github.com/d12frosted/homebrew-emacs-plus/issues/565)).

**Comment by stradicat** [comment]
Thanks for looking into this!

In Linux packages, `-O2` is a commonly used optimization flag for Emacs compilation, which optimizes space-speed tradeoff; the resulting compiled executable runs a bit faster than `-Os` (optimized for code size, same as _emacs-plus_), and it's more noticeable on older machines (I'm still using an Intel Mac with OpenCore Legacy Patcher, and I also compile Emacs from source on some i386 PCs).
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

Since _emacs-plus_ is compiled from source and the host machine is its own target, throwing in `-march=native` enables/disables optimization flags for the host's own CPU architecture, more often than not improving execution speed by a margin.

Taking into account that Emacs is an interpreter, above all, this can give it a performance edge.

What do you think?

**Comment by stradicat** [comment]
Better yet: I'll run some measurements and come back with a PR.

**Comment by d12frosted** [comment]
> What do you think?

What you say makes total sense. So I will be happy to see your PR 😸 

P.S. Thanks for explanations 🙏

**Comment by stradicat** [comment]
Closing since #698 was accepted :)
