### ISSUE TITLE
Mac M2: Could not install with   29.0.90 -> 29.1 --with-xwidgets --with-no-frame-refocus --with-native-comp --with-poll --with-imagemagick --with-mailutils --with-modern-pen-icon

### ISSUE THREAD

**Issue by neuhalje** [d12frosted/homebrew-emacs-plus#615]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Upgrade with `brew upgrade`. This has been working splendidly the past few times.

## What happened (include command output)

Applying `no-frame-refocus-cocoa.patch` leads to `out of memory` (see [here](#error-here)).

<details>
  <summary>Command output: Paths and  tools</summary>
  <pre>
PATH value was changed to:
/opt/homebrew/opt/make/libexec/gnubin
/opt/homebrew/opt/autoconf/libexec/gnubin
/opt/homebrew/opt/gnu-sed/libexec/gnubin
/opt/homebrew/opt/gnu-tar/libexec/gnubin
/opt/homebrew/opt/grep/libexec/gnubin
/opt/homebrew/opt/awk/libexec/gnubin
/opt/homebrew/opt/coreutils/libexec/gnubin
/opt/homebrew/opt/pkg-config/libexec/gnubin
/opt/homebrew/opt/texinfo/libexec/gnubin
/opt/homebrew/opt/xz/libexec/gnubin
/opt/homebrew/opt/gnutls/libexec/gnubin
/opt/homebrew/opt/librsvg/libexec/gnubin
/opt/homebrew/opt/little-cms2/libexec/gnubin
/opt/homebrew/opt/jansson/libexec/gnubin
/opt/homebrew/opt/tree-sitter/libexec/gnubin
/opt/homebrew/opt/imagemagick/libexec/gnubin
/opt/homebrew/Cellar/dbus/1.14.10/libexec/gnubin
/opt/homebrew/opt/mailutils/libexec/gnubin
/opt/homebrew/opt/make/bin
/opt/homebrew/opt/autoconf/bin
/opt/homebrew/opt/gnu-sed/bin
/opt/homebrew/opt/gnu-tar/bin
/opt/homebrew/opt/grep/bin
/opt/homebrew/opt/awk/bin
/opt/homebrew/opt/coreutils/bin
/opt/homebrew/opt/pkg-config/bin
/opt/homebrew/opt/texinfo/bin
/opt/homebrew/opt/xz/bin
/opt/homebrew/opt/gnutls/bin
/opt/homebrew/opt/librsvg/bin
/opt/homebrew/opt/little-cms2/bin
/opt/homebrew/opt/jansson/bin
/opt/homebrew/opt/tree-sitter/bin
/opt/homebrew/opt/imagemagick/bin
/opt/homebrew/opt/dbus/bin
/opt/homebrew/opt/mailutils/bin
/opt/homebrew/Library/Homebrew/shims/shared
/usr/bin
/bin
/usr/sbin
/sbin
==> which tar
/opt/homebrew/opt/gnu-tar/libexec/gnubin/tar
==> which ls
/opt/homebrew/opt/coreutils/libexec/gnubin/ls
==> which grep
/opt/homebrew/opt/grep/libexec/gnubin/grep

  </pre>
</details>

<details>
  <summary>Command output: Download</summary>
  <pre>
==> Upgrading 1 outdated package:
d12frosted/emacs-plus/emacs-plus@29 29.0.90 -> 29.1
==> Fetching d12frosted/emacs-plus/emacs-plus@29
==> Verifying checksum for 'fix-window-role.patch'
==> Verifying checksum for 'system-appearance.patch'
==> Verifying checksum for 'round-undecorated-frame.patch'
==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-29.1.tar.xz
Already downloaded: /Users/jens/Library/Caches/Homebrew/downloads/e393f4155dcd133ba019e0e966ab106a7d2d7b3f0fc0bc290044c067309a0c06--emacs-29.1.tar.xz
==> Verifying checksum for 'e393f4155dcd133ba019e0e966ab106a7d2d7b3f0fc0bc290044c067309a0c06--emacs-29.1.tar.xz'
  </pre>
</details>

<details>
  <summary>Command output: Upgrading (boring)</summary>
  <pre>
==> Upgrading d12frosted/emacs-plus/emacs-plus@29
  29.0.90 -> 29.1 --with-xwidgets --with-no-frame-refocus --with-native-comp --with-poll --with-imagemagick --with-mailutils --with-modern-pen-icon

rm /opt/homebrew/bin/ebrowse
rm /opt/homebrew/bin/emacs
rm /opt/homebrew/bin/emacs-29.0.91
rm /opt/homebrew/bin/emacsclient
rm /opt/homebrew/bin/etags
rm /opt/homebrew/include/emacs-module.h
rm /opt/homebrew/lib/emacs
rm /opt/homebrew/lib/systemd
rm /opt/homebrew/share/applications/emacs-mail.desktop
rm /opt/homebrew/share/applications/emacs.desktop
rm /opt/homebrew/share/applications/emacsclient-mail.desktop
rm /opt/homebrew/share/applications/emacsclient.desktop
rm /opt/homebrew/share/emacs/29.0.91
rm /opt/homebrew/share/emacs/site-lisp/subdirs.el
rm /opt/homebrew/share/icons/hicolor/128x128/apps/emacs.png
rm /opt/homebrew/share/icons/hicolor/16x16/apps/emacs.png
rm /opt/homebrew/share/icons/hicolor/24x24/apps/emacs.png
rm /opt/homebrew/share/icons/hicolor/32x32/apps/emacs.png
rm /opt/homebrew/share/icons/hicolor/48x48/apps/emacs.png
rm /opt/homebrew/share/icons/hicolor/scalable/apps/emacs.ico
rm /opt/homebrew/share/icons/hicolor/scalable/apps/emacs.svg
rm /opt/homebrew/share/icons/hicolor/scalable/mimetypes/emacs-document.svg
rm /opt/homebrew/share/icons/hicolor/scalable/mimetypes/emacs-document23.svg
rm /opt/homebrew/share/info/emacs
rm /opt/homebrew/share/man/man1/ebrowse.1
rm /opt/homebrew/share/man/man1/emacs.1
rm /opt/homebrew/share/man/man1/emacsclient.1
rm /opt/homebrew/share/man/man1/etags.1
rm /opt/homebrew/share/metainfo
PATH value was changed to:
/opt/homebrew/opt/make/libexec/gnubin
/opt/homebrew/opt/autoconf/libexec/gnubin
/opt/homebrew/opt/gnu-sed/libexec/gnubin
/opt/homebrew/opt/gnu-tar/libexec/gnubin
/opt/homebrew/opt/grep/libexec/gnubin
/opt/homebrew/opt/awk/libexec/gnubin
/opt/homebrew/opt/coreutils/libexec/gnubin
/opt/homebrew/opt/pkg-config/libexec/gnubin
/opt/homebrew/opt/texinfo/libexec/gnubin
/opt/homebrew/opt/xz/libexec/gnubin
/opt/homebrew/opt/gnutls/libexec/gnubin
/opt/homebrew/opt/librsvg/libexec/gnubin
/opt/homebrew/opt/little-cms2/libexec/gnubin
/opt/homebrew/opt/jansson/libexec/gnubin
/opt/homebrew/opt/tree-sitter/libexec/gnubin
/opt/homebrew/opt/imagemagick/libexec/gnubin
/opt/homebrew/Cellar/dbus/1.14.10/libexec/gnubin
/opt/homebrew/opt/mailutils/libexec/gnubin
/opt/homebrew/opt/make/bin
/opt/homebrew/opt/autoconf/bin
/opt/homebrew/opt/gnu-sed/bin
/opt/homebrew/opt/gnu-tar/bin
/opt/homebrew/opt/grep/bin
/opt/homebrew/opt/awk/bin
/opt/homebrew/opt/coreutils/bin
/opt/homebrew/opt/pkg-config/bin
/opt/homebrew/opt/texinfo/bin
/opt/homebrew/opt/xz/bin
/opt/homebrew/opt/gnutls/bin
/opt/homebrew/opt/librsvg/bin
/opt/homebrew/opt/little-cms2/bin
/opt/homebrew/opt/jansson/bin
/opt/homebrew/opt/tree-sitter/bin
/opt/homebrew/opt/imagemagick/bin
/opt/homebrew/opt/dbus/bin
/opt/homebrew/opt/mailutils/bin
/opt/homebrew/Library/Homebrew/shims/shared
/usr/bin
/bin
/usr/sbin
/sbin
==> which tar
/opt/homebrew/opt/gnu-tar/libexec/gnubin/tar
==> which ls
/opt/homebrew/opt/coreutils/libexec/gnubin/ls
==> which grep
/opt/homebrew/opt/grep/libexec/gnubin/grep
rmdir /opt/homebrew/share/icons/hicolor/scalable/mimetypes
PATH value was changed to:
/opt/homebrew/opt/make/libexec/gnubin
/opt/homebrew/opt/autoconf/libexec/gnubin
/opt/homebrew/opt/gnu-sed/libexec/gnubin
/opt/homebrew/opt/gnu-tar/libexec/gnubin
/opt/homebrew/opt/grep/libexec/gnubin
/opt/homebrew/opt/awk/libexec/gnubin
/opt/homebrew/opt/coreutils/libexec/gnubin
/opt/homebrew/opt/pkg-config/libexec/gnubin
/opt/homebrew/opt/texinfo/libexec/gnubin
/opt/homebrew/opt/xz/libexec/gnubin
/opt/homebrew/opt/gnutls/libexec/gnubin
/opt/homebrew/opt/librsvg/libexec/gnubin
/opt/homebrew/opt/little-cms2/libexec/gnubin
/opt/homebrew/opt/jansson/libexec/gnubin
/opt/homebrew/opt/tree-sitter/libexec/gnubin
/opt/homebrew/opt/imagemagick/libexec/gnubin
/opt/homebrew/Cellar/dbus/1.14.10/libexec/gnubin
/opt/homebrew/opt/mailutils/libexec/gnubin
/opt/homebrew/opt/make/bin
/opt/homebrew/opt/autoconf/bin
/opt/homebrew/opt/gnu-sed/bin
/opt/homebrew/opt/gnu-tar/bin
/opt/homebrew/opt/grep/bin
/opt/homebrew/opt/awk/bin
/opt/homebrew/opt/coreutils/bin
/opt/homebrew/opt/pkg-config/bin
/opt/homebrew/opt/texinfo/bin
/opt/homebrew/opt/xz/bin
/opt/homebrew/opt/gnutls/bin
/opt/homebrew/opt/librsvg/bin
/opt/homebrew/opt/little-cms2/bin
/opt/homebrew/opt/jansson/bin
/opt/homebrew/opt/tree-sitter/bin
/opt/homebrew/opt/imagemagick/bin
/opt/homebrew/opt/dbus/bin
/opt/homebrew/opt/mailutils/bin
/opt/homebrew/Library/Homebrew/shims/shared
/usr/bin
/bin
/usr/sbin
/sbin
==> which tar
/opt/homebrew/opt/gnu-tar/libexec/gnubin/tar
==> which ls
/opt/homebrew/opt/coreutils/libexec/gnubin/ls
==> which grep
/opt/homebrew/opt/grep/libexec/gnubin/grep
PATH value was changed to:
/opt/homebrew/opt/make/libexec/gnubin
/opt/homebrew/opt/autoconf/libexec/gnubin
/opt/homebrew/opt/gnu-sed/libexec/gnubin
/opt/homebrew/opt/gnu-tar/libexec/gnubin
/opt/homebrew/opt/grep/libexec/gnubin
/opt/homebrew/opt/awk/libexec/gnubin
/opt/homebrew/opt/coreutils/libexec/gnubin
/opt/homebrew/opt/pkg-config/libexec/gnubin
/opt/homebrew/opt/texinfo/libexec/gnubin
/opt/homebrew/opt/xz/libexec/gnubin
/opt/homebrew/opt/gnutls/libexec/gnubin
/opt/homebrew/opt/librsvg/libexec/gnubin
/opt/homebrew/opt/little-cms2/libexec/gnubin
/opt/homebrew/opt/jansson/libexec/gnubin
/opt/homebrew/opt/tree-sitter/libexec/gnubin
/opt/homebrew/opt/imagemagick/libexec/gnubin
/opt/homebrew/Cellar/dbus/1.14.10/libexec/gnubin
/opt/homebrew/opt/mailutils/libexec/gnubin
/opt/homebrew/opt/libgccjit/libexec/gnubin
/opt/homebrew/opt/gcc/libexec/gnubin
/opt/homebrew/opt/gmp/libexec/gnubin
/opt/homebrew/opt/jpeg/libexec/gnubin
/opt/homebrew/opt/zlib/libexec/gnubin
/opt/homebrew/opt/make/bin
/opt/homebrew/opt/autoconf/bin
/opt/homebrew/opt/gnu-sed/bin
/opt/homebrew/opt/gnu-tar/bin
/opt/homebrew/opt/grep/bin
/opt/homebrew/opt/awk/bin
/opt/homebrew/opt/coreutils/bin
/opt/homebrew/opt/pkg-config/bin
/opt/homebrew/opt/texinfo/bin
/opt/homebrew/opt/xz/bin
/opt/homebrew/opt/gnutls/bin
/opt/homebrew/opt/librsvg/bin
/opt/homebrew/opt/little-cms2/bin
/opt/homebrew/opt/jansson/bin
/opt/homebrew/opt/tree-sitter/bin
/opt/homebrew/opt/imagemagick/bin
/opt/homebrew/opt/dbus/bin
/opt/homebrew/opt/mailutils/bin
/opt/homebrew/opt/libgccjit/bin
/opt/homebrew/opt/gcc/bin
/opt/homebrew/opt/gmp/bin
/opt/homebrew/opt/jpeg/bin
/opt/homebrew/opt/zlib/bin
/opt/homebrew/Library/Homebrew/shims/shared
/usr/bin
/bin
/usr/sbin
/sbin
==> which tar
/opt/homebrew/opt/gnu-tar/libexec/gnubin/tar
==> which ls
/opt/homebrew/opt/coreutils/libexec/gnubin/ls
==> which grep
/opt/homebrew/opt/grep/libexec/gnubin/grep
/usr/bin/env tar --extract --no-same-owner --file /Users/jens/Library/Caches/Homebrew/downloads/e393f4155dcd133ba019e0e966ab106a7d2d7b3f0fc0bc290044c067309a0c06--emacs-29.1.tar.xz --directory /private/tmp/d20230921-7858-quj7o0
/usr/bin/env cp -pR /private/tmp/d20230921-7858-quj7o0/emacs-29.1/. /private/tmp/emacs-plusA29-20230921-7858-1dic5so/emacs-29.1
  </pre>
</details>

<details id="error-here">
  <summary>Command output: Patching (<b>Error here</b>)</summary>
  <pre>
==> Patching
cp -p /opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/patches/emacs-29/no-frame-refocus-cocoa.patch /private/tmp/emacs-plusA29--patch-20230921-7858-1bbvtgp/no-frame-refocus-cocoa.patch
==> Applying no-frame-refocus-cocoa.patch
patch -g 0 -f -p1 -i /private/tmp/emacs-plusA29--patch-20230921-7858-1bbvtgp/no-frame-refocus-cocoa.patch
patch: **** out of memory
  </pre>
</details>

<details>
  <summary>Command output: Installing</summary>
  <pre>
ln -s ../Cellar/emacs-plus@29/29.0.90/bin/ebrowse ebrowse
ln -s ../Cellar/emacs-plus@29/29.0.90/bin/emacs emacs
ln -s ../Cellar/emacs-plus@29/29.0.90/bin/emacs-29.0.91 emacs-29.0.91
ln -s ../Cellar/emacs-plus@29/29.0.90/bin/emacsclient emacsclient
ln -s ../Cellar/emacs-plus@29/29.0.90/bin/etags etags
ln -s ../Cellar/emacs-plus@29/29.0.90/include/emacs-module.h emacs-module.h
ln -s ../../Cellar/emacs-plus@29/29.0.90/share/applications/emacs-mail.desktop emacs-mail.desktop
ln -s ../../Cellar/emacs-plus@29/29.0.90/share/applications/emacs.desktop emacs.desktop
ln -s ../../Cellar/emacs-plus@29/29.0.90/share/applications/emacsclient-mail.desktop emacsclient-mail.desktop
ln -s ../../Cellar/emacs-plus@29/29.0.90/share/applications/emacsclient.desktop emacsclient.desktop
ln -s ../../Cellar/emacs-plus@29/29.0.90/share/emacs/29.0.91 29.0.91
ln -s ../../../Cellar/emacs-plus@29/29.0.90/share/emacs/site-lisp/subdirs.el subdirs.el
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/128x128/apps/emacs.png emacs.png
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/16x16/apps/emacs.png emacs.png
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/24x24/apps/emacs.png emacs.png
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/32x32/apps/emacs.png emacs.png
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/48x48/apps/emacs.png emacs.png
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/scalable/apps/emacs.ico emacs.ico
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/scalable/apps/emacs.svg emacs.svg
mkdir -p /opt/homebrew/share/icons/hicolor/scalable/mimetypes
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/scalable/mimetypes/emacs-document.svg emacs-document.svg
ln -s ../../../../../Cellar/emacs-plus@29/29.0.90/share/icons/hicolor/scalable/mimetypes/emacs-document23.svg emacs-document23.svg
ln -s ../../Cellar/emacs-plus@29/29.0.90/share/info/emacs emacs
ln -s ../../../Cellar/emacs-plus@29/29.0.90/share/man/man1/ebrowse.1 ebrowse.1
ln -s ../../../Cellar/emacs-plus@29/29.0.90/share/man/man1/emacs.1 emacs.1
ln -s ../../../Cellar/emacs-plus@29/29.0.90/share/man/man1/emacsclient.1 emacsclient.1
ln -s ../../../Cellar/emacs-plus@29/29.0.90/share/man/man1/etags.1 etags.1
ln -s ../Cellar/emacs-plus@29/29.0.90/share/metainfo metainfo
ln -s ../Cellar/emacs-plus@29/29.0.90/lib/emacs emacs
ln -s ../Cellar/emacs-plus@29/29.0.90/lib/systemd systemd
  </pre>
</details>

<details>
  <summary>Command output: Formula and Configuration</summary>
  <pre>

==> Formula
Tap: d12frosted/emacs-plus
Path: /opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@29.rb
==> Configuration
HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 5 days ago
Core tap JSON: 21 Sep 16:29 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/jens/.oh-my-zsh/plugins/emacs/emacsclient.sh
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0
Rosetta 2: false
==> ENV
CC: /usr/bin/clang
CXX: /usr/bin/clang++
OBJC: /usr/bin/clang
OBJCXX: /usr/bin/clang++
CFLAGS: -Os -w -pipe  -mmacosx-version-min=13 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
CXXFLAGS: -Os -w -pipe  -mmacosx-version-min=13 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
CPPFLAGS: -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/jpeg/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/libomp/include -I/opt/homebrew/opt/icu4c/include -isystem/opt/homebrew/include -F/opt/homebrew/Frameworks -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
LDFLAGS: -L/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/jpeg/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/libomp/lib -L/opt/homebrew/opt/icu4c/lib -L/opt/homebrew/lib  -F/opt/homebrew/Frameworks -Wl,-headerpad_max_install_names -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
MAKEFLAGS: -j12
CMAKE_PREFIX_PATH: /opt/homebrew/opt/zlib:/opt/homebrew/opt/jpeg:/opt/homebrew/opt/readline:/opt/homebrew/opt/m4:/opt/homebrew/opt/libomp:/opt/homebrew/opt/icu4c:/opt/homebrew:/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr
CMAKE_FRAMEWORK_PATH: /opt/homebrew/Frameworks:/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /opt/homebrew/opt/zlib/share/pkgconfig:/opt/homebrew/opt/zlib/lib/pkgconfig:/opt/homebrew/opt/jpeg/share/pkgconfig:/opt/homebrew/opt/jpeg/lib/pkgconfig:/opt/homebrew/opt/readline/share/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/m4/share/pkgconfig:/opt/homebrew/opt/m4/lib/pkgconfig:/opt/homebrew/opt/libomp/share/pkgconfig:/opt/homebrew/opt/libomp/lib/pkgconfig:/opt/homebrew/opt/icu4c/share/pkgconfig:/opt/homebrew/opt/icu4c/lib/pkgconfig
PKG_CONFIG_LIBDIR: /opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13:/usr/lib/pkgconfig
HOMEBREW_GIT: git
ACLOCAL_PATH: /opt/homebrew/opt/zlib/share/aclocal:/opt/homebrew/opt/jpeg/share/aclocal:/opt/homebrew/opt/readline/share/aclocal:/opt/homebrew/opt/m4/share/aclocal:/opt/homebrew/opt/libomp/share/aclocal:/opt/homebrew/opt/icu4c/share/aclocal
PATH: /opt/homebrew/opt/zlib/bin:/opt/homebrew/opt/jpeg/bin:/opt/homebrew/opt/readline/bin:/opt/homebrew/opt/m4/bin:/opt/homebrew/opt/libomp/bin:/opt/homebrew/opt/icu4c/bin:/opt/homebrew/Library/Homebrew/shims/shared:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/kitty.app/Contents/MacOS:/opt/go/1.18.2/bin:/Users/jens/go/bin:/Users/jens/bin:/Users/jens/.local/bin:/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/opt/homebrew/opt/grep/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/make/bin:/opt/homebrew/opt/autoconf/bin:/opt/homebrew/opt/gnu-sed/bin:/opt/homebrew/opt/gnu-tar/bin:/opt/homebrew/opt/grep/bin:/opt/homebrew/opt/awk/bin:/opt/homebrew/opt/coreutils/bin:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/texinfo/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/gnutls/bin:/opt/homebrew/opt/librsvg/bin:/opt/homebrew/opt/little-cms2/bin:/opt/homebrew/opt/tree-sitter/bin:/opt/homebrew/opt/imagemagick/bin:/opt/homebrew/opt/mailutils/bin:/opt/homebrew/opt/gcc/bin:/usr/bin:/bin:/usr/sbin:/sbin
CPATH: /opt/homebrew/include:/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include
  </pre>
</details>

<details>
  <summary>Command output: Final Error message</summary>
  <pre>

Error: d12frosted/emacs-plus/emacs-plus@29 29.1 did not build
Logs:
     /Users/jens/Library/Logs/Homebrew/emacs-plus@29/02.which
     /Users/jens/Library/Logs/Homebrew/emacs-plus@29/03.which
     /Users/jens/Library/Logs/Homebrew/emacs-plus@29/01.which
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Could not install emacs-plus@29 https://github.com/d12frosted/homebrew-emacs-plus/issues/544
Could not install emacs-plus@29 with --with-xwidgets --with-imagemagick --with-native-comp https://github.com/d12frosted/homebrew-emacs-plus/issues/556

  </pre>
</details>

                   

## Output of `brew config`

<pre>
$ brew config

HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 5 days ago
Core tap JSON: 21 Sep 16:29 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/jens/.oh-my-zsh/plugins/emacs/emacsclient.sh
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by d12frosted** [comment]
Hey @neuhalje 

Does it still reproducible? I tried building on multiple machines and never encountered this error. Although I didn't get my hands on M2 yet. Just a wild guess, what is your system's ulimit?

**Comment by neuhalje** [comment]
Will check tomorrow, thanks for looking into it

**Comment by d12frosted** [comment]
🤔 You can try applying the patch manually outside of brew installation routine just to check if it works.

```
# cd to some working dir
mkdir emacs-plus-patch-apply-test && cd emacs-plus-patch-apply-test

# clone emacs mirror (⚠️ ⚠️ ⚠️ notice that we clone emacs-29 branch ⚠️ ⚠️ ⚠️ )
git clone --branch emacs-29 git@github.com:emacs-mirror/emacs.git

# clone emacs-plus
git clone --depth 1 git@github.com:d12frosted/homebrew-emacs-plus.git

# try to apply no-frame-refocus-cocoa.patch
cd emacs
git am ../homebrew-emacs-plus/patches/emacs-29/no-frame-refocus-cocoa.patch
```

**Comment by neuhalje** [comment]
Quick question ahead: when I run `brew install -d d12frosted/emacs-plus/emacs-plus@29` it ends with
```text
/usr/bin/env tar --extract --no-same-owner --file /Users/jens/Library/Caches/Homebrew/downloads/e393f4155dcd133ba019e0e966ab106a7d2d7b3f0fc0bc290044c067309a0c06--emacs-29.1.tar.xz --directory /private/tmp/d20231008-96310-1vava9t
/usr/bin/env cp -pR /private/tmp/d20231008-96310-1vava9t/emacs-29.1/. /private/tmp/emacs-plusA29-20231008-96310-1hxgvsk/emacs-29.1
==> Patching
==> Applying fix-window-role.patch
patch: **** out of memory
/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
BuildError: Failed executing: patch -g 0 -f -p1 -i /private/tmp/emacs-plusA29--patch-20231008-96310-1nxj47n/fix-window-role.patch

1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

When I open a shell in another window (prompt still displaying) the file  `/private/tmp/emacs-plusA29--patch-20231008-96310-1nxj47n/fix-window-role.patch` does not exist. No file named `fix-window-role.patch` exists under `/private/tmp/`.

Any idea why the file disappears?

**Comment by neuhalje** [comment]
## Test with `git am`

with the `git am` flow the patch applies flawlessly and I can reproduce the `OOM`

## Test with `patch`
```sh
~/tmp/emacs-plus-patch-apply-test/emacs emacs-29
❯ patch -g 0 -f -p1 -i ../homebrew-emacs-plus/patches/emacs-29/no-frame-refocus-cocoa.patch
patch: **** out of memory
```

### Patch Version
```sh
 which patch
/opt/homebrew/bin/patch

 patch --version
GNU patch 2.7.6
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert
```

**Comment by neuhalje** [comment]
*Solution*:
This seems to be a know bug in `patch` (GNU patch issue [#62958](https://savannah.gnu.org/bugs/?62958)).

```sh
> limit       
cputime         unlimited
filesize        unlimited
datasize        unlimited
stacksize       7MB
coredumpsize    0kB
addressspace    unlimited
memorylocked    unlimited
maxproc         5333
descriptors     unlimited
```

The "culprit" is `descriptors     unlimited`.  Setting it to a lower value makes install run through.

```sh
> ulimit -Sn 10240

> limit
cputime         unlimited
filesize        unlimited
datasize        unlimited
stacksize       7MB
coredumpsize    0kB
addressspace    unlimited
memorylocked    unlimited
maxproc         5333
descriptors     10240
```

**Comment by neuhalje** [comment]
Closing this as it is not an issue with this package and the breadcrumbs should be enough for the wary googler.

**Comment by d12frosted** [comment]
Oh wow. Glad you figured that out! And thank you for sharing the solution. 🎉
