### ISSUE TITLE
Add support for :stipple face attribute

### ISSUE THREAD

**Issue by jasonmj** [d12frosted/homebrew-emacs-plus#622]
In order to use the `indent-bars` package, support for the `:stipple` face attribute is required: 
https://github.com/jdtsmith/indent-bars#compatibility

Could `hombrew-emacs-plus` support this feature?

**Comment by d12frosted** [comment]
hey @jasonmj 

That sounds interesting. Ideally I try to keep Emacs+ as close to GNU Emacs as possible with a few notable exceptions. The question is where to draw the line. XWidgets is a kind of an experiment that I am not sure I would love to add today. But there are safe and quite simple extras that I see no harm in adding.

In general, I see value in adding `:stripple` support. The only issue - I am not familiar with Emacs sources, so I don't really know what needs to be done. After a quick googling, I found [a commit][1] in `emacs-mac` that added `:strippe` support. I haven't tried it yet, but maybe we can use it as a patch for GNU Emacs as well. Will play around with this idea later[^1].

Ideally, this support should come in GNU Emacs. I couldn't find relevant feature request for macOS specifically in the mailing list (although my search skills are not that good), so maybe you can start a new request.

Hope this makes sense 😅 

[1]: https://bitbucket.org/mituharu/emacs-mac/commits/25d1a744fc68eb8cd4e37443ac8ac3f7465f128e/raw

[^1]: Holy moly, I've promised to check so many things related to Emacs+ and I just can't find enough time to do everything, so don't trust me when I say 'I will'.

**Comment by d12frosted** [comment]
Closing this issue as out of scope of this project. Ideally it should be implemented in the upstream. Yet knowing darwin not being focus for upstream, I am still open to ideas.
