### ISSUE TITLE
How to find SHA for a new patch?

### ISSUE THREAD

**Issue by SreenivasVRao** [d12frosted/homebrew-emacs-plus#623]
Hi Boris - thanks for maintaining this brew recipe! I use it all the time. :) 

I'm interested in creating a patch based on https://github.com/emacs-lsp/emacs - at least for my own sandbox. 

I see https://github.com/d12frosted/homebrew-emacs-plus/pull/510/ for the `--with-poll` feature - and I can see it's pretty straightforward. 

However, I wasn't able to figure out how to get the SHA for the patch. Can you help explain?

**Comment by SreenivasVRao** [comment]
nvm - looks like I just run `sha256sum <filename of patch>` :)

**Comment by d12frosted** [comment]
@SreenivasVRao indeed, it's just a `sha256sum` of the file 😺 

I know you didn't ask, but I like to comment when I have something to share, so here we are 😅 

IMO using patch makes sense when it's easy to extract it and you want to apply on specific upstream commit/branch. In some cases (for example, when applying patches becomes messy) it's actually easier to change the link of the sources from emacs mirror to the fork:

https://github.com/d12frosted/homebrew-emacs-plus/blob/e8695a9e92b2a52cdbf702fd81c1b988eb123922/Formula/emacs-plus%4030.rb#L77

This way you'll be able to test the fork much faster. There is a risk that some of the Emacs+ patches fail to apply cleanly on that fork, but in a local copy you are free to roam and remove whatever doesn't play nice with the fork haha.

Enjoy!
