### ISSUE TITLE
Opening Tramp produces error in @30

### ISSUE THREAD

**Issue by NatHarari** [d12frosted/homebrew-emacs-plus#625]
I'm trying to do an C-x C-f to open up /ssh: and I get the following error (and it prevents me from connecting to server):

> [Error in pre-command-hook (vertico--prepare): (error "auth-source-netrc-parse-entries: Unexpected 'machine' token at line 2")]

The strange thing is that I have bookmarks already to other servers, and if I use those bookmarks, they work just fine. But I can't open a new /ssh: to another server.

I just upgraded to the latest version of 30 about 5 minutes ago so the version is: GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin23.1.0, NS appkit-2487.20 Version 14.1.1 (Build 23B81)) of 2023-11-09

**Comment by NatHarari** [comment]
Just a little update: There's an easy work around (naturally...this is Emacs, after all!). I'm posting this in case anyone else runs into this problem:

1) Open ~/.emacs.d/bookmarks
2) Copy a bookmark which you already have from another TRAMP bookmarked site
3) Change it to the new address/user/port
4) Save it

It'll ask you if you want to reload your bookmarks in the mini buffer. Say yes. Then it will work spectacularly well.

So: No real problems with it at the moment. Thanks for the great work BTW.

**Comment by d12frosted** [comment]
@NatHarari hey

First of all, I am happy you found a workaround. Secondly, not sure if it's the best place to discuss this kind of problems as it seems to be related to Emacs itself and not to the formula.

> Thanks for the great work BTW.

You should thank GNU Emacs developers 😄

**Comment by NatHarari** [comment]
Sorry about that. I wasn't certain if it was related or not. As per this thread I found, I thought that it might be:

https://github.com/doomemacs/doomemacs/issues/6445#issuecomment-1160396742

I apologize if I was in error.

**Comment by d12frosted** [comment]
I am still not sure how it's related to the formula (this is repository for a build recipe for homebrew and not for Emacs itself). That being said, don't worry :)

**Comment by NatHarari** [comment]
Yes, I can see that now. I suppose I was a bit confused and misread it. Please close this issue then. :)
