### ISSUE TITLE
Frame refocusing behavior is broken/inconsistent

### ISSUE THREAD

**Issue by brosasaki** [d12frosted/homebrew-emacs-plus#628]
emacs-plus@29 installed from Homebrew on MacOS 12.6.8; I use emacs in client/server mode with a script encosed in a dummy app which launches a new client frame.

Currently, the frame refocusing behavior (granted by avoiding the --with-no-refocus option) does not function consistently with other macOS apps.

In Firefox and Finder, "killing a frame" (OS "window") focuses the next frame in the workspace; if there's no frame in the workspace, keyboard focus remains with the "faceless" application*, e.g. if you open and close a lone Finder window and don't select another application, you can press cmd-t to open a new Finder window.

In emacs-plus@29, killing a frame focuses the last-made(?) emacs frame, switching to its workspace if necessary, even if other emacs frames exist on the current workspace. If there are no other emacs frames, focus is sent to the next app in the workspace (I think). This is inconsistent and rarely desired behavior.

*or perhaps the focus is sent to an "out of view" window on another space, if it exists? Pressing cmd-t after closing the only Firefox window in a space switches to the space of another firefox window , if it exists, and opens a new tab, (and cmd-l also switches spaces) but I'm not sure if this behavior is correct or intentional.

**Comment by ganesh-krishnan** [comment]
+1. I'm seeing the same thing. The refocus behavior is not consistent. Currently I'm still seeing it switch focus back to another Emacs frame on a different desktop. A couple of days ago, it would switch the active app to Emacs but not switch focus to the Emacs frame. Will post more details as I learn more.

**Comment by d12frosted** [comment]
I am pretty sure inconsistency comes from macos itself.

> In emacs-plus@29, killing a frame focuses the last-made(?) emacs frame, switching to its workspace if necessary, even if other emacs frames exist on the current workspace. If there are no other emacs frames, focus is sent to the next app in the workspace (I think). This is inconsistent and rarely desired behavior.

You can try toying with System Settings > Desktop & Dock > When switching to an application, switch to space with open windows for the application. Turn it off and you should not see that behaviour anymore.

![image](https://github.com/user-attachments/assets/b7b92050-97aa-47b9-ba6c-e97a4d4a8246)

**Comment by d12frosted** [comment]
Ah and we no longer have no-frame-refocus patch, so closing this.

**Comment by onetom** [comment]
This workaround doesn't seem to work on 
- _Tahoe 26.5 (25F71)_
- _GNU Emacs 32.0.50 (build 1, aarch64-apple-darwin25.3.0, NS appkit-2685.40 Version 26.3 (Build 25D125)) of 2026-05-19_

Emacs was installed with `brew install emacs-plus-app@master`.

I was able to reproduce the issue by opening and closing a new frame with `C-x 5 2`, `C-x 5 0` in an `emacs -Q` session.

It's reproducable on this nightly version too:
https://emacsformacosx.com/emacs-builds/Emacs-2026-05-27_00-09-58-b174382a2dfaf77af0709c0ad87ad8db9cc46dc7-universal.dmg

```shell
open -a /Applications/Emacs-2026-05-27_00-09-58-b174382a2dfaf77af0709c0ad87ad8db9cc46dc7.app --args -Q
```

So it's not an Emacs Plus issue, but I feel like these kinds of fixes are typically incubated in this fork.

**Comment by d12frosted** [comment]
if you find out the solution, we can figure out where it should land - here or in the upstream (and if needed, I can prepare patch to the upstream)

**Comment by perryprog** [comment]
I don't use emacs-plus but I got pointed to this issue by someone on IRC—it is an upstream issue; I've always worked around it with `(when window-system (x-focus-frame nil))` at the bottom of my init. Now that I know this isn't just a me-issue I'll go ahead and send in a patch to upstream fixing this.

Edit: [patch submitted](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=81683).
