### ISSUE TITLE
homebrew has deprecated some syntax

### ISSUE THREAD

**Issue by casouri** [d12frosted/homebrew-emacs-plus#65]
It gives me these warning when I try to install emacs.
```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
```
```
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
```

**Comment by d12frosted** [comment]
Hey @casouri, thanks for the report.

First warning should be already fixed. Will fix the second one.

**Comment by d12frosted** [comment]
Ok, I don't get where are getting the warning about `python` from. Are you sure it was from `emacs-plus`? There is no direct dependency on `python`.

**Comment by casouri** [comment]
My bad! Even though I updated homebrew it's still trying to update other taps and print errors. It's not emacs-plus.😅

**Comment by d12frosted** [comment]
No problem 😸 Anyway, thanks for reaching me out regarding these warnings :)
