### ISSUE TITLE
Could not install emacs@30 in macos M1

### ISSUE THREAD

**Issue by vinurs** [d12frosted/homebrew-emacs-plus#652]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do
install emacs@30
## What happened (include command output)

<pre>
$ brew install emacs-plus@30 --with-dbus --with-debug --with-mailutils --with-elrumo2-icon --with-imagemagick --with-xwidgets --with-poll
</pre>

<details>

  <pre>

brew install emacs-plus@30 --with-dbus --with-debug --with-mailutils --with-elrumo2-icon --with-imagemagick --with-xwidgets --with-poll
==> Downloading https://formulae.brew.sh/api/formula.jws.json
###################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
###################################################################################### 100.0%
==> Fetching d12frosted/emacs-plus/emacs-plus@30
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/vinurs/Library/Caches/Homebrew/emacs-plus@30--git
From https://github.com/emacs-mirror/emacs
   18de131222e..e2be1987a2e  master     -> origin/master
==> Checking out branch master
Previous HEAD position was 6abea4d98d1 Fix typo in commit 3c093148958d56e0ed8e12a8e00ced1ef052259a
Switched to branch 'master'
Your branch is behind 'origin/master' by 12 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at e2be1987a2e ; Fix a crash in sfnt_read_fvar_table
==> Installing emacs-plus@30 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file 'src/nsterm.m'
==> Applying system-appearance.patch
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.m'
==> Applying poll.patch
patching file configure.ac
patching file 'src/nsterm.m'
patching file 'src/process.c'
patching file 'src/sysdep.c'
patching file 'src/syspoll.h'
patching file 'src/sysselect.h'
==> Applying round-undecorated-frame.patch
patching file 'src/frame.c'
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.h'
patching file 'src/nsterm.m'
==> ImageMagick PKG_CONFIG_PATH:
/opt/homebrew/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --disable-silent-rules --enable-locallisppath=/opt/homebrew/share/emacs/site-
==> gmake
Last 15 lines from /Users/vinurs/Library/Logs/Homebrew/emacs-plus@30/03.gmake:
gmake[2]: Leaving directory '/private/tmp/emacs-plusA30-20240108-12173-6rxsrj/lisp'
gmake[1]: *** [Makefile:537: lisp] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA30-20240108-12173-6rxsrj'
gmake[1]: Entering directory '/private/tmp/emacs-plusA30-20240108-12173-6rxsrj'
***
*** "make all" failed with exit status 2.
***
*** You could try to:
*** - run "make bootstrap", which might fix the problem
*** - run "make V=1", which displays the full commands invoked by make,
***   to further investigate the problem
***
gmake[1]: *** [Makefile:418: advice-on-failure] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA30-20240108-12173-6rxsrj'
gmake: *** [Makefile:374: all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues
  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 4.2.2-29-gb3751bc
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6
Last commit: 9 hours ago
Core tap HEAD: 2e5a1cad52074ef53f1ae1b73c47dafa5e1f93ad
Core tap last commit: 46 minutes ago
Core tap JSON: 08 Jan 09:18 UTC
Core cask tap HEAD: 2a20819d19fa9bee05857a52539a8c230785144e
Core cask tap last commit: 54 minutes ago
Core cask tap JSON: 08 Jan 09:18 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.1
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  adoptopenjdk8
  kindle

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  alerter
  exa
  fasd
  gpm
  openssl@1.1

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

</pre>

**Comment by vinurs** [comment]
```
brew install --verbose emacs-plus@30 --with-dbus --with-debug --with-mailutils --with-elrumo2-icon --with-imagemagick --with-xwidgets --with-poll > error.log
/usr/bin/env git config remote.origin.url https://github.com/emacs-mirror/emacs.git
/usr/bin/env git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
/usr/bin/env git config remote.origin.tagOpt --no-tags
/usr/bin/env git config advice.detachedHead false
/usr/bin/env git config core.fsmonitor false
/usr/bin/env git fetch origin
/usr/bin/env git checkout -f master --
Already on 'master'
/usr/bin/env git reset --hard origin/master --
Error: d12frosted/emacs-plus/emacs-plus@30 30.0.50 did not build
[error.log](https://github.com/d12frosted/homebrew-emacs-plus/files/13858354/error.log)

```

**Comment by d12frosted** [comment]
Seems like you've run into https://github.com/d12frosted/homebrew-emacs-plus/issues/551. Please clear your cache (see the latest comment for inspiration).

**Comment by vinurs** [comment]
@d12frosted  thanks, works now
