### ISSUE TITLE
[General]: Stuck on git clone with emacs@30

### ISSUE THREAD

**Issue by summeremacs** [d12frosted/homebrew-emacs-plus#654]
### Issue description

Hi there!
I'm trying to do a reinstall from scratch with emacs@30. However, it gets stuck hanging at the following line:

`Cloning into '/Users/summer/Library/Caches/Homebrew/emacs-plus@30--git'...`

I checked the directory and it has a folder there named emacs-plus@30--git. I did a get info on it and each time I try, it gives me various sizes: from 32k to 200m, but it never changes. The size is random each time. It does sometimes start downloading the .git folder inside, but sometimes not.

So I tried with emacs-plus@29 which installed fine, but I noticed it didn't put a folder in /Users/summer/Library/Caches/Homebrew - instead, it's using a .tar file.

Now, I'm not a coder but I figure maybe @30 shouldn't be trying to download an untarred folder? Is that the issue? What can I do about this?

Thanks for any help! 🙃

P.S. I did `brew doctor` and `brew cleanup` and nothing to report. As I said: it does install 29 correctly, but my config has some stuff for 30 in it which is kinda a pain to comment out when 29 isn't fully loading (because of my config). So I'd love to be on 30 again.

P.P.S. I did see the note about bootstrapping but I'm not sure what that means, or if I download the full file first manually? Please let me know if so and where to put it before trying whatever you want me to try. TYSM!

**Comment by summeremacs** [comment]
Never mind! It was just taking a while for some reason. After about 10 minutes, it finished the clone and installed fine. Sorry about this (I don't know how to delete a thread).

**Comment by d12frosted** [comment]
That would be my suggestion - to wait. In the worst case - trying cloning yourself is also a good idea (to any location - just to make sure cloning works). 

I know you resolved the issue, but there was a question regarding tar and clone, so let me comment on that. The major difference today between 29 and 30 is that 29 is a released version and 30 is a development version. Hence there are tars for 29 and only sources for 30. Hope that makes sense.
