### ISSUE TITLE
Possible typo in formulae

### ISSUE THREAD

**Issue by casouri** [d12frosted/homebrew-emacs-plus#66]
I know I just reported a false issue, but I think this is a real one. 

In
```
  if build.with? "natural-title-bar"
    if build.head? or build.devel?
      odie "--with-natural-title-bars is unnecessary on --HEAD or --devel, try (setq 'default-frame-alist '((ns-transparent-titlebar . t) (ns-appearance . 'nil)))"
    end
```
```(setq 'default-frame-alist '((ns-transparent-titlebar . t) (ns-appearance . 'nil)))``` 
should be
```(setq default-frame-alist '((ns-transparent-titlebar . t) (ns-appearance . 'nil)))``` 
right?
The expression with quote gives me error and expression without it works fine.

And putting quote in front of variable doesn't make sense anyway.

**Comment by d12frosted** [comment]
Yes, you're right. PR is welcome :)

**Comment by casouri** [comment]
Will do in a minute.

**Comment by casouri** [comment]
Actually more than a minute. But will do.
