### ISSUE TITLE
[General]: --without-cocoa requires xorgproto libxau libxdmcp libxcb libx11 libxext libxrender pixman cairo gdk-pixbuf fribidi harfbuzz pango librsvg

### ISSUE THREAD

**Issue by WuMingIT** [d12frosted/homebrew-emacs-plus#662]
### Issue description

Trying to install @29 terminal only. No Cocoa and no X11. Fails with error:

`brew unpin xorgproto libxau libxdmcp libxcb libx11 libxext libxrender pixman cairo gdk-pixbuf fribidi harfbuzz pango librsvg as installing d12frosted/emacs-plus/emacs-plus@29 requires the latest version of pinned dependencies`

I am not sure about all of them but most look related to a WM. Why is so? Thanks.

**Comment by d12frosted** [comment]
Never used brew pinning. The message clearly says that you need to unpin.

> I am not sure about all of them but most look related to a WM

What is the meaning of WM in this context?

P.S. if you enouncter 'installation' error, please use appropriate template. It asks you provide all the relevant information. For example, I don't understand which options you are using, which version of OS you are using etc.

**Comment by WuMingIT** [comment]
Actually I want to keep the dependencies pinned. Otherwise won’t have the issue I think. But don’t understand why most of them are needed in the first place. Without X and Cocoa being required. Xorg? LibX*? Gdk*? WM stayed for window manager. 

Sorry about the template choice. I thought it as not a general error.  macOS 10.13 and without-cocoa as only additional option.

**Comment by WuMingIT** [comment]
> Build logs :)

I wish could satisfy your request :). But no emacs-plus logs are available in ~/Library/Logs/Homebrew/ . Best I can do is paste stdout of `install -v` below:

```
brew install -v emacs-plus --without-cocoa
Running `brew update --auto-update`... 
[...]
PATH value was changed to:
/usr/local/Cellar/make/4.4.1/libexec/gnubin
/usr/local/opt/autoconf/libexec/gnubin
/usr/local/opt/gnu-sed/libexec/gnubin
/usr/local/Cellar/gnu-tar/1.35/libexec/gnubin
/usr/local/Cellar/grep/3.11/libexec/gnubin
/usr/local/Cellar/awk/20230909/libexec/gnubin
/usr/local/Cellar/coreutils/9.4/libexec/gnubin
/usr/local/opt/pkg-config/libexec/gnubin
/usr/local/Cellar/texinfo/7.1/libexec/gnubin
/usr/local/opt/xz/libexec/gnubin
/usr/local/Cellar/gnutls/3.8.3/libexec/gnubin
/usr/local/Cellar/librsvg/2.57.1/libexec/gnubin
/usr/local/opt/little-cms2/libexec/gnubin
/usr/local/Cellar/jansson/2.14/libexec/gnubin
/usr/local/Cellar/tree-sitter/0.20.8/libexec/gnubin
/usr/local/Cellar/imagemagick/7.1.1-27/libexec/gnubin
/usr/local/Cellar/dbus/1.14.10/libexec/gnubin
/usr/local/Cellar/mailutils/3.17/libexec/gnubin
/usr/local/opt/make/bin
/usr/local/opt/autoconf/bin
/usr/local/opt/gnu-sed/bin
/usr/local/opt/gnu-tar/bin
/usr/local/opt/grep/bin
/usr/local/opt/awk/bin
/usr/local/opt/coreutils/bin
/usr/local/opt/pkg-config/bin
/usr/local/opt/texinfo/bin
/usr/local/opt/xz/bin
/usr/local/opt/gnutls/bin
/usr/local/opt/librsvg/bin
/usr/local/opt/little-cms2/bin
/usr/local/opt/jansson/bin
/usr/local/opt/tree-sitter/bin
/usr/local/opt/imagemagick/bin
/usr/local/opt/dbus/bin
/usr/local/opt/mailutils/bin
/usr/local/Homebrew/Library/Homebrew/shims/shared
/usr/bin
/bin
/usr/sbin
/sbin
==> which tar
/usr/bin/tar
==> which ls
/bin/ls
==> which grep
/usr/bin/grep
PATH value was changed to:
/usr/local/Cellar/make/4.4.1/libexec/gnubin
/usr/local/opt/autoconf/libexec/gnubin
/usr/local/opt/gnu-sed/libexec/gnubin
/usr/local/Cellar/gnu-tar/1.35/libexec/gnubin
/usr/local/Cellar/grep/3.11/libexec/gnubin
/usr/local/Cellar/awk/20230909/libexec/gnubin
/usr/local/Cellar/coreutils/9.4/libexec/gnubin
/usr/local/opt/pkg-config/libexec/gnubin
/usr/local/Cellar/texinfo/7.1/libexec/gnubin
/usr/local/opt/xz/libexec/gnubin
/usr/local/Cellar/gnutls/3.8.3/libexec/gnubin
/usr/local/Cellar/librsvg/2.57.1/libexec/gnubin
/usr/local/opt/little-cms2/libexec/gnubin
/usr/local/Cellar/jansson/2.14/libexec/gnubin
/usr/local/Cellar/tree-sitter/0.20.8/libexec/gnubin
/usr/local/Cellar/imagemagick/7.1.1-27/libexec/gnubin
/usr/local/Cellar/dbus/1.14.10/libexec/gnubin
/usr/local/Cellar/mailutils/3.17/libexec/gnubin
/usr/local/opt/make/bin
/usr/local/opt/autoconf/bin
/usr/local/opt/gnu-sed/bin
/usr/local/opt/gnu-tar/bin
/usr/local/opt/grep/bin
/usr/local/opt/awk/bin
/usr/local/opt/coreutils/bin
/usr/local/opt/pkg-config/bin
/usr/local/opt/texinfo/bin
/usr/local/opt/xz/bin
/usr/local/opt/gnutls/bin
/usr/local/opt/librsvg/bin
/usr/local/opt/little-cms2/bin
/usr/local/opt/jansson/bin
/usr/local/opt/tree-sitter/bin
/usr/local/opt/imagemagick/bin
/usr/local/opt/dbus/bin
/usr/local/opt/mailutils/bin
/usr/local/Homebrew/Library/Homebrew/shims/shared
/usr/bin
/bin
/usr/sbin
/sbin
==> which tar
/usr/bin/tar
==> which ls
/bin/ls
==> which grep
/usr/bin/grep
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

Error: You must `brew unpin xorgproto libxau libxdmcp libxcb libx11 libxext libxrender pixman cairo gdk-pixbuf fribidi harfbuzz pango librsvg` as installing d12frosted/emacs-plus/emacs-plus@29 requires the latest version of pinned dependencies
```

Section with `PATH value was changed to` is actually repeated. Not a copy and paste mistake.

> Everything else is experimental and there was no effort to make --with-x and --without-cocoa builds optimal or whatnot.

Wanted to have a terminal-only installation. No X11. No Cocoa. But also my vintage laptop is slow at `brew upgrade`. So I simply pinned those formulas with more demanding compilation and which I don't need much. Guess will make do with emacs provided by Apple instead.

**Comment by WuMingIT** [comment]
Solved by installing the cask and invoking `emacs -nw`

**Comment by d12frosted** [comment]
> Best I can do is paste stdout of install -v below:

This is exactly what I normaly ask :) 

I wonder what is `[...]`.

> Wanted to have a terminal-only installation. No X11. No Cocoa. But also my vintage laptop is slow at brew upgrade. So I simply pinned those formulas with more demanding compilation and which I don't need much. Guess will make do with emacs provided by Apple instead.

You can always start Emacs with `-nw` option. Regardless of the installation - with X, with cocoa, whatever.

> Solved by installing the cask and invoking emacs -nw

As long is it works for you 👍 
In that case, closing the issue. Let me know if you need any other help.
