### ISSUE TITLE
Dark themes not working properly with multiple frames

### ISSUE THREAD

**Issue by skalyan91** [d12frosted/homebrew-emacs-plus#665]
Dark themes work fine as long as I have only one frame open. However, if I have two or more frames open, and switch from a light theme to a dark theme, then as soon as I switch to the second frame, I get the following result:

<img width="704" alt="Screenshot 2024-02-17 at 2 28 36 pm" src="https://github.com/d12frosted/homebrew-emacs-plus/assets/2990272/895689cf-1aa1-4089-bd2f-373f789d1a05">

In other words, the background and foreground colours are those of the light theme (see the minibuffer for an instance of the foreground colour), but the other faces are those of the dark theme. (I used `doom-one-light` for the light theme, and `doom-dark+` for the dark theme.)

Here is what this looks like on a typical buffer:

<img width="704" alt="Screenshot 2024-02-17 at 3 52 17 pm" src="https://github.com/d12frosted/homebrew-emacs-plus/assets/2990272/707c7b9c-1352-4ed3-8707-13f61ec9ad9a">

I’m not sure if this is an issue with Emacs itself, or with Emacs+ specifically.

**Comment by d12frosted** [comment]
Emacs+ is pretty much GNU Emacs (there are only very few additions unless you are using some experimental flags like xwidgets). Usually these kind of problems are more of a configuration problem. I would suggest trying to reproduce without Doom.

P.S. I am closing the issue as there is nothing to do on my side - it's either a configuration issue or GNU Emacs issue - but don't be discouraged from futher activity in this issue. If you find something interesting - let me know 🙏
