### ISSUE TITLE
d12frosted/emacs-plus/emacs-plus@30: private method `new' called for Tap:Class ~ 

### ISSUE THREAD

**Issue by LuciusChen** [d12frosted/homebrew-emacs-plus#668]
### Version

emacs-plus@30

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
$ brew install emacs-plus@30   
</pre>

<details>
  <summary>Command output</summary>
  <pre>

d12frosted/emacs-plus/emacs-plus@30: private method `new' called for Tap:Class

  </pre>
</details>

### brew doctor output

Your system is ready to brew.

### brew config output

HOMEBREW_VERSION: 4.2.11-54-g76c7245
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76c7245d10d4f6219a2c3ac9b584dd8d9661087d
Last commit: 9 hours ago
Core tap JSON: 07 Mar 02:14 UTC
Core cask tap JSON: 07 Mar 02:14 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 14
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 14-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false

**Comment by stschaef** [comment]
same issue 
```
HOMEBREW_VERSION: 4.2.11-54-g76c7245
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76c7245d10d4f6219a2c3ac9b584dd8d9661087d
Last commit: 10 hours ago
Core tap HEAD: 9bcd9bbcc66cd9c7484bb787aa7a0d33b778fffb
Core tap last commit: 12 months ago
Core tap JSON: 07 Mar 03:01 UTC
Core cask tap HEAD: 4aa9fca50259ccb5c709be738120fe09281126cf
Core cask tap last commit: 12 months ago
Core cask tap JSON: 07 Mar 03:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

**Comment by LuciusChen** [comment]
I reinstall Homebrew fixed it

**Comment by stschaef** [comment]
What do you mean reinstall homebrew? 

Anyway I see to do that involves uninstalling everything I've ever installed with brew

**Comment by LuciusChen** [comment]
https://github.com/homebrew/install#uninstall-homebrew

**Comment by soonhokong** [comment]
I got the same issue with emacs-plus@29.

**Comment by yamyeti** [comment]
This same warning shows up when you brew doctor if you already have emacs installed.

```
Warning: Some installed formulae are not readable:
  d12frosted/emacs-plus/emacs-plus@30: private method `new' called for Tap:Class
```

**Comment by d12frosted** [comment]
@soonhokong you are correct. I would appreciated a PR 🙏
