### ISSUE TITLE
[Feature request]: Move Emacs.app to Applications automatically

### ISSUE THREAD

**Issue by welcome-linja** [d12frosted/homebrew-emacs-plus#683]
### Feature request description

Some formulae for apps (I know of Transmission and AppCleaner) move the .app file into Applications automatically upon install. It'd be nice if E+ did that.

**Comment by d12frosted** [comment]
Hey @welcome-linja 

You are talking about casks, and we do not provide one. There is a ticket for this - https://github.com/d12frosted/homebrew-emacs-plus/issues/41. TL;DR someone needs to contribute it.

So closing this one as duplicate.
