### ISSUE TITLE
[Build Failure]: Error: An exception occurred within a child process: NoMethodError: undefined method `+' for nil

### ISSUE THREAD

**Issue by bleppie** [d12frosted/homebrew-emacs-plus#690]
### Version

emacs-plus@30

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
$ brew install --verbose emacs-plus@30
</pre>

<details>
  <summary>Command output</summary>
  <pre>

[installout.txt.zip](https://github.com/user-attachments/files/15858161/installout.txt.zip)

  </pre>
</details>

### brew doctor output

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1

### brew config output

HOMEBREW_VERSION: 4.3.5-118-g766b9b8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 766b9b8d9fe214df6015818571e009747f4c4217
Last commit: 18 hours ago
Core tap HEAD: 2fc9fa519f9dbcf9c973d5f60db164f491207f8d
Core tap last commit: 4 hours ago
Core tap JSON: 16 Jun 13:15 UTC
Core cask tap HEAD: 94fe09d6b11913f723cdad61f04c21c0ada44ee7
Core cask tap last commit: 3 hours ago
Core cask tap JSON: 16 Jun 13:15 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

### Any extra information

This is with "env :std" commented out in the formula. With "env :std" left in, I get the same error as #688 
Thank you.

**Comment by italoaa** [comment]
I did some digging but first some things I did to get to my position:
- I managed to get gccjit working
- I commented out the env :std line as shown below:
```rb  
on_macos do
    # env :std
  end
```

and it seems the error comes from the variable `shared_idx` being nil in the following code on the file called EmacsBase.rb:
```rb
  shared_idx = path_full.find_index { |x|
      x.end_with? "/Library/Homebrew/shims/shared"
    }
```
I made a little change to include a nil check and it is does show nil:
```rb
   if shared_idx.nil?
        odie "Could not find '/Library/Homebrew/shims/shared' in PATH"
    end
```
The output was the following:
<img width="628" alt="image" src="https://github.com/d12frosted/homebrew-emacs-plus/assets/72895337/7b867cc0-0619-42a8-a0ca-32c3694d56e6">
I am not sure what that path does or how to fix it but at least I hope this helps in solving the issue. I will try digging more later and if I can I will try making a pr.

**Comment by d12frosted** [comment]
Theoretically, if you comment out `env :std` you can also comment out `inject_path` as it doesn't work as expected in `superenv` (default env) anyways.

https://github.com/d12frosted/homebrew-emacs-plus/blob/2c9dcd167b202bcbdd4722cfca7368715ad7a3e3/Formula/emacs-plus%4030.rb#L222-L223

**Comment by italoaa** [comment]
It worked!!! Thank you @d12frosted I have been struggling with native comp for super longg :)

**Comment by d12frosted** [comment]
This issue was resolved. But I have also [reverted to using super (i.e. default) environment](https://github.com/d12frosted/homebrew-emacs-plus/commit/a5ccb0d703735f9a2c7ccb9fe27c8617dcc3c4c5), which should fix most of the issues related to missing binaries or unexpected behaviour related to BSD vs GNU versions of several utilities. Path injection is still in place, but it no longer affects installation experience.

That being said, please open a new ticket if you still encounter installation issues.
