### ISSUE TITLE
Huge performance increase for OSX users increase compiling to use vfork

### ISSUE THREAD

**Issue by codygman** [d12frosted/homebrew-emacs-plus#71]
Should consider or at least talk about stabilizing --with-vfork option added to fork https://github.com/aaronjensen/homebrew-emacs-plus to improve spacemacs performance for OSX users.

```
$ brew uninstall emacs-plus
$ brew tap aaronjensen/emacs-plus
$ brew reinstall aaronjensen/emacs-plus/emacs-plus --with-vfork
```

see https://github.com/magit/magit/issues/2909#issuecomment-292978090 for more info.

**Comment by codygman** [comment]
Oh, from this issue: https://github.com/d12frosted/homebrew-emacs-plus/issues/63

It looks like this is already being done. Feel free to close this issue if it's not useful.

**Comment by d12frosted** [comment]
Yeah, it's included by default. :)
