### ISSUE TITLE
[Feature request]: Patch User Agent for xwidget-webkit

### ISSUE THREAD

**Issue by iblowmymind** [d12frosted/homebrew-emacs-plus#718]
### Feature request description

xwidget-webkit uses an ancient User-Agent by default on Emacs 29+, defined in src/nsxwidget.m. The following is an excerpt of it with its default user agent definition:
```objc
  self = [super initWithFrame:frame configuration:configuration];
  if (self)
    {
      self.xw = xw;
      self.urlScriptBlocked = [[[NSMutableDictionary alloc] init]
                                autorelease];
      self.navigationDelegate = self;
      self.UIDelegate = self;
      self.customUserAgent =
        @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)"
        @" AppleWebKit/603.3.8 (KHTML, like Gecko)"
        @" Version/11.0.1 Safari/603.3.8";
      [scriptor addScriptMessageHandler:self name:@"keyDown"];
      WKUserScript *userScript = [[[WKUserScript alloc]
                                    initWithSource:xwScript
                                     injectionTime:
                                      WKUserScriptInjectionTimeAtDocumentStart
                                    forMainFrameOnly:NO] autorelease];
      [scriptor addUserScript:userScript];
    }
  return self;
}
```
This leads to many websites behaving as if the WebKit version is of Safari 11's (from 2017!) while the latest versions of macOS ship with a modern WebKit version of 618.3.11 (Safari 17). (Now, Safari doesn't self report as WebKit 618 either, but rather is fixed on 605.1.15 with its Safari version value changing. `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15` is its Useragent value for the latest version of Safari in macOS 14.6, but I'll get to that later).
 
Ideally, this should be auto-set by the formula by getting the version of Safari that was included in the version of macOS that built the formula. I believe Safari has frozen the WebKit version to 605.1.15 since Safari 14 so that's irrelevant, however we should just get the Safari version like so:
```sh
printf 'self.customUserAgent =''\n''  @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"''\n''  @" AppleWebKit/605.1.15 (KHTML, like Gecko)"''\n''  @" Version/'$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" /Applications/Safari.app/Contents/Info.plist)' Safari/605.1.15";''\n'
```

However, a crude fix would also suffice: 
```diff
90,92c90,92
<         @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)"
<         @" AppleWebKit/603.3.8 (KHTML, like Gecko)"
<         @" Version/11.0.1 Safari/603.3.8";
---
>         @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
>         @" AppleWebKit/605.1.15 (KHTML, like Gecko)"
>         @" Version/17.6 Safari/605.1.15";
```
Please let me know if you have any further suggestions!

**Comment by iblowmymind** [comment]
Update: Created my own fork (https://github.com/iblowmymind/homebrew-emacs-plus) that has this behaviour, and it's working fine. I'll reach out to emacs-devel now.

**Comment by d12frosted** [comment]
@iblowmymind wow, fast! Keep me posted :)
