### ISSUE TITLE
[Build Failure]: 31 fails on MacOS: Add: "NSSpeechRecognitionUsageDescription" Entry Already Exists

### ISSUE THREAD

**Issue by realneel** [d12frosted/homebrew-emacs-plus#721]
### Version

emacs-plus@31

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
brew install emacs-plus@31 --with-imagemagick --with-native-comp --with-xwidgets
</pre>

<details>
  <summary>Command output</summary>
  <pre>

==> /usr/libexec/PlistBuddy -c 'Add :LSEnvironment dict' '/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Emacs.app/Contents/
==> /usr/libexec/PlistBuddy -c 'Add :LSEnvironment:PATH string' '/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Emacs.app/Co
==> /usr/libexec/PlistBuddy -c 'Set :LSEnvironment:PATH /Users/xxx/.asdf/shims:/Users/neel/.asdf/bin:/opt/homebrew/bin:
==> /usr/libexec/PlistBuddy -c 'Print :LSEnvironment' '/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Emacs.app/Contents/Inf
==> touch '/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Emacs.app'
==> Injecting description for protected resources usage
==> /usr/libexec/PlistBuddy -c 'Add NSCameraUsageDescription string' '/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Emacs.a
==> /usr/libexec/PlistBuddy -c 'Set NSCameraUsageDescription Emacs requires permission to access the Camera.' '/opt/home
==> /usr/libexec/PlistBuddy -c 'Add NSMicrophoneUsageDescription string' '/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Ema
==> /usr/libexec/PlistBuddy -c 'Set NSMicrophoneUsageDescription Emacs requires permission to access the Microphone.' '/
==> /usr/libexec/PlistBuddy -c 'Add NSSpeechRecognitionUsageDescription string' '/opt/homebrew/Cellar/emacs-plus@31/31.0
Last 15 lines from /Users/neel/Library/Logs/Homebrew/emacs-plus@31/14.Info.plist':
2024-08-31 15:49:01 +0000

/usr/libexec/PlistBuddy -c 'Add NSSpeechRecognitionUsageDescription string' '/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Emacs.app/Contents/Info.plist'

Add: "NSSpeechRecognitionUsageDescription" Entry Already Exists

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

  </pre>
</details>

### brew doctor output

Your system is ready to brew.

### brew config output

HOMEBREW_VERSION: 4.3.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: abc0584215659c5a8716d0798ea2801388d01368
Last commit: 5 days ago
Core tap JSON: 31 Aug 15:37 UTC
Core cask tap JSON: 31 Aug 15:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

**Comment by d12frosted** [comment]
https://github.com/d12frosted/homebrew-emacs-plus/commit/6f099bb618334885f509c907efc9a0e0e4257ac5 fixes it.
