### ISSUE TITLE
[Build Failure]: Fails to fetch Emacs

### ISSUE THREAD

**Issue by i-am-linja** [d12frosted/homebrew-emacs-plus#725]
### Version

emacs-plus@30

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

```
==> Fetching d12frosted/emacs-plus/emacs-plus@30
==> Cloning https://github.com/emacs-mirror/emacs.git
Cloning into '/Users/linja/Library/Caches/Homebrew/emacs-plus@30--git'...
error: RPC failed; curl 56 Recv failure: Operation timed out
error: 5630 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Error: emacs-plus@30: Failed to download resource "emacs-plus@30"
Failure while executing; `/usr/bin/env git clone --branch emacs-30 --config advice.detachedHead=false --config core.fsmonitor=false https://github.com/emacs-mirror/emacs.git /Users/linja/Library/Caches/Homebrew/emacs-plus@30--git` exited with 128. Here's the output:
Cloning into '/Users/linja/Library/Caches/Homebrew/emacs-plus@30--git'...
error: RPC failed; curl 56 Recv failure: Operation timed out
error: 5630 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

### brew doctor output

Your system is ready to brew.

### brew config output

HOMEBREW_VERSION: 4.3.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f9bd2de89883ec9a59db3eab0f5475bce06d5bc
Last commit: 5 days ago
Core tap JSON: 06 Sep 23:07 UTC
Core cask tap JSON: 06 Sep 23:07 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--fontdir=/Library/Fonts"]
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false

**Comment by d12frosted** [comment]
Hey @i-am-linja 

It's likely an issue with your connection/network. Git fails to clone Emacs mirror repository, which is no even the repository you are reporting the issue to :) 

Try cloning it manually to see if it works:

```
git clone https://github.com/emacs-mirror/emacs.git
```

Closing the issue as it's not relevant to Emacs+, but feel free to ask for further help.

**Comment by TomoeMami** [comment]
@i-am-linja You can try increasing post buffer size by 

`git config --global http.postBuffer 524288000`
