### ISSUE TITLE
Emacs 26.1

### ISSUE THREAD

**Issue by d12frosted** [d12frosted/homebrew-emacs-plus#73]
RC1 is already out. Waiting for the official release to update.

**Comment by dmgm** [comment]
I proposed a pull to update the --devel option to use RC1. On reddit one of the developers is saying it's pretty stable and please help them test it.

**Comment by d12frosted** [comment]
@dmgm yeah, good point ❤️! I've updated the formulae

**Comment by j-martin** [comment]
@d12frosted it's now out :)

https://lists.gnu.org/archive/html/emacs-devel/2018-05/msg00765.html

**Comment by d12frosted** [comment]
Super great to hear! Please see #81. Once it's green - I'll merge it into master 😸

**Comment by d12frosted** [comment]
It's out. I'll also update the bottle for Sierra. For High Sierra will be available once I return home from the trip. Or if I manage to connect to computer with High Sierra.

**Comment by d12frosted** [comment]
Ok, bottle for High Sierra is out.
