### ISSUE TITLE
[General]: python--auto-mode-alist-regexp  error

### ISSUE THREAD

**Issue by Odysseus6000** [d12frosted/homebrew-emacs-plus#735]
### Issue description

After installing the latest emacs-plus@30 :File mode specification error: (wrong-type-argument stringp python--auto-mode-alist-regexp)? mac，GNU Emacs 30.0.91 (build 1, aarch64-apple-darwin23.4.0

**Comment by d12frosted** [comment]
Hey. 

Are you sure this is the right place for report? This is just s formula to build GNU Emacs. So unless you can reproduce the issue with this formula, you should report the issue to Emacs bug tracker.
