### ISSUE TITLE
[General]: tree-sitter dependency update breaks emacs-plus@29 on homebrew

### ISSUE THREAD

**Issue by mwolson** [d12frosted/homebrew-emacs-plus#737]
### Issue description

Hi,

I'm getting the following error when trying to start emacs-plus@29 after doing a `brew uprade` on macOS Sequoia 15.0.1:

```
dyld[48154]: Library not loaded: /opt/homebrew/opt/tree-sitter/lib/libtree-sitter.0.23.dylib
  Referenced from: <05DDFC52-C586-3F8A-8EF3-A74FCA9A66A1> /opt/homebrew/Cellar/emacs-plus@29/29.4/Emacs.app/Contents/MacOS/Emacs
  Reason: tried: '/opt/homebrew/opt/tree-sitter/lib/libtree-sitter.0.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/tree-sitter/lib/libtree-sitter.0.23.dylib' (no such file), '/opt/homebrew/opt/tree-sitter/lib/libtree-sitter.0.23.dylib' (no such file), '/opt/homebrew/Cellar/tree-sitter/0.24.3/lib/libtree-sitter.0.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/tree-sitter/0.24.3/lib/libtree-sitter.0.23.dylib' (no such file), '/opt/homebrew/Cellar/tree-sitter/0.24.3/lib/libtree-sitter.0.23.dylib' (no such file)
[
```

When trying to debug it, I noticed that the tree-sitter formula has been updated to version 0.24.4, which no longer has the `libtree-sitter.0.23.dylib` file. I temporarily worked around it by running this:

```sh
cd /opt/homebrew/opt/tree-sitter/lib
sudo ln -s $(readlink libtree-sitter.0.dylib) libtree-sitter.0.23.dylib
```

I spot-checked a `.go` file with tree-sitter-go in Emacs after making this change, and it seemed to at least syntax-highlight the file and load the workspace without any errors, so it's possible that the 0.24 tree-sitter change was very small (upstream CHANGELOG.md currently lacks an entry for it).

**Comment by mwolson** [comment]
I think this might have been caused by the OS X Command Line tools getting corrupted / outdated, since that was causing attempts to upgrade the emacs-plus@29 package to fail, which might have been ultimately responsible for the outdated tree-sitter dependency. I'll close it out. Here's what I did to fix it:

* Manually remove and reinstall OS X Command Line tools
* Get an update from Apple a couple hours later in the day for the tools
* Reboot
* Now removing emacs-plus and installing it again works

**Comment by tillydray** [comment]
Had the same issue with emacs@30.0.91 using doom. All I needed to do was update to emacs@30.0.92. Emacs opens just fine. I needed to run `doom sync` to get doom working again but that's of course only for doom emacs users
