### ISSUE TITLE
[General]: with-poll not working

### ISSUE THREAD

**Issue by tedroden** [d12frosted/homebrew-emacs-plus#738]
### Issue description

I can't seem to get `--with-poll` to work.  I've installed it with the flag, but it doesn't seem to carry over when compiling. It certainly could be user error. I'm not using a specific branch, maybe I should be? 

Also, I love emacs-plus, been using it for years. Thanks to all who contribute.

```
# uninstall first
brew uninstall emacs-plus@30
# install
brew install emacs-plus@30 --with-native-comp --with-poll
```

I've done some digging and it doesn't appear in the places I'd expect:

When I look at the config.log it doesn't appear there

```
It was created by GNU Emacs configure 30.0.91, which was
generated by GNU Autoconf 2.72.  Invocation command line was

  $ ./configure --disable-dependency-tracking --disable-silent-rules
 --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp 
--infodir=/opt/homebrew/Cellar/emacs-plus@30/30.0.91/share/info/emacs 
--prefix=/opt/homebrew/Cellar/emacs-plus@30/30.0.91
 --with-xml2 --with-gnutls --with-native-compilation=aot 
--without-compress-install --without-dbus 
--without-imagemagick --with-modules --with-rsvg
 --with-webp --with-ns --disable-ns-self-contained
```

When I check via `C-h v system-configuration-options`

It shows:

```
"--disable-dependency-tracking --disable-silent-rules
 --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp
 --infodir=/opt/homebrew/Cellar/emacs-plus@30/30.0.91/share/info/emacs
 --prefix=/opt/homebrew/Cellar/emacs-plus@30/30.0.91
 --with-xml2 --with-gnutls --with-native-compilation=aot 
--without-compress-install --without-dbus --without-imagemagick
 --with-modules --with-rsvg --with-webp --with-ns 
--disable-ns-self-contained 'CFLAGS=-O2 -DFD_SETSIZE=10000 
-DDARWIN_UNLIMITED_SELECT -I/opt/homebrew/opt/gcc/include
 -I/opt/homebrew/opt/libgccjit/include' 'LDFLAGS=-L/opt/homebrew/lib/gcc/14 
-I/opt/homebrew/opt/gcc/include -I/opt/homebrew/opt/libgccjit/include'"
```

And `system-configuration-features` doesn't show it. I think POLL should be in here:

"ACL GIF GLIB GMP GNUTLS JPEG LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM ZLIB"

This isn't a huge deal unless I open a couple different projects using LSP.

**Comment by d12frosted** [comment]
@tedroden the fix is in the master, can you please double check? 🙏

**Comment by d12frosted** [comment]
@tedroden sad news :) The patch is actually causing issues with async processes, so we decided to remove it all together. No one is really owning that patch anyways. 

see https://github.com/d12frosted/homebrew-emacs-plus/pull/746

**Comment by tedroden** [comment]
Oof. No problem. I think that bug just bit me too.
