### ISSUE TITLE
[General]: with-poll causes issues with elpaca

### ISSUE THREAD

**Issue by aaronjensen** [d12frosted/homebrew-emacs-plus#745]
### Issue description

I don't know the cause, and it is probably beyond my capacity and time to debug it, but now that with-poll works, I've tried using it and found that it appears to cause issues with asynchronous shell commands. Elpaca hangs on initial install. Magit appears to hang when issuing git commands.

If anyone else can corroborate this, I'd recommend removing the patch. It seems to do more harm than good.

**Comment by bbenchen** [comment]
@aaronjensen
I also had related problems and now I don't use with-poll anymore.

**Comment by aaronjensen** [comment]
That's enough for me, thanks @bbenchen. #746
