### ISSUE TITLE
Gotta rebuild emacs-plus bottle and bump version again because some library got updated

### ISSUE THREAD

**Issue by Blaisorblade** [d12frosted/homebrew-emacs-plus#75]
```
$ brew upgrade
[...]
$ /usr/local/Cellar/emacs-plus/25.3/Emacs.app/Contents/MacOS/Emacs
dyld: Library not loaded: /usr/local/opt/imagemagick@6/lib/libMagickWand-6.Q16.5.dylib
  Referenced from: /usr/local/Cellar/emacs-plus/25.3/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
Abort trap: 6
```

Workaround I'm testing:
```
cd /usr/local/opt/imagemagick@6/lib/
ln -s libMagickWand-6.Q16.6.dylib libMagickWand-6.Q16.5.dylib
ln -s libMagickCore-6.Q16.6.dylib libMagickCore-6.Q16.5.dylib
```

But I'm confused, I'd expect emacs-plus to link to `libMagickCore-6.Q16.dylib` and `libMagickWand-6.Q16.dylib`, I'd think they exist for that? But never done native development on Mac, only Linux.

**Comment by d12frosted** [comment]
Hey,

Did you update/reinstall your system? I made an update recently and I had to reinstall all my brew packages due to a similar issue.

**Comment by Blaisorblade** [comment]
Reinstall no, update libmagick: yes. So you need a new revision. This is a bit like https://github.com/d12frosted/homebrew-emacs-plus/issues/44, you remember?

**Comment by Blaisorblade** [comment]
But in this case I don’t know that a new bottle exists... but if you don’t have the issue with updated homebrew, that’s the reason.

**Comment by d12frosted** [comment]
Oh. Probably I've just updated my system and got into the issue with `libmagick` and thought that it's due the system update.

Ok. Will do the update soon. Thanks for letting me know ❤️

**Comment by dqdinh** [comment]
FWIW, this issue was blocking my workflow as I use spacemacs. I got it to run with

`brew reinstall emacs-plus --HEAD`.

The only issue I get is when trying to update packages in spacemaces:

`-> Warning: cannot update 155 package(s), possibly due to a temporary network problem:`

**Comment by Blaisorblade** [comment]
@dqdinh that failure might be a regression or incompatibility of the beta version you get from HEAD.

I think your trick worked not because of the head version but because you didn't use the bottle (which must be recompiled), so using `brew install emacs-plus --build-from-source` (after uninstalling) might be a safer solution. Yet alternatively, installing the bottle and using the workaround with `ln` I mentioned might be safer (this works perfectly for me, though I'm not sure I have tried using images or anything actually using those libraries — I think I never do that).

But of course I don't guarantee any of this.

**Comment by d12frosted** [comment]
Ok, an updated bottle should be available shortly. Unfortunately, only for Sierra (haven't updated to High Sierra yet).

**Comment by dqdinh** [comment]
@Blaisorblade - Thanks, you were right about HEAD being the cause of the failure and using `ln` as the better workaround.

@d12frosted  - Thank you for pushing up an updated bottle. I reinstalled and everything works!

**Comment by Blaisorblade** [comment]
Worked for me too, closing!
