### ISSUE TITLE
[Build Failure]: emacs-plus@29

### ISSUE THREAD

**Issue by aisamu** [d12frosted/homebrew-emacs-plus#751]
### Version

emacs-plus@29

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
$  brew install emacs-plus@29 --with-imagemagick --with-native-comp --with-retro-sink-bw-icon
</pre>

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Fetching d12frosted/emacs-plus/emacs-plus@29
==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-29.4.tar.xz
Already downloaded: /Users/aisamu/Library/Caches/Homebrew/downloads/40b0d2afb6a8abb0782d2f870c83209c0ebb7136de4de640b427214523ed5278--emacs-29.4.tar.xz
==> Installing emacs-plus@29 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
==> Applying system-appearance.patch
==> Applying round-undecorated-frame.patch
==> ImageMagick PKG_CONFIG_PATH: 
/opt/homebrew/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --disable-silent-rules --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-plus@29/29.4/share/info/emacs --with-xml2 --with-gnutls --with-native-compilation --without-compress-install --without-dbus --with-imagemag
==> gmake
Last 15 lines from /Users/aisamu/Library/Logs/Homebrew/emacs-plus@29/03.gmake:
gmake[2]: Leaving directory '/private/tmp/emacs-plusA29-20241112-77507-dsyxmb/emacs-29.4/src'
gmake[1]: *** [Makefile:544: src] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20241112-77507-dsyxmb/emacs-29.4'
gmake[1]: Entering directory '/private/tmp/emacs-plusA29-20241112-77507-dsyxmb/emacs-29.4'
***
*** "make all" failed with exit status 2.
***
*** You could try to:
*** - run "make bootstrap", which might fix the problem
*** - run "make V=1", which displays the full commands invoked by make,
***   to further investigate the problem
***
gmake[1]: *** [Makefile:414: advice-on-failure] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20241112-77507-dsyxmb/emacs-29.4'
gmake: *** [Makefile:370: all] Error 2
  </pre>
</details>

### brew doctor output

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  nvalt

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-fonts
Untap them with `brew untap`.

### brew config output

HOMEBREW_VERSION: 4.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 254bf3fe9d8fa2e1b2fb55dbcf535b2d870180c4
Last commit: 28 hours ago
Core tap JSON: 12 Nov 15:24 UTC
Core cask tap JSON: 12 Nov 15:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
Rosetta 2: false

### Any extra information

```uname -a                                                         
Darwin aisamu 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:36 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6020 arm64 arm Darwin```

**Comment by etlapale** [comment]
Same here. Cannot rebuild on an old system, or install on a new one. `~/Library/Logs/Homebrew/emacs-plus@30/03.gmake` error is:

```
/opt/homebrew/opt/coreutils/bin/gmkdir -p ../etc
rm -f ../etc/DOC
../lib-src/make-docfile -d . \
  dosfns.o msdos.o xterm.o xfns.o xmenu.o xselect.o xrdb.o xsmfns.o fringe.o image.o fontset.o dbusb
ind.o cygw32.o nsterm.o nsfns.o nsmenu.o nsselect.o nsimage.o nsfont.o macfont.o nsxwidget.o w32.o w
32console.o w32cygwinx.o w32fns.o w32heap.o w32inevt.o w32notify.o w32menu.o w32proc.o w32reg.o w32s
elect.o w32term.o w32xfns.o w16select.o widget.o xfont.o ftfont.o xftfont.o gtkutil.o xsettings.o xg
select.o termcap.o hbfont.o haikuterm.o haikufns.o haikumenu.o haikufont.o androidterm.o androidfns.
o androidfont.o androidselect.c androidvfs.c sfntfont-android.c sfntfont.c dispnew.o frame.o scroll.
o xdisp.o menu.o  window.o charset.o coding.o category.o ccl.o character.o chartab.o bidi.o cm.o ter
m.o terminal.o xfaces.o    emacs.o keyboard.o macros.o keymap.o sysdep.o bignum.o buffer.o filelock.
o insdel.o marker.o minibuf.o fileio.o dired.o cmds.o casetab.o casefiddle.o indent.o search.o regex
-emacs.o undo.o alloc.o pdumper.o data.o doc.o editfns.o callint.o eval.o floatfns.o fns.o sort.o fo
nt.o print.o lread.o emacs-module.o syntax.o  bytecode.o comp.o dynlib.o process.o gnutls.o callproc
.o region-cache.o sound.o timefns.o atimer.o doprnt.o intervals.o textprop.o composite.o xml.o lcms.
o kqueue.o  profiler.o decompress.o thread.o systhread.o sqlite.o  treesit.o itree.o json.o        f
ontset.o fringe.o image.o     nsterm.o nsfns.o nsmenu.o nsselect.o nsimage.o macfont.o > ../etc/DOC
Undefined symbols for architecture arm64:
  "_sqlite3_load_extension", referenced from:
      _Fsqlite_load_extension in sqlite.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile:745: temacs] Error 1
gmake[2]: Leaving directory '/private/tmp/emacs-plusA30-20241112-32511-qx66po/emacs-30.0.92/src'
```

**Comment by jimwise** [comment]
Same here, identical log.

**Comment by Morilindo** [comment]
Try [this](https://github.com/d12frosted/homebrew-emacs-plus/issues/750#issuecomment-2471039941), worked for me
