### ISSUE TITLE
[Build Failure]: Applying round-undecorated-frame.patch doesn't work

### ISSUE THREAD

**Issue by zikajk** [d12frosted/homebrew-emacs-plus#761]
### Version

emacs-plus@31

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
$ brew install emacs-plus@31 --with-mailutils --with-xwidgets --with-imagemagick --with-native-comp
</pre>

<details>
  <summary>Patch can't be applied</summary>
  <pre>
 
  ~ brew install emacs-plus@31 --with-mailutils --with-xwidgets --with-imagemagick --with-native-comp
==> Fetching d12frosted/emacs-plus/emacs-plus@31
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/akiz/Library/Caches/Homebrew/emacs-plus@31--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 775290efdf1 ; * doc/misc/tramp.texi (Frequently Asked Questions): Minor edits.
==> Installing emacs-plus@31 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
==> Applying system-appearance.patch
==> Applying round-undecorated-frame.patch

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues
 
  </pre>
</details>

### brew doctor output

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  meld

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  gnupg@2.2
  openssl@1.1

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-fonts
Untap them with `brew untap`.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  numpy

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install emacs

### brew config output

brew config
HOMEBREW_VERSION: 4.4.8-11-gd646450
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6464506ba08c1b5b0ae520ac077b9bfaebc42e9
Last commit: 2 hours ago
Branch: master
Core tap JSON: 26 Nov 21:19 UTC
Core cask tap JSON: 26 Nov 21:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false

### Any extra information
 By adding `--debug` to `brew install` you can skip this patch but consequences aren't clear.

**Comment by zikajk** [comment]
There is no problem with `emacs-plus30` so it is quite possible it is just a temporary problem.

**Comment by d12frosted** [comment]
Should be OK now. There is a fix in the master. Do `brew update` and give it another try 🙏
