### ISSUE TITLE
[Build Failure]: Error: invalid option: --with-native-comp

### ISSUE THREAD

**Issue by ashrafhasson** [d12frosted/homebrew-emacs-plus#762]
### Version

emacs-plus@29

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
$ brew uninstall emacs-plus
$ brew install emacs-plus@29 --with-native-comp --with-xwidgets
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  Error: invalid option: --with-native-comp

  </pre>
</details>

<pre>
$ brew install emacs-plus@29
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  ==> Downloading https://formulae.brew.sh/api/cask.jws.json
#################################################################################################### 100.0%
Error: d12frosted/emacs-plus/emacs-plus@29: /opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@29.rb:121: syntax error, unexpected <<
<<<<<<< Updated upstream
^~

  </pre>
</details>

### brew doctor output

❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  fish_add_path /opt/homebrew/sbin

### brew config output

HOMEBREW_VERSION: 4.4.8-38-g6089077
ORIGIN: https://github.com/Homebrew/brew
HEAD: 60890774e0a70fe93f94973b080068cf7b0d1c93
Last commit: 2 days ago
Branch: master
Core tap JSON: 30 Nov 13:41 UTC
Core cask tap JSON: 30 Nov 13:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false

### Any extra information

brew bin is actually in the path .. 🤷 .. but anyways that doesn't seem to matter.

**Comment by ashrafhasson** [comment]
Ugh, I had updated the Formula manually to add sqlite dependency and completely forgotten about it, brew installing meant the formula had breaking changes because of my edits and that's what was causing the error above. Apologies for the noise!

**Comment by aaronjensen** [comment]
The exact same thing happened to me. It's not a very helpful error message when it happens, that's for sure.
