### ISSUE TITLE
[Build Failure]:  No error  but dies with last 15 lines from autogen.sh

### ISSUE THREAD

**Issue by slackorama** [d12frosted/homebrew-emacs-plus#765]
### Version

emacs-plus@29

### Make sure to follow these steps before submitting the issue

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
$ brew install emacs-plus@29
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  ==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Fetching dependencies for d12frosted/emacs-plus/emacs-plus@29: gnu-sed, gnu-tar, grep, awk, jansson and tree-sitter
==> Fetching gnu-sed
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-sed/manifests/4.9-2
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/76f36ee40de04c6391017f0d87ac55b273e9e870c9b6ca1feb923d95ffc1c0cd--gnu-sed-4.9-2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-sed/blobs/sha256:4d10e5703feb75bc37e450178f2c6bdc3
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/98f9f603e9bc7cf119a2f5602e8124f77a8da5d948a272b99c7af10afe0772f9--gnu-sed--4.9.sonoma.bottle.2.tar.gz
==> Fetching gnu-tar
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-tar/manifests/1.35-1
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/e0ce070efd811d45bde2dc83fa029e863379a5e778eafae566b5a3f709eb82e0--gnu-tar-1.35-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-tar/blobs/sha256:a9a0d278cd686a626b45cbfd43aa8f34a
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/7a71b383bd0850e22b98895d3f3d4af74f64019e4b252a0c7e2162cd4100950d--gnu-tar--1.35.sonoma.bottle.1.tar.gz
==> Fetching grep
==> Downloading https://ghcr.io/v2/homebrew/core/grep/manifests/3.11-2
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/ad81f65102ec61a6dacd2d8927cd680d905e10addb8c5e955ffd454b1910d8e0--grep-3.11-2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/grep/blobs/sha256:ce3337c484b58a52ffc841fae13f3f530fbe
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/b3ae74f8bec87052880f05e780bcf77910e19fbeabbe197c173f540df5c0159a--grep--3.11.sonoma.bottle.2.tar.gz
==> Fetching awk
==> Downloading https://ghcr.io/v2/homebrew/core/awk/manifests/20240728
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/a872154422855fa91de8a4e98f8c96799f02a7806ac0b350aba552dc8e3140ea--awk-20240728.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/awk/blobs/sha256:08df642292e0e58a9f8ba843bad3006105f54
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/192817d0701a7bfb85a26c64aff10568afeaf4c5efa32917d92a0844c4356787--awk--20240728.sonoma.bottle.tar.gz
==> Fetching jansson
==> Downloading https://ghcr.io/v2/homebrew/core/jansson/manifests/2.14
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/dcf5fb966d90746cd91204b1e9c96d935d2541ea00ccc8209f6017f684e838cd--jansson-2.14.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/jansson/blobs/sha256:cdac3d9d6f635983a33734c1eb3e159df
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/81126948e8ae21452097fa293c4987537958024657ea180cb4382ddda404d856--jansson--2.14.sonoma.bottle.tar.gz
==> Fetching tree-sitter
==> Downloading https://ghcr.io/v2/homebrew/core/tree-sitter/manifests/0.24.5
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/ba68a2238e25b3c5c379af3c4db9395c3deb862d3b38418ab661e8e85800cb86--tree-sitter-0.24.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/tree-sitter/blobs/sha256:f6018400d46f16ef849bd821d0c89
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/13221bcda7aa9becc3eacb3e007d604798d0acecfe011e8f769d6ab0f9baee7f--tree-sitter--0.24.5.sonoma.bottle.tar.gz
==> Fetching d12frosted/emacs-plus/emacs-plus@29
==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-29.4.tar.xz
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/40b0d2afb6a8abb0782d2f870c83209c0ebb7136de4de640b427214523ed5278--emacs-29.4.tar.xz
==> Installing emacs-plus@29 from d12frosted/emacs-plus
==> Installing dependencies for d12frosted/emacs-plus/emacs-plus@29: gnu-sed, gnu-tar, grep, awk, jansson and tree-sitter
==> Installing d12frosted/emacs-plus/emacs-plus@29 dependency: gnu-sed
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-sed/manifests/4.9-2
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/76f36ee40de04c6391017f0d87ac55b273e9e870c9b6ca1feb923d95ffc1c0cd--gnu-sed-4.9-2.bottle_manifest.json
==> Pouring gnu-sed--4.9.sonoma.bottle.2.tar.gz
🍺  /usr/local/Cellar/gnu-sed/4.9: 13 files, 594KB
==> Installing d12frosted/emacs-plus/emacs-plus@29 dependency: gnu-tar
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-tar/manifests/1.35-1
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/e0ce070efd811d45bde2dc83fa029e863379a5e778eafae566b5a3f709eb82e0--gnu-tar-1.35-1.bottle_manifest.json
==> Pouring gnu-tar--1.35.sonoma.bottle.1.tar.gz
🍺  /usr/local/Cellar/gnu-tar/1.35: 17 files, 1.8MB
==> Installing d12frosted/emacs-plus/emacs-plus@29 dependency: grep
==> Downloading https://ghcr.io/v2/homebrew/core/grep/manifests/3.11-2
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/ad81f65102ec61a6dacd2d8927cd680d905e10addb8c5e955ffd454b1910d8e0--grep-3.11-2.bottle_manifest.json
==> Pouring grep--3.11.sonoma.bottle.2.tar.gz
🍺  /usr/local/Cellar/grep/3.11: 18 files, 1009.2KB
==> Installing d12frosted/emacs-plus/emacs-plus@29 dependency: awk
==> Downloading https://ghcr.io/v2/homebrew/core/awk/manifests/20240728
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/a872154422855fa91de8a4e98f8c96799f02a7806ac0b350aba552dc8e3140ea--awk-20240728.bottle_manifest.json
==> Pouring awk--20240728.sonoma.bottle.tar.gz
🍺  /usr/local/Cellar/awk/20240728: 9 files, 157.2KB
==> Installing d12frosted/emacs-plus/emacs-plus@29 dependency: jansson
==> Downloading https://ghcr.io/v2/homebrew/core/jansson/manifests/2.14
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/dcf5fb966d90746cd91204b1e9c96d935d2541ea00ccc8209f6017f684e838cd--jansson-2.14.bottle_manifest.json
==> Pouring jansson--2.14.sonoma.bottle.tar.gz
🍺  /usr/local/Cellar/jansson/2.14: 12 files, 211.6KB
==> Installing d12frosted/emacs-plus/emacs-plus@29 dependency: tree-sitter
==> Downloading https://ghcr.io/v2/homebrew/core/tree-sitter/manifests/0.24.5
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/ba68a2238e25b3c5c379af3c4db9395c3deb862d3b38418ab661e8e85800cb86--tree-sitter-0.24.5.bottle_manifest.json
==> Pouring tree-sitter--0.24.5.sonoma.bottle.tar.gz
🍺  /usr/local/Cellar/tree-sitter/0.24.5: 15 files, 15.3MB
==> Installing d12frosted/emacs-plus/emacs-plus@29
==> Patching
==> Applying fix-window-role.patch
==> Applying system-appearance.patch
==> Applying round-undecorated-frame.patch
==> ./autogen.sh
Last 15 lines from /Users/seth/Library/Logs/Homebrew/emacs-plus@29/01.autogen.sh:
by your system is too old, it is normally straightforward to build
these packages from source.  You can find the sources at:

https://ftp.gnu.org/gnu/PACKAGE/

Download the package (make sure you get at least the minimum version
listed above), extract it using tar, then run configure, make,
make install.  Add the installation directory to your PATH and re-run
this script.

If you know that the required versions are in your PATH, but this
script has made an error, then you can simply re-run this script with
the --no-check option.

Please report any problems with this script to bug-gnu-emacs@gnu.org .

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

  </pre>
</details>

### brew doctor output

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: No Cask quarantine support available: unknown reason.

### brew config output

HOMEBREW_VERSION: 4.4.11-24-g0bcb764
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0bcb7648ce209631a1e483c1fdff50842584e209
Last commit: 7 hours ago
Branch: master
Core tap HEAD: f891096d14992dc4d5fe7529cea72a08e888a8cb
Core tap last commit: 2 hours ago
Core tap JSON: 12 Dec 02:28 UTC
Core cask tap HEAD: ca5681ca91907d9d6b485a229ee3f86c649afd15
Core cask tap last commit: 2 hours ago
Core cask tap JSON: 12 Dec 02:28 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 16.0.0 build 1600
Git: 2.45.1 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-x86_64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A

### Any extra information

Just upgraded to 15.1.1 and emacs-plus wouldn't run so tried to reinstall.

**Comment by JP-Ellis** [comment]
Trying to bypass the error by adding `--no-check` (in case everything is actually fine) does not actually help much:

```
==> ./autogen.sh --no-check
Last 15 lines from /Users/joshua.ellis/Library/Logs/Homebrew/emacs-plus@29/01.autogen.sh:
2024-12-16 22:38:04 +0000

./autogen.sh
--no-check

Running 'autoreconf -fi -I m4' ...
./autogen.sh: /opt/homebrew/opt/autoconf/bin/autoreconf: /usr/bin/perl5.30: bad interpreter: No such file or directory

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues
```

Not that I'm unsure whether I did it correctly given the error message.

**Comment by slackorama** [comment]
Thanks, reinstalling autconf got me past the above. Now I'm running into
```
1040   │ /Library/Developer/CommandLineTools/usr/bin/ranlib: file: libgnu.a(u64.o) has no symbols
1041   │ /Library/Developer/CommandLineTools/usr/bin/ranlib: file: libgnu.a(unistd.o) has no symbols
```
when make is running. 

Tried re-installing command line tools but that didn't work. Going to try starting from a clean slate with brew now.

Thanks again for the help.

**Comment by JP-Ellis** [comment]
Strange that you're having this issue; my installation proceeded just fine.

Are you installing `emacs-plus@29` with any additional flags? Personally, I had the following flags:

```
--with-xwidgets --with-no-frame-refocus --with-imagemagick --with-modern-doom3-icon
```

**Comment by slackorama** [comment]
Agreed. It's strange. The other box I upgraded had no problems at all. Pretty similar starting points too.

I'm just running plain old `brew install emacs-plus@29`.

**Comment by slackorama** [comment]
Clean slate got it installed.
