### ISSUE TITLE
[General]: Is it necessary to install librsvg-2.59.2 before compiling emacs-plus@31?

### ISSUE THREAD

**Issue by Odysseus6000** [d12frosted/homebrew-emacs-plus#766]
### Issue description

brew install emacs-plus@31 --with-dbus --with-debug --with-mailutils --with-xwidgets --with-imagemagick --with-native-comp --with-ctags 
output :
checking for utimens... no
checking for lutimens... no
checking for working mmap... yes
checking for main in -lXbsd... no
checking for pthread library... none needed
checking for thread support... yes
checking for librsvg-2.0 >= 2.14.0... no
checking for libwebpdemux >= 0.6.0... no
checking for WebPGetInfo... no
checking for libwebpdemux >= 0.6.0 libwebpdecoder >= 0.6.0... no
checking for sqlite3_open_v2 in -lsqlite3... yes
checking for sqlite3_load_extension in -lsqlite3... yes
checking for MagickWand >= 7... no
checking for Wand >= 6.3.5 Wand != 6.8.2... no
configure: error: ImageMagick wanted, but it does not compile.  Maybe some library files are missing?
However,
brew info librsvg
==> librsvg: stable 2.58.4 (bottled)
Library to render SVG files using Cairo
https://wiki.gnome.org/Projects/LibRsvg
Installed
/opt/homebrew/Cellar/librsvg/2.58.4

**Comment by LuciusChen** [comment]
I also encountered a similar error, but it turned out that `round-undecorated-frame.patch` needed some modifications. After I made the changes, I was able to compile it successfully.
[round-undecorated-frame.patch](https://github.com/user-attachments/files/18219069/round-undecorated-frame.patch)

**Comment by d12frosted** [comment]
The fix to the patch is in the master now. 

Regarding original question - no, brew should install it for you as `librsvg` is a dependency for Emacs+. Can you try building without any extra options?
