### ISSUE TITLE
Portable Dumper flag

### ISSUE THREAD

**Issue by frankjonen** [d12frosted/homebrew-emacs-plus#77]
I just saw this on Spacemacs' Twitter: [portable-dumper](https://github.com/syl20bnr/spacemacs/blob/develop/EXPERIMENTAL.org#spacemacs-dumps-using-the-portable-dumper)

Maybe add a flag `--portapotty` to the formula to enable that in emacs-plus?

**Comment by d12frosted** [comment]
Hey @frankjonen 

Thanks for the feature request.

I am not committing, but I'll work on it during next two weeks. Will keep you updated.

**Comment by d12frosted** [comment]
@frankjonen hey, I've created a PR for this. You can try it by performing following steps:

```
$ git checkout git@github.com:d12frosted/homebrew-emacs-plus.git
$ git checkout feature/pdumper_support
$ brew uninstall emacs-plus
$ brew install Formula/emacs-plus.rb --with-pdumper --HEAD
```

`--with-pdumper` uses `pdumper` branch and a patch to increase the size of `remembered_data`.

Let me know if it doesn't work for you.

Soon (probably tomorrow or the day after tomorrow) I will merge this PR and update Spacemacs doc regarding installation instructions for macOS. 

cc @syl20bnr

**Comment by frankjonen** [comment]
Ace! That was fast. I'll give it a shot over the weekend as I've never used homebrew this way.
