### ISSUE TITLE
Emacs 26.1 's formula has  no option to disapear natural title bars 

### ISSUE THREAD

**Issue by Gilbert-Wong** [d12frosted/homebrew-emacs-plus#83]
Warning: d12frosted/emacs-plus/emacs-plus: this formula has no --with-natural-title-bars option so it will be ignored!

**Comment by d12frosted** [comment]
Hey, unfortunately, yes. I've updated the readme and added few words to caveats section to reflect required actions (52192f0). 

Sorry for inconvenience.

**Comment by Gilbert-Wong** [comment]
Thank you for reply.
