### ISSUE TITLE
Emacs depends on little-cms2

### ISSUE THREAD

**Issue by mzgnr** [d12frosted/homebrew-emacs-plus#85]
After upgrading emacs stopped working.

`brew install little-cms2` fixed

**Comment by d12frosted** [comment]
You've used bottle, right?

If yes, this is a known issue - travis build is failing for exact reason. I am not sure that `little-cms2` is needed. 

I am returning today from a trip and will check it at last.

**Comment by mzgnr** [comment]
@d12frosted https://fossies.org/linux/emacs/src/lcms.c I think its needed

**Comment by d12frosted** [comment]
Ok. You are right. Already pushed the change. I've actually tried installing it manually in the `before_install` hook, but it didn't work. Explicitly adding it as a dependency did the trick.

Thanks for rising this issue!
