### ISSUE TITLE
Logs for `brew services restart emacs-plus`

### ISSUE THREAD

**Issue by bittopaz** [d12frosted/homebrew-emacs-plus#88]
`brew services restart emacs-plus` is a good way to manage the daemon of emacs. But for the logging, it might be better to output the logs when starting the daemon.

```
brew services restart emacs-plus
Stopping `emacs-plus`... (might take a while)
==> Successfully stopped `emacs-plus` (label: homebrew.mxcl.emacs-plus)
==> Successfully started `emacs-plus` (label: homebrew.mxcl.emacs-plus)
```

**Comment by d12frosted** [comment]
Hey,

That makes sense. But I could not find a way to do it with `launchctl`. Though I've modified plist to write logs to files, so you can check them at any moment.

```
$ tail -f /tmp/homebrew.mxcl.emacs-plus.stdout.log
$ tail -f /tmp/homebrew.mxcl.emacs-plus.stderr.log
```

**Comment by bittopaz** [comment]
Great, I guess that is the best workaround for now. Thanks @d12frosted

**Comment by d12frosted** [comment]
I don't see any better solution than the log files, so I consider this issue as (partially) fixed.
